novuhq/novu

- .eslintrc.json
- jest.config.js
- package.json
- src/lib/content/content.engine.spec.ts
- src/lib/content/content.engine.ts
- src/lib/handler/email.handler.spec.ts
- src/lib/handler/sms.handler.spec.ts
- src/lib/notifire.spec.ts
- src/lib/notifire.ts
- src/lib/provider/provider.store.spec.ts
- src/lib/provider/provider.store.ts
- src/lib/template/template.store.spec.ts
- src/lib/template/template.store.ts
- src/lib/trigger/trigger.engine.spec.ts
- src/lib/trigger/trigger.engine.ts
- tsconfig.json
- yarn.lock
Switches unit tests to run with jest instead of ava
Add unit tests to all internal classes
Closes #1
> Add unit tests to main functionality

- src/lib/template/template.interface.ts
- src/lib/template/template.store.spec.ts
- src/lib/template/template.store.ts
- src/lib/trigger/trigger.engine.ts
> Adds active filter to template messages

- .cspell.json
- package.json
- src/lib/content/content.engine.spec.ts
- src/lib/content/content.engine.ts
- src/lib/notifire.interface.ts
- src/lib/notifire.ts
- src/lib/trigger/trigger.engine.spec.ts
- src/lib/trigger/trigger.engine.ts
- yarn.lock
> Adds variable protection on trigger of notification

- packages/core/package.json
- packages/core/src/lib/content/content.engine.ts
- packages/core/src/lib/handler/email.handler.spec.ts
- packages/core/src/lib/handler/email.handler.ts
- packages/core/src/lib/handler/sms.handler.spec.ts
- packages/core/src/lib/handler/sms.handler.ts
- packages/core/src/lib/notifire.spec.ts
- packages/core/src/lib/notifire.ts
- packages/core/src/lib/provider/provider.interface.ts
- packages/core/src/lib/provider/provider.store.spec.ts
- packages/core/src/lib/template/template.interface.ts
- packages/core/src/lib/template/template.store.spec.ts
- packages/core/src/lib/theme/theme.interface.ts
- packages/core/src/lib/theme/theme.store.spec.ts
- packages/core/src/lib/trigger/trigger.engine.spec.ts
- providers/twilio/src/lib/twilio.provider.spec.ts
- tsconfig.json
- yarn.lock
In order to provide a more typesafe library for our end customer, strict mode was introduced
during the compilation phase.
re #68
> refactor(@notifire/core): adds a strict mode typescript compilation

- README.md
Replaced string with template variable in the `img` tag.
> [doc] Updated readme's example

- providers/ses/.eslintrc.json
- providers/ses/.gitignore
- providers/ses/README.md
- providers/ses/jest.config.js
- providers/ses/package.json
- providers/ses/src/index.ts
- providers/ses/src/lib/ses.config.ts
- providers/ses/src/lib/ses.provider.spec.ts
- providers/ses/src/lib/ses.provider.ts
- providers/ses/tsconfig.json
- providers/ses/tsconfig.module.json
- yarn.lock
Add Amazon SES email provider
Resolves #39 
Amazon SES can be used as an email provider
> Add Amazon SES email provider

- packages/core/src/lib/handler/email.handler.spec.ts
- packages/core/src/lib/handler/email.handler.ts
- packages/core/src/lib/handler/sms.handler.spec.ts
- packages/core/src/lib/handler/sms.handler.ts
- packages/core/src/lib/template/template.interface.ts
- packages/core/src/lib/trigger/trigger.engine.spec.ts
- packages/core/src/lib/trigger/trigger.engine.ts
Check if template is a function and then use result from function as content in handler.
Only text and handlebars templates are allowed.
Check if template is a function and then use result from function as content in handler.
https://github.com/notifirehq/notifire/issues/31
This is one of my first PR against an open source project 😄
> Allow custom template function

- packages/core/src/lib/content/content.engine.ts
- packages/core/src/lib/handler/email.handler.spec.ts
- packages/core/src/lib/handler/email.handler.ts
- packages/core/src/lib/handler/sms.handler.spec.ts
- packages/core/src/lib/handler/sms.handler.ts
- packages/core/src/lib/provider/provider.interface.ts
- packages/core/src/lib/template/template.interface.ts
Add so attachment can be sent.
https://github.com/notifirehq/notifire/issues/21
Attachment can be sent.
> Add Attachments Interface

- providers/mailjet/src/lib/mailjet.provider.ts
Feature implementing #101 
Notifire's mailjet proivder now supports file attachments.
> feat: added attachment support for mailjet provider

- providers/nodemailer/src/lib/nodemailer.provider.spec.ts
- providers/nodemailer/src/lib/nodemailer.provider.ts
Feature request: #100 
Nodemailer provider now supports attachments.
> Nodemailer attachments support

- providers/postmark/src/lib/postmark.provider.spec.ts
- providers/postmark/src/lib/postmark.provider.ts
Feature request: #99 
Postmark provider now supports attachments.
> Postmark attachments support

- providers/sendgrid/src/lib/sendgrid.provider.spec.ts
- providers/sendgrid/src/lib/sendgrid.provider.ts
Feature request: #94 
Sendgrid's provider now supports attachments.
> Sendgrid attachments support

- providers/mailgun/src/lib/mailgun.provider.spec.ts
- providers/mailgun/src/lib/mailgun.provider.ts
Feature request: https://github.com/notifirehq/notifire/issues/97
Mailgun provider now supports attachments.
> feat: add attachment support to MailgunEmailProvider

- docs/docs/community/create-provider.md
docs update. 
Issue #67 documentation for create provider
n/a 
Provided updates to help communicate initialization, description and code snippets for end users.
> 67 docs for template provider

- docs/docs/overview/introduction.md
- **What kind of change does this PR introduce?** docs update.
> Fixed some typo

- docs/docs/overview/introduction.md
- docs/docs/overview/outgoing-communication-layer.md
- docs/docs/templates/messages.md
- **What kind of change does this PR introduce?** (docs update, ...)
> Some typo and grammar fix

- package.json
- Changes acc. to code review for PR #165 
- Fixed version for dependencies
- Add pnpm as devDependency
- update build script
> Update package.json(NX workspace code review)

- _templates/provider/new/.czrc.ejs.t
- _templates/provider/new/package.ejs.t
feat: #166 
#166 
Will generate new provider acc. to new changes for nx to build successfully.
> Update providers template

- .idea/misc.xml
- package.json
Closes #177 
Co-Authored-By: Dima Grossman <dima@grossman.io>
> Add project build on setup:project command

- apps/widget/package.json
- apps/widget/src/components/layout/Layout.tsx
> Border style on window widget #176

- package.json
> Add npx only-allow-pnpm to avoid people running yarn install

- Dockerfile.api
- Dockerfile.web
- Dockerfile.widget
- Dockerfile.ws
> Update docker files to use pnpm

- .github/workflows/test-api.yml
- .github/workflows/test-core.yml
- .github/workflows/test-providers.yml
- .github/workflows/test-sdk.yml
- .github/workflows/test-web.yml
- .github/workflows/test-widget.yml
> Update github actions to use pnpm

- apps/web/cypress/tests/activities-page.spec.ts
- apps/web/src/pages/activities/ActivitiesPage.tsx
> Add capitalization to subscribers names on activity list page

- .idea/notifire.iml
- .idea/vcs.xml
- apps/api/src/app/auth/e2e/password-reset.e2e.ts
Couldn't find the issue origin or reproduce it, added a couple of debug lines to catch it next time it happens again
> RLD-68 Flaky password reset test add debug lines

- docker/docker-compose.yml
Update deprecated old environment variable
> Updated deprecated environment variable

- docker/docker-compose.yml
> Update docker-compose to use pre-built images from ghcr

- apps/api/src/bootstrap.ts
- docker/.env.example
- docker/docker-compose.development.yml
- docker/docker-compose.yml
- libs/sdk/Dockerfile
- libs/sdk/package.json
- libs/sdk/rollup.config.ts
- libs/sdk/src/shared/resources.js
- package.json
> RLD-92 Add sdk serving to docker compose

- apps/api/src/.env.local
- pnpm-lock.yaml
- providers/telnyx/.eslintrc.json
- providers/telnyx/.gitignore
- providers/telnyx/README.md
- providers/telnyx/jest.config.js
- providers/telnyx/package.json
- providers/telnyx/src/index.ts
- providers/telnyx/src/lib/telnyx.interface.ts
- providers/telnyx/src/lib/telnyx.provider.spec.ts
- providers/telnyx/src/lib/telnyx.provider.ts
- providers/telnyx/src/types/example.d.ts
- providers/telnyx/tsconfig.json
- providers/telnyx/tsconfig.module.json
feature
Telnyx SMS provider not supported
closes #127 
Telnyx SMS provider is now supported
> Implements Telnyx SMS provider

- docs/docs/providers/_category_.json
- docs/docs/recipes/_category_.json
- docs/docs/templates/_category_.json
- docs/docs/trigger/_category_.json
- docs/docs/trigger/hooks.md
- **What kind of change does this PR introduce?** ( docs update)
- **What is the current behavior?** ([open issue here](https://github.com/notifirehq/notifire/issues/23))
> Added: doc for Hooks feature

- README.md
Added new SMS provider
Just wasn't existing 
Now it is shown 
- **Other Information**:
> Added new SMS provider (Telnyx)to Readme.md

- apps/api/src/app/organization/usecases/create-organization/create-organization.usecase.ts
- packages/cli/package.json
- packages/cli/src/api/api.service.ts
- packages/cli/src/api/application.ts
- packages/cli/src/api/organization.ts
- packages/cli/src/commands/init.consts.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/constants/constants.ts
- pnpm-lock.yaml
> Create Organization & Application

- packages/cli/src/commands/init.ts
- packages/cli/src/server/http-server.ts
> Fix bug update const typo

- packages/cli/src/constants/dashboard/index.html
> Add demo dashboard html

- packages/cli/src/api/application.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/constants/constants.ts
- packages/cli/src/services/config.service.ts
> Validate and switch use application

- apps/api/src/app/notification-template/dto/create-notification-template.dto.ts
- apps/api/src/app/notification-template/notification-template.controller.ts
- apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.command.ts
- apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.usecase.ts
- libs/shared/src/dto/notification-templates/create-template.dto.ts
- packages/cli/src/api/index.ts
- packages/cli/src/api/notification-groups.ts
- packages/cli/src/api/notification-templates.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/constants/constants.ts
> During application, creation create a demo template

- packages/cli/src/constants/dashboard/index.html
> Add copy button that copies curl command

- packages/cli/src/constants/dashboard/index.html
- packages/cli/src/server/http-server.ts
> Add hide the jwt and api key

- libs/sdk/src/sdk.ts
> Widget bell style jump 

- packages/cli/package.json
- packages/cli/src/commands/init.consts.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/constants/constants.ts
- pnpm-lock.yaml
> Account Creation Flow

- packages/cli/src/commands/init.ts
**What kind of change does this PR introduce?** 
- Bug fix
**What is the current behavior?** (You can also link to an open issue here)
- The widget does not get the correct application Identifier
> Fix application id in the widget

- apps/web/src/design-system/tabs/tabs.stories.tsx
- apps/web/src/design-system/tabs/tabs.styles.ts
- apps/web/src/design-system/tabs/tabs.tsx
feature
closes #246 
Adds a tabs horizontal menu component/stories to notifire web application design system
> Implements tabs horizontal menu(design system)

- libs/dal/src/index.ts
- libs/dal/src/repositories/integration/index.ts
- libs/dal/src/repositories/integration/integration.entity.ts
- libs/dal/src/repositories/integration/integration.repository.ts
- libs/dal/src/repositories/integration/integration.schema.ts
- libs/shared/src/consts/providers/index.ts
- libs/shared/src/consts/providers/provider.enum.ts
- libs/shared/src/consts/providers/provider.interface.ts
- packages/cli/src/commands/init.consts.ts
> Create Integration Data-Model

- packages/cli/src/commands/init.consts.ts
- packages/cli/src/commands/init.ts
- bugfix
Once you go to 'Run manually using docker' your CLI closes and the GitHub readme is not open due to race condition
> Fix cli race condition on docker setup

- apps/web/src/components/templates/TemplateSMSEditor.tsx
- apps/web/src/components/templates/TemplatesSideBar.tsx
- apps/web/src/components/templates/email-editor/EmailContentCard.tsx
> Tooltips Errors  

- apps/api/src/app/auth/auth.controller.ts
> 🔧 Add a warning exception for github oauth flow

- apps/web/src/components/layout/components/SideNav.tsx
- apps/web/src/components/templates/NotificationSettingsForm.tsx
- apps/web/src/components/templates/TemplatesSideBar.tsx
- apps/web/src/design-system/template-button/TemplateButton.tsx
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
> 💄 Fix responsive issue in template editor

- README.md
> Added a link to our Discord server

- apps/web/.gitignore
- apps/web/env.sh
- apps/web/package.json
- apps/web/public/index.html
feature
https://github.com/novuhq/novu/issues/378
> Added: Script to inject env var in window object

- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- apps/api/src/app/events/usecases/trigger-event/message-filter.matcher.spec.ts
- apps/api/src/app/events/usecases/trigger-event/message-filter.matcher.ts
- apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
- apps/api/src/app/notification-template/dto/create-notification-template.dto.ts
- apps/api/src/app/notification-template/dto/update-notification-template.dto.ts
- apps/api/src/app/notification-template/e2e/create-notification-templates.e2e.ts
- apps/api/src/app/notification-template/e2e/get-notification-template.e2e.ts
- apps/api/src/app/notification-template/e2e/update-notification-template.e2e.ts
- apps/api/src/app/notification-template/notification-template.controller.ts
- apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.command.ts
- apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.usecase.ts
- apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.command.ts
- apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts
- apps/web/cypress/tests/notifications-editor.spec.ts
- apps/web/src/components/templates/NotificationSettingsForm.tsx
- apps/web/src/components/templates/use-template-controller.hook.ts
- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.repository.ts
- libs/dal/src/repositories/notification-template/notification-template.schema.ts
- libs/shared/src/dto/notification-templates/create-template.dto.ts
- libs/shared/src/dto/notification-templates/shared.ts
- libs/shared/src/dto/notification-templates/update-template.dto.ts
- libs/shared/src/entities/notification-template/notification-template.interface.ts
- libs/testing/src/create-notification-template.interface.ts
- libs/testing/src/notification-template.service.ts
- libs/testing/src/user.session.ts
- packages/cli/src/commands/init.ts
> Convert messages to steps

- apps/web/.storybook/main.js
> 🐛  fix storybook crash because of emotion

- apps/api/src/app/environments/environments.controller.ts
- apps/api/src/app/environments/usecases/get-my-environments/get-my-environments.command.ts
- apps/api/src/app/environments/usecases/get-my-environments/get-my-environments.e2e.ts
- apps/api/src/app/environments/usecases/get-my-environments/get-my-environments.usecase.ts
- apps/api/src/app/environments/usecases/index.ts
> Nv 332 get user environments api

- .eslintrc.js
- apps/api/src/app/organization/usecases/create-organization/create-organization.usecase.ts
- apps/web/src/App.tsx
- apps/web/src/api/environment.ts
- apps/web/src/components/layout/components/SideNav.tsx
- apps/web/src/design-system/segmented-control/SegmentedControl.styles.ts
- apps/web/src/design-system/segmented-control/SegmentedControl.tsx
- apps/web/src/store/authContext.ts
- apps/web/src/store/use-auth-controller.ts
> Nv 311 switch environment

- apps/web/package.json
- apps/web/src/components/layout/components/PageContainer.tsx
- apps/web/src/components/layout/components/PageMeta.tsx
- apps/web/src/pages/activities/ActivitiesPage.tsx
- apps/web/src/pages/integrations/IntegrationsStorePage.tsx
- apps/web/src/pages/invites/MembersInvitePage.tsx
- apps/web/src/pages/settings/SettingsPage.tsx
- apps/web/src/pages/templates/TemplatesListPage.tsx
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
- pnpm-lock.yaml
feature
https://github.com/novuhq/novu/issues/486
Page title help better identification of the visited page
> [NV-296] Update pages meta title to indicate visiting pge

- apps/web/src/design-system/input/Input.tsx
- apps/web/src/pages/settings/components/ApiKeysCard.tsx
Hey, the design is a bit changed but it is the most accurate according to the Figma design. Please let me know what you think.
The result it the following:
> Add application identifier in settings

- apps/web/src/pages/settings/SettingsPage.tsx
- apps/web/src/pages/settings/tabs/ApiKeysCard.tsx
- apps/web/src/pages/settings/tabs/BrandingForm.tsx
- apps/web/src/pages/settings/tabs/InAppCenterCard.tsx
- apps/web/src/pages/settings/tabs/components/Security.tsx
- apps/web/src/pages/settings/tabs/index.ts
Hey, the design is a bit changed but it is the most accurate according to the Figma design. Please let me know what you think.
This PR does not contain the communication to the API because it still was not developed, I will create a separate PR for the additional API support.
The result is the following:
> 🚧  Add Security component

- apps/web/src/App.tsx
> Nv 386 env token validation

- apps/api/src/app/content-templates/usecases/compile-template/compile-template.spec.ts
- apps/api/src/app/content-templates/usecases/compile-template/compile-template.usecase.ts
> ✨  added pluralize helper

- apps/api/src/app/shared/commands/command.helper.ts
> ✨  added breadcrumb

- apps/api/src/app/activity/activity.controller.ts
- apps/api/src/app/activity/e2e/get-activity-feed.e2e.ts
- apps/api/src/app/activity/usecases/get-activity-feed/get-activity-feed.command.ts
- apps/api/src/app/activity/usecases/get-activity-feed/get-activity-feed.usecase.ts
- libs/dal/src/repositories/message/message.entity.ts
- libs/dal/src/repositories/message/message.repository.ts
- libs/dal/src/repositories/message/message.schema.ts
While working I saw this email filter, that filters the subscriber, however, the activity email filter was missing. 
Let me know if I misunderstood the filter part.
> Fix activity emails filter

- packages/notification-center/src/components/notification-center/components/Main.tsx
- packages/notification-center/src/shared/utils/getLinearGradientColorStopValues.ts
> Fix gradient picker cross browser

- apps/web/src/components/templates/NotificationSettingsForm.tsx
- **grammatical error fix on line 70**
> fixed grammatical error in notification form

- apps/web/src/components/templates/TemplateEditor.tsx
- apps/web/src/components/templates/TemplatePageHeader.tsx
- apps/web/src/components/templates/TemplateSettings.tsx
- apps/web/src/components/templates/TemplatesSideBar.tsx
- apps/web/src/components/templates/email-editor/EmailMessagesCards.tsx
- apps/web/src/components/templates/in-app-editor/TemplateInAppEditor.tsx
- apps/web/src/design-system/button/Button.styles.ts
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
> 💄 Fix editor styling

- apps/web/src/pages/activities/ActivitiesPage.tsx
> :bug: Fix capitalize not existing subscriber

- packages/notification-center/src/store/socket/use-socket-controller.ts
> Update transports from "polling, websocket" to "websocket"

- apps/web/src/components/templates/TemplateSettings.tsx
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
show trigger modal on any create click, not just from settings page
> Show trigger snippet modal on every create

- apps/web/src/components/templates/TemplateFormProvider.tsx
- apps/web/src/components/templates/TemplatesSideBar.tsx
- apps/web/src/components/templates/use-template-controller.hook.ts
- apps/web/src/components/workflow/ChannelNode.tsx
- apps/web/src/components/workflow/FlowEditor.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
> Error  styles  through the form hook

- apps/web/src/components/layout/components/SideNav.tsx
- Changed integration to integrations store
- #667 
> style changed integration to integrations

- apps/web/src/pages/settings/tabs/ApiKeysCard.tsx
changed api to API
#665 https://github.com/novuhq/novu/issues/665
> changed api to API

- apps/web/cypress/tests/notifications-editor.spec.ts
- apps/web/src/components/templates/use-template-controller.hook.ts
- apps/web/src/design-system/template-button/ChannelButton.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
Add tests for delete step, drag and drop, step active status and more.
> Cypress testing

- apps/web/src/components/auth/LoginForm.tsx
- apps/web/src/components/auth/SignUpForm.tsx
- apps/web/src/config/index.ts
- docker/docker-compose.yml
fixes #687 
Throws invalid type error on some platforms while using docker
Fixed the error by replacing boolean env with string
> fix: updated the docker env to string

- apps/web/cypress/tests/notifications-editor.spec.ts
- apps/web/cypress/tests/onboarding.spec.ts
- apps/web/src/components/templates/UnsavedChangesModal.tsx
- apps/web/src/components/templates/use-template-controller.hook.ts
- apps/web/src/hooks/use-prompt.tsx
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
Warn user on navigation outside of workflow editor or page refresh when there are unsaved changes.
> feat: add hook use prompt, warn on  navigation

- apps/api/nest-cli.json
- apps/web/src/pages/auth/InvitationPage.tsx
Bug fix: display a clear message about why the "Team Invite" page not working and an option to log out.
https://github.com/novuhq/novu/issues/656
https://www.loom.com/share/426e9c40e3464a9b9a4ce5024c472f3a
> fix: team invite not working when already logged in

- apps/web/cypress/tests/notifications-editor.spec.ts
- apps/web/src/components/templates/TemplateFormProvider.tsx
- apps/web/src/components/templates/email-editor/EmailMessageEditor.tsx
- apps/web/src/components/workflow/FlowEditor.tsx
Fix the error circle on nodes to fit new structure of steps errors.
fix double warn navigation on upload logo.
add tests. 
Closes [NV-535](https://linear.app/novu/issue/NV-535/upload-logo-through-email-editor-2-warnings), [NV-534](https://linear.app/novu/issue/NV-534/error-circles-not-showing-on-nodes)
> Error circles not showing on nodes

- apps/web/cypress/tests/onboarding.spec.ts
- apps/web/src/components/templates/NotificationSettingsForm.tsx
- apps/web/src/components/templates/TemplateFormProvider.tsx
- apps/web/src/design-system/select/Select.tsx
- apps/web/src/design-system/template-button/TemplateButton.tsx
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
fixes not being able to click on workflow button if there are any errors anywhere. Now only on notification settings errors. 
fixes dirty but empty notification name considered valid. Still does not re-appear the error itself on notification name.
> Workflow button issues 

- apps/web/src/components/templates/TemplatesSideBar.tsx
- apps/web/src/design-system/icons/gradient/ConnectGradient.tsx
- apps/web/src/design-system/icons/index.ts
Icon added. 
with description:
> feat: add workflow icon

- docs/docs/notification-center/react-components.md
#697 
#697 
Updated documentation
> import IMessage + Dark mode (colorScheme update) Documentation

- packages/notification-center/src/components/popover-notification-center/PopoverNotificationCenter.tsx
> Added unseenCount in popover notification component

- apps/web/src/components/workflow/FlowEditor.tsx
- apps/web/src/components/workflow/TriggerNode.tsx
Added drop area on Trigger Node
> fix: drop area not shown on trigger

- apps/web/src/components/templates/use-template-controller.hook.ts
- apps/web/src/components/workflow/ChannelNode.tsx
- apps/web/src/components/workflow/FlowEditor.tsx
- apps/web/src/components/workflow/TriggerNode.tsx
- apps/web/src/design-system/template-button/ChannelButton.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
closes [NV-558](https://linear.app/novu/issue/NV-558/edit-message-is-empty-after-delete-on-go-back-node-is-still-shown)
Removed watch on steps in every channel button.
> edit message not shown after delete, deleted node not shown again

- apps/web/src/components/templates/LackIntegrationError.tsx
- apps/web/src/components/templates/email-editor/EmailMessagesCards.tsx
Fix bug of navigation to configure integration not working
Closes [NV-562](https://linear.app/novu/issue/NV-562/navigate-to-integration-store-is-broken)
> fix: use only one unsaved changes error

- docs/docs/notification-center/react-components.md
- > Documentation improvement -- Improved the code block regarding react-component in which `navigate()` function was not defined. Added the `useNavigate()` hook from `react-router-dom`.
---
- > The `navigate()` function is not defined, so the user can get confused.
---
- > Added the `useNavigate()` hook from `react-router-dom`.
> Docs: improve react-component code block

- apps/web/src/design-system/icons/general/Digest.tsx
- apps/web/src/design-system/template-button/ChannelButton.tsx
- apps/web/src/pages/templates/shared/channels.ts
- apps/web/src/pages/templates/workflow/DigestMetadata.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
> fix: styles and texts for digest action

- packages/notification-center/src/components/notification-center/components/FeedsTabs.tsx
- packages/notification-center/src/components/notification-center/components/UnseenBadge.tsx
- packages/notification-center/src/components/notification-center/components/layout/tabs/Tabs.styles.ts
- packages/notification-center/src/components/notification-center/components/layout/tabs/Tabs.tsx
- packages/notification-center/src/shared/config/themeDefaultValues.ts
> Design Feeds - Notification Center

- apps/web/src/pages/quick-start/QuickStartPage.tsx
Bug fix / UI
CTA w/o pointer cursor
CTA w/ pointer cursor
> fix: add pointer cursor to cta

- apps/web/src/components/auth/SignUpForm.tsx
> fix: add a return statement on invite accept

- apps/web/cypress/tests/invites.spec.ts
- apps/web/src/components/auth/SignUpForm.tsx
- apps/web/src/pages/auth/InvitationPage.tsx
Also added test to assert the behaviour on invite accept.
> Fix organization invite issue

- libs/embed/src/embed.ts
> Fix embed widget position option

- apps/web/src/design-system/dropdown/Dropdown.tsx
- apps/web/src/design-system/icons/general/DigestGradient.tsx
- apps/web/src/design-system/template-button/ChannelButton.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
fix some console warning and errors:
> fix: remove console errors

- pnpm-lock.yaml
- providers/gupshup/package.json
Introduced by a typo to include another polyfill package
> fix: remove un-needed node-fetcher dependency

- apps/web/src/design-system/template-button/ChannelButton.tsx
- apps/web/src/design-system/template-button/DragButton.tsx
- apps/web/src/design-system/template-button/TemplateButton.tsx
> fix: add button type for unstyled buttons

- .github/workflows/tag-images.yml
Currently I'm doing this manually from my computer. The goal is to automate this step a bit, for now it only tags and pushes the new tag of docker but later might want to add more functionalities to here. 
Right now the actions is triggered manually with the specified tag.
> Docker tag action for packages

- packages/notification-center/src/components/novu-provider/NovuProvider.tsx
Currently jwt is not refreshed when expired
> fix: reinitiate token on page load

- apps/api/package.json
- apps/api/src/app/shared/services/storage/storage.service.ts
- apps/api/src/app/shared/shared.module.ts
- pnpm-lock.yaml
feature. Addressing issue #865
AWS s3 is the only supported storage service
Can switch to google cloud storage with .env change
> feat: add support for google cloud storage

- .github/workflows/dev-deploy-api.yml
- _templates/provider/new/package.ejs.t
- apps/api/Dockerfile
- apps/api/package.json
- package.json
- pnpm-lock.yaml
- providers/gupshup/package.json
- providers/termii/package.json
- scripts/pnpm-context.mjs
This adds support for multi stage builds and reduces the final API docker image from 1.8GB to 900MB
Right now we are passing a huge context and leaving the devDependencies in the docker, in the new approach only needed context is passed and bundled to the docker.
> Docker staged build on API docker file

- package.json
- providers/emailjs/package.json
- providers/gupshup/package.json
- providers/mailersend/src/lib/mailersend.provider.spec.ts
- providers/mailersend/src/lib/mailersend.provider.ts
- providers/mailersend/src/types/index.d.ts
- providers/nexmo/src/lib/nexmo.provider.spec.ts
- providers/nodemailer/src/lib/nodemailer.provider.spec.ts
- providers/sendgrid/src/lib/sendgrid.provider.spec.ts
- Fixed running mechanism of provider test so they will fail in CI when errored
> fix: running exit codes and broken tests for providers

- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/fi.ts
Adds the 'fi' language for notification center.
> Finnish language for notification center

- docs/docs/channels/direct/slack.md
@djabarovgeorge awesome job documenting this. I think the first sentence is not clear, added some grammatical modifications. Let me know if you have questions? thanks
> Direct docs corrections

- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/hi.ts
feature
#943 
Add i18n hindi support
> feat: add i18n hindi support

- packages/notification-center/src/i18n/languages/hi.ts
- **What kind of change does this PR introduce?** Fix in translation
- **Other information**: Just changed the translation of `markAllRead` in `Hindi` where a word was left English in the Hindi translation.
> Fixed the hindi for markAllRead

- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/sp.ts
Feature
https://github.com/novuhq/novu/issues/944
Added i18n Spanish support
> Added i18n Spanish Support

- libs/embed/package.json
- pnpm-lock.yaml
fix
Vulnerable semantic-release v15
https://security.snyk.io/vuln/SNYK-JS-SEMANTICRELEASE-1041706
upgrade to v17
> fix: upgrade semantic-release

- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/it.ts
- Fixes issue #939 by adding italian support
- I'm a native italian speaker
> i18n - Italian Support

- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/uk.ts
Translation from my ukrainian-native coworkers
> i18n - Ukrainian support

- apps/web/src/components/templates/notification-setting-form/TemplatePreference.tsx
Still need to work on the critical input
> Copy for web

- apps/web/cypress/tests/layout/side-menu.spec.ts
- apps/web/src/components/layout/components/SideNav.tsx
fixes https://github.com/novuhq/novu/issues/1040
> feat: added support and docs bottom links to sidenav

- scripts/jarvis.js
Make a refactor to the jarvis project inspired by @LetItRock
> Refactor jarvis4

- apps/web/cypress/tests/auth.spec.ts
- apps/web/cypress/tests/invites.spec.ts
- apps/web/src/components/auth/SignUpForm.tsx
- apps/web/src/design-system/checkbox/Checkbox.tsx
Created this small change until we get the design
> web accept terms and privacy

- docs/docs/overview/quick-start.md
This PR introduces a minor update in the Docs improving readability and user experience.
- **What is the current behavior?** 
Currently, at Line 51, handlebars is abbreviated as hbs.
- **What is the new behavior?**
Now, at Line 51, the abbreviation (hbs) is extended to handlebars and links to handlebars documentation.
> Fixed Typo [Line 51]✔️

- packages/cli/src/services/config.service.ts
File rename
Config file is named as `notu-cli`
Rename the file name to `novu-cli`
> fix config file name

- apps/api/src/app/organization/e2e/get-members.e2e.ts
- apps/api/src/app/organization/organization.controller.ts
- apps/api/src/app/organization/usecases/membership/get-members/get-members.command.ts
- apps/api/src/app/organization/usecases/membership/get-members/get-members.usecase.ts
- apps/web/src/components/invites/MembersTable.tsx
Hide the email addresses from other team members for users that aren't admin
> feat: hide member emails from other members

- docs/docs/channels/chat/slack.md
feature
slack incoming webhook info is missing
info added
> feat: add slack webhook info

- apps/api/src/app/subscribers/dtos/subscriber-response.dto.ts
- libs/dal/src/repositories/subscriber/subscriber.entity.ts
- libs/dal/src/repositories/subscriber/subscriber.schema.ts
- libs/shared/src/dto/organization/create-organization.dto.ts
fix: add missing fields in subscriber ro and entity
#1098 
> fix: add missing fields in subscriber ro and entity

- apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.usecase.ts
fix: remove repeated find statement
> fix: remove repeated find statement after notification create

- CONTRIBUTING.md
- Updating the contributing docs
- Making installation of Redis easier for new contributor.
- New members will be able to install Redis easily on their computers with the guide.
To make it easier to follow along on the installation of Redis on either Linux, Windows or macOS.
> Chore: Redis installation docs

- apps/web/cypress/tests/auth.spec.ts
- apps/web/src/components/auth/SignUpForm.tsx
analog to https://github.com/novuhq/novu/pull/1038 this adds better user errors for the signup page
n also link to an open issue here)
> feat: added better errors for signup

- docs/docs/platform/subscribers.md
Just some minor spelling errors.
> chore: Fix minor spelling errors

- apps/web/src/design-system/switch/Switch.styles.ts
Use the pointer cursor for the switch component instead of default.
> fix: use cursor pointer for switch

- providers/twilio/README.md
Example was requested in a YouTube comment
- **What kind of change does this PR introduce?** (docs update)
- **What is the current behavior?** N/A
- **What is the new behavior (if this is a feature change)?** N/A
> docs: twilio example with number

- docs/netlify.toml
This pull request adds updates for redirects for API documentation.
https://docs.novu.co/api/#overview
https://docs.novu.co/api/overview/
N/A
> feat: update redirects for API documentation

- README.md
updated the readme documentation to make the email parameter as Array.
> docs: updated the readme documentation to make email param as array.

- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/zh.ts
feature
Added Chinese Language to Language List
Add i18n Chinese support
> i18n - Chinese support

- docs/docusaurus.config.js
fix: social image and add meta keywords for seo
social preview image is broken
fixed
for robots metadata see [this](https://blog.johnnyreilly.com/2021/10/18/docusaurus-meta-tags-and-google-discover)
> fix: social image and add keywords

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
feature: added willing to submit pr option
> feat: willing to submit pr

- apps/api/src/app/events/services/workflow.queue.service.ts
- packages/node/src/lib/subscribers/subscriber.interface.ts
on trigger: 
```
{
to: [],
payload: {},
overrides: {
"delay": { "unit": "seconds", "amount": 30}
}
}
```
> feat(wip): add payload override to delay action

- docs/docs/notification-center/react-components.md
This adds the new languages for the notification-center to the docs.
> fix: added new languages to docs

- README.md
> feat(readme): change contributors link to community heroes

- docs/docs/community/run-locally.md
- docs/src/css/custom.scss
- docs/src/css/details.scss
This adds all environment variables for the apps and explanations for them to the docs.
> feat: added env variables & explanation to docs

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/hr.ts
added Croatian language to notification center
> added Croatian

- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- apps/api/src/app/events/usecases/send-message/send-message-chat.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-push.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts
fixes https://github.com/novuhq/novu/issues/1245
This fixes inactive integrations being used for sending notifications.
> fix: fix inactive integrations still being used

- apps/web/src/hooks/use-novu.ts
- apps/web/src/pages/settings/tabs/InAppCenterCard.tsx
- docs/docs/notification-center/iframe-embed.md
- libs/embed/src/embed.ts
- libs/embed/test/index.html
fixes https://github.com/novuhq/novu/issues/1148
This adds the ability to add callbacks for notification click / action click to the iframe embed.
> feat: iframe callbacks

- libs/shared/src/consts/providers/credentials/provider-credentials.ts
- libs/shared/src/consts/providers/provider.enum.ts
- pnpm-lock.yaml
- providers/mailgun/package.json
- providers/mailgun/src/lib/mailgun.provider.spec.ts
- providers/mailgun/src/lib/mailgun.provider.ts
fixes https://github.com/novuhq/novu/issues/1251
This adds the base url option for the mailgun provider
> fix: added base url for mailgun provider

- README.md
I've added both black and white mode versions for Hacktoberfest banners.
Happy Hacktoberfest :)
> Uploaded Hacktoberfest banners

- packages/node/src/lib/subscribers/subscribers.ts
I fixed a small mistage (hardly a bug)
> Fix for BUG #1269

- apps/api/src/app/events/e2e/trigger-event.e2e.ts
Adjust test to test so default values are not overriding trigger payload
So bug are not created in the future
> test: fix so test are testing so defaults are not overriding trigger payload

- README.md
This pull request adds small design updates to the `README` file
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
N/A
> chore: small design improvements for the README file

- packages/notification-center/src/store/novu-theme.context.ts
> fix bug #1275

- package.json
- pnpm-lock.yaml
- scripts/jarvis.js
Allows to run the jarvis script that runs the docs by fixing the running flow and adding a missing dependency.
To allow all the script options to be fully runnable.
N/A
> fix(jarvis): run docs script branch

- README.md
docs update
It will help new contributors
https://discord.com/channels/895029566685462578/1023616359051042827/1023616359051042827
> fix: add run local doc link in readme

- apps/api/src/app/events/e2e/delay-events.e2e.ts
- apps/api/src/app/events/e2e/digest-events.e2e.ts
- apps/api/src/app/events/services/workflow.queue.service.ts
- apps/api/src/app/events/usecases/add-job/add-delay-job.usecase.ts
- apps/api/src/app/events/usecases/add-job/add-digest-job.usecase.ts
- apps/api/src/app/events/usecases/add-job/add-job.command.ts
- apps/api/src/app/events/usecases/add-job/add-job.usecase.spec.ts
- apps/api/src/app/events/usecases/add-job/add-job.usecase.ts
- apps/api/src/app/events/usecases/add-job/should-add-digest-job.usecase.ts
- apps/api/src/app/events/usecases/index.ts
- apps/api/src/app/events/usecases/queue-next-job/queue-next-job.usecase.ts
- apps/api/src/app/events/usecases/run-job/run-job.command.ts
- apps/api/src/app/events/usecases/run-job/run-job.usecase.ts
- apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
Adding usecases for code that was in side of the workflow queue service before
To make it easier to follow whats happens with a job
> refactor: workflow queue service

- .eslintrc.js
- apps/api/e2e/api/environment/regenerate-api-keys.e2e.ts
- apps/api/src/app/environments/environments.controller.ts
- apps/api/src/app/environments/usecases/index.ts
- apps/api/src/app/environments/usecases/regenerate-api-keys/regenerate-api-keys.usecase.ts
- apps/web/.eslintrc.js
- apps/web/package.json
- apps/web/src/api/environment.ts
- apps/web/src/pages/settings/tabs/ApiKeysCard.tsx
- apps/web/src/pages/settings/tabs/components/ConfirmRegenerationModal.tsx
- apps/web/src/pages/settings/tabs/components/Regenerate.tsx
- apps/widget/package.json
- libs/dal/src/repositories/environment/environment.repository.ts
- package.json
- **What kind of change does this PR introduce?** Feature : allows to regenerate Api keys from the Api and the web app
- **Why this change was needed?** #768
- **Other information:** I apologize because I did not setup novu locally so I kind of made this "blindly", there will probably be issues and bugs
> Regenerate api keys

- docs/docs/notification-center/getting-started.md
This PR deals with a Docs update and fixes the minor typos and grammatical errors for the above-said page.
- **Why this change was needed?**
This PR fixes https://github.com/novuhq/novu/issues/1339
> Copyedit the Getting Started Page under Notification Center in Novu Docs Website

- README.md
> Added how to get Novu's swag

- providers/discord/src/lib/discord.provider.spec.ts
> test describe wrong

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/sa.ts
This PR adds Sanskrit Language support for Novu.
This PR fixes https://github.com/novuhq/novu/issues/1084
> [NV-796] - i18n - Sanskrit Support

- docs/docs/channels/chat/discord.md
- docs/docs/channels/chat/index.md
- docs/docs/channels/chat/slack.md
- docs/docs/channels/email/index.mdx
- docs/docs/channels/email/sendgrid.md
I have fixed typos and removed redundant words in five documentation files.
To make the documentation pages more clear.
> (docs): fix typos in multiple files

- apps/web/src/pages/activities/services/chart-bar/option.service.ts
The month number broken, should be the month day.
> fix: [NV-933] - Activity Feed

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/or.ts
This PR adds the Odia Language support for Novu
- **Why this change was needed?**
This PR fixes https://github.com/novuhq/novu/issues/1327.
> NV-1327 i18n - Odia Support

- apps/api/src/app/change/e2e/promote-changes.e2e.ts
- apps/api/src/app/events/e2e/digest-events.e2e.ts
- apps/web/src/api/hooks/use-subscribers.ts
- apps/web/src/pages/subscribers/SubscribersListPage.tsx
- apps/widget/public/iframeResizer.contentWindow.js
- docs/docs/notification-center/iframe-embed.md
- docs/docs/overview/quick-start.md
- libs/embed/README.md
- Docs update and it updates variable names
- Just a bit picky with spelling because it improves readability!
I've renamed some variables and I've renamed their references as well.
If I've missed something, please do tell me!
> Fix some typos

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/ne.ts
- This PR introduces support for the Nepali language for the @novu/notification-center component interface
- For internationalization
- Fixes #1355
> Add Nepali language support for @novu/notification-center

- apps/widget/cypress/e2e/shell-embed.spec.ts
- apps/widget/cypress/global.d.ts
- apps/widget/cypress/plugins/index.ts
- apps/widget/cypress/support/commands.ts
- apps/widget/src/components/notification-center/NotificationCenterWidget.tsx
- libs/embed/src/embed.ts
- packages/notification-center/src/components/notification-center/components/FeedsTabs.tsx
- **What kind of change does this PR introduce?** (feature)
Adding test to new seen read feature.
In order to validate that we do not break the expected behavior.
WIP
> Seen read test

- docs/docs/overview/architecture.md
- This is a documentation update
- Typo and grammatical error were fixed
- architecture.md was updated
> Fix typo in architecture.md

- docs/docs/overview/introduction.md
Fixed some grammatical errors using Grammarly
For better reading experience
> Grammatical errors fixed

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/pl.ts
Polish language translations
Resolves https://github.com/novuhq/novu/issues/1378
Don't think there's any more to add.
> i18n - Polish support

- README.md
We needed to make change to the text on the banners - should be fine now.
> Updated the header bannners

- .github/ISSUE_TEMPLATE.md
- It's a fix which closes #1392 
closes #1392  because the check list squares were not placed properly.
> fixed bug in template

- README.md
Grammar Correction in README.md file
- doc update (grammar correction in README.md file)
> Grammar Correction in README.md file

- docs/docs/overview/introduction.md
I have updated docs - `Introduction.md` file.
This closes issue #1390 
This is under hacktoberfest. Kindly review and merge it.
> Update line in introduction.md file

- docs/docs/channels/email/postmark.md
Added docs for Postmark using the SendGrid example.
The intent is to provide helpful docs for users to use novu's platform easily.
Created by seeing SendGrid as an example.  Willing to take any feedback and make the required changes.
Ref: #1349
> Added Docs page for Postmark

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/cs.ts
Addition of the Czech language.
This PR expands the variety of supported languages.
> i18n – Czech support

- docs/docs/platform/templates.md
Documentation update
For people to understand easily
Edited templates.md
> Fix Grammatical errors in templates.md

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/ta.ts
Feature and Docs update: 
This PR adds Tamil Language support for Novu.
This PR fixes #1405
> i18n - Tamil Support

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/pu.ts
What kind of change does this PR introduce?
This PR adds Punjabi Language support for Novu.
Why this change was needed? (You can also link to an open issue here)
This PR fixes https://github.com/novuhq/novu/issues/1374
> i18n - Punjabi Support

- docs/docs/platform/subscribers.md
- Documentation update
- For people to understand documentation easily
- Updated subscribers.md
> Fix grammatical errors in subscribers.md

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/ma.ts
- packages/notification-center/src/i18n/languages/mr.ts
This PR adds Marathi Language support for Novu.
This PR fixes: #1367
> feat: i18n support for marathi

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/ko.ts
Added support for korean language
> feat: i18n support for Korean language

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/pa.ts
Corrected the language code of Panjabi language from pu to pa
> Language code correction: punjabi

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/hu.ts
> feat: i18n support for Hungarian language

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/id.ts
Indonesian language translations
Resolves #1422 
Don't think there's any more to add.
> chore(i18n): add Indonesian language support

- libs/dal/src/index.ts
- libs/dal/src/repositories/execution-details/execution-details.entity.ts
- libs/dal/src/repositories/execution-details/execution-details.repository.ts
- libs/dal/src/repositories/execution-details/execution-details.schema.ts
- libs/dal/src/repositories/execution-details/index.ts
- **What kind of change does this PR introduce?** (Feature)
One of the new things to be created for the Advanced Debugging project is to create a new Entity called `ExecutionDetails` that will store in the database all the information related to the feedback and the details of every notification triggered in the system.
[https://linear.app/novu/issue/NV-1019/execution-details-repository](https://linear.app/novu/issue/NV-1019/execution-details-repository)
N/A
> feat(dal): execution details repository implementation

- apps/web/src/components/auth/CreateOrganizationForm.tsx
- apps/web/src/components/auth/LoginForm.tsx
- apps/web/src/components/auth/PasswordResetForm.tsx
- apps/web/src/components/auth/PasswordResetRequestForm.tsx
- apps/web/src/components/auth/SignUpForm.tsx
- apps/web/src/components/templates/VariableManager.tsx
- apps/web/src/components/templates/email-editor/EmailContentCard.tsx
- apps/web/src/components/templates/in-app-editor/TemplateInAppEditor.tsx
- apps/web/src/components/templates/notification-setting-form/NotificationSettingsForm.tsx
- apps/web/src/pages/activities/ActivitiesPage.tsx
- apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx
- apps/web/src/pages/invites/MembersInvitePage.tsx
- apps/web/src/pages/settings/tabs/BrandingForm.tsx
- apps/web/src/pages/settings/tabs/components/Security.tsx
- apps/web/src/pages/templates/filter/FilterModal.tsx
- apps/web/src/pages/templates/workflow/DelayMetadata.tsx
- apps/web/src/pages/templates/workflow/DigestMetadata.tsx
This PR updates the form validation across the web project, unifying it by delegating form validation to react-hook-form / zod throughout all forms in the web project. Further all Input fields had their error provided from their respective Controller's `fieldState` (some had it missing, some had fairly long expressions instead; this way everything is consistent and fairly concise).
#1345 
\-
> fix: NV-904 Errors in Integration Store

- docs/docs/platform/subscribers.md
Copyedit the Subscribers Page under Platform in Novu Docs Website 
PR linked 
#1404
> Copyedit the Subscribers Page under Platform in Novu Docs Website 

- apps/api/src/app/testing/usecases/seed-data/seed-data.usecase.ts
- apps/web/cypress/global.d.ts
- apps/web/cypress/plugins/index.ts
- apps/web/cypress/support/commands.ts
- apps/web/cypress/tests/auth.spec.ts
- apps/web/cypress/tests/invites.spec.ts
- apps/web/src/pages/auth/InvitationPage.tsx
- libs/testing/package.json
- libs/testing/src/index.ts
- libs/testing/src/user.service.ts
- libs/testing/src/user.session.ts
- pnpm-lock.yaml
- **What kind of change does this PR introduce?** (Bug fix)
When inviting an existing user to novu who is already logged in, while visiting the invite link: http://localhost:4200/auth/invitation/%3CTOKEN%3E the user is prompted that he is already logged in and asks him to log out first. When clicking on the CTA button it goes back to login screen and the invite flow is ignored, the user then accidentally creates a new account instead of joining a new one. 
- **Why this change was needed?**
https://linear.app/novu/issue/NV-940/bug-when-inviting-existing-logged-in-user-to-the-system
N/A
> fix(auth): during invitation if active session logout redirect

- docs/docs/community/monorepo-structure.md
I am new to github . so I hope this adds value
> Updated the monorepo

- docs/docs/platform/templates.md
> Fixed minor grammatical error

- CONTRIBUTING.md
Signed-off-by: Abhilipsa Sahoo <abhilipsasahoo03@gmail.com>
docs update: Minor improvement in the CONTRIBUTING.md file 
To fix issue #1499
> docs: minor fix in CONTRIBUTING.md file

- docs/docs/platform/digest.md
-updated the sentence grammatical error in docs
this change was needed because previous sentence was not at all correct, third form "delivered" was used which should be replaced with first form "delivers"
> updated the sentence grammatical error in docs

- README.md
It introduces docs fix. I have updated the Report Bug link in the `README.md` file
This PR closes issue #1454  
KIndly review and merge it.
> Update "Report bug" link in README

- .github/PULL_REQUEST_TEMPLATE.md
fix #1483
fix of pull request template typo
see  #1483 
> fix: pull request template typo

- docs/docs/platform/delay.md
Fixed delay.md by adding necessary changes in grammars 
This change was necessary because some sentences were not grammatically correct
such as "amount of time specified elapses" changed to "specified period of time has elapsed"
Sentences started with "Will determine how long...." to "Regular Delay will determine"
> Fixed delay.md by adding necessary changes in grammars 

- apps/api/src/app/events/usecases/process-subscriber/process-subscriber.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-chat.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-in-app.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-push.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts
- libs/dal/src/repositories/job/job.entity.ts
- libs/dal/src/repositories/job/job.schema.ts
- libs/dal/src/repositories/message/message.entity.ts
- libs/dal/src/repositories/message/message.schema.ts
Add providerId to job before it is queued
So we can show the provider in the workflow feed and step modal
> feat: add provider id to job entity and job id to message entity

- apps/api/src/app/execution-details/e2e/get-execution-details.e2e.ts
- apps/api/src/app/execution-details/execution-details.controller.ts
- apps/api/src/app/execution-details/usecases/get-execution-details/get-execution-details.command.ts
- apps/api/src/app/execution-details/usecases/get-execution-details/get-execution-details.usecase.ts
Change path param to query params for execution details endpoint.
Makes more sense to have it as query params instead of path params.
> refactor: execution details endpoint

- docs/docs/overview/architecture.md
Fixed grammatical errors in architecture.md
This change was needed for better readability 
> Fixed grammatical errors in architecture.md

- docs/docs/platform/environments.md
Updated environments.md by fixing errors
- changed "promote the to Production..." -> "promote to the Production"
- sentence started from "Will..." changed to "It ..."
> Updated environments.md by fixing errors

- docs/docs/notification-center/react-components.md
Updated react-components.md by fixing minor comma errors
proper use of commas in the document is required for good readability.
> Updated react-components.md by fixing minor comma errors

- docs/docs/channels/chat/slack.md
Updated slack.md by fixing docs
**Made these changes for better readability**
- made changes in sentences like "here you could generate a test webhook for your own workspace to test your integration with."---->"To test your integration with your workspace, you could generate a test webhook here"
- "In this guide, we will perform the flow........ " ----->"This guide will walk you through the steps"
> Updated slack.md by fixing docs

- docs/docs/community/monorepo-structure.md
Updated monorepo-structure.md by fixing docs
The changes were needed for better readability---
- "PNPM help with reducing the....." ----->"PNPM reduces the installation time and ........"
- removed the extra use of will
> Updated monorepo-structure.md by fixing docs

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/vi.ts
> i18n - adding Vietnamese language support.

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/no.ts
Feature to add i18n - Norwegian Language Support
Fixes issue 🚀 Feature: i18n - Norwegian Support  #1556 
-Kindly review and merge this PR
> i18n - Norwegian support

- CONTRIBUTING.md
Bug Fix
Since the previous link has expired, members were not able to join the discord server!
> Updated Discord Server Invite Link

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/ig.ts
Added the feature of Igbo language support #1586 
this change was needed for the translation support
I have given this pull request after contacting the native speaker @codewarsfx , he is an open source contributor from Nigeria
> Feature to add i18n - Igbo Language support

- packages/notification-center/src/i18n/languages/hi.ts
चिन्हित is more correct than निशान
> Improve the translation for hindi

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/sv.ts
Feature to add i18n - Swedish Language Support
Fixes issue 🚀 Feature: i18n - #1581 
-Kindly review and merge this PR
> Feature to add i18n - Swedish Language Support

- docs/docs/notification-center/react-components.md
fixed react-components.md
Corrected language indonesia to indonesian in react-components.md
> Bug fixes: fixed react-components.md

- docs/docs/platform/subscribers.md
Updated subscribers.md with necessary changes
This changes was needed to improve the readability of the sentences
"We recommend using the internal id your application uses for a specific user."---->"We recommend that you use the internal id that your application uses for a specific user..."
"In case the user want to use chat channel, he will need to....."------>"Users who wish to use chat channels will need to set their ..."
> Updated subscribers.md with necessary changes

- packages/notification-center/src/i18n/languages/hi.ts
It adds one more word for the translation to hindi
Because settings word was not translated to hindi
> Added Word For Hindi Translation

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/th.ts
Feature to add i18n - Thai Language Support
Fixes issue 🚀 Feature: i18n - Thai Language Support #1594 
> i18n - Thai Language support

- docs/docs/channels/chat/discord.md
- docs/docs/channels/chat/slack.md
Updated slack.md and discord.md by fixing documentation
Changes were needed for improved readability and consistency
- "Go to `Manage Distribution`, at the bottom of the page make sure to tick the..." --> "Go to `Manage Distribution` and at the bottom of the page make sure to tick..."
- Replaced improper commas with periods and made new sentences
- Changed past tense instruction verbs to present tense
- Fixed typo and made all references to `Slack` consistent
> Update slack.md and discord.md by fixing documentation

- docs/docs/overview/introduction.md
Fixed the introduction.md docs
These changes were needed for better readablity as these are initial docs
- "Building a notification layer is the thing that we as developers have to do for every new project."----->"Developing a notification layer is the first thing we do when designing a new application."
- "Need to add a new provider? Switch your email provid........"->"Do you need to add a new provider? Consider switching your email "
- " And oh boy how wrong we were......"----->"Oh boy, how wrong we were......."
> Fixed the introduction.md 

- packages/node/src/lib/changes/changes.spec.ts
- packages/node/src/lib/changes/changes.ts
-Bug Fix
-Tests for the Changes Module were failing
> fix: Tests failing

- packages/notification-center/src/i18n/languages/ru.ts
Update ru translation
Add missing translation message of Setting to ru
> feat: add missing ru translation

- packages/notification-center/src/i18n/languages/bn.ts
- 
fixes mistranslation
fixes #1550 
> corrected mistranslation of notifications in bn.ts translation file

- README.md
> Updating the link in the provider section

- docs/docs/community/monorepo-structure.md
docs update
While commiting code changes getting below error
`MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]`
> fix: Changes heading level to be consistent with markdownlint

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/km.ts
feature: add Khmer language
Closes https://github.com/novuhq/novu/issues/1561
> feat(i18n): add km(Khmer) language

- docs/docs/platform/delay.md
Docs
There was a typo which I corrected
> Corrected a typo error

- packages/notification-center/src/i18n/languages/fa.ts
Added translation of settings to Persian!
> Added word in Persian translation

- docs/docs/overview/quick-start.md
Updated quick-start.md by fixing necessary changes 
Capitalize the words as well as added necessary commas for better readability in quickstart.md
> Updated quick-start.md by fixing necessary changes 

- docs/docs/platform/activity-feed.md
Fixed activity-feed.md by adding changes
added github link of novu in docs
added the commas in place for better readability
> Fixed activity-feed.md by adding changes

- README.md
- **What kind of change does this PR introduce?** Documentation update
- **Why was this change needed?** Check the issue description [here](https://github.com/novuhq/novu/issues/1619)
> grammatical error in readme fixed

- CONTRIBUTING.md
- apps/web/cypress/tests/layout/side-menu.spec.ts
- apps/web/src/components/layout/components/SideNav.tsx
- docs/docusaurus.config.js
- packages/cli/README.MD
- packages/node/README.md
- In a mixed territory. I would say, you could view it as docs update  since I am just updating the links.
- To standardize a discord link throughout the entire codebase
Addresses issue #1622
> chore: standardize novu's discord server link throughout the codebase

- packages/node/README.md
docs update
Update some information.
> Update @novu/node readme

- apps/api/src/app/shared/commands/base.command.ts
- apps/api/src/app/shared/framework/response.interceptor.ts
- apps/webhook/src/shared/framework/response.interceptor.ts
- apps/ws/src/shared/framework/response.interceptor.ts
- libs/dal/src/repositories/base-repository.ts
- packages/application-generic/src/commands/base.command.ts
fix: deprecated class-transformer methods
https://github.com/typestack/class-transformer/blob/develop/src/index.ts#L15
https://github.com/typestack/class-transformer/blob/develop/src/index.ts#L66
> fix: deprecated class-transformer methods

- docs/docs/platform/digest.md
Docs update
For reducing the errors of the documentation
> Corrected some typos and punctuation

- apps/api/src/app/activity/dtos/activities-response.dto.ts
- apps/api/src/app/notification-template/usecases/get-notification-templates/get-notification-templates.usecase.ts
- apps/api/src/app/subscribers/subscribers.controller.ts
- apps/api/src/app/widgets/dtos/message-response.dto.ts
- apps/api/src/app/widgets/e2e/get-unseen-count.e2e.ts
- apps/api/src/app/widgets/usecases/get-notifications-feed/get-notifications-feed.usecase.ts
- libs/dal/src/repositories/message/message.repository.ts
fix: add pagination for subscriber feed endpoint `/v1/subscribers/:subscriberId/notifications/feed`
#1433 
> fix: add pagination support for subscriber feed endpoint

- packages/notification-center/src/i18n/languages/ar.ts
Translated the word settings to arabic!
> Added Translation Arabic Word

- docs/docs/overview/quick-start.md
Fixed punctuation and grammatical errors. Also improved the wording to express our document better.
Docs update
To make our documentation better.
> Fixed some documentation errors

- apps/web/src/components/layout/components/AuthContainer.tsx
Improve the responsiveness of AuthContainer by fixing its alignment for <= 1100 screen width.
AuthContainer has weird alignment on smaller screen sizes
Screenshot of the fix
> style: improve responsiveness of auth container

- docs/docs/community/run-locally.md
Docs Update
Improve the quality of documentation
> Documentation error fixed

- packages/notification-center/src/i18n/languages/fi.ts
#1668  Translation for _settings_ is visible now.
> Added the 'settings' translation

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/ms.ts
Malay language translations
Resolves #1671 
Don't think there's any more to add.
> chore(i18n): add Melayu language support

- apps/api/src/app/change/changes.controller.ts
- apps/api/src/app/change/dtos/change-request.dto.ts
- apps/api/src/app/change/dtos/change-response.dto.ts
- apps/api/src/app/change/usecases/get-changes/get-changes.command.ts
- apps/api/src/app/change/usecases/get-changes/get-changes.usecase.ts
- apps/api/src/app/notification-template/usecases/get-notification-templates/get-notification-templates.command.ts
- apps/web/src/api/changes.ts
- apps/web/src/api/hooks/use-environment-changes.ts
- apps/web/src/components/changes/ChangesTableLayout.tsx
- apps/web/src/pages/changes/PromoteChangesPage.tsx
- libs/dal/src/repositories/change/change.repository.ts
feature: add pagination in changes page and api
To handle long list of changes
https://user-images.githubusercontent.com/39362422/194744348-468a1ae1-c59d-435f-9db8-18f249e08a33.mov
> feat: add pagination in changes page and api

- README.md
> Minor grammatical changes in Readme file

- packages/notification-center/src/i18n/languages/uk.ts
This is a bug fix required for adding the settings translation within the Ukrainian translations file.
see issue #1674
> Added the missing Ukrainian translation

- README.md
- docs/docs/community/monorepo-structure.md
- packages/cli/README.MD
- packages/node/README.md
- packages/stateless/README.md
docs update
Keep every providers lists up to date.
Some providers are not added: APNs, MailerSend, FireText. Should I add them?
> Update providers list in readmes and docs

- docs/docs/notification-center/iframe-embed.md
- What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
This PR introduces grammar amendments for the iframe docs.
- Why was this change needed? (You can also link to an open issue here)
The sentence flow was previously clunky and difficult to understand, these changes make the sentences flow better and therefore the docs are easier to read and to understand.
> Fix Grammatical errors and sentence flows

- docs/docs/channels/sms/sns.md
> Updated sns.md

- docs/docs/channels/sms/telnyx.md
- Documentation for Telnyx.
- #1659 
- In Telnyx [documentation](https://developers.telnyx.com/docs/v2/messaging), there is mentioned a [auth](https://portal.telnyx.com/#/app/auth/v2) section in their portal where the API keys located, but as I could not find it, I have not included it.
> docs: added documentation for telnyx

- packages/notification-center/src/i18n/languages/bn.ts
This change poses an improvement over [furtidev's changes](https://github.com/novuhq/novu/pull/1692) to the Bengali language and makes it cope with English to provide a more casual approach.
Some Bengali people might not actually opt for the language if its formal. This has been done to interact with them well, as opposed to some other products supporting the language.
> Feat: Bengali Language Merged with English

- docs/docs/channels/sms/SMS77.md
- docs/docs/channels/sms/index.md
Created documentation page for [NV-919] #1657 
> SMS77 documentation page

- apps/api/src/app/events/events.module.ts
- apps/api/src/app/events/usecases/add-job/add-job.usecase.ts
- apps/api/src/app/events/usecases/process-subscriber/process-subscriber.usecase.ts
- apps/api/src/app/events/usecases/run-job/run-job.usecase.ts
- apps/api/src/app/events/usecases/send-message/digest/digest.usecase.ts
- apps/api/src/app/events/usecases/send-message/digest/get-digest-events.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-chat.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-in-app.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-push.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message-type.usecase.ts
- apps/api/src/app/events/usecases/send-message/send-message.command.ts
- apps/api/src/app/events/usecases/send-message/send-message.usecase.ts
- apps/api/src/app/events/usecases/verify-payload/verify-payload.usecase.ts
- apps/api/src/app/execution-details/dtos/execution-details-response.dto.ts
- apps/api/src/app/execution-details/e2e/get-execution-details.e2e.ts
- apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.command.ts
- apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.spec.ts
- libs/dal/src/repositories/execution-details/execution-details.entity.ts
- libs/dal/src/repositories/execution-details/execution-details.schema.ts
Create execution details where logs today are created.
So we can start to use these in frontend
> feat: create execution details where logs today are created

- apps/web/src/pages/integrations/components/ProviderCard.cy.tsx
Adds cypress tests for `apps/web/src/pages/integrations/components/ProviderCard.tsx` component
Resolves #1658
> feat: Add cypress tests for ProviderCard

- docs/docs/channels/email/emailjs.md
Created a Email.js provider documentation page
> Created a Email.js provider documentation page #1665

- README.md
- packages/cli/README.MD
- packages/node/README.md
docs update
There were some inconsistent links to request feature and report bug throughout the codebase
This PR edits the links to redirect user to proper new issue templates when clicking Request Feature or Report Bug Throughout the codebase
> fix: links to request feature and report bug throughout the codebase

- docs/docs/channels/email/mailjet.md
Fixes: [[NV-922] - Create a Twillio provider documentation page](https://github.com/novuhq/novu/issues/1663)
This change was needed because documentation is currently lacking in the areas of setup for many of these channels which would be a lot easier on users.
> docs: Added Mailjet provider documentation page

- docs/docs/overview/architecture.md
Doc Update [ architecture.md ]
Improved Application Architecture Diagram 
fixes #1690
> Updated Architecture Diagram

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/af.ts
Added Afrikaans language support for i18n
Fixes issue #1725
> feat: i18n support for Afrikaans language

- docs/docs/channels/push/expo.md
Full fix for #1735 from an assignee.
Incorrect punctuation doesn't look good and influents text readability.
> fix: full #1735 fix

- docs/docs/channels/email/sendinblue.md
> docs: Add Send In Blue provider documentation page

- docs/docs/channels/email/nodemailer.md
Docs update for Nodemailer integration
https://github.com/novuhq/novu/issues/1661
> feat: add nodemailer integration docs

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/be.ts
> feat: i18n support for Belarusian language

- docs/docs/community/code-conduct.md
fix #1734 
Link was just pointing to the mozilla repo
> Updated link to enforcement ladder [ code-conduct.md ]

- docs/docs/channels/email/sendinblue.md
Docs Update: Fixes typo in sendinblue.md
Close #1746 
To Improve documentation
> docs: Fix Typos in sendinblue.md

- providers/postmark/src/lib/postmark.provider.spec.ts
Fixes failing test in postmark provider
Resolves #1755 
> fix: postmark tests

- apps/web/src/components/auth/SignUpForm.tsx
Refactor
Updated the `terms & conditions` and `privacy policy` links to open in a new tab.
> refactor: updated links to open in a new tab

- providers/slack/README.md
> docs(slack): small typo fix

- docs/docs/notification-center/react-components.md
> docs: Fix typo in react-components.md

- README.md
docs update 
There are lot of grammar mistake and typos which should be fixed!
> Fixed all grammar issues and typos in README.md

- docs/docs/channels/sms/twilio.md
@p-fernandez @scopsy Please review
Docs update
To make the quality of the document better
> Fixed documentation errors

- .github/labeler.yml
- .github/workflows/pr-labeler.yml
Automatically adds a PR label depending on the code area that was changed in the PR. Following up the conversation and motion @p-fernandez started.
To help consolidate and automate the process of adding labels to PR to easily identify affected changes
More globs could be added if I missed anything :).
> feat(): Add auto PR labeler

- docs/docs/community/monorepo-structure.md
docs Update: Improves monorepo documentation
To keep an improved and consistent documentation.
Close #1768 
> docs: Improve monorepo documentation

- packages/notification-center/src/components/notification-center/components/layout/tabs/Tabs.styles.ts
- packages/notification-center/src/store/novu-theme.context.ts
> Tab Border Color Notification center

- apps/web/src/components/layout/components/HeaderNav.tsx
Implement #1781.
***The reason has already been mentioned in the issue.***
> feat: implement #1781

- packages/nest/README.md
Docs update (Typo)
`Receiver` spelling was written as `reciever`.
> Fix `receiver` spelling.

- .github/workflows/milestone-assign.yml
- .github/workflows/scripts/milestone-assigner.js
> feat: assign milestone

- README.md
Readme Update.
#1807 
For proper rendering of contributors list from GitHub link.
> Contributors section properly loading in README

- README.md
- Documentation update
- **Why was this change needed?**
- Table of Content: link to "Need Help?" part doesn't work
> Fix "Need Help?" link in the Readme file

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/sq.ts
Added i18n support for Albanian
Fixes #1824
> feat: i18n support for Albanian

- apps/web/src/components/templates/SaveChangesModal.tsx
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
fix
Close save changes modal and show error that something is missing if saved is clicked and there are errors in workflow
> Fix modals state debugging

- apps/web/src/api/activity.ts
- apps/web/src/components/activity/ExecutionDetailsModal.tsx
- apps/web/src/components/activity/ExecutionDetailsSteps.tsx
- apps/web/src/components/utils/GotAQuestionButton.tsx
- apps/web/src/design-system/config/colors.ts
- apps/web/src/pages/activities/ActivitiesPage.tsx
- apps/web/src/pages/activities/components/ActivityItem.tsx
- apps/web/src/pages/activities/components/ActivityList.tsx
Create the UI to show the execution details of the different steps of the jobs executed during the triggering of a notification.
So users can see broad details of what's happening and help them to debug cases where it is failing.
> feat(web): execution details list inside modal

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/lt.ts
Implement #1839.
Add new language.
> feat: add lithuanian i18n support

- packages/notification-center/src/i18n/languages/ta.ts
- **What kind of change does this PR introduce?** Fixes translation errors in the Tamil i18n file
- **Why was this change needed?** Links to #1754 
- **Other information**: NA
> [fix] Fix Tamil translation errors

- apps/web/src/components/activity/ExecutionDetailsModal.tsx
- apps/web/src/components/templates/ExecutionDetailsModalWrapper.tsx
- apps/web/src/components/templates/TestWorkflowModal.cy.tsx
- apps/web/src/components/templates/TestWorkflowModal.tsx
- apps/web/src/pages/templates/editor/TemplateEditorPage.tsx
> Test workflow - open execution details modal

- README.md
Now the user can go to the official website of novu with a single click.
In Readme.md file
Resolved #1848
> Hyperlinked the novu logo.

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/lv.ts
Implement #1850.
Add a new language.
> feat: Latvian language i18n support

- README.md
- **What kind of change does this PR introduce?** Docs update
- **Why was this change needed?** #1847
> [feat] Add section about Jarvis

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/bh.ts
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Added i18n support for Bihari language
> i18n support for Bihari language

- docs/docs/community/faq.md
- **What kind of change does this PR introduce?** Added an FAQ - "How do I customize messages on Novu?"
- **Why was this change needed?** I feel like this is one of the first questions that a new user would ask
- **Other information**: NA
> [docs] FAQ: How do I customize messages on Novu?

- packages/notification-center/src/i18n/languages/fr.ts
Just an modification on French translation
It was a minor typo but still needed to be corrected 
> very minor typo in fr translation

- docs/docs/platform/subscribers.md
Spotted some crucial grammatical error.
Thank you
> Improved subscriber.md

- apps/web/src/components/activity/ExecutionDetail.tsx
- apps/web/src/components/activity/ExecutionDetailShowRaw.tsx
- apps/web/src/components/activity/ExecutionDetailsModal.tsx
- apps/web/src/components/activity/ExecutionDetailsStepContent.tsx
> fix: show and hide raw content of detail

- docs/docs/notification-center/react-components.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/am.ts
Feature: Amharic language notification support added
For internationalization
> i18n Amharic language support

- apps/web/src/components/templates/TriggerSnippetTabs.tsx
- apps/web/src/pages/quick-start/components/OnboardingSteps.tsx
- apps/web/src/pages/settings/tabs/InAppCenterCard.tsx
Bug fix
This UI issue causes on medium/small screens, looks strange, eg:
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/198546407-c7cc715c-48fe-4d14-a223-4d1bd3083d4b.png) | ![image](https://user-images.githubusercontent.com/4408379/198546288-3dedfddd-1136-4d47-8286-2acd0ebbb333.png) |
> fix: make visible code block border on scroll

- docs/docs/overview/quick-start.md
This changes the minor but crucial grammatical and spelling errors.
docs
> chore: Improved quick-start.md

- docker/Readme.md
- docs/docs/overview/docker-deploy.md
- Docs updates for the deploy using docker pages
Improve Readability.
> docs: Improve deploy using docker pages

- docs/docs/overview/architecture.md
- Docs updates for the Architecture page.
Improve Readability.
> docs: Improve Architecture page

- CONTRIBUTING.md
- docs/docs/community/monorepo-structure.md
- docs/docs/community/run-locally.md
- docs/docs/overview/architecture.md
- docs/docs/overview/quick-start.md
> docs: fixed typo's 🛠

- apps/api/src/app/events/usecases/add-job/add-job.usecase.ts
- apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.command.ts
- apps/web/src/components/activity/ExecutionDetailsStepHeader.tsx
new delay execution detail:
suggestions for changes in detail strings:
> Small details changes - debugging

- apps/web/src/pages/quick-start/components/TriggerCard.tsx
UI improvement
Trigger cards with example code usage must be explicitly clickable in UI, because personally I had not even realize it if I didn't accidentally click on the Node.js card. So  a card with hidden content should have the usual pointer cursor and hover state. 
> refactor: make trigger cards clickable

- docs/docs/notification-center/react-components.md
- docs/docs/overview/quick-start.md
- packages/notification-center/src/i18n/lang.ts
- packages/notification-center/src/i18n/languages/sm.ts
- Feature: i18n Samoan language support added
closes #1890
- For convenience and ease
- I know this language
> i18n Samoan language support 

- docs/docs/community/run-locally.md
docs update
It can improve the doc a little.
Just fix some typos.
> fix(doc): fix typos in "Run Novu locally" doc

- docs/docs/overview/quick-start.md
- Docs updates for the Quick Start page.
Improve Readability.
> docs: Improve quick start

- docs/docs/community/run-locally.md
- Docs updates for the Run Novu locally page.
Improve Readability.
> docs: Improve Run Novu locally docs

- packages/node/src/index.ts
- packages/node/src/lib/feeds/feeds.interface.ts
- packages/node/src/lib/feeds/feeds.spec.ts
- packages/node/src/lib/feeds/feeds.ts
- packages/node/src/lib/novu.ts
Completes the [feeds module](https://docs.novu.co/api/create-feed/ for @novu/node.
This resolves #1324 
> feat: Add Feeds Module to node package

- apps/api/src/app/events/usecases/process-subscriber/process-subscriber.usecase.ts
- apps/web/src/components/activity/ExecutionDetailTrigger.tsx
- apps/web/src/components/activity/ExecutionDetailsAccordion.tsx
- apps/web/src/components/activity/ExecutionDetailsModal.tsx
- apps/web/src/components/activity/ExecutionDetailsStepContent.tsx
- libs/dal/src/repositories/notification/notification.entity.ts
- libs/dal/src/repositories/notification/notification.repository.ts
- libs/dal/src/repositories/notification/notification.schema.ts
https://linear.app/novu/issue/NV-1113/subscriber-variables-doesn-not-exist-in-trigger
> fix: so email and phone are show on subscriber in trigger example

- apps/web/src/components/activity/ExecutionDetailsFooter.tsx
> fix: remove box shadow from got a question button

- apps/web/src/design-system/icons/general/Digest.tsx
> feat: add default width and height for digest icon

- docs/docs/community/community-usecase-projects.md
> feat: add community usecase projects docs page

- docs/docs/community/community-usecase-projects.md
- docs/docs/community/projects-and-articles.md
> fix: docs about projects and articles

- apps/web/src/components/activity/ExecutionDetailsStepHeader.tsx
> fix: so success message in execution modal will be last detail message

- README.md
- apps/web/README.md
- packages/cli/README.MD
- packages/node/README.md
- packages/stateless/README.md
> Fix grammar and typos in the READMEs

- apps/web/src/components/templates/TestWorkflowModal.tsx
Add error message of invalid json in the test workflow
> feat: add error of invalid json on test workflow params

- packages/stateless/src/lib/provider/provider.interface.ts
- providers/mandrill/src/lib/mandrill.provider.ts
- providers/postmark/src/lib/postmark.provider.ts
- providers/telnyx/src/lib/telnyx.provider.ts
- providers/twilio/src/lib/twilio.provider.ts
Cleaning up after a few provider webhooks have been implemented
> Refactor webhook provider statuses

- apps/web/src/components/activity/ExecutionDetailsModal.tsx
> feat: add text about update frequency

- apps/web/src/components/activity/ExecutionDetailsModal.tsx
https://linear.app/novu/issue/NV-1134/open-details-debugging-modal-centered-on-screen
Centered the debugging modal
https://user-images.githubusercontent.com/29251776/199718101-ccb1dd88-7fdc-44c9-b3b1-0efdd2e6f70f.mov
> fix: center the debugging modal

- apps/web/src/components/activity/ExecutionDetailsAccordion.tsx
- apps/web/src/pages/activities/components/ActivityItem.tsx
- apps/web/src/pages/activities/components/ActivityList.tsx
Adds hover styles to activity list items.
To get aligned with designs and rest of features relative to Advanced Debugging.
AFTER
> feat(web): add hover styles to activity list items

- apps/api/src/app/notifications/dtos/activities-response.dto.ts
- apps/web/src/components/activity/ExecutionDetailTrigger.tsx
- apps/web/src/components/activity/ExecutionDetailsAccordion.tsx
- apps/web/src/components/activity/ExecutionDetailsModal.tsx
- apps/web/src/components/activity/ExecutionDetailsStepContent.tsx
- libs/dal/src/repositories/notification/notification.repository.ts
Probably during the trimming of the data from the API I removed the value used to fill the workflow data in the trigger snippet.
To get again the full information for the trigger snippet.
> fix(web): pass the values to trigger snippet

- apps/web/src/components/activity/ExecutionDetailTrigger.tsx
- apps/web/src/components/templates/TriggerSnippetTabs.tsx
- apps/web/src/pages/activities/components/DigestedStep.tsx
> Nv 1136 show only the json object on trigger information window

- apps/web/src/components/activity/ExecutionDetailsStepHeader.tsx
Better pending messages for digest and delay
> feat: improve pending messages for digest and delay

- apps/web/src/components/activity/ExecutionDetailsModal.tsx
- apps/web/src/pages/activities/hooks/useNotificationStatus.ts
> Stop refetch when status is not pending 

- apps/api/src/app/auth/auth.controller.ts
- apps/web/src/components/auth/LoginForm.tsx
- apps/web/src/components/auth/SignUpForm.tsx
- apps/web/src/components/layout/components/PartnerIntegrationLayout.tsx
- apps/web/src/components/partner-integrations/vercel/LinkMoreProjectRow.tsx
- apps/web/src/components/partner-integrations/vercel/LinkProjectContainer.tsx
- apps/web/src/pages/partner-integrations/LinkVercelProjectPage.tsx
> refactor: updated the link for create organization redirect

- packages/notification-center/src/components/notification-center/components/user-preference/SubscriberPreference.tsx
> feat: add scrolling to user preference list

- apps/web/src/pages/activities/components/ActivityItem.tsx
- libs/dal/src/repositories/subscriber/subscriber.repository.ts
Fixed the issue of rendering deleted subscribers.
bug fix.
https://discord.com/channels/895029566685462578/1040011241722220576
> fix: render deleted subscriber

- apps/web/src/components/widget/NotificationCenterWidget.tsx
- packages/notification-center/src/components/notification-center/components/FeedsTabs.tsx
- packages/notification-center/src/components/popover-notification-center/components/Popover.tsx
- packages/notification-center/src/hooks/use-notifications.hook.ts
- packages/notification-center/src/hooks/use-unseen-count-controller.hook.ts
- packages/notification-center/src/shared/interfaces/index.ts
- packages/notification-center/src/store/notifications-provider.context.tsx
- packages/notification-center/src/store/unseen-provider.context.tsx
fix breaking changes
unnecessary breaking changes were made that will brake code base.
> version fix - breaking changes

- packages/client/src/api/api.service.ts
- packages/notification-center/src/store/notifications-provider.context.tsx
Remove the use of deprecated API endpoint
The old endpoint will be removed in the future so we need to make sure we do not use it.
> remove use of deprecated api endpoint

- .eslintrc.js
- apps/web/public/env-config.js
- apps/web/src/pages/settings/tabs/BrandingForm.tsx
- apps/web/src/pages/settings/tabs/InAppCenterCard.tsx
**Bug fix**
<ul>
<li>[**fixed this error**](https://stackoverflow.com/questions/64933543/parsing-error-cannot-read-file-tsconfig-json-eslint) </li>
<li>changed language from JSX to javascript in Prism InAppCenterCard.tsx</li>
<li>Added Fira Code font</li>
</ul>
> modified .eslintrc.js

- apps/api/src/app/widgets/usecases/mark-action-as-done/update-message-actions.usecause.ts
Validate id entities are available for modification.
In order to provide valid return values from the API.
> fix: missing entity validations

- apps/api/src/app/events/usecases/digest-filter-steps/digest-filter-steps-regular.usecase.ts
Removes the old logic for update mode that was never put out to the user because of bugs and misunderstandings of the feature... 
It was confusing and talking to @LetItRock and explaining Digest to him this code could be made easier.
> refactor: filter steps regular

- apps/api/src/app/partner-integrations/dtos/complete-and-update-vercel-integration-request.dto.ts
- apps/api/src/app/partner-integrations/partner-integrations.controller.ts
- apps/api/src/app/partner-integrations/usecases/complete-vercel-integration/complete-vercel-integration.usecase.ts
- apps/api/src/app/partner-integrations/usecases/get-vercel-configuration/get-vercel-configuration.command.ts
- apps/api/src/app/partner-integrations/usecases/get-vercel-configuration/get-vercel-configuration.usecase.ts
- apps/api/src/app/partner-integrations/usecases/get-vercel-projects/get-vercel-projects.usecase.ts
- apps/api/src/app/partner-integrations/usecases/index.ts
- apps/api/src/app/partner-integrations/usecases/update-vercel-configuration/update-vercel-configuration.command.ts
- apps/api/src/app/partner-integrations/usecases/update-vercel-configuration/update-vercel-configuration.usecase.ts
- apps/web/src/App.tsx
- apps/web/src/api/vercel-integration.ts
- apps/web/src/components/partner-integrations/vercel/LinkProjectContainer.tsx
- apps/web/src/components/partner-integrations/vercel/ProjectRow.tsx
- apps/web/src/pages/partner-integrations/LinkVercelProjectPage.tsx
- libs/dal/src/repositories/base-repository.ts
- libs/dal/src/repositories/organization/organization.entity.ts
- libs/dal/src/repositories/organization/organization.repository.ts
- libs/dal/src/repositories/organization/organization.schema.ts
Allows users to modify/update their vercel integration at a later stage from the vercel dashboard
https://user-images.githubusercontent.com/29251776/201670398-1edab821-f7a3-4d68-adc3-d0ae76002386.mov
> feat: update vercel integration

- packages/stateless/src/lib/handler/chat.handler.ts
- packages/stateless/src/lib/trigger/trigger.engine.spec.ts
`npm run setup:project` fails due to the build error inside stateless
> fix: missing initialisation for content engine

- docs/docs/community/run-locally.md
Adds documentation references to local environment setup script.
To let users know an option introduced in the Jarvis task runner
> chore(docs): local env setup script doc

- apps/web/src/components/widget/InAppWidgetPreview.tsx
Fixes the width being shrink on the notification content placeholder
> Nv 1185 notification content inside in app

- apps/api/src/app/events/usecases/send-message/send-message-push.usecase.ts
- apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.command.ts
Similat to https://github.com/novuhq/novu/pull/2047 but for push notification.
@davidsoderberg suggested after discovering the bug in send chat message that push notification message could suffer something similar if credentials missing.
> fix(api): send push message potential push bug

- packages/notification-center/jest.config.js
- packages/notification-center/package.json
- packages/notification-center/src/index.test.ts
- packages/notification-center/src/index.ts
- packages/notification-center/src/shared/enums/index.ts
- packages/notification-center/src/shared/interfaces/index.ts
- pnpm-lock.yaml
Returns export of IMessage interface and others, in addition, i added tests to prevent those types of issues to be repeated.
The export of IMessage was missing.
Address comment in issue #612
> fix interface exports

- apps/api/package.json
- apps/api/src/app/shared/interceptors/cached.interceptor.ts
- apps/api/src/app/shared/interceptors/index.ts
new cache decorator
in order to reuse the caching logic
> feat: add cache decorator

- apps/api/src/app/shared/interceptors/index.ts
- apps/api/src/app/shared/interceptors/invalidate-cache.interceptor.ts
Adds invalidation decorator.
In order to maintain stale cache
> feat: add invalidation decorator

- docs/docs/overview/docker-deploy.md
Fixes - #2091
Updates the docs for the docker setup
To makesure that docs novu is correctly tested and used by the users
N/A
> (docs - #2091) - Updated the docs for the docker

- docker/.env.example
Adds the environment variable needed for deploying the Web app with Docker in the local environment.
We are having a lot of questions open regarding the Docker setup and not being able to deploy it in the local with fully functional as they receive a CORS error due a wrongly set up environment variable.
> chore(docker): improve-docs

- apps/api/src/app/events/usecases/run-job/run-job.usecase.ts
- apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.command.ts
- apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.usecase.ts
- apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts
- apps/api/src/app/shared/dtos/notification-step.ts
- apps/web/cypress/tests/notification-editor/main-functionality.spec.ts
- apps/web/cypress/tests/notification-editor/steps-actions.spec.ts
- apps/web/src/pages/templates/workflow/ShouldStopOnFailSwitch.tsx
- apps/web/src/pages/templates/workflow/StepActiveSwitch.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.schema.ts
Adds an option to control the flow of a workflow,
Currently, if a message fails then the next messages in the same workflow doesn't gets executed,
With this change now the user will be able to control the behaviour explicitly, letting the whole workflow to run even if some messages fail or stop the workflow on a failure
> feat: Check for shouldRun

- .cspell.json
- apps/api/src/app/content-templates/usecases/compile-template/compile-template.usecase.ts
- apps/web/src/components/templates/email-editor/EmailCustomCodeEditor.tsx
- libs/shared/src/consts/handlebar-helpers/handlebarHelpers.ts
- libs/shared/src/consts/handlebar-helpers/index.ts
- libs/shared/src/consts/index.ts
- libs/shared/src/entities/message-template/message-template.interface.ts
Autocomplete dropdown for custom editor. Shows handlebar helpers and system variables
> feat: autocomplete for custom editor

- libs/dal/src/repositories/topic/index.ts
- libs/dal/src/repositories/topic/topic.entity.ts
- libs/dal/src/repositories/topic/topic.repository.ts
Adds the repository layer for the topics.
We need to be able to export this layer to be used in the use cases and have the separation of concerns with Mongoose and MongoDB.
> feat(dal): create topic repository in dal

- apps/web/src/components/templates/email-editor/variables-management/VarItemsDropdown.tsx
- apps/web/src/design-system/icons/arrows/ChevronDown.tsx
- apps/web/src/design-system/icons/arrows/ChevronUp.tsx
- apps/web/src/design-system/icons/gradient/EditGradient.tsx
- apps/web/src/pages/templates/editor/PreviewSegment/MobileIcon.tsx
- apps/web/src/pages/templates/editor/PreviewSegment/WebIcon.tsx
Icon errors - failing deploy to dev
> fix: fix errors for icons

- apps/api/src/app/shared/cache/cache-service.spec.ts
- apps/api/src/app/shared/cache/cached-interceptor.spec.ts
adds cache service and cache interceptor tests
probably will add more in the future while developing.
In order to make sure that the caching works as expected.
> Nv 1264 cache service and interceptor tests

- apps/api/src/app/events/usecases/process-subscriber/process-subscriber.usecase.ts
- apps/api/src/app/shared/cache/cache-service.spec.ts
- apps/api/src/app/shared/cache/cached-interceptor.spec.ts
- apps/api/src/app/subscribers/usecases/update-subscriber/update-subscriber.usecase.ts
- libs/dal/src/repositories/subscriber/subscriber.repository.ts
- libs/dal/src/shared/interceptors/cached.interceptor.ts
- libs/dal/src/shared/interceptors/invalidate-cache.interceptor.ts
- libs/dal/src/shared/interceptors/shared-cache.interceptor.ts
caching of the subscribers findOne query.
This request is very common on the trigger flow however it is not updated so frequently.
> feat: add subscribers find one caching

- apps/api/src/app/subscribers/subscribers.controller.ts
- apps/api/src/app/widgets/widgets.controller.ts
fix the response of mark as seen.
Closes #2071
> fix: mark-as-seen response dto

- apps/api/src/app.module.ts
- apps/api/src/app/shared/shared.module.ts
- apps/api/src/app/topics/dtos/create-topic.dto.ts
- apps/api/src/app/topics/dtos/topic.dto.ts
- apps/api/src/app/topics/e2e/create-topic.e2e.ts
- apps/api/src/app/topics/topics.controller.ts
- apps/api/src/app/topics/topics.module.ts
- apps/api/src/app/topics/types/index.ts
- apps/api/src/app/topics/use-cases/create-topic.command.ts
- apps/api/src/app/topics/use-cases/create-topic.use-case.ts
- apps/api/src/app/topics/use-cases/index.ts
- libs/dal/src/index.ts
- libs/dal/src/repositories/topic/index.ts
- libs/dal/src/repositories/topic/topic-subscribers.entity.ts
- libs/dal/src/repositories/topic/topic-subscribers.repository.ts
- libs/dal/src/repositories/topic/topic.entity.ts
- libs/dal/src/repositories/topic/topic.repository.ts
- libs/dal/src/repositories/topic/types.ts
Adds topic creation endpoint, use case and tests.
First step of the topics API.
> feat(api): create topic use case and endpoint

- apps/web/src/components/templates/TemplatePushEditor.tsx
- apps/web/src/components/templates/TemplateSMSEditor.tsx
- apps/web/src/components/templates/VariableManager.cy.tsx
- apps/web/src/components/templates/VariableManager.tsx
- apps/web/src/components/templates/chat-editor/TemplateChatEditor.tsx
- apps/web/src/components/templates/email-editor/EmailMessagesCards.tsx
- apps/web/src/components/templates/in-app-editor/TemplateInAppEditor.tsx
- apps/web/src/hooks/use-variables-manager.ts
https://www.loom.com/share/a31434a8741347e783d34b22c2626252
> Variables not updated in var manager

- packages/notification-center/src/components/notification-center/components/notification-item/NotificationListItem.tsx
> fix: actions buttons shown twice in notification center

- apps/web/src/components/templates/email-editor/EmailContentCard.tsx
- apps/web/src/pages/templates/editor/Preview.tsx
Change to active integration for preview
> feat: change to active integrations for preview

- apps/web/src/components/templates/email-editor/variables-management/VarItem.tsx
Add style to types in variable management
> feat: add styling of type for variable management

- apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts
So preheaders variables are replaced like in the subject
> fix: so preheader can contain variables

- apps/web/src/components/templates/email-editor/variables-management/VarItemsDropdown.tsx
- apps/web/src/components/templates/email-editor/variables-management/VariablesManagement.tsx
- apps/web/src/hooks/use-process-variables.ts
Fix so vars can be nested in a step and displayed correctly in the variable manager
> fix: nested vars in variable manager

- libs/shared/src/consts/handlebar-helpers/handlebarHelpers.ts
Description changes for handlebar helpers
To make the full description visible in the editor autocomplete
> feat: improve the descriptions for handlebar helpers

- scripts/dev-environment-setup.sh
Fixes some of the errors checked by DeepSource when passes the `shellcheck` validator.
Help to pass integration checks of code source quality.
> chore(infra): fix-shellcheck-errors-from-deepsource

- apps/api/src/app/change/usecases/promote-feed-change/promote-feed-change.ts
- apps/api/src/app/events/usecases/send-message/send-message.usecase.ts
- apps/api/src/app/logs/usecases/create-log/create-log.usecase.ts
- apps/web/cypress/tests/auth.spec.ts
- apps/web/src/components/layout/components/SideNav.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
- apps/widget/cypress/support/commands.ts
- docs/src/theme/DocPage/index.js
- docs/src/theme/Footer/Links/MultiColumn/index.js
- libs/embed/src/embed.ts
Fixes some of the errors checked by DeepSource when passes the JavaScript checker.
Help to pass better the integration checks of code source quality.
DeepSource applies different rules and checks that our defined configuration of Eslint and TypeScript so we should align them.
> chore(infra): apply suggestions from deepsource for js code

- apps/api/src/app/topics/e2e/create-topic.e2e.ts
remove .only on api tests
small mismatch from branch merges
> fix: remove only flag

- apps/api/e2e/setup.ts
- apps/api/src/app/change/e2e/promote-changes.e2e.ts
- apps/api/src/app/events/e2e/process-subscriber.e2e.ts
- apps/api/src/app/events/e2e/trigger-event.e2e.ts
fix the missing cache service that will invalidate the old cache
previews solution was out of score therefore the service was undefined and could not invalidate the cache.
> fix: single cache instance

- .cspell.json
- apps/api/src/app/topics/dtos/topic.dto.ts
- apps/api/src/app/topics/e2e/get-topic.e2e.ts
- apps/api/src/app/topics/types/index.ts
- apps/api/src/app/topics/use-cases/create-topic-subscribers/create-topic-subscribers.command.ts
- apps/api/src/app/topics/use-cases/create-topic-subscribers/create-topic-subscribers.use-case.ts
- apps/api/src/app/topics/use-cases/create-topic-subscribers/index.ts
- apps/api/src/app/topics/use-cases/create-topic/create-topic.use-case.ts
- apps/api/src/app/topics/use-cases/index.ts
- libs/dal/src/repositories/subscriber/subscriber.entity.ts
- libs/dal/src/repositories/subscriber/types.ts
- libs/dal/src/repositories/topic/topic-subscribers.entity.ts
- libs/dal/src/repositories/topic/topic-subscribers.schema.ts
- libs/dal/src/repositories/topic/topic.entity.ts
- libs/dal/src/repositories/topic/topic.repository.ts
- libs/dal/src/repositories/topic/topic.schema.ts
- libs/dal/src/repositories/topic/types.ts
Adds the use case to create the topic subscribers entry in the database so when we create the topic we create it too.
Thus we can safely add subscribers and then remove them from a topic.
> feat(api): create topic subscribers use case

- apps/web/package.json
- pnpm-lock.yaml
This also fixes the failing CI tests for Web
This error was due to the errors in mantine old version, was fixed in latest versions
https://github.com/mantinedev/mantine/issues/3115#issuecomment-1337661940
> fix: upgrade the dropzone version

- .github/labeler.yml
- .github/workflows/test-notification-center-angular.yml
- .github/workflows/test-notification-center-vue.yml
- .github/workflows/test-notification-center.yml
- packages/notification-center-angular/package.json
- packages/notification-center-vue/package.json
Added GitHub actions for the Notification Center Vue/Angular packages.
To verify that the packages do build and tests are passing.
> chore(notification-center): added the gh actions for nc vue and angular packages

- apps/api/src/app/auth/e2e/password-reset.e2e.ts
- apps/api/src/app/auth/usecases/password-reset-request/password-reset-request.usecase.ts
- apps/api/src/app/auth/usecases/password-reset/password-reset.usecase.ts
- apps/web/src/components/auth/PasswordResetRequestForm.tsx
- libs/dal/src/repositories/user/user.entity.ts
- libs/dal/src/repositories/user/user.repository.ts
- libs/dal/src/repositories/user/user.schema.ts
Adds limit to the number of requests that can be made for password reset,
Max 5 requests per minute
Max 15 requests per 24 hours
> Nv 1203 lack of rate limiting mechanism

- apps/web/cypress/tests/notification-editor/create-notification.spec.ts
- apps/web/src/components/templates/EditorPreviewSwitch.tsx
- apps/web/src/components/templates/email-editor/TestSendEmail.tsx
- apps/web/src/components/templates/email-editor/variables-management/VarItem.tsx
- apps/web/src/components/templates/email-editor/variables-management/VarItemsDropdown.tsx
- apps/web/src/components/templates/email-editor/variables-management/VarLabel.tsx
- apps/web/src/pages/templates/editor/Preview.tsx
Test for template editor features
> test: template editor features

- apps/web/src/pages/templates/editor/Preview.tsx
Fix reload of preview on change in json input field
> fix: reload of preview on change in json input field

- apps/web/src/components/templates/email-editor/ButtonRowContent.tsx
Adding an example for a buttons placeholder to make it more clear for the user
Closes #2147
> Change the empty state copy for the URL for button

- apps/api/src/app/change/usecases/create-change.spec.ts
- apps/api/src/app/content-templates/usecases/parse-preview/preview-email.usecase.ts
- apps/api/src/app/events/services/storage-helper-service/storage-helper.service.spec.ts
- apps/web/cypress/plugins/index.ts
- libs/embed/tools/gh-pages-publish.ts
- packages/headless/src/lib/headless.service.test.ts
- packages/notification-center/src/i18n/lang.ts
Reducing the amount of conflicts Deep Source raises in the integration check.
Improve the DX of the CI.
> fix(infra): resolve some deepsource javascript issues

- apps/api/src/app/topics/dtos/index.ts
- apps/api/src/app/topics/dtos/rename-topic.dto.ts
- apps/api/src/app/topics/e2e/rename-topic.e2e.ts
- apps/api/src/app/topics/topics.controller.ts
- apps/api/src/app/topics/use-cases/index.ts
- apps/api/src/app/topics/use-cases/rename-topic/index.ts
- apps/api/src/app/topics/use-cases/rename-topic/rename-topic.command.ts
- apps/api/src/app/topics/use-cases/rename-topic/rename-topic.use-case.ts
- libs/dal/src/repositories/topic/topic.repository.ts
Adds endpoint to rename a topic and its tests.
Giving options to users to manage topics.
> feat(api): add endpoint to rename the topic

- apps/api/src/app/partner-integrations/partner-integrations.controller.ts
- apps/api/src/app/partner-integrations/usecases/get-vercel-projects/get-vercel-projects.command.ts
- apps/api/src/app/partner-integrations/usecases/get-vercel-projects/get-vercel-projects.usecase.ts
- apps/web/src/api/vercel-integration.ts
- apps/web/src/components/auth/LoginForm.tsx
- apps/web/src/components/auth/PasswordResetRequestForm.tsx
- apps/web/src/components/layout/components/PartnerIntegrationLayout.tsx
- apps/web/src/components/partner-integrations/vercel/LinkMoreProjectRow.tsx
- apps/web/src/components/partner-integrations/vercel/LinkProjectContainer.tsx
- apps/web/src/components/partner-integrations/vercel/ProjectRow.tsx
- apps/web/src/design-system/select/Select.tsx
- apps/web/src/pages/auth/PasswordResetPage.tsx
https://user-images.githubusercontent.com/29251776/208098190-052414ec-2531-457b-a8fd-ecc3ad60bd2e.mov
> feat: added infinite api scroll for vercel projects

- apps/api/src/app/events/e2e/trigger-event-topic.e2e.ts
Tests for the implementation of sending a notification to multiple topics and multiple subscribers through the trigger event endpoint.
Give confidence that the implementation of topics reuse downstream all the functionalities of trigger event endpoint.
> feat(api): test suite for multiple payloads and multiple subscribers

- packages/node/src/index.ts
- packages/node/src/lib/feeds/feeds.spec.ts
- packages/node/src/lib/novu.ts
- packages/node/src/lib/topics/topic.interface.ts
- packages/node/src/lib/topics/topics.spec.ts
- packages/node/src/lib/topics/topics.ts
Creates the Topics API in the Node.js package.
Give support of topics feature to Novu package.
> feat(package): implement topics functionality

- apps/api/src/app/events/e2e/trigger-event-topic.e2e.ts
- apps/api/src/app/topics/e2e/add-subscribers.e2e.ts
- apps/api/src/app/topics/e2e/filter-topics.e2e.ts
- apps/api/src/app/topics/e2e/rename-topic.e2e.ts
- apps/api/src/app/topics/topics.controller.ts
- apps/api/src/app/topics/use-cases/add-subscribers/add-subscribers.use-case.ts
Returns feedback to the user of the subscribers succeeded and the ones failed when adding them to a topic.
Better UX.
> feat(api): when adding subscribers provide succeeded and failed subsc

- apps/web/src/design-system/table/Table.tsx
recreating https://github.com/novuhq/novu/pull/2277
Issue = https://github.com/novuhq/novu/issues/2194
> fix: pushes pagination to bottom

- apps/api/src/app/shared/helpers/content.service.ts
- apps/web/src/components/activity/ExecutionDetailsWebhookFeedback.tsx
- apps/web/src/pages/integrations/IntegrationsStorePage.tsx
This PR solves the issue of no return statement in the callback function of the array method.
just converted the map to the forEach loop. 
The array has several methods for filtering, mapping, and folding. If we forget to write a return statement in a callback of those, it's probably a mistake.
> fix: no return in map function

- .idea/codeStyles/Project.xml
- apps/api/src/app/events/usecases/send-message/send-message.usecase.ts
- apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
- apps/api/src/app/integrations/integrations.controller.ts
- apps/api/src/app/integrations/usecases/create-integration/create-integration.command.ts
- apps/api/src/app/integrations/usecases/create-integration/create-integration.usecase.ts
- apps/api/src/app/notifications/usecases/get-activity/get-activity.usecase.ts
- apps/api/src/app/partner-integrations/partner-integrations.controller.ts
- apps/api/src/app/partner-integrations/usecases/complete-vercel-integration/complete-vercel-integration.usecase.ts
- apps/api/src/app/subscribers/usecases/get-subscriber-preference/get-subscriber-preference.usecase.ts
- apps/api/src/app/subscribers/usecases/update-subscriber-preference/update-subscriber-preference.usecase.ts
- apps/api/src/app/widgets/usecases/initialize-session/initialize-session.usecase.ts
- apps/api/src/app/widgets/usecases/mark-action-as-done/update-message-actions.usecase.ts
- apps/api/src/app/widgets/usecases/mark-message-as/mark-message-as.usecase.ts
- libs/dal/src/repositories/member/member.repository.ts
Add missing properties to existing events and new events.
> feat: Missing events

- apps/api/src/app/events/usecases/process-subscriber/process-subscriber.usecase.ts
- apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
- apps/api/src/app/notification-template/notification-template.controller.ts
- apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.command.ts
- apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts
- apps/api/src/app/shared/interceptors/shared-cache.ts
fix notification template ivalidation
at the current state, the identifier was templateId, but id was needed.
> Fix notification template invalidation

- apps/api/src/app/shared/services/cache/cache.service.ts
fix redis parser error on ci test 
the ci tests failed on the test environment.
> fix: redis parser error on ci tests

- apps/api/src/app/subscribers/e2e/get-unseen-count.e2e.ts
- apps/api/src/app/widgets/usecases/get-feed-count/get-feed-count.usecase.ts
fix when API user provides an invalid subscriber id
in order to get a more informative response from the API.
> feat: add exception throw on invalid subscriber id

- docs/docs/overview/docker-deploy.md
adds usecase caching documantattion.
so the new and old users of the system will be aware of the new caching added and how to enable it.
> feat: add cache documentation

- .cspell.json
- apps/ws/src/socket/ws.gateway.ts
- packages/notification-center/src/store/socket/use-socket-controller.ts
Sends auth token over a secured channel instead of being sent in query params
> feat: moved token to auth header

- apps/api/src/app/events/e2e/trigger-event-topic.e2e.ts
- apps/api/src/app/topics/e2e/create-topic.e2e.ts
- apps/api/src/app/topics/e2e/filter-topics.e2e.ts
- apps/api/src/app/topics/e2e/get-topic.e2e.ts
- apps/api/src/app/topics/e2e/remove-subscribers.e2e.ts
- apps/api/src/app/topics/e2e/rename-topic.e2e.ts
- apps/api/src/app/topics/topics.controller.ts
- apps/api/src/app/topics/use-cases/get-topic/get-topic.use-case.ts
- packages/node/src/lib/topics/topic.interface.ts
- packages/node/src/lib/topics/topics.spec.ts
- packages/node/src/lib/topics/topics.ts
Review of types, tests and code of topics feature.
👀
> fix(api): topics feature type and tests nits

- apps/api/src/app/shared/dtos/notification-step.ts
- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.schema.ts
adds new on webhook props in dal scheme
in order to save the new props in the db
> feat: add new webhook filter on the dal scheme

- apps/api/src/app/change/usecases/promote-notification-template-change/promote-notification-template-change.ts
- apps/web/src/components/templates/in-app-editor/EnableAvatarSwitch.tsx
- apps/web/src/components/templates/in-app-editor/TemplateInAppEditor.tsx
- apps/web/src/components/templates/notification-setting-form/NotificationSettingsForm.tsx
- apps/web/src/components/widget/ActionBlockContainer.tsx
- apps/web/src/components/widget/AvatarContainer.styles.ts
- apps/web/src/components/widget/AvatarContainer.tsx
- apps/web/src/components/widget/InAppWidgetPreview.tsx
- apps/web/src/components/workflow/FlowEditor.tsx
- apps/web/src/components/workflow/edge-types/AddNodeEdge.tsx
- apps/web/src/components/workflow/node-types/AddNode.tsx
- apps/web/src/pages/changes/PromoteChangesPage.tsx
- apps/web/src/pages/templates/workflow/DelayMetadata.tsx
- apps/web/src/pages/templates/workflow/DigestMetadata.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
This error happened whenever someone made any changes to the workflow template in the `production` environment and then switches back to `development` environment and saves them.
**Reproduction steps Video:**
https://user-images.githubusercontent.com/29251776/209322863-ce1b88aa-bb2c-4375-ae71-8567e8261fa8.mov
**Add nodes in Production ENV**:
https://user-images.githubusercontent.com/29251776/209348766-1f99a368-bccf-4773-a813-c79a08ec7383.mov
**Changes made in this PR:**
- Added a `NotFoundException` to when a notificationGroup isn't found.
- Added Error message popup on the UI
- Disabled Template changes in the `production` environment.
Also, I think we should disable updating directly to the `production` env template at the API level.
> Nv 1400 typeerror cannot read properties of null

- .github/workflows/issue-label.yml
- .github/workflows/reusable-web-e2e.yml
- .github/workflows/scripts/add-triage-label.js
- .github/workflows/scripts/is-community-contributor.js
- apps/web/package.json
Automatically add `triage` label for community issues to help us track it.
For better backlog management process, this label will be added automatically
> feat: add triage label on communtiy issues

- apps/web/src/pages/templates/filter/FilterModal.tsx
adds new on webhook filter on step
in order to filter with the help of an async webhook
https://www.loom.com/share/f04dc006588c4ea384761e254a347a9b
> feat: add webhook filter support

- apps/api/src/app/events/usecases/send-message/send-message.usecase.ts
- apps/api/src/app/events/usecases/trigger-event/message-filter.matcher.ts
add webhook filter support 
in order to support new ui feature of filtering async webhook
> feat: add webhook filter support in the api

- README.md
Change in the Readme file
I think that someone forgot to check SNS as supported
> fix: set sns as supported

- docs/docs/home.md
This PR has changed documentation homepage
Because messaging about what Novu does could've been clearer and that is what this PR contains.
> docs: rephrased line 20 for better clarity

- apps/web/src/components/templates/in-app-editor/TemplateInAppEditor.tsx
Updated redirection url text
Current text is confusing as redirection url is for complete notification not for CTA buttons
> fix: update redirection url text

- docs/docs/community/run-locally.md
small docs update
warning wasn't rendered correctly due to a typo
> docs: warning wasn't rendered correctly

- providers/apns/src/lib/apns.provider.ts
Change the environment variable for production from `production `to `prod`
`Closes #2346 `
no other information
> change environment parameter from 'production' to 'prod'

- docs/docs/channels/push/fcm.md
- docs/docs/community/faq.md
- docs/docs/notification-center/angular-component.md
- docs/docs/notification-center/react-components.md
- docs/docs/notification-center/vue-component.md
- docs/docs/overview/docker-deploy.md
- docs/docs/platform/subscribers.md
Added few FAQs and missing info
> feat: add few faqs

- apps/api/src/app/change/e2e/get-changes.e2e.ts
- apps/api/src/app/change/e2e/promote-changes.e2e.ts
- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- apps/api/src/app/message-template/shared/sanitizer.service.spec.ts
- apps/api/src/app/notification-template/e2e/create-notification-templates.e2e.ts
- apps/api/src/app/widgets/dtos/message-response.dto.ts
- apps/web/src/components/templates/email-editor/ContentRow.tsx
- apps/web/src/components/templates/email-editor/ControlBar.tsx
- apps/web/src/components/templates/email-editor/EmailMessageEditor.tsx
- libs/dal/src/index.ts
- libs/dal/src/repositories/layout/index.ts
- libs/dal/src/repositories/layout/layout.entity.ts
- libs/dal/src/repositories/layout/layout.repository.ts
- libs/dal/src/repositories/layout/layout.schema.ts
- libs/dal/src/repositories/layout/types.ts
- libs/dal/src/repositories/message-template/index.ts
- libs/dal/src/repositories/message-template/message-template.entity.ts
- libs/dal/src/repositories/message-template/types.ts
- libs/dal/src/repositories/user/index.ts
- libs/dal/src/repositories/user/types.ts
- libs/dal/src/repositories/user/user.entity.ts
- libs/shared/src/entities/message-template/message-template.interface.ts
- libs/shared/src/types/index.ts
- libs/shared/src/types/message-template/index.ts
- libs/testing/src/user.session.ts
Adding Layout repository. Also adding some enums and interfaces to unify code across the stack.
First steps of Layout feature.
> feat(dal): layout repository

- apps/api/src/bootstrap.ts
Adds the tag needed to Topics to be parsed by Swagger.
To be able to generate the docs for TOpics feature for our users to check.
> fix(docs): add topics tag to swagger bootstrap

- libs/dal/src/repositories/subscriber/subscriber.entity.ts
- libs/dal/src/repositories/subscriber/subscriber.schema.ts
Changes to the subscriber entity
> feat: added online status properties for subscribers

- apps/api/src/app/subscribers/subscribers.controller.ts
> fix: typescript error for messageIds

- apps/api/src/app/events/usecases/process-subscriber/process-subscriber.usecase.ts
- apps/api/src/app/shared/services/cache/invalidate-cache.service.ts
- apps/api/src/app/subscribers/usecases/create-subscriber/create-subscriber.command.ts
- apps/api/src/app/subscribers/usecases/create-subscriber/create-subscriber.usecase.ts
- apps/api/src/app/subscribers/usecases/update-subscriber/update-subscriber.usecase.ts
remove redundant cache invalidation.
> fix: remove redundant cache invalidation

- apps/api/src/app/subscribers/usecases/update-subscriber-channel/update-subscriber-channel.usecase.ts
> fix: remove redundant update

- apps/api/src/app/layouts/dtos/get-layout.dto.ts
- apps/api/src/app/layouts/dtos/index.ts
- apps/api/src/app/layouts/dtos/layout.dto.ts
- apps/api/src/app/layouts/e2e/get-layout.e2e.ts
- apps/api/src/app/layouts/layouts.controller.ts
- apps/api/src/app/layouts/use-cases/create-layout/create-layout.use-case.ts
- apps/api/src/app/layouts/use-cases/get-layout/get-layout.command.ts
- apps/api/src/app/layouts/use-cases/get-layout/get-layout.use-case.ts
- apps/api/src/app/layouts/use-cases/get-layout/index.ts
- apps/api/src/app/layouts/use-cases/index.ts
- libs/dal/src/repositories/layout/layout.entity.ts
- libs/dal/src/repositories/layout/layout.repository.ts
Adds endpoint to retrieve a layout.
With this endpoint and the create layout one, UI is unblocked to develop.
> feat(api): get layout endpoint

- apps/ws/src/shared/shared.module.ts
- apps/ws/src/shared/subscriber-online/index.ts
- apps/ws/src/shared/subscriber-online/subscriber-online.service.ts
- apps/ws/src/socket/ws.gateway.ts
Added a method to handle the online status of subscribers on connection and disconnection
> feat: online status handler

- apps/web/src/components/templates/email-editor/ContentRow.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
Fixed Deepsource issues that suddenly appeared on the `next` branch. It's failing all the PRs now.
> chore(web): fixed deepsource issues with wai aria

- apps/web/src/api/layouts.ts
- apps/web/src/design-system/index.ts
- apps/web/src/design-system/loading-overlay/LoadingOverlay.tsx
- apps/web/src/pages/brand/BrandPage.tsx
- apps/web/src/pages/brand/tabs/BrandingForm.tsx
- apps/web/src/pages/brand/tabs/LayoutEditor.tsx
- apps/web/src/pages/brand/tabs/LayoutsListPage.tsx
- apps/web/src/pages/brand/tabs/index.ts
Add get layout and create layout 
Will create types in shared in a future pr, when we have all endpoints
> Nv 1464 web create layout page

- apps/widget/public/iframeResizer.contentWindow.js
> chore: fixed additional deepsource issue

- apps/web/src/components/templates/use-template-controller.hook.ts
- apps/web/src/pages/templates/filter/FilterModal.styles.ts
- apps/web/src/pages/templates/filter/FilterModal.tsx
- apps/web/src/pages/templates/filter/Filters.tsx
- apps/web/src/pages/templates/filter/OnlineFiltersForms.tsx
- Added the form UI for the online filters
- Refactored existing code inside `FilterModal.tsx`
> feat: Added form UI for the online filters

- apps/web/src/api/hooks/use-layouts.ts
- apps/web/src/api/layouts.ts
- apps/web/src/api/query.keys.ts
- apps/web/src/pages/brand/tabs/LayoutEditor.tsx
- apps/web/src/pages/brand/tabs/LayoutsListPage.tsx
- libs/shared/src/entities/layout/index.ts
- libs/shared/src/entities/layout/layout.interface.ts
- libs/shared/src/index.ts
> Nv 1476 web   get layouts endpoint

- apps/web/src/components/layout/components/PartnerIntegrationLayout.tsx
- apps/web/src/components/partner-integrations/vercel/LinkProjectContainer.tsx
- apps/web/src/components/partner-integrations/vercel/ProjectRow.tsx
- apps/web/src/pages/partner-integrations/LinkVercelProjectPage.tsx
Fixes the flickering screen issue when the system uses the light theme as the default theme.
https://user-images.githubusercontent.com/29251776/212544572-382609a3-15ad-4f8f-a90b-b3c87e20f9e0.mov
https://user-images.githubusercontent.com/29251776/212544629-e12d87cb-aa8e-4e91-811c-92a3a2dd01e5.mov
> fix: page flickering issue while using light theme on system

- apps/api/src/app/partner-integrations/usecases/get-vercel-projects/get-vercel-projects.command.ts
- apps/api/src/app/partner-integrations/usecases/get-vercel-projects/get-vercel-projects.usecase.ts
- apps/api/src/app/partner-integrations/usecases/update-vercel-configuration/update-vercel-configuration.usecase.ts
Removes the Novu env from the vercel project if the user removes the project from the Novu Configuration page.
https://user-images.githubusercontent.com/29251776/212545429-d676fda7-f5e0-4966-ba41-237447c54ad7.mov
> Nv 1486 remove env from the vercel project if

- apps/web/src/api/hooks/integrations/use-integration-limit.ts
- apps/web/src/api/integration.ts
- apps/web/src/components/layout/components/HeaderNav.tsx
- apps/web/src/components/layout/components/SideNav.tsx
- apps/web/src/components/templates/email-editor/EmailInboxContent.tsx
- apps/web/src/pages/integrations/components/LimitBar.tsx
- apps/web/src/pages/templates/editor/EmailIntegrationInfo.tsx
- apps/web/src/pages/templates/editor/PreviewMobile.cy.tsx
- apps/web/src/pages/templates/editor/PreviewMobile.tsx
- apps/web/src/pages/templates/editor/PreviewMobileInbox/index.tsx
- apps/web/src/pages/templates/editor/PreviewWeb.cy.tsx
- apps/web/src/pages/templates/editor/PreviewWeb.tsx
> Fix novu integration limit

- packages/node/src/lib/integrations/integrations.interface.ts
- packages/node/src/lib/integrations/integrations.spec.ts
- packages/node/src/lib/integrations/integrations.ts
- packages/node/src/lib/novu.ts
Completes the `novu/node` integrations module
For the completion of the `novu/node` package SDK #1319
> Complete `novu/node` integrations module

- apps/web/src/components/layout/components/HeaderNav.tsx
- apps/web/src/components/layout/components/PartnerIntegrationLayout.tsx
> feat: change logo in header nav

- apps/web/src/pages/templates/workflow/ReplyCallback.tsx
- apps/web/src/pages/templates/workflow/SideBar/AddStepMenu.tsx
- apps/web/src/pages/templates/workflow/SideBar/SelectedStep.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
Added additional place in workflow step editor to add reply callback is enabled and URL input.
In order to provide the user to add URL reply callback
> feat: add reply callback step controller

- apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts
- apps/api/src/app/notification-template/dto/update-notification-template-request.dto.ts
- apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.command.ts
- apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts
- apps/api/src/app/shared/dtos/notification-step.ts
- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.schema.ts
- packages/stateless/src/lib/provider/provider.interface.ts
> feat(wip): add reply callback support

- apps/api/src/app/layouts/usecases/create-layout/create-layout.use-case.ts
- apps/api/src/app/layouts/usecases/update-layout/update-layout.use-case.ts
- apps/web/src/pages/brand/tabs/BrandingForm.tsx
- apps/web/src/pages/brand/tabs/LayoutEditor.tsx
- apps/web/src/pages/brand/tabs/LayoutsListPage.tsx
Add warn on unsaved changes, enforce {{{body}}} exists in layout content, some design changes 
lay
> Nv 1457 web move update button to top header

- apps/web/src/components/activity/ExecutionDetailsConditionItem.cy.tsx
- apps/web/src/components/activity/ExecutionDetailsConditionItem.tsx
- apps/web/src/components/activity/ExecutionDetailsConditions.cy.tsx
- Added component testing for the condition filters
> Nv 1490 e2e tests for the filter condition

- .github/workflows/dev-deploy-web.yml
- apps/inbound-mail/src/server/queue-service.ts
- apps/web/src/pages/settings/tabs/EmailSettings.tsx
> fix: update mail server domain env

- apps/inbound-mail/.env.development
- apps/inbound-mail/.env.production
- apps/inbound-mail/.env.test
- apps/inbound-mail/.example.env
- apps/inbound-mail/Dockerfile
> fix: add env files

- .github/workflows/dev-deploy-inbound-mail.yml
- package.json
> Reply callbacks

- apps/web/src/pages/brand/tabs/LayoutEditor.tsx
if you are in Production, Edit Layout and then switches to Development. The layout edit page is still the production layout. 
https://www.loom.com/share/c770a5f18e464ca9b4ffe8b961d56c16
> fix: edit layout page, navigate to screens per env change

- apps/inbound-mail/Dockerfile
- apps/inbound-mail/src/.env.development
- apps/inbound-mail/src/.env.production
- apps/inbound-mail/src/.env.test
- apps/inbound-mail/src/config/env-validator.ts
- apps/inbound-mail/src/config/index.ts
- apps/inbound-mail/src/main.ts
- pnpm-lock.yaml
> fix: add env config

- apps/api/src/app/change/e2e/promote-changes.e2e.ts
- apps/api/src/app/layouts/usecases/delete-layout/delete-layout.use-case.ts
Adds tests for the layout promotion.
Not need to explain why tests are needed. :)
> feat(api): tests for layout promotion

- apps/web/src/api/hooks/use-layouts-editor.ts
Make count changes on badge updated as soon as a layout change is made
> Update changes count badge on layout change

- apps/web/cypress/tests/notification-editor/main-functionality.spec.ts
- apps/web/src/components/templates/email-editor/EmailMessageEditor.tsx
- apps/web/src/pages/brand/tabs/LayoutsListPage.tsx
- Add description field to layout table
- Update changes badge on delete layout
- Fix click on add logo to brand page, instead of settings
> Add description to layout table

- apps/api/src/app/layouts/e2e/get-layout.e2e.ts
- packages/node/src/index.ts
- packages/node/src/lib/layouts/index.ts
- packages/node/src/lib/layouts/layout.interface.ts
- packages/node/src/lib/layouts/layouts.spec.ts
- packages/node/src/lib/layouts/layouts.ts
- packages/node/src/lib/novu.ts
Exposes Layout API in the Node package.
To keep aligned the API with the Novu package that our users install.
> feat(package): add layout api to node package

- apps/api/src/app/layouts/dtos/create-layout.dto.ts
- apps/api/src/app/layouts/e2e/set-default-layout.e2e.ts
- apps/api/src/app/layouts/e2e/update-layout.e2e.ts
- apps/api/src/app/layouts/layouts.controller.ts
- apps/api/src/app/layouts/usecases/set-default-layout/set-default-layout.use-case.ts
- apps/api/src/bootstrap.ts
- libs/dal/src/repositories/layout/layout.repository.ts
Adds Layout API docs. Also fixes some bugs and adds tests for it.
Help the users to understand the API.
> feat(docs): add api docs for layouts and fix some bugs and add tests

- docs/docs/notification-center/getting-started.md
- docs/docs/notification-center/react-components.md
- packages/notification-center/src/components/popover-notification-center/components/Popover.tsx
> fix(docs): update notification center docs 

- docs/docs/platform/layouts.md
Adds examples and explanations on how to use the Layouts feature with the Node package.
Give more insights to the users on the possibilities of the API.
> feat(docs): add examples of the layouts api in the package

- README.md
> chore: polishing season

- packages/node/src/lib/events/events.interface.ts
- packages/node/src/lib/events/events.spec.ts
- Added a new data property to the overrides of fcm
- Made override keys as optional
- Added a test for it
This closes #2603
> NV-1582 bug report node package does not allow

- apps/web/src/components/invites/MembersTable.tsx
Fix for the invite link for new members not including the context path
> Fix for the invite link for members not including the context path

- apps/web/src/design-system/ThemeProvider.tsx
Fix notifications style after the Mantine upgrade.
> fix: shows wrong notification styles 

- apps/web/src/components/layout/components/AuthLayout.tsx
- apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx
- apps/web/src/pages/integrations/components/ProviderCard.tsx
Our static url needs the context path in it so I have added the `CONTEXT_PATH` to uses of the static url in web app
Also fixes a bug I had introduced previously that meant the background image of the login page of the web app was not rendering.
> Static url fix

- apps/api/src/app/organization/e2e/get-in-app-activated.e2e.ts
- apps/api/src/app/organization/organization.controller.ts
- apps/api/src/app/organization/usecases/get-In-app-activated/get-In-app-activated.command.ts
- apps/api/src/app/organization/usecases/get-In-app-activated/get-In-app-activated.usecase.ts
- apps/api/src/app/organization/usecases/index.ts
adds a new endpoint on the API.
we need it in order to help us indicate if a new user initialized the in-app on this side.
> feat: add in app activated api support

- apps/api/src/app/events/usecases/send-message/send-message.usecase.ts
- apps/api/src/app/events/usecases/trigger-event/filter-processing-details.ts
- apps/api/src/app/events/usecases/trigger-event/message-matcher.service.spec.ts
- apps/api/src/app/events/usecases/trigger-event/message-matcher.service.ts
Analytics for step processing
Add what filter was used and what passed or failed
> feat: add what filters was used for step to analytic event

- docs/docs/platform/topics.md
Adds proper casing in the example.
Topic type is key sensitive.
> fix(docs): unnoticed casing problem in the examples

- packages/notification-center/src/i18n/languages/no.ts
> fix: improve 'no' translations

- README.md
> chore: added notifications directory

- apps/web/src/components/templates/email-editor/EmailContentCard.tsx
- apps/web/src/components/templates/email-editor/EmailInboxContent.tsx
The changes that was needed in my previous PR that I forgot to push before merge after agree on design...
> feat: add labels and tooltip to inbox view

- apps/api/src/app/events/e2e/digest-events.e2e.ts
Skipping a flakey tests. I am reviewing Backoff functionality next week so I can put it back once fixed.
Unblock CI.
> fix(api): skip test to unblock ci

- apps/web/cypress/tests/brand.spec.ts
> chore(web): clear e2e branding test

- apps/web/cypress/tests/integration-store.spec.ts
Fix tests implementation in Cypress for Nodemailer.
Changes some implemented tests in a merged PR that reflects proper the expected behaviour of Nodemailer integration.
> fix(cypress): properly reflect the behaviour in the tests for nodemailer

- packages/cli/src/commands/init.ts
- packages/cli/src/server/http-server.ts
> feat: remove demo

- apps/api/src/app/notifications/usecases/get-activity/get-activity.command.ts
Fixes the Sentry issue: https://novu-r9.sentry.io/issues/3605578678/?project=6248811&query=is%3Aunresolved&referrer=issue-stream
> fix(api): notifications controller - notification id validation

- _templates/provider/new/package.ejs.t
Upgrades the script of the template for providers.
Keeping up to date with the versions.
> feat(infra): move script of provider template to v.0.12.0

- apps/web/src/pages/templates/components/TemplatePageHeader.tsx
> feat: show template name instead of Workflow Editor

- apps/api/src/app/events/usecases/digest-filter-steps/digest-filter-steps-backoff.usecase.ts
- apps/api/src/app/events/usecases/index.ts
- apps/api/src/app/events/usecases/store-subscriber-jobs/index.ts
- apps/api/src/app/events/usecases/store-subscriber-jobs/store-subscriber-jobs.command.ts
- apps/api/src/app/events/usecases/store-subscriber-jobs/store-subscriber-jobs.usecase.ts
- apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
Adds a new use case to isolate part of the flow that was living directly written in the trigger event use case.
Keeps clearing the Trigger Event flow to be able to identify the different problems happening in the functionalities (mainly digest).
Document to guide through the Trigger Event flow revision and analyse the different problems and the reasoning behind them:
https://www.notion.so/novuhq/Trigger-Event-revision-8a9126af57ca4b4d9cd618fd84f7f442?pvs=4
> feat(api): create store job use case

- README.md
- apps/web/src/components/layout/AppLayout.tsx
- apps/web/src/pages/quick-start/components/Cards.tsx
- apps/web/src/pages/quick-start/components/QuickStartWrapper.tsx
- apps/web/src/pages/quick-start/steps/FrameworkSetup.tsx
- apps/web/src/pages/quick-start/steps/Setup.tsx
Fixed a couple of the responsive issues found on the new Onboarding pages.
https://user-images.githubusercontent.com/2607232/221216245-b2d21f22-761b-41f3-ae05-5190afa5e258.mov
https://user-images.githubusercontent.com/2607232/221216064-49c12fa2-5e60-4659-8ef2-c89af4268b5b.mov
> fix(web): fixed onboarding setup responsive issues

- apps/web/src/pages/activities/hooks/useNotificationStatus.ts
> fix: jobs undefined

- apps/api/package.json
> fix(docker): correct param order to correct build

- apps/web/src/pages/integrations/IntegrationsStoreModal.tsx
- apps/web/src/pages/integrations/components/Modal/ConnectIntegrationForm.tsx
When connecting integration inside modal - it submits the workflow form as well. 
Also, inside modal, connecting one provider will trigger submit (will show errors) on all other fields with the same name in all other providers.
> Nv 1828 fix nested form behavior

- apps/web/src/pages/quick-start/components/layout/HeaderLayout.tsx
> Get Started - Create header component

- apps/web/src/pages/quick-start/components/layout/BodyLayout.tsx
Add navigation between the steps.
> Get Started - Create navigation component

- apps/web/src/design-system/icons/arrows/ArrowRight.tsx
- apps/web/src/design-system/icons/gradient/ArrowLeftGradient.tsx
- apps/web/src/pages/quick-start/components/demo-flow/nodes/NodeStep.tsx
- apps/web/src/pages/quick-start/components/layout/FooterLayout.tsx
Adds footer for navigation and docs.
https://www.loom.com/share/8508eac5c3c24d848f42d280bef0d12c
> Get Started -  add footer component

- apps/web/src/components/layout/components/PageContainer.tsx
- apps/web/src/pages/quick-start/steps/DigestPreview.tsx
- apps/web/src/pages/quick-start/steps/GetStarted.tsx
Create get started the first step - 'integration configuration' and the second step - 'digest preview'
> Get Started - Add get started steps

- .github/workflows/prod-deploy-web.yml
- apps/web/src/config/index.ts
- apps/web/src/pages/settings/tabs/EmailSettings.tsx
add mail server domain to config
in order to make sure we get the env
> fix: add mail server domain to config

- docs/docs/channels/sms/index.md
- docs/docs/channels/sms/nexmo.md
Add documentation for Nexmo provider
To show the user how to use the Nexmo provider on the Novu platform
closes #1348
> feat(docs): add nexmo provider documentation

- docs/docusaurus.config.js
- docs/package.json
- pnpm-lock.yaml
Add Plausible Analytics integration
Required to test data collection, as Plausible could be a great alternative to GA in the future
> feat(docs): add Plausible Analytics integration

- apps/api/src/providers/provider.regression.ts
- apps/api/src/providers/secrets/index.ts
- libs/testing/src/index.ts
- libs/testing/src/mailtrap.service.ts
- libs/testing/src/notifications.service.ts
- pnpm-lock.yaml
Integration with Mailtrap.io (tool to be able to inspect and test emails sent).
It is the tool we will use to check the emails sent to the different integrations are right.
> feat(regression): add mailtrap integration

- apps/web/src/components/digest-demo-flow/DigestDemoFlow.tsx
- apps/web/src/components/digest-demo-flow/DigestNode.tsx
- apps/web/src/components/digest-demo-flow/EmailNode.tsx
- apps/web/src/components/digest-demo-flow/TriggerNode.tsx
Small polishing after the merges
> feat: add action item

- apps/web/src/pages/quick-start/steps/GetStarted.tsx
fix: default link in get started page
> fix: change default link in get started page

- apps/web/src/components/digest-demo-flow/DigestDemoFlow.tsx
- apps/web/src/components/digest-demo-flow/DigestNode.tsx
- apps/web/src/components/digest-demo-flow/EmailNode.tsx
- apps/web/src/components/digest-demo-flow/NodeStep.tsx
- apps/web/src/components/digest-demo-flow/consts.ts
Added timer on the digest playground.
https://www.loom.com/share/ec5eec1b16924d84aea9ebbc8ea676e6
> feat: add digest time count down

- apps/api/src/app/integrations/integrations.controller.ts
- apps/api/src/app/integrations/usecases/update-integration/update-integration.command.ts
- apps/api/src/app/integrations/usecases/update-integration/update-integration.usecase.ts
- apps/web/src/api/hooks/notification-templates/useCreateDigestDemoWorkflow.ts
> feat: reduce digest onboarding templates

- apps/web/src/pages/integrations/IntegrationsStorePage.tsx
- libs/dal/src/repositories/integration/integration.schema.ts
- libs/shared/src/dto/integration/construct-integration.interface.ts
Add baseUrl to entites.
Closes #3051
> fix: base url store

- apps/api/src/providers/provider.regression.ts
- apps/api/src/providers/secrets/index.ts
Adds Sendinblue to the regression test suite. It passes the tests.
Provider to test.
> feat(regression): test suite for sendinblue

- apps/api/src/providers/provider.regression.ts
- apps/api/src/providers/secrets/index.ts
Add Mailjet to regression test suite. It passes regression test.
Add provider for regression.
> feat(regression): test suite for mailjet

- libs/dal/src/dal.service.ts
> feat: reduce min pool size 

- apps/web/src/pages/quick-start/consts.tsx
1. Replace ssh clone link with https
2. Add cd notification-center-demo command
3. Update NC FAQ url
Please review [ nc demo PR](https://github.com/novuhq/notification-center-demo/pull/6) also with this PR 
closes [NV-1865](https://linear.app/novu/issue/NV-1865/inapp-demo-app)
> fix: update nc demo commands

- apps/api/src/app/user/usecases/get-my-profile/get-my-profile.usecase.ts
> fix: save userhash for intercom in getmyprofile usecase

- docs/docs/channels/email/mailersend.md
- docs/docs/channels/email/mailjet.md
- docs/docs/channels/email/outlook365.md
- docs/docs/channels/email/postmark.md
- docs/docs/channels/email/resend.md
- docs/docs/channels/email/sendgrid.md
- docs/docs/channels/email/sendinblue.md
- docs/docs/channels/email/ses.md
- docs/docs/channels/email/sparkpost.md
- docs/docs/channels/push/apns.md
- docs/docs/channels/push/expo.md
- docs/docs/channels/push/fcm.md
- docs/docs/channels/push/index.md
- docs/docs/channels/sms/twilio.md
- docs/docs/community/create-provider.md
- providers/fcm/src/lib/fcm.provider.ts
Add webpush override in FCM
Update FCM docs
Update few providers sidebar label and position
> feat: add webpushconfig and update sidebar positions

- docs/docusaurus.config.js
- docs/package.json
- pnpm-lock.yaml
This PR disables the use of GA and removes its associated dependencies
Plausible is currently configured and there is no need to use GA
N/A
> chore(docs): disabling Google Analytics

- .github/workflows/dev-deploy-api.yml
- .github/workflows/dev-deploy-inbound-mail.yml
- .github/workflows/dev-deploy-ws.yml
- .github/workflows/prod-deploy-api.yml
- .github/workflows/prod-deploy-inbound-mail.yml
- .github/workflows/prod-deploy-ws.yml
This pr changes the deployment matrix to ensure we are deploying the ee version to Novu Cloud.
> Bug[Actions]: Ensure only the Novu Enterprise Container is getting pushed to AWS

- packages/notification-center/src/i18n/languages/nb.ts
- packages/notification-center/src/i18n/languages/sv.ts
provide nb and sv translations for notification actions
> chore: add nb and sv translations for notification actions

- apps/api/src/app/topics/e2e/delete-topic.e2e.ts
- apps/api/src/app/topics/e2e/helpers/index.ts
- apps/api/src/app/topics/topics.controller.ts
- apps/api/src/app/topics/use-cases/delete-topic/delete-topic.command.ts
- apps/api/src/app/topics/use-cases/delete-topic/delete-topic.use-case.ts
- apps/api/src/app/topics/use-cases/delete-topic/index.ts
- apps/api/src/app/topics/use-cases/index.ts
- docs/docs/platform/topics.md
- libs/dal/src/repositories/topic/topic.repository.ts
- packages/node/src/lib/topics/topic.interface.ts
- packages/node/src/lib/topics/topics.spec.ts
- packages/node/src/lib/topics/topics.ts
Adds endpoint to delete a topic, tests and documentation.
Community request for valid use cases (topics management for throw away topics).
> feat(api): delete topic endpoint

- docs/docs/platform/step-filter.md
Added a section about the Seen / Read filter
0.13.0v release contained the new filter and we need to add some documentation about it
> Added a section about the Seen/Read filter

- README.md
Add Ruby to the list of SDKs we have.
> Add Novu Ruby to the list of SDKs in README.md

- README.md
> Docs: Add Novu Kotlin to the list of SDKs in Readme.md

- libs/shared/src/consts/providers/channels/sms.ts
- libs/shared/src/consts/providers/provider.enum.ts
fix: termii sms provider in integration store
Closes [NV-2062](https://linear.app/novu/issue/NV-2062)
> fix: show termii sms provider in integration store

- apps/web/src/components/layout/components/OrganizationSelect.cy.tsx
Component Testing
#1457 
Closes #1457
> feat(test): Add cypress component test to OrganizationSelect component

- docs/docs/notification-center/custom-styling.md
> feat: add iframe styles example

- apps/api/src/app/inbound-parse/inbound-parse.controller.ts
- apps/api/src/app/notifications/activity.controller.ts
- apps/api/src/app/subscribers/subscribers.controller.ts
- apps/api/src/bootstrap.ts
- docs/docs/notification-center/FAQ.md
Add Inbound parse api tag
Add ApiExcludeController in deprecated activity apis to hide them from docs
Add font awesome FAQ for iframe NC
> fix: add inbound parse api tag and nc font awesome faq

- packages/notification-center/src/components/notification-center/components/AppContent.tsx
made the notification center responsive for mobile devices
see issue #3125 
NA
> fix : responsive notification center for mobile devices

- .github/workflows/prod-deploy-web.yml
> fix: add missing mail server domain env

- apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts
> fix: missing email override

- apps/inbound-mail/src/server/index.ts
> fix: address extraction

- docker/kubernetes/kustomize/worker-deployment.yaml
- docker/kubernetes/kustomize/worker-service.yaml
- docker/local/deployment/docker-compose.yml
- docker/local/development/docker-compose.development.yml
Updated the docker compose files and k8s to use the worker app.
> feat(docker): updated the docker compose files and k8s to use worker app

- docs/docs/channels/email/mandrill.md
Add Mandrill provider documentation
> feat(docs): Add mandrill provider documentation

- docs/docs/channels/email/mailgun.md
- docs/docs/channels/email/netcore.md
Add Netcore provider documentation
> feat(docs): Add netcore provider documentation

- packages/application-generic/src/services/in-memory-provider/elasticache-cluster-provider.ts
Self explanatory.
Only applied to Redis Cluster and service cache. Now the same for Elasticache and service cache.
> feat(infra): enable autopipelining to elasticache

- libs/dal/src/repositories/notification/notification.repository.ts
- libs/dal/src/repositories/notification/notification.schema.ts
Why? (Context)
We want to remove as many inefficient indexs and queries as possible.
Stop using single indexes on the mongoose key implementation
Add compound indexes for common queries and patterns using MongoDB index best practices
Remove unused indexes from MongoDB atlas after implementing the new compound indexes
> Index Cleanup - Notification

- apps/api/src/app/notification-template/usecases/delete-notification-template/delete-notification-template.usecase.ts
Adds missing cache invalidation on a notification template.
> fix: add missing invalidation

- docs/docs/channels/email/custom-smtp.md
- docs/docs/channels/email/mailersend.md
- docs/docs/channels/email/mailgun.md
- docs/docs/channels/email/mailjet.md
- docs/docs/channels/email/mandrill.md
- docs/docs/channels/email/netcore.md
- docs/docs/channels/email/outlook365.md
- docs/docs/channels/email/postmark.md
- docs/docs/channels/email/resend.md
- docs/docs/channels/email/sendgrid.md
- docs/docs/channels/email/sendinblue.md
- docs/docs/channels/email/ses.md
- docs/docs/channels/email/sparkpost.md
- docs/docs/channels/sms/SMS77.md
- docs/docs/channels/sms/nexmo.md
- docs/docs/channels/sms/telnyx.md
> chore(docs): Update the email and sms provider docs

- apps/api/src/app/execution-details/usecases/index.ts
- apps/worker/src/app/workflow/usecases/run-job/run-job.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message.usecase.ts
- apps/worker/src/app/workflow/usecases/update-job-status/update-job-status.usecase.ts
- apps/worker/src/app/workflow/workflow.module.ts
- libs/dal/src/repositories/job/job.repository.ts
- packages/application-generic/src/usecases/add-job/add-delay-job.usecase.ts
- packages/application-generic/src/usecases/add-job/add-job.usecase.ts
- packages/application-generic/src/usecases/bulk-create-execution-details/bulk-create-execution-details.command.ts
- packages/application-generic/src/usecases/bulk-create-execution-details/bulk-create-execution-details.usecase.ts
- packages/application-generic/src/usecases/bulk-create-execution-details/index.ts
- packages/application-generic/src/usecases/index.ts
- packages/application-generic/src/usecases/store-subscriber-jobs/store-subscriber-jobs.usecase.ts
- packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
…update env id
execution details: insertMany, 
job update many -> updateOne
job update status - environmentId vs organizationId 
no loop over integrations for in app
Note - I will tidy up bulk execution code, first I want to see the effect in performance in dev
> Bulk write for execution details

- apps/web/cypress/tests/activities-page.spec.ts
Lonely only removed in Cypress tests.
> fix(cypress): leftover only in tests

- docs/docs/notification-center/headless/api-reference.md
- docs/docs/notification-center/headless/headless-service.md
- packages/headless/src/lib/headless.service.ts
- adds markNotificationsAsSeen method to headless service
> Nv 2214 add marknotificationsasseen prop in

- apps/api/src/app/subscribers/usecases/handle-chat-oauth/is-not-empty.spec.ts
Adds test for the @IsNotEmpty validator.
Because tests are awesome!
Those tests and the Validator itself will be moved to the new validator folder that was created in this PR https://github.com/novuhq/novu/pull/3312, once it will be merged.
> feat: add is not empty tests

- packages/application-generic/src/usecases/create-notification-jobs/create-notification-jobs.usecase.ts
- packages/application-generic/src/usecases/store-subscriber-jobs/store-subscriber-jobs.usecase.ts
Remove update call for each notification - it only updates channels, which we can know in creation of the notifications.
> feat: remove notification update for channels

- apps/worker/src/app/workflow/usecases/send-message/send-message.usecase.ts
- use cached subscriber
- don't query subscriber preferences for action step or critical template
> No query for subscriber preference, cache subscriber

- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.schema.ts
Add fields for scheduled digest steps...
> feat: add data model for scheduled digest

- apps/api/migrations/expire-at/expire-at.migration.ts
- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- docs/docs/community/faq.md
- libs/dal/src/repositories/base-repository.ts
> in-app messages change expireAt to 12 months

- docs/docs/channels/chat/slack.md
New Slack onboarding docs.
So the docs will be more informative in addition to the new onboarding flow.
> feat: update slack docs

- apps/api/src/app/environments/usecases/get-my-environments/get-my-environments.e2e.ts
- apps/web/cypress/tests/activity-graph.spec.ts
- apps/web/src/App.tsx
- apps/web/src/hooks/useEnvironmentChanges.ts
- apps/web/src/hooks/useLayouts.ts
- apps/web/src/hooks/useSubscribers.ts
- apps/web/src/hooks/useTemplates.ts
- apps/web/src/pages/brand/tabs/LayoutEditor.tsx
- apps/web/src/pages/partner-integrations/LinkVercelProjectPage.tsx
- apps/web/src/pages/partner-integrations/components/LinkProjectContainer.tsx
- apps/web/src/pages/templates/components/in-app-editor/preview/InAppWidgetPreview.tsx
- packages/application-generic/src/services/cache/interceptors/cached.interceptor.ts
- packages/application-generic/src/usecases/compile-template/compile-template.usecase.ts
- packages/notification-center/src/components/notification-center/components/layout/Layout.tsx
- packages/notification-center/src/utils/react-to-webcomponent.ts
- providers/clickatell/src/lib/clickatell.provider.spec.ts
- providers/discord/src/lib/discord.provider.spec.ts
- providers/expo/src/lib/expo.provider.spec.ts
- providers/fcm/src/lib/fcm.provider.spec.ts
- providers/infobip/src/lib/infobip.provider.spec.ts
- providers/maqsam/src/lib/maqsam.provider.spec.ts
- providers/nexmo/src/lib/nexmo.provider.spec.ts
- providers/plivo/src/lib/plivo.provider.spec.ts
- providers/slack/src/lib/slack.provider.spec.ts
- providers/sms77/src/lib/sms77.provider.spec.ts
- providers/telnyx/src/lib/telnyx.provider.spec.ts
- providers/twilio/src/lib/twilio.provider.spec.ts
Fixes some of DeepSource analysis recommendations.
https://app.deepsource.com/gh/novuhq/novu/run/0e4dbadc-cea0-4546-902c-36ec0e195e6c/javascript
> fix(deepsource): analysis recommendations improvements

- packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
No need to find all integrations and do decrypt.
> feat: find one integration and only select provider id, remove decrypt

- apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx
- apps/web/src/pages/integrations/components/Modal/ConnectIntegrationForm.tsx
- apps/web/src/pages/settings/tabs/ApiKeysCard.tsx
- docs/docs/channels/chat/slack.md
Add explanations on the: 
* URL prams (subscriber id, environment id).
* HMAC.
> Update Slack docs

- apps/api/src/app/subscribers/dtos/chat-oauth-request.dto.ts
- apps/api/src/app/subscribers/e2e/chat-oauth-callback.e2e.ts
- apps/api/src/app/subscribers/e2e/chat-oauth.e2e.ts
- apps/api/src/app/subscribers/subscribers.controller.ts
- apps/api/src/app/subscribers/usecases/chat-oauth-callback/chat-oauth-callback.usecase.ts
- apps/api/src/app/subscribers/usecases/chat-oauth/chat-oauth.usecase.ts
- apps/web/src/pages/integrations/IntegrationsStorePage.tsx
- apps/web/src/pages/integrations/components/Modal/ConnectIntegrationForm.tsx
- docs/docs/channels/chat/slack.md
> Update chat api interface

- .github/workflows/dev-deploy-worker.yml
- .github/workflows/dev-deploy-ws.yml
Add dev builds for worker and WS 
Closes #3414 
none
> fix(actions): Add worker and WS to dev deployment

- apps/web/src/pages/templates/workflow/DigestMetadata.tsx
- packages/application-generic/src/services/calculate-delay/calculate-delay.service.ts
Removes enterprise flag for timed digest
> fix: remove enterprise flag for timed digest

- libs/dal/src/repositories/notification/notification.repository.ts
sort by createdAt in activity feed
> fix: sort by created at for activity feed

- apps/api/src/config/env-validator.ts
Adds environment variable for Launch Darkly
Values for the different environment API keys added manually to Doppler.
> feat(api): add launch darkly sdk key env variable

- apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx
- apps/web/src/pages/templates/components/formTypes.ts
- apps/web/src/pages/templates/components/notificationTemplateSchema.ts
- apps/web/src/pages/templates/components/templateToFormMappers.ts
- apps/web/src/pages/templates/workflow/DigestMetadata.tsx
- apps/web/src/pages/templates/workflow/RegularDigestMetadata.tsx
- apps/web/src/pages/templates/workflow/digest/BackOffFields.tsx
- apps/web/src/pages/templates/workflow/digest/TimedDigestWillBeSentHeader.tsx
- apps/web/src/pages/templates/workflow/digest/WillBeSentHeader.tsx
Fix for the issues mentioned in the ticket. Also found a few small things related to the header, will describe them in the comments.
https://github.com/novuhq/novu/assets/2607232/885004bc-2965-4a1b-a234-d8b6cdc4f56d
> fix(web): timed digest form fixes

- apps/web/src/api/api.client.ts
- apps/web/src/api/notification-templates.ts
- apps/web/src/config/index.ts
> feat: client points to novu cms centralized server

- apps/web/src/pages/integrations/components/ConnectIntegrationForm.cy.tsx
- apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx
- apps/web/src/pages/integrations/components/Modal/ConnectIntegrationForm.tsx
- libs/shared/src/consts/providers/channels/chat.ts
- libs/shared/src/consts/providers/channels/email.ts
- libs/shared/src/consts/providers/channels/push.ts
- libs/shared/src/consts/providers/channels/sms.ts
- Updated the doc reference links of the providers to the Novu guides.
https://github.com/novuhq/novu/assets/29251776/abf7a899-2594-4335-9ccf-748168d6cd52
> Nv 2204 update ux copy and links to the documentation for providers

- apps/api/src/app/integrations/usecases/get-In-app-activated/get-In-app-activated.usecase.ts
- apps/web/cypress/tests/changes.spec.ts
- apps/web/src/pages/integrations/components/FrameworkDisplay.tsx
- apps/web/src/pages/integrations/components/InAppSelectFramework.tsx
- apps/web/src/pages/integrations/components/NovuInAppProviderModal.tsx
> feat: add framework select accordion

- .github/workflows/test.yml
- apps/api/src/app/feature-flags/e2e/get-feature-flag.e2e.ts
- apps/api/src/app/feature-flags/feature-flags.module.ts
- apps/api/src/app/feature-flags/services/feature-flags.service.ts
- apps/api/src/app/feature-flags/services/launch-darkly.service.ts
- apps/api/src/app/feature-flags/types/index.ts
- apps/api/src/app/feature-flags/use-cases/get-feature-flag/get-feature-flag.command.ts
- apps/api/src/app/feature-flags/use-cases/get-feature-flag/get-feature-flag.use-case.ts
- apps/api/src/app/feature-flags/use-cases/get-feature-flag/index.ts
- apps/api/src/app/feature-flags/use-cases/index.ts
Implements the feature flag for the Template Store feature in the backend.
Helps to test the implementation of the feature flags module is working as expected.
> Nv 2325 create template store feature flag

- apps/web/src/pages/integrations/components/LimitBar.tsx
- apps/web/src/pages/integrations/components/Modal/NovuIntegrationCard.tsx
- apps/web/src/pages/integrations/components/NovuIntegrationCard.tsx
- fixes the copy for the Limit count status of novu providers
> fix: copy of limit status for novu providers

- apps/api/src/app/feature-flags/e2e/get-feature-flag.e2e.ts
> feat: skip ff test

- docs/docs/overview/quickstart/general-quickstart.md
- docs/docs/platform/topics.md
Fixes broken links on general quickstart
Fixes last failed deploy
> Docs(quickstarts: Fix broken links

- apps/web/src/pages/templates/components/GenerateContentButton.tsx
- apps/web/src/pages/templates/components/GenerateContentContextModal.tsx
- apps/web/src/pages/templates/components/StepName.tsx
Modal skeleton for the content generation context.
> feat(web): generate content context modal

- apps/web/src/pages/templates/components/GenerateContentButton.tsx
- apps/web/src/pages/templates/components/GenerateContentContextModal.tsx
- apps/web/src/pages/templates/components/StepName.tsx
Implement prompt for user's goal in the modal
> feat(web): create form and description generation for modal

- .github/workflows/prod-deploy-web.yml
Update eu mail server in prod deploy workflow for EU region
> fix: update eu mail server in prod deploy workflow

- apps/web/src/design-system/dropdown/Dropdown.tsx
- apps/web/src/design-system/popover/Popover.tsx
- apps/web/src/pages/auth/components/PasswordRequirementPopover.tsx
- Fixes the password strength meter crash
- Added middleware to Popover and Dropdown in our design system to fix crashes.
> Nv 2400 bug report sign up not working for docker based deployment

- packages/application-generic/src/services/analytics.service.ts
Add catch and log the error we get from segment.
In order to prevent job failure.
> feat: add log when segment is throwing error

- libs/shared/src/consts/template-store/index.ts
> feat: add popular template

- apps/api/src/app/messages/dtos/get-messages-requests.dto.ts
- apps/api/src/app/messages/e2e/get-messages.e2e.ts
- apps/api/src/app/messages/messages.controller.ts
- apps/api/src/app/messages/usecases/get-messages/get-messages.command.ts
- apps/api/src/app/messages/usecases/get-messages/get-messages.usecase.ts
- apps/api/src/app/messages/usecases/index.ts
- apps/api/src/app/notifications/dtos/activities-request.dto.ts
- docs/docs/platform/inbound-parse-webhook.md
- docs/docs/platform/messages.md
- libs/dal/src/repositories/message/message.repository.ts
- packages/node/src/index.ts
- packages/node/src/lib/messages/index.ts
- packages/node/src/lib/messages/messages.interface.ts
- packages/node/src/lib/messages/messages.spec.ts
- packages/node/src/lib/messages/messages.ts
- packages/node/src/lib/novu.ts
- Add transactionId filter in query params
- Add messages methods in node sdk
- Add related e2e and unit tests
- Add messages documentation
> feat: add transactionId filter in get messages

- docs/docs/notification-center/react/api-reference.md
- packages/client/src/api/api.service.ts
- packages/notification-center/src/hooks/index.ts
- packages/notification-center/src/hooks/useRemoveAllNotifications.ts
- packages/notification-center/src/shared/interfaces/index.ts
- packages/notification-center/src/store/notifications-provider.context.tsx
- Add `useRemoveAllNotification` hook
- Add `removeAllMessages` function in `useNotifications` hook
- Update API reference docs for above
> feat: add removeAllMessages function in react nc

- docs/docs/overview/quickstart/get-started-with-kotlin.md
**Kotlin Quickstart**
To guide Kotlin developers on how to easily set up and use the Novu Kotlin SDK
> Add Kotlin Quickstart Guide

- apps/api/src/app/workflows/usecases/change-workflow-active-status/change-workflow-active-status.command.ts
- apps/api/src/app/workflows/usecases/change-workflow-active-status/change-workflow-active-status.usecase.ts
- apps/api/src/app/workflows/usecases/create-notification-template/index.ts
- apps/api/src/app/workflows/usecases/create-workflow/create-workflow.command.ts
- apps/api/src/app/workflows/usecases/create-workflow/create-workflow.usecase.ts
- apps/api/src/app/workflows/usecases/create-workflow/index.ts
- apps/api/src/app/workflows/usecases/delete-workflow/delete-workflow.usecase.ts
- apps/api/src/app/workflows/usecases/get-workflow/get-workflow.command.ts
- apps/api/src/app/workflows/usecases/get-workflow/get-workflow.usecase.ts
- apps/api/src/app/workflows/usecases/get-workflows/get-workflows.command.ts
- apps/api/src/app/workflows/usecases/get-workflows/get-workflows.usecase.ts
- apps/api/src/app/workflows/usecases/index.ts
- apps/api/src/app/workflows/usecases/update-workflow/update-workflow.command.ts
- apps/api/src/app/workflows/usecases/update-workflow/update-workflow.usecase.ts
- apps/api/src/app/workflows/workflows.controller.ts
- Renamed the name of the usecases and commands to use workflow terminology
This PR is a part of stacked PRs
- https://github.com/novuhq/novu/pull/3704
- https://github.com/novuhq/novu/pull/3703
- https://github.com/novuhq/novu/pull/3702
- https://github.com/novuhq/novu/pull/3701
> feat: renamed the usecases/commands

- apps/api/src/app/workflows/e2e/change-workflow-status.e2e.ts
- apps/api/src/app/workflows/e2e/create-workflows.e2e.ts
- apps/api/src/app/workflows/e2e/delete-workflow.e2e.ts
- apps/api/src/app/workflows/e2e/get-workflow.e2e.ts
- apps/api/src/app/workflows/e2e/get-workflows.e2e.ts
- apps/api/src/app/workflows/e2e/update-workflow.e2e.ts
- apps/api/src/app/workflows/usecases/update-workflow/update-workflow.usecase.ts
- Updated the test cases of the new `Workflows` controller
This PR is a part of stacked PRs
- https://github.com/novuhq/novu/pull/3704
- https://github.com/novuhq/novu/pull/3703
- https://github.com/novuhq/novu/pull/3702
- https://github.com/novuhq/novu/pull/3701
> refactor: updated test cases for the workflow controller

- docs/docs/overview/quickstart/get-started-with-angular.md
- docs/docs/overview/quickstart/get-started-with-kotlin.md
- docs/docs/overview/quickstart/get-started-with-nextjs.md
- docs/docs/overview/quickstart/get-started-with-node.js.md
- docs/docs/overview/quickstart/get-started-with-php.md
- docs/docs/overview/quickstart/get-started-with-react.md
- docs/docs/overview/quickstart/get-started-with-ruby.md
- docs/docs/overview/quickstart/get-started-with-vanilla-js.md
- docs/docs/overview/quickstart/get-started-with-vue.md
> Update Quickstart Docs

- packages/notification-center/package.json
- pnpm-lock.yaml
Removes storybook testing library
Unused.
> fix(notification-center): remove storybook testing library

- docs/docs/overview/quickstart/get-started-with-dotnet.md
add dotnet guide
dotnet guide didnt exist before
> dotnet guide

- apps/web/cypress/tests/notification-editor/index.ts
- apps/web/cypress/tests/notification-editor/steps-actions.spec.ts
- apps/web/src/pages/templates/components/TemplateEditor.tsx
Steps to reproduce:
1. Create a workflow like this:- trigger → sms → delay → sms
2. Click on the first sms, and a content window will open on the right side
3. Add some content
4. Click on the second sms, the first sms content will be there for the second sms as well.
5. Try to change the content in the second sms, it will change for the first sms as well
Now click on either delay or trigger and then repeat step steps 3, 4, and 5. In this case, it will not change for both
> Content is changed in two sms steps with a delay in between.

- package.json
> fix(infra): provider generator should have version 0.16.3

- docs/docs/channels/email/index.mdx
- libs/shared/src/entities/notification-template/notification-template.interface.ts
- packages/node/src/index.ts
- packages/node/src/lib/events/events.interface.ts
- packages/node/src/lib/notification-template/notification-template.interface.ts
- packages/node/src/lib/notification-template/notification-template.spec.ts
- packages/node/src/lib/notification-template/notification-template.ts
1. export missing types
2. fix getAll params
> fix: export missing enums in node sdk for create template

- apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx
Will provide a webhook if it is available.
Only the cloud version supports it at the moment.
> fix: webhook enabled if app is not self-hosted

- apps/web/src/pages/integrations/components/IntegrationInput.tsx
On click on row of integration -> update integration gets the following error:
Happened because conditional register was removed while fixing merge conflict in original pr
> Fix register error

- apps/web/src/hooks/integrations/useIntegrationLimit.ts
- apps/web/src/pages/integrations/types.ts
- apps/web/src/pages/templates/components/email-editor/EmailContentCard.tsx
- apps/web/src/pages/templates/editor/Preview.tsx
Email Editor and Preview - show the correct sender name when there are multiple active integrations.
Multi Channel Provide Config PRD.
> chore(web): email editor and preview show correct sender name

- packages/node/src/lib/subscribers/subscriber.interface.ts
- packages/node/src/lib/subscribers/subscribers.spec.ts
- packages/node/src/lib/subscribers/subscribers.ts
> fix: non existing endpoint and adding mark as read function

- apps/api/src/app/integrations/dtos/get-active-integration-response.dto.ts
- apps/api/src/app/integrations/e2e/get-active-integration.e2e.ts
- apps/api/src/app/integrations/e2e/get-decrypted-integrations.e2e.ts
- apps/api/src/app/integrations/e2e/get-integration.e2e.ts
- apps/api/src/app/integrations/usecases/get-active-integration/get-active-integration.usecase.ts
- libs/testing/package.json
- libs/testing/src/integration.service.ts
- packages/application-generic/src/usecases/get-decrypted-integrations/get-decrypted-integrations.usecase.ts
- pnpm-lock.yaml
Fixes a couple of issues found when playing with the `/integrations/active` endpoint.
The details are specified in the ticket.
Multi Provider Configuration PRD.
> fix(api,application-generic): active integrations endpoint fixes

- apps/web/src/components/layout/AppLayout.tsx
- apps/web/src/components/layout/components/HeaderNav.tsx
- apps/web/src/design-system/sidebar/Sidebar.tsx
- apps/web/src/pages/integrations/IntegrationsListModal.tsx
- apps/web/src/pages/integrations/UpdateProviderPage.tsx
- apps/web/src/pages/integrations/components/multi-provider/UpdateProviderSidebar.tsx
Fixed the issue with the Intercom floating button that was overflowing the Integrations sidebar.
https://github.com/novuhq/novu/assets/2607232/3ffee9f6-4b49-4f60-bef7-2b868e301254
https://github.com/novuhq/novu/assets/2607232/b51b162f-4bb0-4a27-8954-8fc1d00274c5
> fix(web): intercom launcher floating button overflows the integrations sidebar

- docs/docs/channels/_category_.json
- docs/docs/community/_category_.json
- docs/docs/cookbook/_category_.json
- docs/docs/cookbook/introduction.md
- docs/docs/guides/_category_.json
- docs/docs/notification-center/_category_.json
- docs/docs/recipes/_category_.json
- docs/src/components/Discover.tsx
Adds a cookbook with a few recipes to the documentation.
We did not have a cookbook before now.
> Docs(chore): Add cookbook with few recipes

- apps/api/src/app/integrations/integrations.module.ts
- apps/api/src/app/integrations/usecases/create-novu-integrations/create-novu-integrations.command.ts
- apps/api/src/app/integrations/usecases/create-novu-integrations/create-novu-integrations.usecase.ts
- apps/api/src/app/integrations/usecases/index.ts
- apps/api/src/app/organization/organization.module.ts
- apps/api/src/app/organization/usecases/create-organization/create-organization.usecase.ts
- packages/application-generic/src/usecases/get-novu-integration/get-novu-integration.usecase.ts
Add use case to create novu providers and is used from create organization usecase
> feat: create novu providers when organization is created

- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- apps/api/src/app/subscribers/e2e/update-subscriber.e2e.ts
- packages/application-generic/src/usecases/update-subscriber/update-subscriber.usecase.ts
- packages/application-generic/src/utils/subscriber.ts
> Update subscriber trigger payload

- docs/docs/cookbook/introduction.md
> fix: remove version 17 info in cookbook

- packages/application-generic/src/services/analytics.service.ts
- packages/application-generic/src/usecases/add-job/add-job.usecase.ts
- packages/application-generic/src/usecases/digest-filter-steps/digest-filter-steps.usecase.ts
Improving context.
To help debug prod issues.
> fix(app-generic): adding context and information for logs for debugging

- apps/web/cypress/tests/integrations-list-modal.spec.ts
- apps/web/cypress/tests/integrations-list-page.spec.ts
- apps/web/src/pages/integrations/components/multi-provider/SelectProviderSidebar.tsx
- apps/web/src/pages/integrations/useProviders.ts
Remove Novu providers from select provider sidebar and from use providers if self hosted.
> feat: remove novu providers for select provider

- apps/web/cypress/tests/tenants-page.spec.ts
Test tenants list page, create and update sidebars
> feat: add tenant page tests

- docs/docs/overview/quickstart/get-started-with-python.md
> Docs: Add Python quickstart

- .github/ISSUE_TEMPLATE/bug_report.yml
Add few versions fields in bug template
> feat: add few versions fields in bug template

- packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.spec.ts
- packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts
- packages/application-generic/src/services/in-memory-provider/memory-db-cluster-provider.ts
Introduces
Adds MemoryDB as potential provider for InMemoryProviderService
Resiliency improvements. We need to migrate to use it in the different environments.
> Nv 2591 implement memorydb provider in inmemoryproviderservice

- packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.spec.ts
- packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts
- packages/application-generic/src/services/in-memory-provider/index.ts
- packages/application-generic/src/services/in-memory-provider/providers/elasticache-cluster-provider.ts
- packages/application-generic/src/services/in-memory-provider/providers/index.ts
- packages/application-generic/src/services/in-memory-provider/providers/memory-db-cluster-provider.ts
- packages/application-generic/src/services/in-memory-provider/providers/providers.spec.ts
- packages/application-generic/src/services/in-memory-provider/providers/redis-cluster-provider.ts
- packages/application-generic/src/services/in-memory-provider/providers/redis-provider.ts
- packages/application-generic/src/services/in-memory-provider/types.ts
A bit of cleaning and abstraction for the providers of the InMemoryProviderService.
> feat(app-generic): refactor in memory providers provisions

- apps/web/src/pages/integrations/components/multi-provider/SelectProviderSidebar.tsx
Add pointer cursor to provider item on hover
> feat: add hover state for provider item

- apps/api/migrations/novu-integrations/novu-integrations.migration.ts
Add so an Indentifier is created in migration for Novu provider.
> fix: add identifier in migration script for novu providers

- apps/web/src/pages/settings/tabs/ApiKeysCard.tsx
- apps/web/src/pages/settings/tabs/components/Regenerate.tsx
> feat: updated the settings page ui

- apps/web/src/design-system/tag/Tag.tsx
- apps/web/src/pages/invites/components/MembersTable.tsx
- Updated the Member's table UI
- Updated the `Tag` border color, font color in design system.
> feat: Updated members table UI

- apps/web/cypress/tests/subscribers.spec.ts
- apps/web/src/pages/integrations/components/IntegrationNameCell.tsx
- apps/web/src/pages/integrations/components/UpdateIntegrationCommonFields.tsx
- apps/web/src/pages/subscribers/SubscribersListPage.tsx
- apps/web/src/pages/templates/WorkflowListPage.tsx
- apps/web/src/pages/templates/components/notification-setting-form/NotificationSettingsForm.tsx
Change labels according to issue
> feat: make identifier labels consistent

- apps/web/cypress/tests/notification-editor/create-notification.spec.ts
- apps/web/src/pages/templates/components/in-app-editor/InAppEditorBlock.tsx
Render html in in app preview.
> feat: render html in in app preview

- apps/web/src/design-system/icons/general/BoltFilled.tsx
- apps/web/src/design-system/icons/general/BoltOffFilled.tsx
- apps/web/src/design-system/icons/index.ts
- apps/web/src/pages/templates/WorkflowListPage.tsx
- updated the workflow list ui
> Nv 2639 workflows list UI

- apps/web/src/design-system/table/Table.tsx
- apps/web/src/pages/subscribers/SubscribersListPage.tsx
- Updated the date format for created at
> feat: Subscribers list UI

- apps/web/src/components/layout/components/PageContainer.tsx
- apps/web/src/pages/quick-start/components/layout/BodyLayout.tsx
- apps/web/src/pages/quick-start/components/layout/FooterLayout.tsx
- apps/web/src/pages/quick-start/components/layout/GetStartedLayout.tsx
- apps/web/src/pages/quick-start/components/layout/HeaderLayout.tsx
- apps/web/src/pages/quick-start/steps/DigestPreview.tsx
- apps/web/src/pages/quick-start/steps/GetStarted.tsx
- Updated the get started page
- made the footer absolute position
https://github.com/novuhq/novu/assets/29251776/569e29e8-3e78-4092-90c7-433b88be1292
> feat: updated the get started layout page

- apps/api/src/app/organization/e2e/members/change-member-role.e2e.ts
- apps/api/src/app/organization/usecases/membership/change-member-role/change-member-role.usecase.ts
- apps/web/src/pages/invites/components/MemberRole.tsx
- apps/web/src/pages/invites/components/MembersTable.cy.tsx
- apps/web/src/pages/invites/components/MembersTable.tsx
> feat: disable role toggle

- apps/web/src/pages/templates/workflow/SideBar/Sidebar.tsx
- apps/web/src/pages/templates/workflow/WorkflowEditor.tsx
> refactor: editor sidebar

- apps/web/src/pages/templates/components/ProvidersPage.tsx
- adds scrollbar to the providers tab inside editor ui
https://github.com/novuhq/novu/assets/29251776/5fd7ba8e-5bf3-474d-9260-fcad277241ff
> Providers tab scroll

- apps/web/src/components/layout/components/SideNav.tsx
The smallest PR ever :)
Fixes the popover problem with env switch, more details here: https://discord.com/channels/895029566685462578/1045289346598703164/1139504634889785345
Before:
After:
> fix(web): fixed env switch popover issue

- apps/worker/src/app/workflow/services/cold-start.service.ts
- apps/worker/src/app/workflow/services/index.ts
- apps/worker/src/app/workflow/services/old-instance-workflow.worker.ts
- apps/worker/src/app/workflow/services/standard.worker.ts
- apps/worker/src/app/workflow/workflow.module.ts
- packages/application-generic/src/custom-providers/index.ts
- packages/application-generic/src/modules/queues.module.ts
- packages/application-generic/src/services/bull-mq/index.ts
- packages/application-generic/src/services/bull-mq/old-instance-bull-mq.service.ts
- packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts
- packages/application-generic/src/services/in-memory-provider/providers/index.ts
- packages/application-generic/src/services/in-memory-provider/providers/redis-provider.ts
- packages/application-generic/src/services/in-memory-provider/types.ts
- packages/application-generic/src/services/index.ts
- packages/application-generic/src/services/workers/index.ts
- packages/application-generic/src/services/workers/old-instance-workflow-worker.service.ts
Introduces a worker for the old instance of Redis so we can keep reading it until consumption.
For a smooth migration from the Redis instance to MemoryDB.
> feat(infra): implement memory db and dual reads from old database

- .github/actions/run-api/action.yml
- .github/actions/validate-swagger/action.yml
> fix(ci): indenting action

- apps/api/src/app/logs/usecases/create-log/create-log.usecase.ts
- apps/inbound-mail/src/server/index.ts
- apps/worker/src/app/shared/logs/create-log.usecase.ts
- apps/worker/src/app/workflow/services/metric-queue.service.ts
- apps/worker/src/app/workflow/services/workflow-queue.service.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts
- apps/worker/src/app/workflow/usecases/webhook-filter-backoff-strategy/webhook-filter-backoff-strategy.usecase.ts
- apps/ws/src/socket/services/socket-queue-consumer.service.ts
- packages/application-generic/src/services/analytics.service.ts
- packages/application-generic/src/services/cache/cache.service.ts
- packages/application-generic/src/services/cache/interceptors/cached-entity.interceptor.ts
- packages/application-generic/src/services/cache/interceptors/cached-query.interceptor.ts
- packages/application-generic/src/services/cache/interceptors/cached.interceptor.ts
- packages/application-generic/src/services/cache/invalidate-cache.service.ts
- packages/application-generic/src/services/distributed-lock/distributed-lock.service.ts
- packages/application-generic/src/services/feature-flags.service.ts
- packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts
- packages/application-generic/src/services/launch-darkly.service.ts
- packages/application-generic/src/services/readiness.service.ts
- packages/application-generic/src/usecases/create-notification-jobs/create-notification-jobs.usecase.ts
- packages/application-generic/src/usecases/digest-filter-steps/digest-filter-steps.usecase.ts
- packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
> feat: fix logger error order

- apps/webhook/src/webhooks/usecases/execution-details/create-execution-details.usecase.ts
- libs/dal/src/repositories/base-repository.ts
> clean patch - execution details no write concern

- .github/actions/run-backend/action.yml
- .github/workflows/reusable-web-e2e.yml
- .github/workflows/reusable-widget-e2e.yml
- apps/web/src/index.tsx
> Fix failing test for web and widget

- apps/webhook/src/webhooks/usecases/execution-details/create-execution-details.usecase.ts
- libs/dal/src/repositories/base-repository.ts
> feat: execution detail no write concern

- apps/worker/src/app/workflow/workflow.module.ts
> fix: invalid import - process tenant

- apps/web/src/App.tsx
- apps/web/src/constants/routes.enum.ts
- apps/web/src/pages/brand/BrandPage.tsx
- apps/web/src/pages/brand/tabs/BrandingForm.cy.tsx
- apps/web/src/pages/brand/tabs/BrandingForm.tsx
- apps/web/src/pages/brand/tabs/LayoutsListPage.tsx
> Refactor branding tabs to routes

- apps/api/src/app/integrations/dtos/integration-response.dto.ts
- apps/api/src/app/workflows/dto/workflow-response.dto.ts
- apps/api/src/app/workflows/usecases/get-active-integrations-status/get-active-integrations-status.spec.ts
- apps/api/src/app/workflows/usecases/get-active-integrations-status/get-active-integrations-status.usecase.ts
- apps/web/cypress/tests/notification-editor/create-notification.spec.ts
- apps/web/src/components/workflow/FlowEditor.tsx
- apps/web/src/components/workflow/types.ts
- apps/web/src/design-system/icons/general/ChatFilled.tsx
- apps/web/src/design-system/icons/general/EmailFilled.tsx
- apps/web/src/design-system/icons/general/InAppFilled.tsx
- apps/web/src/design-system/icons/general/PushFilled.tsx
- apps/web/src/design-system/icons/general/SmsFilled.tsx
- apps/web/src/hooks/useTemplates.ts
- apps/web/src/pages/templates/WorkflowListPage.tsx
- apps/web/src/pages/templates/components/templates-store/TemplatesStoreModal.tsx
- apps/web/src/pages/templates/components/templates-store/TriggerNode.tsx
- apps/web/src/pages/templates/workflow/DisplayPrimaryProviderIcon.tsx
- apps/web/src/pages/templates/workflow/digest/TimedDigestWillBeSentHeader.tsx
- apps/web/src/pages/templates/workflow/digest/WillBeSentHeader.tsx
- apps/web/src/pages/templates/workflow/workflow/node-types/ChannelNode.tsx
- apps/web/src/pages/templates/workflow/workflow/node-types/TriggerNode.tsx
- apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNode.tsx
- libs/shared/src/types/notification-templates/index.ts
- Shows primary provider in the channel node
> feat: show providers on workflow nodes

- .gitmodules
Add an enterprise submodule so we can use the inner packages.
recreation of nv-2177
> feat: init git submodule

- docs/docs/overview/quickstart/get-started-with-java.md
Quick Start guide for Novu Java Sdk
I created a Quick Starter file for the Java Sdk
> Java Quickstart

- packages/notification-center/src/components/notification-center/components/AppContent.tsx
> Revert "NV-1959B - 🐛 Bug Report: The Notification Center isn't mobile responsive"

- apps/api/package.json
- apps/inbound-mail/package.json
- apps/webhook/package.json
- apps/worker/package.json
- apps/ws/package.json
- packages/application-generic/package.json
- pnpm-lock.yaml
> V0.19.x alpha 1

- apps/web/src/design-system/icons/general/Condition.tsx
- apps/web/src/design-system/icons/index.ts
- apps/web/src/pages/integrations/IntegrationsList.tsx
- apps/web/src/pages/integrations/components/ConditionCell.tsx
- apps/web/src/pages/integrations/types.ts
> Nv 2681 show the number of applied conditions on the integration

- apps/api/src/app/widgets/e2e/get-unread-count.e2e.ts
- apps/api/src/app/widgets/widgets.controller.ts
> fix: unread request

- apps/web/src/components/utils/ProductLead.tsx
- apps/web/src/pages/templates/components/TranslateProductLead.tsx
> fix: so closing x is in the right place

- apps/web/src/pages/integrations/components/UpdateIntegrationSidebarHeader.tsx
- apps/web/src/pages/integrations/components/multi-provider/SelectPrimaryIntegrationModal.tsx
- apps/web/src/pages/integrations/components/multi-provider/UpdateProviderSidebar.tsx
- apps/web/src/pages/integrations/types.ts
Not sure the logic is right so please double-check it otherwise we should be good.
> feat: add logic for select primary integration modal

- apps/web/src/pages/templates/workflow/workflow/node-types/AddNode.tsx
Fix alignment of delay icon in workflow popup action menu.
closes https://github.com/novuhq/novu/issues/4046
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
> NV-2765 - 🐛 Bug Report: delay icon is not aligned with other steps icon

- apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts
- packages/application-generic/src/usecases/select-integration/select-integration.usecase.ts
Fix so integration with conditions is picked.
> fix: select integration with condtions

- .github/actions/checkout-submodules/action.yml
> fix: run rename

- apps/web/cypress/tests/integrations-list-page.spec.ts
- apps/web/src/components/conditions/Conditions.tsx
- apps/web/src/components/execution-detail/ExecutionDetailsConditionItem.cy.tsx
- apps/web/src/components/execution-detail/ExecutionDetailsConditions.cy.tsx
- apps/web/src/pages/integrations/components/ConditionCell.tsx
- apps/web/src/pages/integrations/components/ConditionIconButton.tsx
- apps/web/src/pages/integrations/components/IntegrationNameCell.tsx
- apps/web/src/pages/integrations/components/PrimaryIconButton.tsx
- apps/web/src/pages/integrations/components/multi-provider/CreateProviderInstanceSidebar.tsx
Cypress tests for integrations create/update flow with conditions
> test: conditions for integration tests

- .github/workflows/dev-deploy-inbound-mail.yml
> Fix Inbound Mail Deployment

- packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts
> fix(app-generic): remove in-memory stranded log

- .github/workflows/dev-deploy-api.yml
- .github/workflows/prod-deploy-api.yml
- apps/api/src/bootstrap.ts
> Add missing ee tests on deployment

- apps/api/src/app/shared/dtos/message-template.ts
- apps/api/src/app/shared/helpers/content.service.ts
- apps/api/src/app/workflows/usecases/create-notification-template/create-notification-template.command.ts
- apps/api/src/app/workflows/usecases/update-notification-template/update-notification-template.command.ts
- apps/api/src/app/workflows/usecases/update-notification-template/update-notification-template.usecase.ts
- apps/web/src/pages/templates/components/in-app-editor/InAppEditorBlock.tsx
- apps/web/src/pages/templates/components/in-app-editor/preview/ActionBlockContainer.tsx
- apps/web/src/pages/templates/components/in-app-editor/preview/InAppWidgetPreview.tsx
- apps/web/src/pages/templates/components/templateToFormMappers.ts
- libs/dal/src/repositories/message-template/message-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/shared/src/entities/message-template/message-template.interface.ts
- libs/shared/src/entities/messages/messages.interface.ts
- libs/shared/src/entities/notification-template/notification-template.interface.ts
Added the use of our @ shared interfaces.
so we will be more consistent with our entities.
It was a small refactor but IMO we need to make sure that we reuse the same interfaces in order to help us avoid potential bugs.
> chore: used workflow shared interfaces

- packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
> Catch unexpected error while trigger event

- apps/api/src/app/events/usecases/parse-event-request/parse-event-request.e2e.ts
- apps/api/src/app/events/usecases/parse-event-request/parse-event-request.usecase.ts
> Throw exception on subscriber id as array

- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-in-app.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message.base.ts
- apps/worker/src/app/workflow/workflow.module.ts
- libs/dal/src/repositories/notification-template/notification-template.schema.ts
- libs/shared/src/entities/job/index.ts
- libs/shared/src/entities/job/job.interface.ts
- libs/testing/src/create-notification-template.interface.ts
- libs/testing/src/notification-template.service.ts
- packages/application-generic/package.json
- packages/application-generic/src/usecases/conditions-filter/conditions-filter.command.ts
- packages/application-generic/src/usecases/conditions-filter/conditions-filter.usecase.ts
- packages/application-generic/src/usecases/create-execution-details/create-execution-details.command.ts
- packages/application-generic/src/usecases/create-execution-details/types/index.ts
- packages/application-generic/src/usecases/index.ts
- packages/application-generic/src/usecases/select-integration/select-integration.spec.ts
- packages/application-generic/src/usecases/select-integration/select-integration.usecase.ts
- packages/application-generic/src/usecases/select-variant/index.ts
- packages/application-generic/src/usecases/select-variant/select-variant.command.ts
- packages/application-generic/src/usecases/select-variant/select-variant.spec.ts
- packages/application-generic/src/usecases/select-variant/select-variant.usecase.ts
- packages/application-generic/src/utils/filter-processing-details.ts
- packages/application-generic/src/utils/hmac.ts
- pnpm-lock.yaml
We are introducing the variants and conditions to the workflow steps. Now we have to implement the logic that during the send phase will execute the variant conditions and will determine based on the trigger context provided which variant and content should be sent to the user as a notification.
Use-case: clients want to send different message contents to their tenant users.
* during the send phase write the logic that will determine which variant of the content to send to the user
* e2e tests
* Send execution details with the chosen variant if possible.
> feat: implement the logic that will determine which variant should be

- CONTRIBUTING.md
> docs: fix link to docs

- apps/web/src/components/utils/ProductLead.tsx
- apps/web/src/pages/templates/components/TranslateProductLead.tsx
I see that after some changes the product lead component is broken again. This PR fixes it.
https://github.com/novuhq/novu/assets/2607232/ebc845c1-a77e-4e7f-9b1a-6ecf5a0ffe2e
> fix(web): product lead

- apps/api/src/app/messages/dtos/remove-messages-by-transactionId-request.dto.ts
- apps/api/src/app/messages/e2e/remove-messages-by-transactionId.e2e.ts
- apps/api/src/app/messages/messages.controller.ts
- apps/api/src/app/messages/usecases/index.ts
- apps/api/src/app/messages/usecases/remove-messages-by-transactionId/remove-messages-by-transactionId.command.ts
- apps/api/src/app/messages/usecases/remove-messages-by-transactionId/remove-messages-by-transactionId.usecase.ts
- libs/dal/src/repositories/message/message.repository.ts
- pnpm-lock.yaml
- adds a new endpoint which allows user to delete messages using transactionId.
> Nv 2744 remove messages by transactionid

- apps/worker/src/app/workflow/services/cold-start.service.ts
- apps/worker/src/app/workflow/services/index.ts
- apps/worker/src/app/workflow/services/old-instance-standard.worker.ts
- apps/worker/src/app/workflow/workflow.module.ts
- packages/application-generic/src/modules/queues.module.ts
- packages/application-generic/src/services/workers/index.ts
- packages/application-generic/src/services/workers/old-instance-standard-worker.service.ts
> fix(app-generic): proper naming for the standard worker and worker svc

- apps/worker/src/app/workflow/services/old-instance-workflow.worker.ts
- apps/worker/src/app/workflow/services/standard.worker.ts
- apps/worker/src/app/workflow/services/workflow.worker.ts
- apps/worker/src/app/workflow/usecases/run-job/run-job.usecase.ts
> fix(worker): addded some logs

- apps/api/package.json
- apps/web/package.json
- pnpm-lock.yaml
We are not using `graphql` and it contains a moderate vulnerability.
> chore: remove unused graphql

- libs/embed/package.json
- packages/cli/package.json
- pnpm-lock.yaml
Containing sub dependencies contain some vulnerable yargs-parser versions
> chore: remove unused packages

- apps/api/src/app/inbound-parse/e2e/inbound-email-parse.e2e.ts
- apps/api/src/app/inbound-parse/services/inbound-parse.queue.service.ts
- apps/api/src/app/inbound-parse/usecases/inbound-email-parse/inbound-email-parse.usecase.ts
> Add context to inbound email parse logger

- packages/cli/package.json
- pnpm-lock.yaml
> refactor: replace cp-cli with ncp

- packages/headless/src/lib/headless.service.test.ts
- packages/headless/src/lib/headless.service.ts
Add `markNotificationsAs` to headlessService
> Add markNotificationsAs

- apps/api/e2e/compile-email-template.e2e.ts
- apps/api/src/app/events/usecases/parse-event-request/parse-event-request.usecase.ts
- apps/api/src/app/events/usecases/verify-payload/verify-payload.spec.ts
- apps/api/src/app/subscribers/usecases/search-by-external-subscriber-ids/search-by-external-subscriber-ids.spec.ts
- apps/inbound-mail/src/python/DNS/win32dns.py
- apps/inbound-mail/src/python/dkim/__init__.py
- apps/inbound-mail/src/python/ipaddr.py
- apps/inbound-mail/src/python/spf.py
- apps/worker/src/app/workflow/services/active-jobs-metric.service.ts
- apps/worker/src/app/workflow/services/completed-jobs-metric.service.ts
Fixes assorted typos and spelling
It's easier to understand if it is spelled correctly. This is especially important for those for whom english may not be their first language
> FIX Typos and spelling corrections

- README.md
fix :https://github.com/novuhq/novu/issues/4373
Adds the Rust SDK to the hacktoberfest repo list
We have added a [CONTRIBUTING.md](https://github.com/novuhq/novu-elixir/blob/main/CONTRIBUTING.md) file, ensured CI is passing, and [labeled recent issues for hacktoberfest](https://github.com/novuhq/novu-elixir/issues).
> feat: added RustSDK to README.md file

- apps/api/src/app/workflows/e2e/get-notification-templates.e2e.ts
- libs/dal/src/repositories/notification-template/notification-template.repository.ts
- removes variant data from the workflow list response.
- e2e test for the same
> feat: remove variants from the workflow list response

- packages/application-generic/src/services/bull-mq/bull-mq.service.ts
> 0.20 patch - fix bulk options

- apps/widget/src/components/notification-center/NotificationCenterWidget.tsx
> fix: cors issue for iframe

- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- libs/testing/src/create-notification-template.interface.ts
- libs/testing/src/notification-template.service.ts
- packages/application-generic/src/usecases/subscriber-job-bound/subscriber-job-bound.command.ts
- packages/application-generic/src/usecases/subscriber-job-bound/subscriber-job-bound.usecase.ts
- packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
Fixed the issue with the actor (subscriber) avatar not showing up in the NC notification feed.
Included the E2E tests to cover the avatar functionality.
> fix(worker): user avatar is not showing up in in-app notification

- apps/api/README.md
Update README.md in novu/apps/api
I have included a link to the TypeScript documentation in the README.
It will help users reference and set up the project with ease
> added Typescript docs

- docker/kubernetes/helm/README.md
This PR fixes typo `depencencies -> dependencies`
> docs: fix typo in docker/kubernetes/helm/README.md

- packages/node/README.md
This PR fixes typos `exisiting -> existing` and `environmet -> environment`
> docs: fix typo in packages/node/README.md

- docker/local/Readme.md
Added Redis Cluster documentation
It is necessary to make users understand about Redis Cluster and for that I had put the docs link.
Those who are new to novu repository and exploring the cloud part then for them we can put this.
> redis docs

- README.md
> Remove Product Hunt and added UTMs

- apps/web/src/App.tsx
- apps/web/src/components/workflow/FlowEditor.tsx
- apps/web/src/components/workflow/types.ts
- apps/web/src/design-system/sidebar/Sidebar.tsx
- apps/web/src/pages/templates/components/EditorSidebarHeaderActions.tsx
- apps/web/src/pages/templates/components/StepEditorSidebar.tsx
- apps/web/src/pages/templates/components/VariantItemCard.tsx
- apps/web/src/pages/templates/components/VariantsPage.tsx
- apps/web/src/pages/templates/hooks/useBasePath.ts
- apps/web/src/pages/templates/hooks/useFilterPartsList.ts
- apps/web/src/pages/templates/hooks/useStepVariantsCount.ts
- apps/web/src/pages/templates/hooks/useStepsBefore.ts
- apps/web/src/pages/templates/workflow/WorkflowEditor.tsx
- apps/web/src/pages/templates/workflow/workflow/node-types/ChannelNode.tsx
- pnpm-lock.yaml
- add variants flow for the editorSidebarHeaderActions
> feat: add variant flow

- packages/application-generic/src/factories/mail/handlers/mandrill.handler.ts
- providers/mandrill/README.md
- providers/mandrill/src/lib/mandril.interface.ts
- providers/mandrill/src/lib/mandrill.provider.spec.ts
- providers/mandrill/src/lib/mandrill.provider.ts
Fixed issue #4558 by implementing an additional parameter that Mandrill required. 
Closes #4558
> fix: sender name in mandrill provider

- apps/web/src/pages/templates/components/EditorSidebarHeaderActions.tsx
- apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx
- apps/web/src/pages/templates/components/VariantItemCard.tsx
- adds delete functionality of variants and steps
> feat: added delete functionality

- apps/web/src/components/conditions/Conditions.tsx
Fixed the Conditions component scrollbar and the operator field issues.
Before:
After:
> fix(web): the conditions scrollbar issue

- apps/api/src/app/events/e2e/send-message-push.e2e.ts
- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- pnpm-lock.yaml
There was some flakiness in a pair of tests that failed in the CI/CD and locally. Individually the tests were passing.
Clean the error reporting in the CI/CD.
> fix(api): few tests were flakey in the ci/cd

- packages/notification-center/src/i18n/languages/ka.ts
Adding a typescript file for the Georgian Language
There was no support for the Georgian Language. So I created a typescript file for Georgian language
> Added a typescript file for the Georgian Language

- SECURITY.md
Revised the security.md document for improved clarity and structure, including enhanced security reporting guidelines and contact information.
Closes #4654
> Enhanced Security Contact Information

- README.md
- apps/worker/README.md
- packages/cli/README.MD
- packages/node/README.md
I have changed the name of Twitter to X in all the documentation of this repo.
Everyone must be well aware by now that the legal name of Twitter has been formally changed to X. Therefore, I have updated the README files and corrected the name to X.
This repository has so many stars and forks. Isn't it for the best to be updated with the latest?
Closes #4663 
@Cliftonz @jainpawan21 
Kindly review this Pull Request and merge it. Suggest changes (if any)
> Updated the name of Twitter to X in all docs

- .github/workflows/pr-labeler.yml
Fixes to `pr-labeler.yml` workflow
https://github.com/novuhq/novu/actions/runs/6732383844/job/18298980672?pr=4742
https://github.com/marketplace/actions/labeler
https://github.com/marketplace/actions/pr-metrics
> Fix `pr-labeler.yml` workflow

- apps/api/src/app/shared/dtos/preference-channels.ts
- apps/api/src/app/shared/shared.module.ts
- apps/api/src/app/workflows/dto/create-workflow-override-request.dto.ts
- apps/api/src/app/workflows/dto/create-workflow-override-response.dto.ts
- apps/api/src/app/workflows/dto/workflow-response.dto.ts
- apps/api/src/app/workflows/e2e/create-workflow-override.spec.ts
- apps/api/src/app/workflows/usecases/create-workflow-override/create-workflow-override.command.ts
- apps/api/src/app/workflows/usecases/create-workflow-override/create-workflow-override.usecase.ts
- apps/api/src/app/workflows/usecases/index.ts
- apps/api/src/app/workflows/workflow.controller.ts
- libs/dal/src/repositories/message-template/message-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/dal/src/repositories/workflow-override/index.ts
- libs/dal/src/repositories/workflow-override/types.ts
- libs/dal/src/repositories/workflow-override/workflow-override.entity.ts
- libs/dal/src/repositories/workflow-override/workflow-override.schema.ts
- libs/shared/src/dto/index.ts
- libs/shared/src/dto/workflow-override/create-workflow-override.dto.ts
- libs/shared/src/dto/workflow-override/index.ts
- libs/shared/src/entities/message-template/message-template.interface.ts
- libs/shared/src/entities/workflow-override/index.ts
- libs/shared/src/entities/workflow-override/workflow-override.interface.ts
- libs/shared/src/index.ts
- libs/shared/src/types/index.ts
- libs/shared/src/types/workflow-override/index.ts
- libs/shared/src/types/workflow-override/types.ts
* Workflow configurations (enabled, disabled)
* Channel Preferences
In some cases particular workflows should be managed in coordination with a given tenant, meaning that for a workflow:
* Tenants can have different preference defaults
* The tenant can have the whole workflow as disabled altogether
* add create workflow override usecase.
* e2e
> Create workflow override use-case

- apps/api/src/app/workflows/dto/get-workflow-overrides-request.dto.ts
- apps/api/src/app/workflows/dto/get-workflow-overrides-response.dto.ts
- apps/api/src/app/workflows/e2e/get-workflow-overrides.e2e.ts
- apps/api/src/app/workflows/usecases/get-workflow-overrides/get-workflow-overrides.command.ts
- apps/api/src/app/workflows/usecases/get-workflow-overrides/get-workflow-overrides.usecase.ts
- apps/api/src/app/workflows/usecases/index.ts
- apps/api/src/app/workflows/workflow.controller.ts
- libs/dal/src/repositories/workflow-override/workflow-override.repository.ts
- libs/shared/src/dto/workflow-override/get-workflow-overrides-response.dto.ts
- libs/shared/src/dto/workflow-override/index.ts
- libs/testing/src/workflow-override.service.ts
* Workflow configurations (enabled, disabled)
* Channel Preferences
In some cases particular workflows should be managed in coordination with a given tenant, meaning that for a workflow:
* Tenants can have different preference defaults
* The tenant can have the whole workflow as disabled altogether
* add get workflow overrides usecase.
* e2e
> Get workflow overrides use case

- apps/worker/src/app/workflow/usecases/send-message/digest/digest.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/digest/get-digest-events.usecase.ts
- packages/application-generic/src/usecases/create-execution-details/types/index.ts
- Add the existing digest activity feed log
- Remove duplicate digest activity feed log
> fix(worker): Add activity log for events when they digest in the mergedDigestId flow

- apps/web/src/pages/templates/workflow/digest/BackOffFields.tsx
Add marginLeft 10 with text
Before :-
After :-
> fix(visual-bug): left spacing of frequent event in digest

- packages/node/README.md
location: https://github.com/novuhq/novu/tree/next/packages/node#update-a-subscriber
Resolves #4861 
Before:
After:
> Docs Feedback: js code in update-subscriber method has syntax issues

- packages/node/README.md
I have changed syntax in https://github.com/novuhq/novu/tree/next/packages/node#readme
In this pull request, I've addressed several syntax issues and corrected the code snippets. The primary changes include:
Replaced semicolons (;) with commas (,) in various method calls, fixing syntax errors.
Ensured proper separation of key-value pairs in object literals.
**Syntax Compliance:** The original code contained semicolons as separators in object literals, which is not the correct syntax in JavaScript/TypeScript. By replacing them with commas, we align the code with standard practices, enhancing readability and maintainability.
**Preventing Errors:** Semicolons in object literals can lead to unintended consequences and errors. Correcting this ensures that the code executes without …
> Updated the syntax in many of the methods

- apps/api/src/app/workflows/e2e/create-notification-templates.e2e.ts
- apps/api/src/app/workflows/usecases/create-notification-template/create-notification-template.usecase.ts
Steps to reproduce: 
Go to the workflow page
click on the Create Workflow button
choose password reset workflow (or any other) from pre-made workflows
update something if you want to update some content in that
Go to the changes page, find out changes related to this newly added workflow
Try to promote this change
You will get this error similar to the attached image
Its a bug.
The fix for this is to go back to workflow settings change the notification group to other and update and promote
> Create change on group and feed creation

- .github/workflows/test.yml
- apps/api/src/app/events/e2e/trigger-event.e2e.ts
- apps/api/src/app/workflow-overrides/workflow-overrides.controller.ts
> chore(ci): fixing the e2e pipeline for api

- providers/sparkpost/README.md
This PR adds the usage section in the readme documentation for the sparkpost provider 
The Readme file of Sparkpost was missing with the usage section which makes the user experience weak . This PR adds the missing usage section in the readme file
> Added the usage section in the sparkpost

- apps/api/src/app/inbound-parse/services/inbound-parse.queue.service.ts
- apps/inbound-mail/src/server/inbound-mail.service.spec.ts
- apps/inbound-mail/src/server/inbound-mail.service.ts
- packages/application-generic/src/custom-providers/index.ts
- packages/application-generic/src/health/inbound-parse-queue.health-indicator.ts
- packages/application-generic/src/modules/queues.module.ts
- packages/application-generic/src/services/queues/index.ts
This adds reply to emails to the queue metrics, it will also allow us to see how often the inbound mail is being used.
> Add inbound mail Queue to metrics

- packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
> fix(worker): addressing type backward compatibility

- apps/web/src/components/layout/components/NotificationCenterWidget.tsx
- apps/web/src/config/index.ts
- updated API URL to connect to novu prod API in eu region
> fix(web): nc loading issue for eu env

- apps/api/src/app/inbound-parse/inbound-parse.module.ts
> fix(worker): inbound parse worker initialize

- apps/api/src/app/content-templates/content-templates.module.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-in-app.usecase.ts
- packages/application-generic/package.json
- packages/application-generic/src/usecases/compile-email-template/compile-email-template.usecase.ts
- packages/application-generic/src/usecases/compile-in-app-template/compile-in-app-template.usecase.ts
- packages/application-generic/src/usecases/compile-template/compile-template.base.ts
- packages/application-generic/src/usecases/compile-template/index.ts
Translation variables that are used in the message template are rendered with the correct translation in the previews
> Show translations in email and in app preview

- apps/worker/src/app/workflow/services/execution-log.worker.spec.ts
- libs/shared/src/config/job-queue.ts
- packages/application-generic/src/services/queues/execution-log-queue.service.spec.ts
> Revert "Update job-queue.ts"

- apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message-in-app.usecase.ts
> fix: bind init translation function

- apps/api/package.json
- pnpm-lock.yaml
- providers/sendgrid/jest.config.js
- providers/sendgrid/package.json
Vulnerability in axios dependant
> chore(deps): upgrade sendgrid version to latest

- .github/workflows/reusable-web-e2e.yml
- .github/workflows/test.yml
- apps/web/cypress/tests/translations/translation-group.spec-ee.ts
- apps/web/package.json
> feat: add ee web tests

- .github/workflows/reusable-api-e2e.yml
- .github/workflows/test.yml
e2e-ee if statement.
I suspect that the if statement syntax is not working as expected.
> Fix e2e-ee if statement

- packages/application-generic/package.json
- packages/application-generic/src/services/analytics.service.ts
- packages/cli/package.json
- packages/cli/src/services/analytics.service.ts
- pnpm-lock.yaml
> refactor: replace deprecated segment library

- apps/web/package.json
- apps/web/src/pages/brand/tabs/LayoutEditor.tsx
- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
- apps/web/src/pages/templates/components/email-editor/EmailContentCard.tsx
- apps/web/src/pages/templates/components/in-app-editor/InAppEditorBlock.tsx
- pnpm-lock.yaml
> feat: change from ace editor to monaco editor

- .cspell.json
- apps/api/src/app/testing/translations/delete-translation-group.e2e-ee.ts
- apps/api/src/app/testing/translations/delete-translation.e2e-ee.ts
- delete translation file of a locale
- UI with delete modal
> Nv 2898 delete the translation file

- apps/web/src/pages/templates/components/CustomCodeEditor.css
- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
> feat: add translation suggestions and style editor

- apps/api/src/app/content-templates/content-templates.controller.ts
- apps/api/src/app/content-templates/e2e/preview-step.e2e.ts
- apps/api/src/app/content-templates/usecases/index.ts
- packages/application-generic/src/usecases/compile-step-template/compile-step-template.command.ts
- packages/application-generic/src/usecases/compile-step-template/compile-step-template.usecase.ts
- packages/application-generic/src/usecases/compile-step-template/index.ts
- packages/application-generic/src/usecases/index.ts
- added preview template endpoint for other step channels
> feat: preview step

- apps/api/src/app/workflow-overrides/e2e/create-workflow-override.e2e.ts
- apps/api/src/app/workflow-overrides/usecases/create-workflow-override/create-workflow-override.usecase.ts
Adds organization on override creation.
It was missing.
> Fix - add missing organization

- apps/web/src/pages/templates/components/CustomCodeEditor.css
- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
> feat: add light theme for custom code editor

- apps/web/src/pages/templates/components/email-editor/AutoSuggestionsDropdown.tsx
- apps/web/src/pages/templates/components/email-editor/TextRowContent.tsx
- added autosuggestions dropdown for variables
https://github.com/novuhq/novu/assets/29251776/c365febe-bcc9-482c-85ca-d581662d79c2
> Nv 3002 email editor variables auto suggestion dropdown

- enterprise/packages/translation-web/package.json
- pnpm-lock.yaml
Add diff view after upload of new file for translations - added the monaco dependency
> feat: add diff view for translations

- pnpm-lock.yaml
- providers/resend/package.json
- providers/resend/src/lib/resend.provider.spec.ts
- providers/resend/src/lib/resend.provider.ts
Vulnerability in sub package of axios
> fix: resend sdk version

- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
- apps/web/src/pages/templates/components/email-editor/AutoSuggestionsDropdown.tsx
- add i18n text key to the editor upon selection of suggestions
https://github.com/novuhq/novu/assets/29251776/0804d7e8-a3ad-4cb9-b7fd-06bfa1eb5204
> fix: add i18n to suggestion selection

- apps/web/src/pages/templates/components/email-editor/AutoSuggestionsDropdown.tsx
- added novu helpers to auto suggestions
- fixed some styles
> fix: add novu helpers to auto suggestions

- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
- apps/web/src/pages/templates/components/email-editor/AutoSuggestionsDropdown.tsx
When the editor mounts the auto suggestion completion lists gets duplicated each time.
> fix: duplicated in autocomplete

- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
- apps/web/src/pages/templates/components/email-editor/AutoSuggestionsDropdown.tsx
Content changed by edit was not saved. Problem was that we passed the update fields wrapped with an extra object.
> fix: edited file content not saved

- libs/design-system/src/icons/gradient/TerminalGradient.tsx
> Nv 3375 readonly in prod env

- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
- fixed autocomplete visibility
> fix: suggestions dropdown visible

- apps/web/src/pages/templates/components/email-editor/AutoSuggestionsDropdown.tsx
- apps/web/src/pages/templates/components/email-editor/TextRowContent.tsx
- key events support for autosuggestions dropdown
https://github.com/novuhq/novu/assets/29251776/39631e89-10ad-43d4-9815-f4d8c524c0e2
> Nv 3372 add key updown support for auto suggestions navigations

- apps/api/src/app/content-templates/content-templates.controller.ts
- apps/worker/src/app/workflow/usecases/send-message/send-message.base.ts
- packages/application-generic/src/usecases/compile-template/compile-template.usecase.ts
Add date formatting to translations
> feat: add date formatting

- .github/actions/run-backend/action.yml
- .github/workflows/reusable-web-e2e.yml
- apps/web/cypress/tests/changes.spec.ts
- apps/web/cypress/tests/digest-playground.spec.ts
- apps/web/cypress/tests/notification-editor/create-notification.spec.ts
- apps/web/cypress/tests/notification-editor/main-functionality.spec.ts
- apps/web/cypress/tests/notification-editor/variants.spec.ts
- apps/web/src/pages/templates/components/CustomCodeEditor.tsx
- apps/web/src/pages/templates/editor/useDigestWorkflowTour.tsx
> Fix web pipline for translations

- .cspell.json
- .github/workflows/dev-deploy-web.yml
- .github/workflows/prod-deploy-web.yml
- .github/workflows/reusable-web-deploy.yml
- apps/web/public/index.html
> feat(web): hubspot embed for cloud

- apps/web/src/pages/integrations/components/IntegrationInput.tsx
1. Add SwitchLabel and SwitchDescription styled component in IntegrationInput.tss
To fix overflowing description text in switch input component
closes #4198
> feat: add switch description and label

- apps/api/src/app/widgets/dtos/remove-messages-bulk-request.dto.ts
- apps/api/src/app/widgets/e2e/remove-messages-bulk.e2e.ts
- apps/api/src/app/widgets/usecases/index.ts
- apps/api/src/app/widgets/usecases/remove-messages-bulk/remove-messages-bulk.command.ts
- apps/api/src/app/widgets/usecases/remove-messages-bulk/remove-messages-bulk.usecase.ts
- apps/api/src/app/widgets/widgets.controller.ts
> Feat(API): Add Remove Messages By Bulk

- packages/notification-center/src/hooks/useRemoveNotifications.ts
- packages/notification-center/src/store/notifications-provider.context.tsx
> feat(notification-center): add use remove notifications hook

- CONTRIBUTING.md
Update node version to v20.8.1
Fixes https://github.com/novuhq/docs/issues/389
> fix: change node version to 20.8.1

- apps/web/src/pages/templates/components/WorkflowSidebar.tsx
- libs/design-system/src/config/colors.ts
1. Added `black` color in `design-system` colors
2. fix sidebar title color based on theme
> fix: side bar title color based on theme

- apps/api/migrations/normalize-message-template-cta-action/normalize-message-cta-action-migration.ts
- apps/api/migrations/normalize-message-template-cta-action/normalize-message-template-cta-action-migration.spec.ts
- apps/api/migrations/normalize-message-template-cta-action/normalize-message-template-cta-action-migration.ts
> feat(api-migration): create cta action migration

- apps/api/src/app/testing/billing/create-setup-intent.e2e-ee.ts
* Update submodule ref to bring in Billing fixes
> chore: Update submodule

- apps/api/src/app/widgets/e2e/initialize-widget-session.e2e.ts
- apps/api/src/app/widgets/usecases/initialize-session/initialize-session.usecase.ts
> fix: api key migration widget initialize failure

- .github/workflows/prod-deploy-api.yml
- .github/workflows/prod-deploy-inbound-mail.yml
- .github/workflows/prod-deploy-worker.yml
- .github/workflows/prod-deploy-ws.yml
It's needed to fix a multiplatform build for PROD environment
> fix(ci): Setup qemu to fix a docker exporter

- .github/workflows/prod-deploy-ws.yml
> fix(ci): --load for WS service

- apps/web/cypress/tests/translations/translation-group.spec-ee.ts
- apps/web/src/components/workflow/preview/in-app/Content.styles.ts
- apps/web/src/components/workflow/preview/in-app/Content.tsx
- apps/web/src/components/workflow/preview/in-app/InAppPreview.tsx
- added avatar and cta buttons support in preview
> feat: implement cta and avatar

- libs/design-system/src/modal/Modal.tsx
- added centered props for Modal in design system
> Nv 3420 css inconsistencies with designs

- .github/actions/free-space/action.yml
This fix was an oversight on the original pr that included only a script instead of a full action.
> Convert script to github action

- apps/web/src/components/workflow/preview/ErrorPrettyRender.tsx
- apps/web/src/components/workflow/preview/chat/ChatPreview.tsx
- apps/web/src/components/workflow/preview/email/EmailPreview.tsx
- apps/web/src/components/workflow/preview/in-app/InAppPreview.tsx
- apps/web/src/components/workflow/preview/push/Content.tsx
- apps/web/src/components/workflow/preview/sms/SmsPreview.tsx
- apps/web/src/pages/templates/components/InputVariablesForm.tsx
- apps/web/src/pages/templates/components/TemplatePushEditor.tsx
- apps/web/src/pages/templates/components/formTypes.ts
- apps/web/src/pages/templates/components/notificationTemplateSchema.ts
- apps/web/src/pages/templates/components/templateToFormMappers.ts
- libs/dal/src/repositories/notification-template/notification-template.entity.ts
- libs/dal/src/repositories/notification-template/notification-template.schema.ts
- libs/shared/src/entities/notification-template/notification-template.interface.ts
> feat: error handling echo

- enterprise/packages/chimera-connect/package.json
- pnpm-lock.yaml
> feat: add echo error activity feed logs

- apps/web/src/pages/auth/components/HubspotSignupForm.tsx
> fix: update value of cxo founder

- apps/web/src/pages/activities/components/ActivityGraphGlobalStyles.tsx
> Nv 3593 bug tooltip issue on activities page graph

- libs/design-system/src/panda/colors.tokens.ts
- libs/design-system/src/panda/semanticColors.tokens.ts
- Adds a couple more semantic tokens 
- To make working with design-system easier (and more backwards compatible)
> feat: Tweak semantic color tokens

- apps/worker/src/app/workflow/services/active-jobs-metric.service.ts
- apps/worker/src/app/workflow/services/execution-log.worker.ts
- apps/worker/src/app/workflow/services/standard.worker.ts
- apps/worker/src/app/workflow/services/subscriber-process.worker.ts
- apps/worker/src/app/workflow/services/workflow.worker.ts
> feat(workers): add instrumentation for errors

- apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts
* Cherry pick Echo SMS delivery fix from https://github.com/novuhq/novu/pull/5368
See https://github.com/novuhq/novu/pull/5368
N/A
> fix(worker): Move missing SMS content check inside echo conditional

- apps/api/src/app/auth/auth.controller.ts
- apps/api/src/app/auth/e2e/password-reset.e2e.ts
- apps/api/src/app/auth/usecases/password-reset-request/password-reset-request.command.ts
- apps/api/src/app/auth/usecases/password-reset-request/password-reset-request.usecase.ts
- libs/shared/src/consts/password-helper/PasswordResetFlowEnum.ts
- libs/shared/src/consts/password-helper/index.ts
- Implement a URL Search Param while resetting password
- Implement function to get the Email verification redirect link based on the search param
- This will enable us to reuse logic across password flows and is the basis for front-end changes in #5325
> [Information Architecture] - API Changes for Reset Password

- providers/resend/src/lib/resend.provider.spec.ts
- providers/resend/src/lib/resend.provider.ts
Added missing replyTo field in resend provider
> feat: add reply to field in resend

- .commitlintrc.json
Disable body-max-line-length commitlint rule. It was too strict!
> chore(repo): Disable body-max-line-length

- .cspell.json
- apps/api/src/app/auth/usecases/password-reset-request/password-reset-request.usecase.ts
- apps/web/cypress/tests/settings/user-profile.spec.ts
- apps/web/src/hooks/index.ts
- apps/web/src/hooks/useCountdownTimer.ts
- apps/web/src/pages/settings/user-profile-page/UserProfileFlow.const.ts
- apps/web/src/pages/settings/user-profile-page/UserProfilePage.tsx
- apps/web/src/pages/settings/user-profile-page/UserProfilePasswordEmailVerificationSection.tsx
- apps/web/src/pages/settings/user-profile-page/UserProfilePasswordForm.tsx
- apps/web/src/pages/settings/user-profile-page/UserProfilePasswordSidebar.shared.ts
- apps/web/src/pages/settings/user-profile-page/UserProfilePasswordSidebar.tsx
- apps/web/src/pages/settings/user-profile-page/UserProfilePasswordSidebarEnum.ts
- apps/web/src/pages/settings/user-profile-page/UserProfileSidebarContext.tsx
- apps/web/src/pages/settings/user-profile-page/UserProfileSidebarControl.tsx
- apps/web/src/pages/settings/user-profile-page/selectUserProfileFlow.ts
- apps/web/src/pages/settings/user-profile-page/useUserProfileSearchParams.ts
- apps/web/src/pages/settings/user-profile-page/useUserProfileSetPassword.ts
- libs/design-system/src/sidebar/Sidebar.tsx
- Adds context to the User Profile page to make sharing state easier
- Adds sidebar management through URL params
- Provides a foundation for the "Update Password Flow'
- Closes [NV-3445](https://linear.app/novu/issue/NV-3445/%F0%9F%8F%9B%EF%B8%8F-settings-user-profile-set-a-password)
https://www.loom.com/share/b75e812bd60c4fb09dd8a93d64c7b381?sid=4bb24aff-8c88-46f4-8e57-c70a55e10ace
> [Information Architecture] User Profile | Set Password Flow

- apps/web/cypress/tests/settings/user-profile.spec.ts
- apps/web/src/pages/auth/components/PasswordRequirementPopover.tsx
- apps/web/src/pages/settings/user-profile-page/UserProfilePasswordSidebar.shared.ts
- apps/web/src/pages/settings/user-profile-page/UserProfilePasswordSidebar.tsx
- apps/web/src/pages/settings/user-profile-page/UserProfileUpdatePasswordForm.tsx
- Allow user to update their password when they already have one set
- Closes https://linear.app/novu/issue/NV-3446/🏛️-settings-user-profile-update-a-password
_Note_: outlines are showing re-renders but will not be included in actual code
https://www.loom.com/share/7e2a8be4a9824789a6ae49b588d902fd?sid=cf7d340c-8e56-4faf-9192-3cb895591b31
> [Information Architecture] User Profile | Update Password Flow

- apps/web/src/SettingsRoutes.tsx
- apps/web/src/components/nav/EnvironmentSelect/EnvironmentSelect.tsx
- apps/web/src/components/nav/EnvironmentSelect/useEnvironmentSelect.tsx
- apps/web/src/components/nav/OrganizationSelect/v2/OrganizationSelect.tsx
- apps/web/src/constants/assets.ts
- apps/web/src/pages/invites/v2/MembersInvitePage.tsx
- apps/web/src/pages/settings/AccessSecurityPage.tsx
- apps/web/src/pages/settings/TeamPage.tsx
- apps/web/src/pages/settings/index.ts
- apps/web/src/pages/settings/organization/OrganizationPage.tsx
- Finish remaining pages that didn't have specific designs
- Clean-up and behavior tweaks (like hiding icons during `Select`'s loading state
- Not related to a specific ticket, but necessary follow-up for Information Architecture
https://www.loom.com/share/5b17a40eb0f743ad99d1ce00affe8ea0?sid=65e4d445-b3ef-441d-978e-456101b21a46
> [Information Architecture] Follow-ups & Clean-up

- apps/web/cypress/tests/settings/api-keys.spec.ts
- apps/web/cypress/tests/settings/inbound-webhook.spec.ts
- apps/web/src/SettingsRoutes.tsx
- apps/web/src/components/IconButton.tsx
- apps/web/src/components/Timeline/Timeline.styles.ts
- apps/web/src/components/Timeline/Timeline.tsx
- apps/web/src/components/Timeline/index.ts
- apps/web/src/pages/settings/ApiKeysPage/ApiKeysPage.tsx
- apps/web/src/pages/settings/ApiKeysPage/useApiKeysPage.ts
- apps/web/src/pages/settings/SettingsPageContainer.tsx
- apps/web/src/pages/settings/WebhookPage/WebhookAdditionalInformationLink.tsx
- apps/web/src/pages/settings/WebhookPage/WebhookClaimStatusDisplay.tsx
- apps/web/src/pages/settings/WebhookPage/WebhookPage.shared.tsx
- apps/web/src/pages/settings/WebhookPage/WebhookPage.tsx
- apps/web/src/pages/settings/WebhookPage/WebhookPage.types.ts
- apps/web/src/pages/settings/WebhookPage/getWebhookClaimStatusFromEnvironment.ts
- apps/web/src/pages/settings/WebhookPage/index.ts
- apps/web/src/pages/settings/WebhookPage/useWebhookPage.ts
- apps/web/src/pages/settings/useSettingsEnvRedirect.ts
- libs/design-system/src/config/inputs.styles.ts
- libs/design-system/src/panda/NovuPandaPreset.ts
- libs/design-system/src/panda/semanticSizes.tokens.ts
- Implement the Inbound Webhook page
- Closes [NV-3458](https://linear.app/novu/issue/NV-3458/%F0%9F%8F%9B%EF%B8%8F-settings-inbound-webhook-page)
https://www.loom.com/share/3794aa9f67bd41c1ace6807d0d37560e?sid=a7723bf7-442a-4d44-af0b-51336ee652d3
> [Information Architecture] Webhook Page

- apps/web/cypress/global.d.ts
- apps/web/cypress/support/commands.ts
- apps/web/cypress/tests/settings.spec.ts
- apps/web/src/SettingsRoutes.tsx
- apps/web/src/pages/settings/BillingPage.tsx
- apps/web/src/pages/settings/index.ts
- Fix e2e test for feature flag disabled flow
- Fix styling of the Billing page w/ flag enabled
> [Information Architecture] - Fix tests & billing page

- apps/api/src/app/layouts/e2e/delete-layout.e2e.ts
> fix(e2e): build

- libs/design-system/src/sidebar/Sidebar.styles.ts
- libs/design-system/src/sidebar/Sidebar.tsx
- libs/design-system/src/sidebar/SidebarFormless.tsx
> fix(web): sidebar overflow issue

- apps/webhook/package.json
deploy not passing due to trying to run testing when they are non
<details>
</details>
> remove testing from webhook

- CONTRIBUTING.md
> feat: change

- CONTRIBUTING.md
> feat: test NV-3726

- README.md
> fix: test NV-3727

- apps/api/src/app/organization/dtos/update-branding-details.dto.ts
- apps/api/src/app/user/dtos/update-profile-request.dto.ts
- Removed the hostlist because it was erroring out in the dev env. As the URL is from AWS S3, GCP bucket etc and not localhost or web.novu.co
<details>
</details>
> fix: remove hostlist
