docs/docs/overview/introduction.md
Notifire is and Open-source library > Notifire is an Open-source library
- **What kind of change does this PR introduce?** Fix typo
- **What is the current behavior?** In the doc, the first sentence is `Notifire is and Open-source library for managing multi-channel transactional notifications with a single API.` 
- **What is the new behavior (if this is a feature change)?** Fixed the typo : `Notifire is an Open-source`
=> typo: Notifire is and Open-source library

packages/core/src/lib/template/template.interface.ts, packages/core/src/lib/trigger/trigger.engine.spec.ts, packages/core/src/lib/trigger/trigger.engine.ts
Small method to use validator inside of trigger engine.
No validator can be provided.
https://github.com/notifirehq/notifire/issues/4
If a validator return false an error is thrown. A validator is optional to provide on a IMessage.
=> Allow validator on IMessage level

packages/core/src/lib/content/content.engine.ts, packages/core/src/lib/handler/direct.handler.spec.ts, packages/core/src/lib/handler/direct.handler.ts, packages/core/src/lib/handler/email.handler.ts, packages/core/src/lib/handler/sms.handler.ts, packages/core/src/lib/notifire.spec.ts, packages/core/src/lib/notifire.ts, packages/core/src/lib/provider/provider.interface.ts, packages/core/src/lib/provider/provider.store.ts, packages/core/src/lib/template/template.interface.ts, packages/core/src/lib/trigger/trigger.engine.ts
Adds the ability to create direct providers that allow sending a message to a specific `$channel_id`. In a later point, we can add support for private messages and thread replies.
Closes #108
=> Create direct message interface

apps/widget/public/iframeResizer.contentWindow.js, docs/docs/templates/messages.md
There are small typos in:
- apps/widget/public/iframeResizer.contentWindow.js
- docs/docs/templates/messages.md
Fixes:
- Should read `whether` rather than `wether`.
- Should read `notification` rather than `notificaton`.
- Should read `compatibility` rather than `compatibity`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

_templates/provider/new/.eslintrc.json.ejs.t, _templates/provider/new/README.ejs.t, _templates/provider/new/prompt.js, _templates/provider/new/src/lib/provider.ejs.t, _templates/provider/new/src/lib/test.provider.spec.ejs.t
Add support for optional types in Hygen script generator (SMS/EMAIL)
Hygen script support is now only available in the email generator
Add a new SMS provider generator for Hygen script
There was no open issue
=> feat: add support for optional types in Hygen provider script generator (SMS/EMAIL)

providers/ses/.eslintrc.json, providers/ses/package.json, providers/ses/src/lib/ses.provider.spec.ts, providers/ses/src/lib/ses.provider.ts, yarn.lock
Feature request: #98 
SES provider now supports attachments.
The feature hasn't been tested yet, we need to validate the transporter through nodemailer
=> Added SES attachments support

README.md, providers/nexmo/.eslintrc.js, providers/nexmo/.gitignore, providers/nexmo/README.md, providers/nexmo/jest.config.js, providers/nexmo/package.json, providers/nexmo/src/index.ts, providers/nexmo/src/lib/nexmo.provider.spec.ts, providers/nexmo/src/lib/nexmo.provider.ts, providers/nexmo/tsconfig.json, providers/nexmo/tsconfig.module.json
Supports Vonage/Nexmo SMS
implements https://github.com/notifirehq/notifire/issues/26
=> feat(nexmo.js): add support for Nexmo/Vonage SMS

README.md
docs
The `emailjs` was missing from `readme.md`
`readme.md` now is showing `emailjs` as a provider and the link to it
=> Add `emailjs` to list of providers in `readme.md`

apps/api/src/config/index.ts
It's much better to use a one-liner code to avoid string duplication.
Instead of declaring an empty `path` variable
And using the switch case to determine its value.
=> refactor(api): config path definition

providers/emailjs/src/lib/emailjs.provider.ts
Bug fix
`providers/emailjs/src/lib/emailjs.provider.ts` is returning `undefined` if `attachments` is not present, when it should be returning empty array
Returns new empty array in case attachment is not defined
=> Handle undefined attachments

README.md, docs/docs/recipes/using-translations.md, docs/docs/templates/messages.md, packages/core/src/lib/handler/email.handler.spec.ts, packages/core/src/lib/handler/email.handler.ts, packages/core/src/lib/template/template.interface.ts, packages/core/src/lib/trigger/trigger.engine.ts
This PR introduces the option of passing a `function` to `subject` property when invoking the `trigger method`
The `subject` property only accepts strings.  [Issue here](https://github.com/notifirehq/notifire/issues/152)
The `subject` now accepts `functions` as well as `string`
=> `subject` now accepts a `Function` on `trigger` method

libs/shared/src/consts/providers/index.ts, packages/cli/package.json, packages/cli/src/client/cli.client.ts, packages/cli/src/commands/init.consts.ts, packages/cli/src/constants/constants.ts, packages/cli/src/constants/index.ts, packages/cli/src/server/http-server.ts, packages/cli/src/server/index.ts, pnpm-lock.yaml
For the API usage after the authentication, the API can replay to the CLI with the GitHub OAth payload.
The CLI will raise a native HTTP server because it is the 
http-server was chosen because is is light wight and we do not need any complex functionality/features.
[https://javascript.plainenglish.io/fastify-express-benchmark-4c4aebb726d6](https://javascript.plainenglish.io/fastify-express-benchmark-4c4aebb726d6)
=> [RLD-105] - Create a local server on ephemeral port

packages/cli/package.json, packages/cli/src/commands/init.ts, pnpm-lock.yaml
Easily load and persist config without having to think about where and how.
Saving the token on disk on the machine.
Config store for saving API key and credentials locally: [https://www.npmjs.com/package/configstore](https://www.npmjs.com/package/configstore)
=> [RLD-108] - Persist JWT token in the users CLI storage

apps/api/package.json, apps/api/src/app/widgets/e2e/initialize-widget-session.e2e.ts, apps/api/src/app/widgets/usecases/initialize-session/initialize-session.usecase.ts, pnpm-lock.yaml
Added new e2e test on line 33 in apps/api/src/app/widgets/e2e/intialize-widget-session.e2s.ts and a new ApiException on line 32 of apps/api/src/app/widgets/usecases/initialize-session/intialize-session.usecase.ts.
Right now one e2e test is failing. Dima suggested I draft a PR so we can try and see what's causing that to happen. It is supposed to fix the error described in the title.
https://github.com/notifirehq/notifire/issues/365
Right now the new test I wrote is failing, but I'm not sure why.
No just trying to stop the error from happening and almost there but …
=> Fix TypeError: Cannot read properties of null (reading '_id') issue #365 Draft PR

apps/web/src/design-system/table/Table.tsx
It will not render pagination if there is no total count or page size is less than one.
This fix is related to issue #417 
There will be no pagination for page size less than or equal to one or total count is zero.
=> Display pagination when there is total or page size is greater than one

apps/web/src/hooks/use-novu.ts, apps/widget/src/api/shared.ts
An issue caused by trying to access `window.parent` from within the widget caused the following error.
```
Uncaught DOMException: Blocked a frame with origin "https://widget.novu.co" from accessing a cross-origin frame.
at Module.<anonymous> (https://dev.widget.novu.co/static/js/main.c14ed694.chunk.js:1:22623)
at i (https://dev.widget.novu.co/xBbPgsaY6mdU:1:1224)
at r (https://dev.widget.novu.co/xBbPgsaY6mdU:1:1093)
at Array.t [as push] (https://dev.widget.novu.co/xBbPgsaY6mdU:1:956)
at https://dev.widget.novu.co/static/js/main.c14ed694.chunk.js:1:73
```
=> 🐛  Fix Cors issue when accessing window.parent inside widget

apps/web/src/components/templates/TriggerSnippetTabs.tsx, packages/cli/src/constants/dashboard/index.html
- Content-Type should be `application/json`. This updates the trigger sample code to use `application/json` instead of `environment/json`
- `environment/json` is not valid and results in the request failing if a user uses the example code
- Correct example code is displayed and will work without modification for a user
- N/A
=> Use content-type: application/json for payload in example script

apps/api/src/app/events/services/sms-service/handlers/sms77.handler.ts
- Bug fix of misspell in sms77 constructor call 
- sms77 provider is not usable as reported in [Issue 582](https://github.com/novuhq/novu/issues/582)
- Hopefully sms77 provider working for SMS integration
- Was not tested on my machine, but "sns" for sm77 provider was clearly wrong
=> Changed sms77 constructor call

README.md
- **Docs Update**
Corrected spelling in README.md:  <UUNIQUE_IDENTIFIER> to <UNIQUE_IDENTIFIER>
=> Improved documentation: Corrected spelling in README.md

apps/api/package.json, apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts, apps/api/src/bootstrap.ts, pnpm-lock.yaml
fix #587
- **What kind of change does this PR introduce?** Bug fix
- **What is the current behavior?** The attachments passed to trigger payload wasn't handled properly in the backend (Novu API).
- **What is the new behavior (if this is a feature change)?** Now, the attachments are properly transformed to `Buffer` from the attachments payload and then succesfully passed to the `IEmailOptions`.
- **Other information**: The API testing has been done with attachments passed to the trigger function.
=> fix: added support for attachments passing within Novu API

apps/web/src/components/widget/NotificationCenterWidget.tsx, packages/notification-center/src/components/popover-notification-center/PopoverNotificationCenter.tsx
feature/update (i am not sure)
- **What is the current behavior?** 
If the user of the NotificationCenter does not provide a handler for URL change, the redirection will not work on notification click.
- **What is the new behavior ?**
In order to help NotificationCenter users, we added the onUrlChange as mandatory so the user will be aware of the need to provide the URL change handler.
- **Other Information**:
I could not locate the issue that related to this PR, if anyone is aware of it please feel free to add it here :)
=> :hammer: Update onNotificationClick as mandatory

CONTRIBUTING.md
- An outline of the different ports used by the services the projects spins up:
3000 - API
3002 - WebSocket service
4200 - Web Management UI
4500 - Iframe embed for notification center
=> Made changes in the CONTIBUTING.md file for ports information

packages/notification-center/src/components/notification-center/NotificationCenter.tsx, packages/notification-center/src/components/notification-center/components/layout/Layout.tsx, packages/notification-center/src/hooks/index.ts, packages/notification-center/src/hooks/use-api.hook.ts, packages/notification-center/src/hooks/use-check-provider.hook.ts, packages/notification-center/src/hooks/use-novu-context.hook.ts, packages/notification-center/src/store/novu-provider.context.ts, packages/notification-center/src/store/socket/use-socket-controller.ts
Fixes #629 
Currently, when using hooks or components from the `notification-center` without wrapping it with the `NovuProvider` throws unclear error message.
It will throw a proper error message suggesting the fix.
Error Message: **`Component must be wrapped within the NovuProvider`**
=> Proper Error Message when used without NovuProvider

environment/local/docker-compose.yml
Added docker-compose.yml for local development, so people wont have to install redis and mongodb locally.
People install mongodb and redis locally.
They can just launch the docker-compose.yml without installing any software manually.
=> Docker-compose for local development

apps/web/src/components/workflow/FlowEditor.tsx
Click on Trigger Node to not set form as dirty -> Update button not enabled
=> fix: not set as dirty when clicking on trigger

docs/vercel.json
This PR fixes the redirects bug.
The pages with the prefix `/docs` are not redirected to `/`
The redirects work correctly. Redirect https://example.com/docs/some-doc to https://example.com/some-doc
=> fix: change redirect match to slug

docs/docs/notification-center/react-components.md, docs/docs/overview/quick-start.md
> **Docs Update**
---
- **What is the current behavior?** 
> **There is a typo at `line 55` of `quick-start.md` file and `line 75 as well as 114` of `react-components.md` file**
=> Fix a typo in quick-start.md & react-components.md file

apps/api/src/app/subscribers/e2e/get-subscribers.e2e.ts, apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/subscribers/usecases/get-subscribers/get-subscriber.command.ts, apps/api/src/app/subscribers/usecases/get-subscribers/get-subscriber.usecase.ts, apps/api/src/app/subscribers/usecases/get-subscribers/index.ts, apps/api/src/app/subscribers/usecases/index.ts, packages/node/src/lib/subscribers/subscribers.ts
It adds a endpoint to get all subscribers
The endpoint does not exists.
I think this could be a nice way to be able to debug subscribers but also to be able to list all subscribers inside of Novu in calling application.
=> feat: add endpoint to get all subscribers

apps/web/src/components/templates/DeleteStepModal.tsx
Bug fix https://github.com/novuhq/novu/issues/784
https://github.com/novuhq/novu/issues/784
When the confirmation dialog opens, the "YES" button will be automatically focused.
=> NV-626: fix: Move focus to "YES" in the delete workflow step confirmation modal

docs/docs/platform/integrations.md
Hey guys, really cool project!
I was reading the docs and came across a missing link on the [Integrations Store](https://docs.novu.co/platform/integrations) page. I think the "here" should point to the guide on how to create a custom provider.
PR adds just a tiny fix 👍
=> fix (docs): missing link to guide on how to create a provider

apps/web/src/design-system/template-button/ChannelButton.tsx, apps/web/src/design-system/template-button/TemplateButton.styles.ts
**What kind of change does this PR introduce?**
- Fixes menu not closing on click outside in the flow editor
- Also took the liberty to fix a "flickering" bug which can be noticed whenever you click a channel button. Moving from no border to `border: 1px solid transparent` causes this effect. It's a bit subtle and not extremely important/noticeable so let me know if you don't want it as part of this PR 😅 
**What is the current behavior?**
- The `<Menu />` component can not be closed unless we click on the parent anchor tag [here](https://github.com/novuhq/novu/blob/main/apps/web/src/design-system/template-button/ChannelButton.tsx#L152). #761 
- Moved the `border: 1px solid transparent` css style to be applied to the `button` as opposed to **only** when it is active
**What is the new …
=> fix(apps/web): close menu on click outside in flow editor

docs/vercel.json
It changes the rewrite to redirect on docs.
Docs flash the right page for a little time. If I'm correct, then client side rendering kicks in, tries to get the URL, and because it is proxied (rewritten), clientside rendering cannot find the page and results in a 404.
Redirecting user instead of proxying.
=> Fix docs broken /docs/ redirect

apps/web/cypress/tests/notifications-editor.spec.ts, apps/web/src/components/templates/NotificationSettingsForm.tsx, apps/web/src/components/templates/TemplateSettings.tsx, apps/web/src/design-system/config/inputs.styles.ts, apps/web/src/pages/templates/TemplatesListPage.tsx
Adds the trigger ID to the list and to the settings page for easier copying and for less confusion
(ref #602 )
List and settings page don't include the ID, the ID can be only seen through the trigger snippet page.
Adds the ID to the settings page + list
=> feat: add trigger id to list and settings page

apps/web/src/api/api.client.ts, apps/web/src/api/templates.ts, apps/web/src/components/templates/DeleteConfirmModal.tsx, apps/web/src/components/templates/NotificationSettingsForm.tsx, apps/web/src/components/templates/TemplateSettings.tsx, apps/web/src/components/templates/use-template-controller.hook.ts, apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
**NOTE! Depends on #808 **
Adds a button to remove the notification template
There isn't a button
There now is a button that opens a modal and then deletes the template
=> Add remove notification

apps/web/cypress/tests/auth.spec.ts, apps/web/src/components/auth/CreateOrganizationForm.tsx, apps/web/src/pages/auth/LoginPage.tsx, packages/cli/src/commands/init.ts
Bug fix (I think)
Users are always redirected to the ***Notifications*** page upon signup/login.
https://github.com/novuhq/novu/issues/799
Users will be redirected to the ***Getting Started*** page on their first session, and the ***Notifications*** page for any subsequent sessions.
Using local storage to track the session has the following issues.
- Logging in from a new device will always redirect to the ***Getting Started*** page.
- Logging out does not clear the *first session* flag, which means that creating a new account after logging out will always redirect to the ***Notifications*** page (not sure if this should be changed).
=> NV-631 - fix(web): Redirect to getting started on first session

apps/web/src/components/templates/TemplateSettings.tsx
Bug fix
#846
The **Delete Template** button will disabled on production
=> fix: Disable the delete step button on production

packages/nest/src/interfaces/novu-options.interface.ts, packages/nest/src/module/novu.module.ts, packages/nest/src/providers/novu.providers.ts
- Adds `forRootAsync` method to nestjs module to provide config values dynamically
- closes #318 
=> feat: added nest module async provider option

apps/api/Dockerfile, apps/web/Dockerfile
- Bug fix
Build error with docker:
Build succeeds.
It doesn't have to be the image I used in this PR. Just wanna show it's caused by the wrong docker image.
=> Use a docker image with both nodejs and python

apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts, libs/dal/src/repositories/message/message.entity.ts, libs/dal/src/repositories/message/message.schema.ts
Fixes #901 to use the handlebars compiler instead of the contentReplace service currently used.
=> fix: add subject rendering variables with handlebars

apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx, libs/shared/src/consts/providers/provider-credentials.ts, libs/shared/src/consts/providers/provider.interface.ts
Feature + Bug fix
#754
You can't leave out fields when adding integrations through the form.
Add the ability to make some fields optional for specific providers.
This PR makes the username, password & secure fields for the nodemailer provider optional.
=> feat: Implement optional credential fields

apps/api/src/app/auth/usecases/password-reset-request/password-reset-request.usecase.ts, apps/api/src/app/invites/usecases/accept-invite/accept-invite.usecase.ts, apps/api/src/app/invites/usecases/invite-member/invite-member.usecase.ts
Fixes #625 
For now all template IDs are lower case and you can't create notification template with trigger like 'invite-to-organization-wBnO8NpDn'
=> Template IDs for invites and password reset can be configured by environment

packages/notification-center/src/i18n/lang.ts, packages/notification-center/src/i18n/languages/ru.ts
I'm russian native speaker and it's hard to translate "Powered by". The best translation is ["При поддержке"](https://4brain.ru/blog/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4-powered-by/).
Fixes https://github.com/novuhq/novu/issues/940
=> i18n - Russian support

pnpm-lock.yaml, providers/gupshup/babel.config.js, providers/gupshup/jest.config.js, providers/gupshup/package.json, providers/sms77/babel.config.js, providers/sms77/jest.config.js, providers/sms77/package.json, providers/termii/babel.config.js, providers/termii/jest.config.js, providers/termii/package.json
fix
Vulnerability reported by Snyk: https://security.snyk.io/vuln/SNYK-JS-NODEFETCH-2964180
Resolve by upgrade node-fetch to the recommended version 3.2.10
=> fix: upgrade node-fetch

README.md
Small change on the readme when you click the invite to the discord server it shows the invite is invalid
it says the invite is invalid
It will allow people to join the discord server
=> changed invite link to a working one

libs/testing/src/environment.service.ts, libs/testing/src/notification-template.service.ts
Faker.js has deprecated `faker.name.title` in favor of the `jobTitle`.
Update all the place that used `faker.name.title` to the new method.
=> [NV-767] - Switch deprecated faker.name.title function to jobTitle

package.json
fixes https://github.com/novuhq/novu/issues/1003
lint-staged is not running on the docs and libs folder of the project
the docs and libs folder are now also being checked for staged files to lint
for the docs it checks ts / tsx and json
for the libs it checks ts / js and json
Running lint-staged is already a part of the husky precommit stage as it seems.
=> fix: added docs and libs folders to lint-staged

.eslintrc.js, package.json
This fixes the additional eslint step added to lint-staged. I verified it by modifiy different files inside docs/, libs/, etc...
linking to https://github.com/novuhq/novu/pull/1010
cc @scopsy - Can you check if the error still persists?
=> fix: Fix lint staged for multiple folders and added eslint step

packages/notification-center/src/components/notification-center/components/notification-item/NotificationListItem.tsx, packages/notification-center/src/store/i18n.context.tsx
fixes https://github.com/novuhq/novu/issues/1018
Afaik, moment's ```locale()``` method can no longer be used in chains. It now changes the global moment instance. See https://stackoverflow.com/a/17493350 - Also it requires an import of ```moment/min/locales.min``` for the locales to work.
Because of that the language of the timestamp did not change. I fixed this.
Also I was unable to replicate the issue of the "Notifications" header not changing the text that was pointed out in the linked issue.
=> fix: notification center moment locale change

docs/docs/notification-center/react-components.md, packages/notification-center/src/i18n/lang.ts, packages/notification-center/src/i18n/languages/de.ts, packages/notification-center/src/i18n/languages/es.ts
- Adds a list of supported locales for the react notification center component
- Added german locale to the notifiction center
- Modified docs text for ````date-fns`` and link to supported locales
=> feat: show supported locales for notification-center in docs

apps/web/src/components/templates/email-editor/ButtonRowContent.tsx
fixes https://github.com/novuhq/novu/issues/1058
Shows a success notification when the user either presses the enter key on the email button dropdown or when the user clicks outside (other way of closing)
=> feat: show save notification on email template button

apps/api/src/app/content-templates/usecases/compile-template/compile-template.spec.ts, apps/api/src/app/content-templates/usecases/compile-template/templates/basic.handlebars, apps/api/src/app/widgets/dtos/message-response.dto.ts, apps/web/src/components/templates/email-editor/ButtonRowContent.tsx, apps/web/src/components/templates/email-editor/ContentRow.tsx, apps/web/src/components/templates/email-editor/EmailMessageEditor.tsx, apps/web/src/components/templates/email-editor/TextRowContent.tsx, libs/dal/src/repositories/message-template/message-template.entity.ts, libs/shared/src/consts/providers/provider-credentials.ts, libs/shared/src/entities/message-template/message-template.interface.ts
fixes https://github.com/novuhq/novu/issues/1057
Also I changed the DKIM settings for the nodemailer provider to not be required - I stumpled upon this when trying to setup nodemailer for testing and it is not something that is required. It's also optional in the interface in the nodemailer integration package.
see https://github.com/novuhq/novu/issues/1057
The text direction seems to have never been actually used in the email template itself. So it seems the text direction change was only on the frontend anyways.
=> feat: change email template text direction to text align

docs/docs/community/code-conduct.md
This PR updates the Code_Of_Conduct present on Novu Docs site to v2.0.
This issue fixes https://github.com/novuhq/novu/issues/1076
=> Updated code_of_conduct as per Github Template v2.0

apps/web/src/design-system/select/Select.tsx
fixes https://github.com/novuhq/novu/issues/936
This improves the loading overlay for the select component to match the figma design doc https://www.figma.com/file/9jalQvImfHtbbExZPLW3XO/Concepting?node-id=2834%3A39667
=> feat: better loading overlay for select

apps/web/src/components/layout/components/HeaderNav.tsx
This changes the behaviour of the navbar user menu to use the react-router Link component instead of a simple a tag. Currently it reloads the whole page when trying to navigate to a link in the menu. This is now fixed.
=> fix: use react router link for navbar menu instead of a tag

apps/api/src/app/auth/e2e/login.e2e.ts, apps/api/src/app/auth/e2e/password-reset.e2e.ts, apps/api/src/app/auth/usecases/password-reset-request/password-reset-request.usecase.ts
This adds the missing normalize email method to the password reset function. I also added tests in both login / reset password e2e to test for this.
=> fix: also normalize email on password reset

apps/web/src/components/templates/email-editor/ContentRow.tsx, apps/web/src/components/templates/email-editor/ControlBar.tsx, apps/web/src/components/templates/email-editor/EmailMessageEditor.tsx, apps/web/src/components/templates/email-editor/TextRowContent.tsx, apps/web/src/components/workflow/FlowEditor.tsx, apps/web/src/components/workflow/node-types/AddNode.tsx, apps/web/src/design-system/button/Button.tsx, apps/web/src/design-system/dropdown/Dropdown.tsx
This cleans up some visual bugs in the email workflow
- Improved colors for better visibility (light / dark)
- Remove overlap on settings button with button row
- Better centering for settings button
- Better menu for the align setting
- Fixed a bug where selecting the text row caused the cursor to be at right side
- Dropdown toggle now stays visible while the menu itself is open
- **Before**
- **After**
=> fix: cleanup email workflow visuals

apps/web/src/pages/settings/tabs/components/Security.tsx
fix: remove max width style and add space before link
=> fix: remove maxwidth in hmac desc

docs/netlify.toml
Docs update: This pull request adds configure `redirect and rewrite` rules for `Netlify`.
at the moment we have a configuration file for redirects only for `Vercel`, which does not allow to place on `Netlify`
allows you to keep the links working correctly when transferring the documentation to `Netlify`
I didn't delete the configuration file for Vercel (`vercel.json`) with redirects so that you could migrate to Netlify painlessly and not encounter possible problems with links between migrations, so please delete it after the migration is …
=> feat: configure redirect and rewrite rules for Netlify

.github/workflows/prod-deploy-api.yml
This pull request the step to deploy API documentation.
N/A
when running the `Deploy PROD API` action adds a final step that starts building the project with the API documentation
you need to add a secret named `API_DOCS_BUILD_WEBHOOK` for this repository with the desired value
=> feat: add a step to deploy API documentation

docs/netlify.toml
This pull request adds fixes slug for redirects on API pages.
Status: `200`
N/A
=> fix: slug for redirects on API pages

docs/netlify.toml
This pull request adds fixes for redirects for API documentation.
When you go to a page from the documentation search, we get to a page that does not exist
N/A
=> fix: redirects for API documentation

docs/docs/channels/push/fcm.md
fix: add set credentials info in push
adding device token info is missing in push docs
added
https://discord.com/channels/895029566685462578/1014486587918274663/1014582004215447634
=> fix: add set credentials info in push

docs/docs/overview/docker-deploy.md
- Minor addition made to the docker-deploy docs
- Currently, there is very little documentation with regards to configuring the event triggers for use with a custom installation
- I added a simple example, written in Node.js, for how to configure the Novu object's backendUrl parameter when self-hosting Novu.
=> Added documentation for triggering events when self-hosting

packages/notification-center/src/components/notification-center/NotificationCenter.tsx, packages/notification-center/src/components/notification-center/components/FeedsTabs.tsx, packages/notification-center/src/components/popover-notification-center/PopoverNotificationCenter.tsx, packages/notification-center/src/index.ts, packages/notification-center/src/store/notification-center.context.ts
So developer can track what tab subscriber is viewing to customize headers and items
This does not exists today
The developer can provide a function to get what tab subscriber have clicked on
=> feat: add on tab click property to notification center

README.md
Linked License, Contribution Guidelines, and Contributors List in README.md. (#1160)
-> In this PR, I have changed README.md which would be counted under docs update.
-> Currently, the License, Contribution Guidelines, and Contributors List are not embedded in README.md (#1160)
=> Linked License, Contribution Guidelines and Contributors List in README.md

docs/docusaurus.config.js
Docs update: This pull request adds the `externalUrlRegex` param for Algolia.
When you go to a page from the documentation search, we get to a page that does not exist
This option allows for `window.location` instead of `history.push`. Which solves the problem with links for API documentation. You can find more about this [here](https://docusaurus.io/docs/search#connecting-algolia)
N/A
=> feat: add the externalUrlRegex param for Algolia

apps/web/src/components/templates/TemplatePageHeader.tsx, apps/web/src/components/workflow/FlowEditor.tsx, apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
Fixes the height of the flow editor to be auto but at least 500px instead of currently hard 500px
=> fix: flow editor height

apps/web/src/components/widget/NotificationCenterWidget.tsx, docs/docs/notification-center/react-components.md, packages/notification-center/src/components/popover-notification-center/PopoverNotificationCenter.tsx, packages/notification-center/src/components/popover-notification-center/components/Popover.tsx
Added `position` & `offset` props for the `notification-center`
Fixes #1174 
Currently, there's no option to modify the position of the popover
Allows custom positions to update the popover positions
- `position='left-start'`: <img width="1155" alt="image" src="https://user-images.githubusercontent.com/29251776/188361614-159d9cb9-0b9c-49e4-a1af-713ae2f49c5d.png">
- `position='right-start`: ![image](https://user-images.githubusercontent.com/29251776/188362043-be6f0741-46f5-4c97-b17e-a9c0ce98b328.png)
=> Feat position notification center

apps/api/src/app/subscribers/subscribers.controller.ts
Transform the page to `string` to avoid NaN conversion 
If page is not passed it converts to NaN and fails validation
=> fix: workaround with validation pipe nan casting

apps/widget/src/components/notification-center/NotificationCenterWidget.tsx, libs/embed/src/embed.ts, libs/embed/src/shared/eventTypes.js
**Bug fix:** ticket: #1090 
Currently on Safari, it's not possible to open the Embedded Notification Center Widget.
The issue can be seen on the below screenshots.
Chrome:
Safari:
As you can see on Safari `Embed` sends the `INIT_IFRAME` message before the `Widget` gets the opportunity to register the event listener.
This fix solves the issue described above.
The `Embed <--> Widget` communication is reversed and works based on the `postMessage` API.
---
1. When the `Embed` code is running in the browser it creates the `iframe` DOM element for the `Widget`.
2. Right after it registers the `message` event listener on that `iframe` to receive …
=> fix: embed <--> widget communication issue on safari

docs/docs/notification-center/react-components.md
remove unnecesary ; at last line after notification image
docs update
just a visual correction 
ty
=> remove last ;

apps/api/src/app/activity/activity.module.ts, apps/api/src/app/change/change.module.ts, apps/api/src/app/environments/environments.module.ts, apps/api/src/app/feeds/feeds.module.ts, apps/api/src/app/integrations/integrations.module.ts, apps/api/src/app/notification-groups/notification-groups.module.ts
Fix curl request to notification-groups receiving 500, internal server error 
Issues : [1234](https://github.com/novuhq/novu/issues/1234) and [1259](https://github.com/novuhq/novu/issues/1259)
Seems that the problem is a missing import of AuthModule in notification-groups
Edit : Found several other places with the same issue. 
This PR will fix several API endpoints, not only notification-groups
=> fix: curl req for notification-groups gets error 500

libs/embed/package.json, scripts/pnpm-context.mjs
- **What kind of change does this PR introduce?** (Bug fix)
At the current state, the environment variables are embeded in the static page on rollup build (@rollup/plugin-replace), in this PR we added a build step so that rollup rebuild the environment variables.
While using the docker-compose environment the user will want to use the prebuilt images and update the environment variable in runtime (docker-compose up). 
Closes #1249 
Closes NV-895
=> Fix embed runtime env variables

apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
Fix so default value are used as default and not overriding provided values
So defaults are defaults and not overrides
Text from Lodash docs about merge function:
"This method is like [_.assign](https://lodash.com/docs/4.17.15#assign) except that it recursively merges own and inherited enumerable string keyed properties of source objects into the destination object. Source properties that resolve to undefined are skipped if a destination value exists. Array and plain object properties are merged recursively. Other objects and value types are overridden by assignment. Source objects are applied from left …
=> fix: so default payload are overrided by the provided payload

apps/web/src/design-system/template-button/ChannelButton.tsx
- Change of background color of Step card on hovering anywhere on card
- And fixed z-index of error tooltip in workflow editor
https://github.com/novuhq/novu/issues/1263
Background color of step card was changing only on 3 dots hover.
And error tooltip was coming over the Delete Step confirmation modal, resulting in covering the CTAs
=> style: bg-color of step card and zindex of error tooltip

.markdownlint.jsonc, docs/docs/channels/email/_category_.json, docs/docs/channels/email/index.mdx, docs/docs/channels/email/sendgrid.md, docs/docs/channels/push/_category_.json
Adds SendGrid documentation on how to get an API Key and authenticate sender
As part of our work on the documentation and in preparation for hacktoberfest
=> Add SendGrid provider doc

apps/web/src/components/layout/components/HeaderNav.tsx, apps/web/src/design-system/table/Table.tsx, apps/web/src/pages/subscribers/SubscribersListPage.tsx
- This fixes unneeded styles and cursor: pointer on subscribers table hover when there is no click action.
- Removes the tooltips because they only show the same information again
- Also hide the pagination of the table when there is only one page.
- Also fixes a warning from react for missing key in HeaderNav list rendering.
=> fix: smaller fixes for subscriber table

apps/api/src/app/messages/messages.controller.ts, apps/api/src/app/messages/usecases/get-messages/get-messages.command.ts, apps/api/src/app/messages/usecases/get-messages/get-messages.usecase.ts
Make limit a query param
So larger amount of messages can be fetched with one request
=> feat: add so limit can be provided to endpoint

apps/api/src/app/environments/usecases/create-environment/create-environment.usecase.ts, apps/api/src/app/environments/usecases/generate-unique-api-key/generate-unique-api-key.spec.ts, apps/api/src/app/environments/usecases/generate-unique-api-key/generate-unique-api-key.usecase.ts, apps/api/src/app/environments/usecases/index.ts
We should create UUID with hat and then validate it against the database to avoid collisions. 
Right now we are using hat to randomly generate API Keys, there is a chance of collision when generated.
N/A
=> feat(api): Inforce API key generation is unique

apps/api/src/app/events/usecases/send-message/send-message-chat.usecase.ts, apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts, apps/api/src/app/events/usecases/send-message/send-message-push.usecase.ts, apps/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts, apps/api/src/app/events/usecases/send-message/send-message-type.usecase.ts
- **What kind of change does this PR introduce?** (feature)
This PR comes to solve an edge case where there is log prints of [object Object]
- **Why this change was needed?**
In order to have more information of the reason why the provider threw exceptions.
Before 
After
=> fix: missing error message due object object print

README.md
The "Contribution Guidelines" link pointed to a CONTRIBUTING.md file in a forked repository. After the change, it points to the CONTRIBUTING.md file of novuhq/novu.
Issue Reference: https://github.com/novuhq/novu/issues/1313
=> Changed the Contribution Guidelines link

docs/docs/community/run-locally.md
Docs: Adds a GitPod link to the documentation
We have a .gitpod.yml file and a complete gitpod configuration for running Novu, then why do we not have it on the running locally page for people who want to get it running quick?
=> docs: add gitpod quick open

apps/web/src/components/invites/MembersTable.tsx, apps/web/src/pages/invites/MembersInvitePage.tsx
Added an option to copy the order link for the path for users that run the service on self-hosted docker mode
Due to this reason, the application sends emails invite, while hosting it on docker self-hosted the ability to send emails is missing.
Before
After
=> feat: add invite link

docs/docs/channels/email/sendgrid.md
Docs Update
Cause a little misconception on how the API Key should be added.
SendGrid by default adds 'SG.' to their API key. So mentioning that we add "SG." might develop a misconception of adding other prefixes for other Email providers.
=> Updated the API Key insertion step for SendGrid.

apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx
This PR includes a small change to the ConnectIntegrationForm to prevent the Close button from acting as submit button.
Prior to this change, closing one of the Integration forms using the close button in the top right corner of the modal will submit the form. This isn't as problematic in case of validation errors (although those still show for a split second prior to the modal closing) but fairly annoying when trying to close out of a form without field (like the Slack or Discord integration) which are enabled when just trying to close out the form.
\-
=> fix: close button acts as submit button

apps/api/src/app/events/usecases/send-message/send-message-sms.usecase.ts, packages/stateless/src/lib/provider/provider.interface.ts
Add so identifier are saved for sms messages.
To be able to use sms webhooks
=> fix: so message identifier is saved from send method

README.md
We have no use for it anymore as we updated the banner text.
=> Deleted the 'How to get our swag?' toggle

apps/api/src/app/activity/usecases/get-activity-feed/get-activity-feed.usecase.ts
So activity feed is filtered by subscriber as well
Because today it is not possible to filter on subscriber
=> fix: so subscriber is used to filter activity feed

scripts/jarvis.js
It fixes the Jarvis script to be able to run the Cypress CLI for the Web tests. Also tidies up the options to minimise mistakes.
It wasn't running due to string typoes.
N/A
=> fix(jarvis): fix script for running web tests in cypress cli

packages/notification-center/src/i18n/languages/es.ts
It's a fix for a Spanish translation. It seems that `poweredBy` label it was machine translated, and it was not natural in Spanish.
To have a more precise translation in Spanish.
=> i18n - Fix spanish translation

apps/api/src/app/events/services/mail-service/handlers/sendgrid.handler.ts, packages/application-generic/src/factories/mail/handlers/sendgrid.handler.ts, providers/sendgrid/src/lib/sendgrid.provider.spec.ts, providers/sendgrid/src/lib/sendgrid.provider.ts
Includes the sendgrid credentials.senderName in the provider so it's actually shown, right now it's ignored.
https://github.com/novuhq/novu/issues/1417
=> fix: take into account credentials.senderName in sendgrid provider

package.json, scripts/jarvis.js
- **What kind of change does this PR introduce?** (Feature)
Enables the option to run the API tests through the Jarvis running script.
Adding an option to launch Novu API tests in Jarvis cli will make it more comprehensive for new contributors and maintainers.
N/A
=> feat(jarvis): add options to run api tests

apps/web/src/components/templates/email-editor/EmailContentCard.tsx
As stated in issue #1396, variables added in the message are recognized but variables added in the subject are not. So to fix this I went through the code understanding what was happening and found out that we just needed to add a subject string to the contents prop in component VariableManager. I hope it works as I was unable to run the website on my system due to some problem after spending a lot of my time figuring it out.
#1396
subject variables to variable manager
issue #1396
=> feat: added subject variables to variable manager

packages/notification-center/src/i18n/languages/or.ts
Signed-off-by: Abhilipsa Sahoo <abhilipsasahoo03@gmail.com>
Bug Fix: fixes markAllAsRead field to its correct translation in Odia language. 
This change was needed to solve issue #1492
=> fix: fixes markAllAsRead field to its correct translation

apps/api/src/app.module.ts, apps/api/src/app/execution-details/dtos/execution-details-response.dto.ts, apps/api/src/app/execution-details/e2e/get-execution-details.e2e.ts, apps/api/src/app/execution-details/execution-details.controller.ts, apps/api/src/app/execution-details/execution-details.module.ts, apps/api/src/app/execution-details/usecases/get-execution-details/get-execution-details.command.ts, apps/api/src/app/execution-details/usecases/get-execution-details/get-execution-details.usecase.ts, apps/api/src/app/execution-details/usecases/index.ts, apps/api/src/app/shared/shared.module.ts, apps/api/src/bootstrap.ts
To be able to get execution details for each notification we need an endpoint to get it from the frontend. This PR will create that endpoint in a new module and controller.
=> feat: add endpoint for execution details

README.md
Added a `Table of Contents` on the [README](https://github.com/novuhq/novu#readme) page. Added the section between the [Features](https://github.com/novuhq/novu#-features) and [Getting Started](https://github.com/novuhq/novu#-getting-started) sections.
- It enables viewers to navigate through the page more efficiently. 
- Looking for a specific topic would take less time.
*NA*
=> update: added table of contents in readme

apps/web/src/components/utils/Spotlight.tsx
Introduces ability to navigate to settings in command palette
fixes #1461
What kind of change does this PR introduce?
Feature: Add new navigation to settings as described in [NV-935]
Why was this change needed? To fix #1461
=> Add navigation to Settings in command palette

docs/docs/platform/templates.md
Fixed templates.md by removing comma errors and minor grammatical errors
this change was needed because-:
- But was used as a starting sentence after full stop directly without a comma in the docs
- Previously Notification group meaning started with "Used..." but, in docs its is fixed to "The notification group....."
- Fixed the comma errors, in docs
=> Fixed templates.md by removing comma errors and minor grammatical errors

docs/docs/platform/integrations.md
Updated integrations.md sentences error
- made changes in the sentence "Novu is an open-source project, meaning that if you are missing a particular provider you can always submit a new provider entry." -> "Novu is an open-source project, which allows you to submit a new provider entry whenever you are missing a particular provider"
here the word **meaning** is not fitting the sentence
- "The name that will be displayed as the sender identity the email is coming from." ->"The name that will be displayed as the sender identity for the email"
=> Updated integrations.md sentences error

docs/docs/community/create-provider.md
docs update
The typo `a basic email provider` in the SMS provider section shoul be changed to `a basic sms provider`
=> Fixed typo `email` in the `How to add a provider ?` page

docs/docs/notification-center/react-components.md, packages/notification-center/src/i18n/lang.ts, packages/notification-center/src/i18n/languages/ro.ts
This PR introduces support for the Romanian language for the @novu/notification-center component interface.
For internationalization
Resolves #1525
=> i18n: added Romanian language support

providers/postmark/src/lib/postmark.provider.spec.ts, providers/postmark/src/lib/postmark.provider.ts
Implement `PostmarkProvider.checkIntegration` so that users can test their credentials when configuring a Postmark provider.
#1470
Postmark does not provide any dedicated endpoint/method to test credentials (https://postmarkapp.com/developer/api/overview). As such, I have resorted to using the same send functionality to test credentials. Another alternative is to use a `GET` endpoint (to avoid sending an actual email), but it will not validate the `From` email address.
=> feat: implement Postmark provider connection test

providers/mandrill/src/lib/mandrill.interface.ts, providers/mandrill/src/lib/mandrill.provider.spec.ts, providers/mandrill/src/lib/mandrill.provider.ts
- Fix Mandrill provider test (`mandrill.provider.spec.ts`): The test was mocking `MandrillProvider.sendMessage`, the function being tested itself, which defeats the purpose of the test. Fixed by mocking `MandrillProvider.transporter.messages.send` instead.
- Implement `MandrillProvider.checkIntegration` so that users can test their credentials when configuring a Mandrill provider.
#1467
Mailchimp Transactional provides a [/users/ping](https://mailchimp.com/developer/transactional/api/users/ping/) endpoint to test API keys (https://mailchimp.com/developer/transactional/guides/quick-start/#make-your-first-a …
=> feat: implement Mandrill provider connection test

CONTRIBUTING.md
This PR introduces Doc Update in [CONTRIBUTING.md](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md).
- Solves issue #1508.
- Previously provided link in [Missing a Feature?](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md#missing-a-feature) section was redirecting the contributor to the [Submitting an issue](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md#submitting-an-issue) section. Where nothing about raising a feature request was mentioned explicitly.
- Added a link which would enable the contributor to directly submit a feature request form.
- Also, added instructions to follow next time to …
=> update: link in "missing a feature?"

docs/docs/community/run-locally.md
Fix the format of the requirements section where the localstack bullet seems to be linked with the next sentence.
To avoid confusion. I missed the call-to-action to the notion page during the first couple of times I looked at the page. Which would've have been useful when I was installing the dependencies.
=> docs: fix formatting of the requirements section

docs/docs/notification-center/react-components.md
Abbreviations should always be capitalized if they are spelled letter by letter which is the case for API.  Thank you for reading my PR in advance.
Docs Update
To enhance the quality of the documentation.
=> Corrected a Typo

apps/api/src/app.module.ts, apps/api/src/app/execution-details/dtos/execution-details-response.dto.ts, apps/api/src/app/execution-details/dtos/execution-details.dto.ts, apps/api/src/app/execution-details/e2e/get-execution-details.e2e.ts, apps/api/src/app/execution-details/execution-details.module.ts, apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.command.ts, apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.spec.ts, apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.usecase.ts, apps/api/src/app/execution-details/usecases/index.ts, apps/api/src/app/shared/shared.module.ts, apps/api/src/bootstrap.ts, libs/dal/src/repositories/execution-details/execution-details.entity.ts, libs/dal/src/repositories/execution-details/execution-details.repository.ts, libs/dal/src/repositories/execution-details/execution-details.schema.ts, libs/shared/src/entities/execution-details/execution-details.interface.ts, libs/shared/src/entities/execution-details/index.ts, libs/shared/src/index.ts
- **What kind of change does this PR introduce?** (Feature)
Implement the use case to create execution details.
We need a use case that allows to create execution details on demand for a notification/job to store the data.
N/A
=> feat(api): create execution details use case

apps/web/src/components/layout/AppLayout.tsx
Fixes the spotlight issue seen during Office Hours where other elements are displayed on top.
Its an unexpected behavior
=> fix: update stack ordering to put spotlight on front

packages/notification-center/src/i18n/languages/tl.ts
Extended Powered By translation from "Pinagagana" => "Pinagagana ng".
The translation is incomplete, Pinagagana only translates to Powered (without "by").
From commit: https://github.com/novuhq/novu/pull/1602
=> chore: minor update for fil/tl language support

packages/notification-center/src/i18n/languages/fr.ts
This is a bug fix required for adding the settings translation within the French translations file.
See issue: #1676 
It is a necessary change because the settings keyword and translation are missing for French Users.
note: I am not a native speaker.
=> fix(translations): French Translations file missing settings translation

docs/docs/notification-center/react-components.md, packages/notification-center/src/i18n/lang.ts, packages/notification-center/src/i18n/languages/gl.ts
Adds the translations for the missing last official language from Spain, galego (galician).
All languages are welcome.
https://en.wikipedia.org/wiki/Galician_language
=> feat(lang): add galego language

docs/docs/channels/sms/index.md, docs/docs/channels/sms/twilio.md
This PR was a fix to issue #1662  (https://github.com/novuhq/novu/issues/1662) which simply requested a documentation page for Twilio's SMS system. It goes in detail of creating an account, sending a message, and linking with Novu which is how many of the other Documentation pages were structured.
This change was needed because documentation is currently lacking in the areas of setup for many of these channels which would be a lot easier on users.
=> Added Twilio SMS Docs

docs/docs/channels/sms/index.md
- added telnyx documentation [link ](https://github.com/novuhq/novu/blob/84682038213c26c526f577c3668e028f6da4936a/docs/docs/channels/sms/telnyx.md)in the [index.md](https://github.com/novuhq/novu/blob/84682038213c26c526f577c3668e028f6da4936a/docs/docs/channels/sms/index.md) .
- As the added documentation of SMS providers should be enlisted in [index.md](https://github.com/novuhq/novu/blob/84682038213c26c526f577c3668e028f6da4936a/docs/docs/channels/sms/index.md)
_NA_
=> doc: added telnyx doc link to index.md

providers/emailjs/src/lib/emailjs.provider.spec.ts
This PR adds unit test coverage for the emailjs provider.
There is currently no test coverage for this provider.
=> chore: Added unit test coverage for emailjs provider

docs/docs/channels/push/index.md
- Added Expo Push and Firebase Cloud Messages documentation link to [index.md](https://github.com/novuhq/novu/blob/e0d8e42a6319b7e39be82c8c5dd0d28ea581c915/docs/docs/channels/push/index.md).
- As the documentation of providers should be enlisted in [index.md](https://github.com/novuhq/novu/blob/e0d8e42a6319b7e39be82c8c5dd0d28ea581c915/docs/docs/channels/push/index.md)
_NA_
=> docs: added provider documentation link

docs/docs/channels/email/emailjs.md
- Doc update - Changed every occurrence of Emailjs to **EmailJS** in [emailjs.md](https://github.com/novuhq/novu/blob/12af2340f8c77a482e8feb762b3eca9abd14e340/docs/docs/channels/email/emailjs.md).
- Links and file name are untouched.
- **'EmailJS'** is the official format. It's more suitable and looks better.
_NA_
=> update: fix typo in emailjs.md

packages/notification-center/src/i18n/languages/it.ts
This is a bug fix required for adding the settings translation within the _Italian_ translations file.
See Issue: #1539
=> Updated the missing translation of 'Settings'

docs/docusaurus.config.js, docs/package.json, pnpm-lock.yaml
Docs: This pull request adds Google Analytics for documentation pages
We don't currently collect analytics from the documentation pages
N/A
=> feat: add Google Analytics for documentation pages

apps/web/src/components/utils/Spotlight.tsx
Introduces ability to navigate to team members in command palette
fixes #1342 
What kind of change does this PR introduce?
Feature:Add navigation to team members in command palette as described in [NV-937]
Why was this change needed? To fix #1342
=> feat: Add navigation to team members in command palette

docs/docs/channels/sms/SMS77.md, packages/notification-center/src/i18n/languages/it.ts
Documentation update
This pr fixes the use of "you" and "your" in the `SMS77` documentation.
In the documentation it is usually preferable to use a generic form.
=> Grammar fix for sms77

docs/docs/channels/email/postmark.md, packages/notification-center/src/i18n/languages/it.ts
Documentation update
This pr fixes the use of "you" and "your" in the `Postmark` documentation.
In the documentation it is usually preferable to use a generic form.
=> Grammar fix for postmark

providers/mailjet/src/lib/mailjet.provider.spec.ts, providers/mailjet/src/lib/mailjet.provider.ts
This PR adds implementation for the `checkIntegration` method in the `mailjet` provider to check integration while creating or updating it.
https://github.com/novuhq/novu/issues/1469
For Invalid credentials, It  shows the following message,
=> Test Mailjet connection

apps/web/src/pages/activities/components/ActivityStatistics.cy.tsx
To help increase our test coverage within the `novu/web` project, we can add the newly released [cypress component tests](https://docs.cypress.io/guides/component-testing/testing-react).
A new component test file should be added located near the original source file(see example at `apps/web/src/design-system/button/button.cy.tsx` and could be run after running `npm run start` from the root of the monorepo and specifying "Run Tests" and "Open Cypress", after which select the "Component testing" in the cypress screen.
Write the new test and make sure it passes all assertions.
The component is located at: `apps/web/src/pages/activities/components/ActivityStatistics.tsx `
=> [NV-924] - Add cypress component test to ActivityStatistics component

apps/api/src/app/events/e2e/delay-events.e2e.ts, apps/api/src/app/events/services/workflow.queue.service.ts, apps/api/src/app/events/usecases/add-job/add-delay-job.usecase.ts, apps/api/src/app/events/usecases/add-job/add-digest-job.usecase.ts, apps/api/src/app/events/usecases/add-job/add-job.usecase.ts, apps/api/src/app/events/usecases/add-job/should-add-digest-job.usecase.ts, libs/dal/src/repositories/job/job.repository.ts
fix case of an extra digest created for delayed (regular or scheduled) that comes before digest 
WF:
Triggering twice resulted in :
Now:
Also fixes the problem:
- that events that are delayed are added to a current digest, before their delay time completed.  
- events that have digest pending being sent twice
=> fix: fix decision of when should create another digest event

docs/docs/community/create-provider.md
Docs Update: Removed broken link to provider-template from create-provider.md doc
Close #1760 
The link wasn't working and was supposed to be removed from the doc.
=> docs: Remove link to provider-template

providers/mailersend/src/lib/mailersend.provider.spec.ts, providers/mailersend/src/lib/mailersend.provider.ts, providers/mailersend/src/types/index.d.ts
feature: implemented `checkIntegration` for mailersend
Resolves #1648 
=> feat: mailersend check integration function

apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts
Bug fix
On update of template - trigger snippet was not updated with the new subscriber variables. 
For example : adding an email step and updating an existing template will not add 'email:....' to trigger snippet
=> fix: fix subscriber variables in trigger snippet not being updated

apps/web/src/components/activity/ExecutionDetailsModal.tsx, apps/web/src/components/utils/GotAQuestionButton.tsx, apps/web/src/design-system/button/Button.tsx, apps/web/src/design-system/index.ts, apps/web/src/pages/activities/ActivitiesPage.tsx, apps/web/src/pages/activities/components/ActivityGraph.tsx
- **What kind of change does this PR introduce?** (feature)
Creates a parent component as a scaffold to hold the information for execution details. Also creates a new reusable component `GotAQuestionButton` that takes user to the Intercom server for support.
We need a parent component to render the execution details of the different notifications from the activity feed.
N/A
=> feat(web): nv-1061-scaffold-for-notification-execution

apps/web/src/design-system/color-input/ColorInput.tsx, apps/web/src/pages/settings/tabs/BrandingForm.tsx
Fixes #840
- Updated image size to be 100x100 with `object-fit: contain` so that they always maintain the original aspect ratio if not square
- Makes it possible to input custom values in color picker; helpful especially when the required color is just too specific
This PR was introduced to fixes issue and introduce requested feature in the Setting page.
As per the discussion over at Discord with @scopsy the issue with the font Select component is left as it.
This is because the mantine version used on the web is slightly older version. (Needs #1346)
=> style: Fix UI issues in settings page

docs/docs/channels/chat/discord.md
Docs update
The code example in this has the subscriber ID identifier as `SUBSCRIBER_ID` but below it's `subscriberID`.
=> docs: Change `SUBSCRIBER_ID` to `subscriberId`

apps/web/src/pages/settings/tabs/components/Security.tsx
Small feature improvement
Changing the "Enable HMAC encryption" option and then clicking by "Update" button has no UI effect. As a user, I expect to see confirmation that the change I just made has been saved on server. 
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/197337393-7cd0ce37-6b7a-4abf-b686-dec277be0c3d.png) | ![image](https://user-images.githubusercontent.com/4408379/197337488-2e5f5fa6-7d82-4551-8a7b-a2859da18248.png) |
=> feat: notify about security changes on settings page

packages/notification-center/src/i18n/lang.ts
made all language codes alphabetically correct.
also removed the duplicate entry of language code da from line number 201 and 209.
While all language codes were placed randomly it was possible for an duplicate entry.
its not a big issue to have duplicate entry but it is good practice to avoid it. so removed duplicate entry of da.
=> removed duplicate entry and corrected alphabetical order

apps/api/src/app/events/services/workflow.queue.service.ts, apps/api/src/app/shared/services/queue/queue.service.ts, apps/api/src/config/env-validator.ts, apps/ws/src/shared/framework/redis.adapter.ts, apps/ws/src/shared/queue/queue.service.ts, docs/docs/community/run-locally.md
Added a password option to the redis instance
Currently it's not possible to connect with an external redis instance
Related to: https://github.com/novuhq/novu/issues/1863
=> fix: add Redis optional configurable password

apps/web/src/components/auth/LoginForm.tsx, apps/web/src/components/layout/components/AuthContainer.tsx, apps/web/src/components/layout/components/AuthLayout.tsx, apps/web/src/design-system/password-input/PasswordInput.tsx, apps/web/src/pages/auth/InvitationPage.tsx
Various improvements for auth pages
- First of all, preventing vertical scrolling (due setting of min-width) when it is not needed, see current behavior:
| Desktop   | Mobile    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/198245616-35771eed-e82d-46fc-8133-8588db1b62f2.png) | ![image](https://user-images.githubusercontent.com/4408379/198245738-6321488e-a81c-4517-be78-a8aaeff6f1b5.png) |
- Align content of the auth pages in center looks more neat:
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/198246486-8cddd5d1-9442-4339-a06a-b …
=> refactor: auth pages improvements

.github/PULL_REQUEST_TEMPLATE.md
- Feature, Docs
- This change was needed because I think a detailed PR template would be better and is a good option both for maintainers and contributors
- Any suggestions and improvements are welcome!
cc @scopsy
=> feat: added a detailed PR Template

apps/web/src/components/activity/ExecutionDetailsStepHeader.tsx
https://linear.app/novu/issue/NV-1109/hover-and-time-color-identical-in-dark-mode
=> fix: so date is visible on hover in dark mode

apps/web/src/components/activity/ExecutionDetailsFooter.tsx, apps/web/src/components/activity/ExecutionDetailsModal.tsx, apps/web/src/components/templates/ExecutionDetailsModalWrapper.tsx, apps/web/src/pages/activities/ActivitiesPage.tsx
- **What kind of change does this PR introduce?** (Bug fix)
Removes the link back where the execution details modal has been opened from and fixes the footer layout at the same time.
UI fixes.
BEFORE
AFTER
=> fix(web): remove back link and fix layout footer of exec-det

apps/web/src/components/activity/ExecutionDetailsStepHeader.tsx, apps/web/src/components/activity/ExecutionDetailsWebhookFeedback.tsx
This bit is not implemented yet in the API so we will hide it for now.
=> feat(web): temporarily hide webhook feedback from ui

apps/web/src/design-system/icons/general/Digest.tsx
=> fix: color of digest icon if no explicit color is passed 

apps/web/src/components/activity/ExecutionDetailTrigger.tsx
Prevent in code missing subscriber variables to be parsed.
When the notification has no subscriber variables the execution details modal breaks.
=> fix(web): avoid execution details modal to break when no subscriber vars

apps/web/src/components/activity/ExecutionDetailsAccordion.tsx
Make the border radius round for the steps in the execution details modal when hovered.
The border radius of the steps in the execution details modal when hovered where square.
BEFORE
AFTER
=> fix(web): make step hover border round

apps/web/src/components/activity/ExecutionDetail.tsx, apps/web/src/components/activity/helpers.ts
=> fix: details icon to show failed and success icons

docs/docusaurus.config.js
It will stop your docs site sending traffic data to Google Analytics against blog.johnnyreilly.com
You probably don't want to send traffic to my Google analytics property.
You can see me using it on my blog here: https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/13e0433c32992592dfa59ff682c4443d8c62ef2c/blog-website/docusaurus.config.js#LL53C36-L53C36
=> fix: remove blog.johnnyreilly.com Google Analytics tag

apps/web/src/pages/activities/ActivitiesPage.tsx, apps/web/src/pages/activities/components/ActivityItem.tsx
It makes sense to me to also show the transaction id in an item, but maybe its too much information to show there
=> feat: add transaction id filter to activity list

packages/notification-center/src/components/popover-notification-center/PopoverNotificationCenter.tsx
Make empty state prop a prop on popover as well.
To be able to override the empty state in the popover notification center as well...
=> fix: so empty state can be provided to popover notification center

package.json, scripts/dev-environment-setup.sh, scripts/jarvis.js
A script that can be run individually or plugged by Jarvis to install the minimum tools a development environment system needs. So far run and tested in MacOSx environments. Potentially would work in Linux systems out of the box.
Creating an idempotent script that installs that based on the operative system could help to speed up the onboarding process. Also as @djabarovgeorge suggested, adding it to the Jarvis script could help collaborators to add all the tools needed to run the monolith that are missing in their system. Probably with some kind of interface and some of them skippable, as for example a collaborator wouldn't need to install AWS CLI to help us.
=> feat(infra): add dev env setup script and plug it in jarvis

packages/notification-center/src/hooks/use-default-theme.hook.ts
Fixes an issue where the notification center would break whenever the useDefaultBellColors was used. This was due to `defaultNotificationTheme` being a frozen object and attempting to use `merge` to update properties on it. This PR simply replaces the use of merge with copying the object using the spread operator.
Closes #2004
=> fix: copy bell theme instead of using merge

apps/api/src/app/events/usecases/send-message/send-message-chat.usecase.ts, apps/api/src/app/execution-details/usecases/create-execution-details/create-execution-details.command.ts
Fixes a potential TypeError if no webhookUrl is provided either in the payload or in the subscriber credentials.
Also adds a new execution detail when trying to send a Chat notification and the webhookUrl is not provided to help debug errors to users.
We got contacted by a user that was confused about why Chat notification wasn't working. Investigating we found the internal error.
WHAT USER SAW BEFORE
WHAT USER SHOULD SEE NOW
=> fix(api): if no webhookurl provided there is a typeerror

libs/dal/src/repositories/subscriber/subscriber.entity.ts, libs/dal/src/repositories/topic/index.ts, libs/dal/src/repositories/topic/topic-subscribers.entity.ts, libs/dal/src/repositories/topic/topic-subscribers.schema.ts, libs/dal/src/repositories/topic/topic.entity.ts
Creates the schema and entity to gather the subscribers that will be associated to a topic.
A topic is a way to know to which subscribers will be needed to send a notification in one shot. We need to store those relationships in the database so then users will be able to manage the topic subscribers with different functionalities.
=> Nv 1212 feature create topicsubscribers schema

apps/api/src/app/events/e2e/process-subscriber.e2e.ts, apps/api/src/app/events/usecases/send-message/send-message.usecase.ts, libs/dal/src/repositories/notification-template/notification-template.schema.ts
Allows system critical message to pass through even if subscriber has opt-out from preferences
=> fix: added functionality to override subscriber preference for system critical messages

libs/dal/src/repositories/topic/index.ts, libs/dal/src/repositories/topic/topic-subscribers.repository.ts
Adds the repository layer for the topic subscribers schema where we will store the relationships.
We need to be able to export this layer to be used in the use cases and have the separation of concerns with Mongoose and MongoDB.
=> feat(dal): topic subscribers repository

apps/api/src/app/content-templates/content-templates.controller.ts, apps/api/src/app/content-templates/e2e/preview-email.e2e.ts, apps/api/src/app/content-templates/usecases/parse-preview/preview-email.command.ts, apps/api/src/app/content-templates/usecases/parse-preview/preview-email.usecase.ts, apps/web/src/api/content-templates.ts, apps/web/src/pages/templates/editor/Preview.tsx
So subject are parsed in backend with email content to be rendered in preview
=> fix: so subject are parsed for preview as well

apps/api/src/app/topics/dtos/filter-topics.dto.ts, apps/api/src/app/topics/dtos/index.ts, apps/api/src/app/topics/dtos/topic.dto.ts, apps/api/src/app/topics/e2e/filter-topics.e2e.ts, apps/api/src/app/topics/e2e/get-topic.e2e.ts, apps/api/src/app/topics/topics.controller.ts, apps/api/src/app/topics/use-cases/filter-topics/filter-topics.command.ts, apps/api/src/app/topics/use-cases/filter-topics/filter-topics.use-case.ts, apps/api/src/app/topics/use-cases/filter-topics/index.ts, apps/api/src/app/topics/use-cases/index.ts
Adds an endpoint to be able to filter the topics by key (only for now) with pagination, besides its use case and tests.
This endpoint will allow us to implement the functionality that users will be able to find a topic they created based on the custom topic key they assigned to it.
=> feat(api): add endpoint to filter topics with pagination

apps/api/src/app/topics/e2e/create-topic.e2e.ts, apps/api/src/app/topics/use-cases/create-topic/create-topic.use-case.ts, libs/dal/src/repositories/topic/topic.repository.ts
Add the functionality to ensure the topic key is unique for an user in a certain organisation and environment.
Duplication of topics with the same key could be confusing and we want our users to have an easy way to identify their topics. So making the topic key they choose unique and avoiding creation duplication with same key helps to that.
=> feat(api): ensure topic key is unique for same user, env and org

apps/api/src/app/shared/shared.module.ts, apps/api/src/app/topics/dtos/index.ts, apps/api/src/app/topics/dtos/topic-subscribers.dto.ts, apps/api/src/app/topics/e2e/create-topic.e2e.ts, apps/api/src/app/topics/e2e/filter-topics.e2e.ts, apps/api/src/app/topics/use-cases/get-topic-subscribers/get-topic-subscribers.command.ts, apps/api/src/app/topics/use-cases/get-topic-subscribers/get-topic-subscribers.use-case.ts, apps/api/src/app/topics/use-cases/get-topic-subscribers/index.ts, apps/api/src/app/topics/use-cases/index.ts, libs/dal/src/repositories/topic/topic-subscribers.entity.ts, libs/dal/src/repositories/topic/topic-subscribers.schema.ts, scripts/dev-environment-setup.sh
Adds the use case to retrieve the relationship between a topic and its subscribers.
It is a previous step needed to be able to add and remove subscribers from a topic.
=> feat(api): add use case to get a topic subscribers entity

packages/node/src/lib/subscribers/subscriber.interface.ts
Duplicate identical IUpdateSubscriberPreferencePayload inside subscriber.interface.ts. 
While trying to investigate how Novu works, we stumbled upon this. Found by @milanarif
=> Removed duplicate ISubscriberPayload in subscriber.interface

packages/notification-center-vue/package.json, packages/notification-center-vue/vite.config.js, pnpm-lock.yaml
Fixes the issue for the Vite/Rollup build configuration with the external libraries.
I've solved it with ChatGPT, which is amazing 🤯 
Because on the `next` branch `notification-center-vue` package is failing to build.
=> chore(notification-center-vue): fix rollup issue for the external libraries

apps/api/src/app/topics/dtos/add-subscribers.dto.ts, apps/api/src/app/topics/dtos/index.ts, apps/api/src/app/topics/e2e/add-subscribers.e2e.ts, apps/api/src/app/topics/topics.controller.ts, apps/api/src/app/topics/use-cases/add-subscribers/add-subscribers.command.ts, apps/api/src/app/topics/use-cases/add-subscribers/add-subscribers.use-case.ts, apps/api/src/app/topics/use-cases/add-subscribers/index.ts, apps/api/src/app/topics/use-cases/index.ts, libs/dal/src/repositories/topic/topic-subscribers.repository.ts
Adds the endpoint to add subscribers to a topic.
With this endpoint users can create their topics and assign the subscribers they choose to that topic in order to be able to send a notification to that topic and therefore, those subscribed to the topic receiving said notification. The functionality to send a notification to a topic is yet to be done.
=> feat(api): add subscribers endpoint, use case and tests

apps/api/src/app/topics/dtos/index.ts, apps/api/src/app/topics/dtos/remove-subscribers.dto.ts, apps/api/src/app/topics/e2e/remove-subscribers.e2e.ts, apps/api/src/app/topics/topics.controller.ts, apps/api/src/app/topics/use-cases/index.ts, apps/api/src/app/topics/use-cases/remove-subscribers/index.ts, apps/api/src/app/topics/use-cases/remove-subscribers/remove-subscribers.command.ts, apps/api/src/app/topics/use-cases/remove-subscribers/remove-subscribers.use-case.ts, libs/dal/src/repositories/topic/topic-subscribers.repository.ts
Adds the endpoint to remove subscribers from a topic.
With this endpoint users can create their topics and fully assign and remove the subscribers they choose to that topic in order to be able to send a notification to that topic and therefore, those subscribed to the topic receiving said notification. The functionality to send a notification to a topic is yet to be done.
=> feat(api): remove subscribers endpoint, use case and test

apps/api/src/app/invites/usecases/accept-invite/accept-invite.usecase.ts, apps/api/src/app/organization/usecases/membership/remove-member/remove-member.usecase.ts, libs/dal/src/repositories/member/member.repository.ts
adds 'members' cached findOne.
in order to cache the most used queries on the trigger flow.
I am not sure we will benefit from caching this query because I could not manage to cache all the requests like
isMemberOfOrganization findInviteeByEmail findByInviteToken findMemberByUserId 
because of the missing _id on the request therefore most of them will be not cached.
=> feat: add cached members one find

apps/api/src/app/events/e2e/process-subscriber.e2e.ts
add sleep after event trigger and messages query.
there could be a race condition of the invalidation of the messages while triggering new ones and the find messages query on the test.
=> fix: potential race condition on find query

apps/api/src/app/auth/e2e/login.e2e.ts, apps/api/src/app/auth/usecases/login/login.usecase.ts, libs/dal/src/repositories/user/user.entity.ts, libs/dal/src/repositories/user/user.schema.ts
Adds a lockout mechanism for accounts after consecutive unsuccessful login attempts.
An user account will be blocked for 5 minutes, if it makes 5 unsuccessful login attempts within 5 minutes.
Without a lockout mechanism, one can do a brute force attack to guess the password of an user
=> feat: added user lockout mechanism

apps/api/src/app/auth/e2e/login.e2e.ts, apps/api/src/app/auth/usecases/login/login.usecase.ts, apps/api/src/app/auth/usecases/password-reset-request/password-reset-request.usecase.ts, apps/web/cypress/tests/auth.spec.ts, apps/web/src/components/auth/LoginForm.tsx
Syncs the server response timing for existing and non-existing users
Generalizes the error responses for non-existent users and wrong credentials
Currently, someone can guess if a user email exists in our system or not, just by comparing the server response timing from the two different requests.
similarly, on the basis of error responses, it can be known about the user's existence in the system
=> Nv 1202 username enumeration

apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
Properly handle no steps usecase when event is triggered
The lack of handling caused an unhandled exception of 500 to be thrown for the API user.
=> fix: unhandled no template steps scenario

apps/api/src/app.module.ts, apps/api/src/app/shared/framework/user.decorator.ts
Remove PII from sentry request breadcrumbs
No actual need for storing it there, request could be identified by and id
=> feat: remove pii from sentry reports

apps/api/src/app/events/dtos/trigger-event-request.dto.ts, apps/api/src/app/events/dtos/trigger-event-to-all-request.dto.ts, apps/api/src/app/events/events.controller.ts, apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.e2e.ts, apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.use-case.ts, apps/api/src/config/env-validator.ts, packages/node/src/lib/events/events.interface.ts
We finally integrate the new functionality that maps properly all the recipients (subscriberIds, subscriber payload and topics) into the Trigger event endpoint. The integration is controlled by the feature flag that is disabled by default to not interfere with the current working order of the endpoint until the release 0.10.0 if we find proper the state of the feature to get released.
It also cleans the old typings for the new ones in the subscriber interface, that I consider handle the typing a bit better and clearer.
Finally integration tests for the enablement/disablement of the feature are added.
The full integration allows now to test the feature in isolation and double check if the trigger event endpoint functionality is not affected and the results provided from sending a …
=> feat(api): integrate the map trigger recipients use case in events controller

apps/widget/cypress/e2e/notifications-list.spec.ts
Revert .only flag
It was restricting our test runs
=> fix(web): Remove .only flag

apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.e2e.ts, apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.use-case.ts
Repeated recipients deduplication no matter what type of payload are provided in, as it is done in the use case.
No one likes to get delivered same notification twice and companies don't like to be charged twice for the same notification to a user.
=> feat(api): deduplicate subscribers in recipients

apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx
It changes the color for the text **Here**, in the modal which is shown when we connect to the provider.
#2268
=> fix: adds color to link in modal

apps/api/src/app/events/dtos/trigger-event-request.dto.ts, apps/api/src/app/events/e2e/trigger-event-topic.e2e.ts
Tests for the implementation of sending a notification to a topic through the trigger event endpoint.
Give confidence that the implementation of topics reuse downstream all the functionalities of trigger event endpoint.
=> feat(api): add tests for triggering a event to a single topic

providers/nodemailer/src/lib/nodemailer.provider.spec.ts, providers/nodemailer/src/lib/nodemailer.provider.ts
Make user and password optional for nodemailer so it can be used for internal smtp servers.
=> fix: so nodemailer can be used without user and password

apps/api/src/app/events/usecases/send-message/send-message-in-app.usecase.ts
Add a new socket event when a notification is created
Closing https://github.com/novuhq/novu/issues/1220
=> feat: add socket event notification_received

apps/api/src/app/integrations/usecases/get-webhook-support-status/get-webhook-support-status.usecase.ts, apps/webhook/src/webhooks/usecases/webhook/webhook.usecase.ts
Pass the integration credentials to the builder to fix Twilio error
=> fix: pass credentials to the provider

apps/web/src/hooks/use-variables-manager.ts
Fix to these sentry errors: [1](https://sentry.io/organizations/novu-r9/issues/3585039175/?project=6250907&query=is%3Aunresolved&referrer=issue-stream) [2](https://sentry.io/organizations/novu-r9/issues/3836606905/?project=6250907&query=is%3Aunresolved&referrer=issue-stream)
`Cannot read properties of undefined (reading '0')`
It was caused after a user removed action buttons in in-app editor.
=> fix: fix errors of reading undefined in var manager

apps/web/src/components/templates/email-editor/EmailMessageEditor.tsx
Fixes the email editor brand logo issue described here: #2385
To fix the issue.
=> fix(web): the email editor brand logo issue

apps/webhook/package.json, apps/ws/package.json, packages/headless/package.json, pnpm-lock.yaml
Upgrading some of the socket packages versions to match the ones existing, for webhook package.
Also removing a unused package that connects to Redis.
There has been requests from users that they are getting this error:
```
websocket.js:124 WebSocket connection to 'wss://ws.novu.co/socket.io/?token=SECRETSTUFF*&transport=websocket' failed: Invalid frame header
```
=> fix(ws|webhook): socket versions match

apps/api/src/app/content-templates/usecases/parse-preview/preview-email.usecase.ts, apps/web/src/pages/templates/editor/Preview.tsx
There was no catch to errors thrown for compiling the preview. 
Might also help with the sentry with the errors we are getting on sentry. [example](https://sentry.io/organizations/novu-r9/issues/3844312241/?environment=prod&project=6248811&query=&referrer=issue-stream&statsPeriod=14d)
=> fix: catch compile errors in preview email and show error notification in ui

apps/api/src/app/topics/topics.controller.ts
Improvements of topics swagger docs.
Chore improvement
=> chore(docs): improve-topics-swagger

apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/subscribers/usecases/create-subscriber/create-subscriber.command.ts
small improvement to `subscriberId` validation on `/v1/subscribers/` `POST` request
now it throws an error if it receives `""` or `" "` for `subscriberId`
closes #2394
=> fix(api): improve `subscriberId` validation

apps/ws/src/socket/ws.gateway.ts
For old notification center clients that still use the old query method for authentication.
Old clients would break, unless upgraded to 0.10.0.
Might be also related to: #2392
=> fix: add backwards compatability for auth header

apps/api/src/app/message-template/usecases/create-message-template/create-message-template.spec.ts, libs/dal/src/repositories/message-template/message-template.entity.ts, libs/dal/src/repositories/message-template/message-template.schema.ts
Adds the relationship at DAL level for Message Template and Layout. Also adds missing test in message template creation to validate the change.
Another step forward for the DAL for Layouts feature.
=> feat(dal): add relationship between message template and layout

packages/notification-center/src/components/notification-center/components/user-preference/SubscriberPreference.tsx, packages/notification-center/src/hooks/use-subscriber-preference.hook.ts
After update the search by index was not identical - it would override a different record.
Closes: #2436
=> fix: duplicate preference rows on update

apps/api/src/app/events/usecases/trigger-event/message-matcher.service.spec.ts, apps/api/src/app/events/usecases/trigger-event/message-matcher.service.ts, libs/dal/src/repositories/subscriber/subscriber.schema.ts
Implemented the step filters logic for the "Is Online Filters".
This is a part of the "Is Online Filters" functionality.
=> feat(api): run step filters - is online logic

apps/api/src/app/layouts/dtos/filter-layouts.dto.ts, apps/api/src/app/layouts/dtos/index.ts, apps/api/src/app/layouts/e2e/filter-layouts.e2e.ts, apps/api/src/app/layouts/layouts.controller.ts, apps/api/src/app/layouts/use-cases/filter-layouts/filter-layouts.command.ts, apps/api/src/app/layouts/use-cases/filter-layouts/filter-layouts.use-case.ts, apps/api/src/app/layouts/use-cases/filter-layouts/index.ts, apps/api/src/app/layouts/use-cases/index.ts, libs/dal/src/repositories/layout/layout.repository.ts
Adds endpoint to filter layouts by environment.
UI needs a layout manager to list all the layouts an organization has in certain environment. For that this endpoint will be needed to show and paginate all the layouts.
=> feat(api): filter layouts endpoint

apps/api/src/app/events/usecases/trigger-event/message-matcher.service.spec.ts, apps/api/src/app/events/usecases/trigger-event/message-matcher.service.ts, libs/dal/src/repositories/subscriber/subscriber.entity.ts
Skip processing the subscribers that don't have "online" fields set.
Part of the "Is Online Filters" feature.
=> fix(api): is online filters - skip processing old subscribers

apps/web/cypress/tests/notification-editor/steps-actions.spec.ts, apps/web/src/pages/templates/filter/FilterModal.tsx, apps/web/src/pages/templates/filter/Filters.cy.tsx, apps/web/src/pages/templates/filter/Filters.tsx, apps/web/src/pages/templates/filter/OnlineFiltersForms.tsx, apps/web/src/pages/templates/workflow/WorkflowEditorPage.tsx
Added the test cases for the Web UI
=> feat: added tests for filters

apps/api/src/app/layouts/e2e/delete-layout.e2e.ts, apps/api/src/app/layouts/e2e/filter-layouts.e2e.ts, apps/api/src/app/layouts/e2e/get-layout.e2e.ts, apps/api/src/app/layouts/e2e/helpers/index.ts, apps/api/src/app/layouts/e2e/set-default-layout.e2e.ts, apps/api/src/app/layouts/e2e/update-layout.e2e.ts, apps/api/src/app/layouts/layouts.controller.ts, apps/api/src/app/layouts/use-cases/index.ts, apps/api/src/app/layouts/use-cases/set-default-layout/index.ts, apps/api/src/app/layouts/use-cases/set-default-layout/set-default-layout.command.ts, apps/api/src/app/layouts/use-cases/set-default-layout/set-default-layout.use-case.ts, libs/dal/src/repositories/layout/layout.repository.ts
Adds endpoint and use case to set a layout as default. If there is an existing default layout in the same environment, it will set it to non default while setting as default the chosen one.
The endpoint is probably not going to be used but the use case will be reused in the creation and update endpoints when the `isDefault` property is sent as true. As we can only have one default template per environment we need this functionality.
=> feat(api): add endpoint to set a layout as default

apps/api/src/app/layouts/e2e/create-layout.e2e.ts, apps/api/src/app/layouts/e2e/get-layout.e2e.ts, apps/api/src/app/layouts/e2e/update-layout.e2e.ts, apps/api/src/app/layouts/use-cases/create-layout/create-layout.use-case.ts, apps/api/src/app/layouts/use-cases/update-layout/update-layout.use-case.ts
Integrates the set default layout use case in the create layout and update layout use case for when the command property is default is set to true, to proceed to set the chosen layout as default and to set to non default any existing default layout in the environment.
We just want to have a default layout by environment so when users decide to choose one layout as default either when creating it or updating it, we had to add that case, because if not we would face a situation of having multiple default layouts.
=> feat(api): integrate set default layout in creation and update flows

packages/notification-center/src/store/socket/use-socket-controller.ts
inside `use-socket-controller.ts` useEffect
```js
return () => {
socket = null;
socket?.disconnect();
};
```
the order of statements were wrong
socket.disconnect should be invoked before setting it to null
=> fix: rearranged the order of statements inside the cleanup function

.github/workflows/dev-deploy-embed.yml, .github/workflows/dev-deploy-web.yml, .github/workflows/dev-deploy-widget.yml, .github/workflows/prod-deploy-embed.yml, .github/workflows/prod-deploy-web.yml, .github/workflows/prod-deploy-widget.yml
Remove the build output of the ci before building the docker image 
Related to #2486
=> fix: update ci pipelines to remove build before building docker image

apps/api/src/app/layouts/usecases/set-default-layout/set-default-layout.use-case.ts
In update/create layout, because the db create/update of the new default happens before the SetDefaultLayoutUseCase, there are two at time. It is inconsistent which of them SetDefaultLayoutUseCase finds → so causes a state of two defaults at the same time.
=> fix: ensure one default layout in set as default

apps/api/src/app/change/usecases/get-changes/get-changes.usecase.ts, apps/web/src/components/changes/ChangesTableLayout.tsx
Show layout changes in promote table
=> feat: show layout changes in web

apps/api/src/app/change/usecases/index.ts, apps/api/src/app/change/usecases/promote-change-to-environment/promote-change-to-environment.usecase.ts, apps/api/src/app/change/usecases/promote-layout-change/index.ts, apps/api/src/app/change/usecases/promote-layout-change/promote-layout-change.use-case.ts, apps/api/src/app/change/usecases/promote-message-template-change/promote-message-template-change.ts, apps/api/src/app/layouts/dtos/layout.dto.ts, apps/api/src/app/layouts/usecases/create-layout-change/create-layout-change.use-case.ts, apps/api/src/app/message-template/usecases/create-message-template/create-message-template.usecase.ts, apps/api/src/app/message-template/usecases/update-message-template/update-message-template.usecase.ts, apps/web/src/components/templates/email-editor/EmailInboxContent.tsx, apps/web/src/pages/brand/tabs/LayoutEditor.tsx, apps/web/src/pages/brand/tabs/LayoutsListPage.tsx, libs/dal/src/repositories/layout/layout.entity.ts, libs/dal/src/repositories/layout/layout.schema.ts, libs/shared/src/dto/layout/layout.dto.ts, libs/shared/src/entities/change/change.interface.ts, libs/shared/src/entities/layout/layout.interface.ts
Adds use case to be able to promote existing changes between environments in layouts.
To keep aligned our users' environments after they create and test their email notification layouts.
=> feat(api): promote changes of layouts

docs/docusaurus.config.js
Add a new link in footer as `Home` which will open `novu.co` in a new tab.
Closes #978
=> feat: add footer link for home

apps/web/src/components/templates/in-app-editor/content/Content.tsx, packages/notification-center/src/components/notification-center/components/notification-item/NotificationListItem.tsx
fixes an issue with longer notification text overflowing the container
closes #2449
=> fix: long text overflows container

apps/api/src/app/layouts/e2e/delete-layout.e2e.ts, apps/api/src/app/layouts/e2e/update-layout.e2e.ts, apps/api/src/app/layouts/usecases/delete-layout/delete-layout.use-case.ts, apps/api/src/app/layouts/usecases/find-deleted-layout/find-deleted-layout.spec.ts, apps/api/src/app/layouts/usecases/set-default-layout/set-default-layout.use-case.ts, apps/api/src/app/layouts/usecases/update-layout/update-layout.use-case.ts
We need to make sure user can not remove the only default layout - I see two usecases that could happen : 
In web - unchecking the default 
When deleting a layout, we disallow delete of an assigned layout, but it could be unassigned and the default.
=> feat: ensure one default layout

apps/web/src/components/utils/GotAQuestionButton.tsx
Refactored the `GotAQuestionButton` component to not throw error when `INTERCOM_APP_ID` & `IntercomProvider` is unavailable
=> Nv 1579 useintercom must be inside

apps/api/src/app/layouts/usecases/create-layout-change/create-layout-change.use-case.ts, apps/inbound-mail/src/server/mailUtilities.ts
After multiple updates in dev, there should be one row per layout in the changes table. Before, it shows all updates separately and they needed to be promoted individually (could cause unexpected behavior in the production if one change depends on another)
Now, all changes made to a layout will be aggregated into a single promotable change. 
* I still need to add tests. Will do in this pr
=> fix: so changes are aggregated into one

apps/web/src/components/templates/LackIntegrationError.tsx, apps/web/src/components/templates/email-editor/EmailContentCard.tsx
Change copy for when no email integration is active.
For it to not be misleading with the new predefined provider.
=> fix: copy when there is no email integration active

apps/web/src/components/templates/email-editor/TestSendEmail.tsx
So sending test email can be done with Novu email provider
=> fix: test send email with nouv email integration

packages/notification-center/src/components/notification-center/components/AppContent.tsx
Removing the usage of normalize css for our notification center
So the normalize css are not applied to our users websites
=> fix: so no global style are applied

apps/api/src/bootstrap.ts
The 20mb was only applied to event trigger - not for the broadcast, test email or to save and update the email content.
=> fix: size of email content "too large" 

apps/api/src/app/events/e2e/delay-events.e2e.ts, apps/api/src/app/integrations/usecases/calculate-limit-novu-integration/calculate-limit-novu-integration.usecase.ts, libs/dal/src/repositories/base-repository.ts
Add environmentId to the query to avoid collections scans on it and limited the amount of objects scanned until reached limit
The current query is not utilizing indexes properly since an index on organizationId does not exists
=> fix: missing indexes for count query

apps/web/src/pages/activities/components/ActivityGraphGlobalStyles.tsx, apps/web/src/pages/activities/services/chart-bar/option.service.ts
The Activity Feed tooltip on the bar was not showing up.
=> fix(web): activity feed tooltip issue

apps/web/cypress/tests/layout/side-menu.spec.ts, apps/web/src/components/layout/components/SideNav.tsx
- Added a link to create github issue on the side nav.
=> feat: add link to github issue to sidebar

apps/web/src/components/utils/Spotlight.tsx
- Added `Share Feedback` as one of the item for the command palette, which will open the github issue page when accessed.
=> feat: added share feedback to open github issue through command palette

apps/api/src/app/notification-template/e2e/delete-notification-template.e2e.ts, apps/api/src/app/notification-template/usecases/delete-notification-template/delete-notification-template.usecase.ts
Same behaviour as on update notification template
To fix so template is deleted in prod env when using promote all
=> fix: so previous change id is used on delete change for notification template

apps/api/src/app/events/usecases/send-message/send-message.usecase.ts, apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts, apps/api/src/app/subscribers/e2e/create-subscriber.e2e.ts, apps/api/src/app/subscribers/e2e/get-preferences.e2e.ts, apps/api/src/app/subscribers/e2e/helpers/index.ts, apps/api/src/app/subscribers/e2e/remove-subscriber.e2e.ts, apps/api/src/app/subscribers/e2e/update-online-flag.e2e.ts, apps/api/src/app/subscribers/e2e/update-preference.e2e.ts, apps/api/src/app/subscribers/e2e/update-subscriber.e2e.ts, apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/subscribers/usecases/update-subscriber-preference/update-subscriber-preference.usecase.ts, apps/api/src/app/widgets/dtos/update-subscriber-preference-request.dto.ts, apps/api/src/app/widgets/dtos/update-subscriber-preference-response.dto.ts
Adds more defensive checks in the code and avoids to accept bad formatted payloads. Adds more E2E tests for the update of the subscriber preferences after some investigation regarding potential bugs reported by users. Also improves the API docs with more detailed descriptions.
Improve the confidence in the code and clarify the intention to the users.
=> fix(api): api docs not generated and added more e2e tests

docs/docs/platform/topics.md
Updates the Topic docs to do away with enums and simply use strings. 
This change is needed to simplify the understanding of developers trying to trigger notifications to topics. Before now, they need to go into the codebase to check the value of the enum. With this change, they can just copy and paste and trigger.
Furthermore, it makes it easy for non-JavaScript/non-Node developers to flow with the topics docs.
=> docs(topic): Replace enum with string for simplified understanding

apps/api/src/app/message-template/usecases/create-message-template/create-message-template.spec.ts, apps/api/src/app/message-template/usecases/create-message-template/create-message-template.usecase.ts, apps/api/src/app/message-template/usecases/update-message-template/update-message-template.usecase.ts, apps/api/src/app/shared/helpers/verify-payload.service.ts
so empty string can not be used as default value
To be more logical with how we handle default values
=> fix: so empty string can not be used as default value

apps/web/cypress.config.ts, apps/web/cypress/tests/notification-editor/create-notification.spec.ts, apps/web/src/pages/integrations/components/ConnectIntegrationForm.tsx, apps/web/src/pages/integrations/components/NovuIntegrationCard.tsx, apps/web/src/pages/integrations/components/ProviderCard.tsx
[NV-1657] ✨ Polishing: Some design issues in the Integration Store #2744
minor design changes in integration store
buttons do not scroll when inside form + added padding so it looks much better & when u hover on a !active provider card the opacity comes up to 1
better looking 
closes #2744
closes #2388
https://user-images.githubusercontent.com/98285260/218696972-a1eae4f4-83a8-4551-bc54-7e5f28c97117.mov
=> Polishing: Some design issues #2744

apps/api/src/app/events/usecases/send-message/send-message.usecase.ts, apps/api/src/app/subscribers/e2e/get-preferences.e2e.ts, apps/api/src/app/subscribers/e2e/helpers/index.ts, apps/api/src/app/subscribers/usecases/get-subscriber-template-preference/get-subscriber-template-preference.command.ts, apps/api/src/app/subscribers/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts
- Refactor usage of subscriberId and internal subscriber id on fetch preference
- Throw exception when subscriber not found
- Added missing change
NV-1459
=> fix: proper error handling for missing subscriber on preference update

apps/web/src/design-system/table/Table.tsx
Mends the Notification Listing Table's `Loader's` `zIndex` value to less than of `Notification bar` and `User Dropdown`.
Closes https://github.com/novuhq/novu/issues/2198
After Fix:
[Templates _ Novu Manage Platform (1).webm](https://user-images.githubusercontent.com/58044533/218698551-65398784-5e78-41a6-b2e5-4a8ea03f9441.webm)
Before Fix:
[Templates _ Novu Manage Platform.webm](https://user-images.githubusercontent.com/58044533/218665613-d43dec87-4fe1-4b33-bb75-ec1380e7c56e.webm)
=> NV-538 - Change Z-index for user profile dropdown to overlay the loader in notification template screen

apps/web/src/components/activity/ExecutionDetailsModal.tsx
Updates the  `Execution Details` Modal  title to `Execution Details for <TEMPLATE_NAME>`
Closes https://github.com/novuhq/novu/issues/2716
=> NV-1588 - Execution Details modal Should include Template name

apps/api/src/app/events/services/push-service/handlers/apns.handler.ts, apps/web/src/pages/integrations/components/IntegrationInput.tsx, libs/shared/src/consts/providers/credentials/provider-credentials.ts, providers/apns/src/lib/apns.provider.ts
Two new fields for apns config in integration store, production existed before to the apns provider but was always set to true if cloud version was used. Topic was an required field from start and was missed during first implementation
=> feat: add more integration fields for apns

apps/api/src/app/events/usecases/send-message/send-message-email.usecase.ts, apps/api/src/app/events/usecases/send-message/send-message.command.ts, apps/api/src/app/message-template/usecases/create-message-template/create-message-template.command.ts, apps/api/src/app/message-template/usecases/create-message-template/create-message-template.usecase.ts, apps/api/src/app/message-template/usecases/update-message-template/update-message-template.command.ts, apps/api/src/app/message-template/usecases/update-message-template/update-message-template.usecase.ts, apps/api/src/app/notification-template/e2e/create-notification-templates.e2e.ts, apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.usecase.ts, apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts, apps/api/src/app/shared/dtos/message-template.ts, apps/web/src/components/templates/TemplateFormProvider.tsx, apps/web/src/components/templates/email-editor/EmailInboxContent.tsx, apps/web/src/components/templates/templateToFormMappers.ts, libs/dal/src/repositories/message-template/message-template.entity.ts, libs/dal/src/repositories/message-template/message-template.schema.ts, libs/shared/src/entities/message-template/message-template.interface.ts
So sender name can be changed from each email template if needed empty field uses default from integration.
=> feat: make sender name an input field for email card

_templates/provider/new/package.ejs.t, _templates/provider/new/prompt.js
It fixes dependencies upgrades, removal of unused ones and aligns the versions to the current monorepo ones.
Also gives better hint for the naming pattern (kebab-case) that we adopted recently.
Yesterday while @unicodeveloper was investigating the process of creating a new provider he ran into problems by mismatching versions, mainly of our `stateless` package. From there I decided it was better to upgrade the script until we find a way to automatically inject the latest versions of the needed dependencies.
=> fix(infra): upgrade and clean dependencies for provider creation script

apps/web/src/pages/integrations/components/IntegrationInput.tsx, apps/web/src/pages/integrations/components/IntegrationSecretTextarea.tsx, libs/shared/src/consts/providers/credentials/provider-credentials.ts
Fix so private key in apns can be multiline
=> feat: hide content of textarea with multiline keys

docs/docs/channels/email/custom-smtp.md, docs/docs/channels/email/mailersend.md, docs/docs/channels/email/mailjet.md, docs/docs/channels/email/outlook365.md, docs/docs/channels/email/postmark.md, docs/docs/channels/email/resend.md, docs/docs/channels/email/sendgrid.md, docs/docs/channels/email/sendinblue.md, docs/docs/channels/email/ses.md
This adds Resend documentation to the list of [Email Channels](https://docs.novu.co/channels/email), and updates other email channel docs.
To make Resend visible docs, and guide users to integrate Resend.
=> [Docs Update]: Add Resend documentation & Update Existing Email Provider docs

apps/widget/src/components/notification-center/NotificationCenterWidget.tsx, libs/embed/src/embed.ts, libs/embed/src/shared/eventTypes.js, packages/notification-center/src/components/novu-provider/NovuProvider.tsx, packages/notification-center/src/shared/interfaces/index.ts, packages/notification-center/src/utils/token.ts
closes #1289 
- Added a logout method that removes the widget auth token, disconnects the WebSocket
=> Nv 942 bug report no way to reset destroy the

apps/web/src/design-system/config/inputs.styles.ts
This PR introduces a new CSS rule that applies a border color of `colors.error` to an input field when it is in the invalid state and has focus. This change was made to provide a more visible indication to the user that there is an error with the input field, specifically when the notification name field in Notification settings is deleted and the workflow button is clicked. The new rule helps to focus the user's attention on the error state of the field and encourages them to correct the error.
closes [#2714](https://github.com/novuhq/novu/issues/2714)
[Video demonstration of this fix](https://user-images.githubusercontent.com/57623705/217866864-4ffc352a-72c7-432e-b774-662566cc6694.mov)
=> NV-540 - After clearing notification name field - error is not shown again

apps/api/src/app/events/usecases/trigger-event/message-matcher.service.spec.ts, apps/api/src/app/events/usecases/trigger-event/message-matcher.service.ts
This change passes a string to lodash.get() instead of an array so that it is able to access nested data. For example, instead of calling `_.get(obj, ['subscriber', 'data.myKey'])`, we now call `_.get(obj, 'subscriber.data.myKey')`. 
Closes #2756, fixing a bug to allow filter steps to filter by nested data.
In the following screenshot, you can see that the notification has a step filter of (`subscriber.data.customKey`, `EQUALS`, `"customValue"`) and there is a user with custom data `{customKey: 'customValue'}`. When the notification is triggered, the user receives the notification.
=> fix: allow step filtering by nested payload/subscriber data

apps/webhook/src/shared/shared.module.ts, apps/webhook/src/webhooks/usecases/webhook/webhook.usecase.ts
Two tracking events so we can track how much provider webhooks is used.
To be able to understand usage of our provider webhook feature
=> feat: add analytics event to track usage of provider webhooks

apps/web/src/components/templates/notification-setting-form/TemplatePreference.tsx
copy text inside user preferences static no matter if on or off
Copy inside User Preference Editor
needs to be fixed and clear
Closes #2843
=> style: copy text static

apps/web/src/components/layout/components/PolishingBanner.tsx, docs/docs/community/run-locally.md, docs/docs/platform/inbound-parse-webhook.md, docs/docs/platform/templates.md
Add info for SaaS only feature in inbound parse webhook
Add triple curly braces faq in template page
Update port info for cummunity doc
Closes [NV-1623](https://linear.app/novu/issue/NV-1623)
Closes [NV-1676](https://linear.app/novu/issue/NV-1676)
=> fix: add info for saas only in inbound parse webhook

apps/api/src/app/change/e2e/promote-changes.e2e.ts, apps/api/src/app/change/usecases/get-changes/get-changes.usecase.ts, apps/api/src/app/change/usecases/promote-change-to-environment/promote-change-to-environment.usecase.ts, apps/api/src/app/change/usecases/promote-layout-change/promote-layout-change.use-case.ts, apps/api/src/app/layouts/usecases/create-default-layout-change/create-default-layout-change.command.ts, apps/api/src/app/layouts/usecases/create-default-layout-change/create-default-layout-change.usecase.ts, apps/api/src/app/layouts/usecases/create-layout/create-layout.use-case.ts, apps/api/src/app/layouts/usecases/index.ts, apps/api/src/app/layouts/usecases/set-default-layout/set-default-layout.use-case.ts, apps/api/src/app/layouts/usecases/update-layout/update-layout.use-case.ts, apps/web/src/components/changes/ChangesTableLayout.tsx, libs/dal/src/repositories/change/change.repository.ts, libs/dal/src/repositories/layout/layout.repository.ts, libs/shared/src/entities/change/change.interface.ts
- Makes default layout changes dependent
- Created a new change type: `DefaultLayout`
-
=> Nv 1576 make default layout changes dependent

apps/web/src/pages/changes/PromoteChangesPage.tsx
- Resets the page number on tab switch on the changes page
=> fix: reset page number on tab switch

.cspell.json, apps/api/src/app/events/services/mail-service/handlers/nodemailer.handler.ts, apps/web/cypress/tests/integration-store.spec.ts, libs/dal/src/repositories/integration/integration.entity.ts, libs/shared/src/consts/providers/credentials/provider-credentials.ts, libs/shared/src/consts/providers/provider.enum.ts, libs/shared/src/dto/integration/construct-integration.interface.ts, packages/application-generic/src/factories/mail/handlers/nodemailer.handler.ts, providers/nodemailer/README.md, providers/nodemailer/src/lib/nodemailer.provider.spec.ts, providers/nodemailer/src/lib/nodemailer.provider.ts
Introduces the ability for the users to override and set up TLS configurations.
To give configuration power to SMTP providers for our users and be able to integrate Novu.
=> feat(providers): add tls options to nodemailer

docs/docs/notification-center/react/react-components.md, packages/notification-center/src/i18n/lang.ts, packages/notification-center/src/i18n/languages/nb.ts
renaming `no` locale to `nb` 
date-fns [doesn't support](https://github.com/date-fns/date-fns/tree/main/src/locale) `no` locale. This pr will fix the Norwegian translation of the date/time distance in the widget.
=> fix: update and rename no.ts to nb.ts

apps/api/src/app/events/usecases/create-notification-jobs/create-notification-jobs.command.ts, apps/api/src/app/events/usecases/create-notification-jobs/create-notification-jobs.usecase.ts, apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts
I moved the template providers decryption out of the step generation loop when creating a notification for every subscriber.
I consider we were doing an expensive operation multiple times when we could just do it once for all the template steps. Downstream, the decryption is using synchronous calls to the `crypto` module (`createDecipheriv` functionality), so we were doing (number of subscribers * number of steps) synchronous calls. We can expect they might be resource expensive as being cryptographic functionalities so it seems sensible to only do the minimum needed to achieve our goals. And because for now, the flow is set to just have one template when triggering an event we can safely reuse the providers of said template for the different subscribers that will be passed in the `to` …
=> feat(api): move the providers decryption for the template out of loop

apps/api/src/app/topics/e2e/remove-subscribers.e2e.ts, libs/dal/src/repositories/topic/topic-subscribers.repository.ts
Fixes the issue: #2902 
When the subscriber is added to multiple topics the `POST /topics/:topic_key/subscribers/removal` endpoint removes him from all the topics, but should only remove from the exact topic by the `:topic_key`.
Fixes the above issue.
=> [NV-1759] fix(api): fixed remove subscriber from topic functionality

providers/sendinblue/src/lib/sendinblue.provider.ts
Fix for SendinBlue cc and bcc properties
Because we cannot send mails!
=> fix: optional cc and bcc in email creation

apps/api/src/app/shared/helpers/content.service.ts, apps/web/src/components/execution-detail/helpers.ts, libs/shared/src/entities/message-template/message-template.interface.ts
…n execution detail
content service does not iterate over the push title - vars are not saved for trigger and handlebars errors in title are not shown to user on update(allows submit with errors)
also - fix push icon not shown in execution steps in activity feed
=> fix: content service not iterating over push title 

apps/web/src/pages/templates/components/email-editor/ContentRow.tsx
- Fixes the page crash when clicking on the content row option at the bottom of the screen.
Issue Reproduction: 
https://user-images.githubusercontent.com/29251776/222141164-4fd68273-c551-4d17-a1cf-59527ce0b264.mov
Fixed: 
https://user-images.githubusercontent.com/29251776/222138955-b48dac25-2e19-4679-8625-861ab6edde67.mov
=> fix: force position top to avoid page crash

apps/web/Dockerfile
Static web apps, such as the React app being used by Novu do not need their `node_modules` at runtime. This allows for the ability to build in a `builder` container, then copy over only the static resources to a container that will serve the files.
Currently, `novu/web:0.12.0` is 2.42GB according to `docker image ls -a`. This change reduces the size of the container to 175MB, and keeps intact the features required for dynamic environment variable injection (upon its fix in #2943).
I am currently running this image (`ghcr.io/joeyeamigh/novu/web:slim`) in my environments, and it is working just as well as the live one. If someone knows something I don't about a system in the project that keeps this from being possible, let me know.
=> Feat/Fix: Reduce Size of Web Docker Container

packages/node/src/lib/subscribers/subscriber.interface.ts, packages/node/src/lib/subscribers/subscribers.spec.ts, packages/node/src/lib/subscribers/subscribers.ts
- adds the `unsetCredentials` method to subscribers
- Updates the tests to test the functionality of the new method
Closes https://github.com/novuhq/novu/issues/2043
Currently you need to do:
```javascript
await novu.subscribers.setCredentials('subscriberId', ChatProviderIdEnum.Slack, {
webhookUrl: undefined,
});
```
to unset credentials...
=> NV-2043 - add a way to unset a subcriber's credentials

libs/dal/package.json, package.json, pnpm-lock.yaml
=> chore(infra): remove octokit as unused dependency

packages/stateless/src/lib/provider/provider.interface.ts, providers/fcm/src/lib/fcm.provider.spec.ts, providers/fcm/src/lib/fcm.provider.ts
This PR introduces the `fcmOptions` (link [here](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.fcmoptions.md#fcmoptions_interface)) optional override for Firebase, as this allows us to implement analytics labels for Firebase tracking. 
Closes #2965
=> feat: Add fcmOptions to Firebase provider

providers/apns/src/lib/apns.provider.ts
Closes #2966 
Throws error only when the notification fails, and should be able to send success response on notification being delivered successfully
Notifications sent successfully were being marked as failed.
=> fix: only throw error if response contains any failed data

apps/api/Dockerfile, apps/inbound-mail/Dockerfile, apps/web/Dockerfile, apps/webhook/Dockerfile, apps/widget/Dockerfile, apps/ws/Dockerfile, libs/embed/Dockerfile, package.json, scripts/dev-environment-setup.sh
Homogenise the PNPM version all throughout the monorepo.
PNPM it was upgraded to 7.28.0 (https://github.com/novuhq/novu/blob/56ddf76a915aba4bb26c70bfef47ef6984b08f98/package.json#L4) but not in the Docker images and some scripts. This fixes that.
Also it is an investigation step to see why this CI check fails for a dependency update:
https://github.com/novuhq/novu/actions/runs/4373578609/jobs/7651925951
=> fix(infra): when upgrading to pnpm 7.28.0 we didn't update the images

_templates/provider/new/package.ejs.t
Adds back to provider template the dependency `npm-run-all`.
When I cleaned the template dependencies I deleted it thinking it wasn't used but it is necessary for the building stage of the providers.
=> fix(providers): add back to template npm-run-all

packages/stateless/src/lib/provider/provider.interface.ts, providers/fcm/src/lib/fcm.provider.spec.ts, providers/fcm/src/lib/fcm.provider.ts
Support adding additional options for FCM message
- ~FCM option with analytics_label~ It already done on #2979
- Priority for android message
- `apns` with additional headers include priority header, Ref https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
- Add test case for above changes
Closes #2233, #2965
- Update IPushOptions for new extra fields
- ~add fcmOptions~ It already done on #2979
=> FCM support add extra options

.cspell.json, apps/api/src/app/change/usecases/promote-notification-template-change/promote-notification-template-change.usecase.ts, apps/api/src/app/events/usecases/create-notification-jobs/create-notification-jobs.usecase.ts, apps/api/src/app/events/usecases/digest-filter-steps/digest-filter-steps-backoff.usecase.ts, apps/api/src/app/events/usecases/digest-filter-steps/digest-filter-steps-regular.usecase.ts, apps/api/src/app/events/usecases/digest-filter-steps/digest-filter-steps.command.ts, apps/api/src/app/events/usecases/digest-filter-steps/digest-filter-steps.usecase.ts, apps/api/src/app/message-template/usecases/create-message-template/create-message-template.usecase.ts, apps/api/src/app/message-template/usecases/update-message-template/update-message-template.usecase.ts, apps/api/src/app/notification-template/usecases/create-notification-template/create-notification-template.usecase.ts, libs/dal/src/repositories/message-template/message-template.entity.ts
Small refactor to aggregate the logic accordingly.
Inside of the use case that was in charge on deciding if a digest step should be created or not we were doing more things, like filtering the active steps for the notification, adding extra complexity to that use case.
These changes should facilitate the vision if we are committing to decisions on creating or not digest steps before we should.
=> feat(api): clarify the notification steps creation

packages/node/src/lib/events/events.interface.ts, packages/node/src/lib/events/events.ts
It adds optional `transactionId` to event request data.
To allow transactionId to be passed to event request rather than generating random id on every request.
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
=> NV-1793 - enable custom transactionId in trigger

docs/docs/channels/push/apns.md, docs/docs/channels/push/fcm.md
This adds the docs to help activate and integrate apns. It also improves the firebase set up documentation.
Docs is non-existent.
=> NV-1618 - Add Missing APNS Docs

docs/docs/channels/email/sparkpost.md
Add documentation for SparkPost provider
To show the user how to use the SparkPost provider on the Novu platform
Reference issue #80
=> feat(docs): add sparkpost provider documentation

.cspell.json, apps/api/src/app/topics/dtos/index.ts, apps/api/src/app/topics/dtos/topic-subscriber.dto.ts, apps/api/src/app/topics/e2e/get-topic-subscriber.e2e.ts, apps/api/src/app/topics/topics.controller.ts, apps/api/src/app/topics/use-cases/get-topic-subscriber/get-topic-subscriber.command.ts, apps/api/src/app/topics/use-cases/get-topic-subscriber/get-topic-subscriber.use-case.ts, apps/api/src/app/topics/use-cases/get-topic-subscriber/index.ts, apps/api/src/app/topics/use-cases/get-topic-subscribers/get-topic-subscribers.use-case.ts, apps/api/src/app/topics/use-cases/get-topic/get-topic.use-case.ts, apps/api/src/app/topics/use-cases/index.ts, docs/docs/platform/topics.md, libs/dal/src/repositories/topic/topic-subscribers.repository.ts, packages/node/src/lib/topics/topic.interface.ts, packages/node/src/lib/topics/topics.spec.ts, packages/node/src/lib/topics/topics.ts
Implement and endpoint that provided a topicKey and the external subscriber ID retrieves the relationship if existing or a 404 Not Found if any of both are not existing.
Implement it in Novu package.
Add tests and documentation.
We have been requested by users to provide with a way for them to check if a subscriber belongs to a certain topic. This could improve the engagement with the feature and traction of potential new users that could implement their use cases and use Novu.
=> feat(api): endpoint to check if subscriber belongs to a topic

README.md
Added Resend to email provider list in README, pointed to existing provider subdir
To keep email provider list up to date in README
N/A
=> Add Resend to email provider list in README

apps/web/src/components/digest-demo-flow/DigestDemoFlow.tsx, apps/web/src/pages/quick-start/components/layout/BodyLayout.tsx, apps/web/src/pages/quick-start/components/layout/FooterLayout.tsx, apps/web/src/pages/quick-start/components/layout/HeaderLayout.tsx
=> Style : onboarding paddings and centering

apps/web/src/components/layout/components/SideNav.tsx, apps/web/src/constants/routes.enum.ts, apps/web/src/pages/quick-start/components/NavButton.tsx, apps/web/src/pages/quick-start/components/QuickStartWrapper.tsx, apps/web/src/pages/quick-start/components/layout/BodyLayout.tsx, apps/web/src/pages/quick-start/components/layout/GetStartedLayout.tsx, apps/web/src/pages/quick-start/components/route/store.ts, apps/web/src/pages/quick-start/steps/FrameworkSetup.tsx, apps/web/src/pages/quick-start/steps/NotificationCenter.tsx, apps/web/src/pages/quick-start/steps/Setup.tsx, apps/web/src/pages/quick-start/steps/Trigger.tsx
Remove all the management of the steps history logic, switched it to the parent component to be responsible for the knowledge of what is the previous page, in addition, changed the route of '/quickstart/notification-center/trigger' to '/quickstart/notification-center/set-up/:framework/trigger' in order to have the indication from what page we got to the '.../trigger' route so we could manage the route back.
Due to the possibility of bugs (and maintaining overhead)
=> feat: remove onboarding history management

docs/docs/platform/subscribers.md
according to doc i was trying to delete user using "novu.subscribers.remove" but getting error that remove is not a function. so i have checked @novu/node repo and the function name was "delete" instead of "remove"
=> change method from remove to delete

apps/api/src/app/events/services/performance-service/index.ts
Prints the proper method name when calculating the averages for the marks we want to measure. So far was printing the same name. I introduced that bug.
Tested locally. Safe to merge. Tagging you to be aware.
Proper binding to the method name.
=> fix(api): publishing measures had wrong method names, always the same

packages/notification-center-vue/package.json, packages/notification-center-vue/src/index.ts, pnpm-lock.yaml
The `notification-center-vue` package has a dependency on the forked `floating-vue` library, which has an important fix applied. The original library is not maintained. 
The quick fix for use before was to as the link to a GH resource (tarball) in the dependencies list. But, this solution is not working well everywhere, for ex. some Indian ISPs are blocking downloads from the GH, resulting in the failed installation of the `notification-center-vue` package.
Now, we've forked the `floating-vue` library under the Novu org and released it on the NPM, so we can now install it normally through the NPM registry. And this PR is using that NPM package.
Context: https://discord.com/channels/895029566685462578/1083589887804067880
https://user-images.githubusercontent.com/2607232/226416626-3a982f40-f …
=> feat(notification-center-vue): use the novu forked floating-vue library

README.md
Removed the broken Jarvis link from the README ToC.
(apologies the PR body doesn't use the PR template, GH Codespaces created the PR automatically)
=> (docs/readme) removed broken jarvis link

apps/api/src/app/events/dtos/event-job.dto.ts, apps/api/src/app/events/dtos/index.ts, apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/api/src/app/events/services/workflow-queue/workflow.queue.service.spec.ts, apps/api/src/app/events/services/workflow-queue/workflow.queue.service.ts, apps/api/src/app/events/usecases/index.ts, apps/api/src/app/events/usecases/webhook-filter-backoff-strategy/index.ts, apps/api/src/app/events/usecases/webhook-filter-backoff-strategy/webhook-filter-backoff-strategy.command.ts, apps/api/src/app/events/usecases/webhook-filter-backoff-strategy/webhook-filter-backoff-strategy.usecase.ts
Extracts from the WorkflowService the logic to calculate the backoff strategy and it also helps to move a step forward to remove the ExecutionDetails dependency from it.
Keep on the work to make WorkflowService driven by dependency injection so the use cases injected drive the behaviour of it in a more formal clean architecture.
=> feat(api): create webhook filter backoff strategy use case

apps/api/package.json, apps/api/src/app/events/services/workflow-queue/workflow.queue.service.spec.ts, apps/api/src/app/events/services/workflow-queue/workflow.queue.service.ts, apps/inbound-mail/package.json, apps/webhook/package.json, apps/ws/Dockerfile, libs/testing/package.json, packages/application-generic/package.json, packages/application-generic/src/logging/index.ts, packages/application-generic/src/services/bull-mq.service.ts, pnpm-lock.yaml
We have mismatched version between the difference services. Updated all versions to be the same.
=> fix: upgrade bullmq versions

apps/api/src/app/events/services/sms-service/handlers/infobip.handler.ts
Updates the provider id from `infobip` to `infobip-sms` in `InfobipSmsHandler` constructor.
Fixes https://github.com/novuhq/novu/issues/3083
none
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> NV-1915 - 🐛 Bug Report: infobip sms provider error

docs/docs/community/create-provider.md
Updates the provider name CLI prompt message on docs.
It seems that the standard case style for the CLI provider name changed and the docs seems outdated.
So I'm updating just to avoid any mistake.
N/A
=> refactor(docs) Update CLI prompt message

apps/web/src/pages/integrations/IntegrationsStorePage.tsx
- Added a check before json stringifying the value to avoid showing the empty string in the input textbox. ( as per screenshot)
- Added the missing keys in the credentials interface under the store page.
- Bug was introduced in the following PR https://github.com/novuhq/novu/pull/3048#issuecomment-1491673914 
- API docs doesn't contains following credentials keys ( `requireTls`, `ignoreTls` and `tlsOptions` ) for Integrations APIs
=> fix: added check for tls options before json stringify to avoid empty string

apps/api/src/app/events/e2e/process-subscriber.e2e.ts, apps/api/src/app/events/services/workflow-queue/trigger-handler-queue.service.ts, apps/api/src/app/shared/services/cache/cache.service.ts, apps/api/src/app/shared/services/in-memory-provider/in-memory-provider.service.ts, apps/api/src/app/shared/services/in-memory-provider/index.ts, apps/api/src/app/shared/services/in-memory-provider/redis-provider.ts, apps/api/src/app/shared/shared.module.ts, apps/api/src/app/widgets/e2e/get-unseen-count.e2e.ts
Created a new service that isolates the implementation of any in-memory provider (in this case `ioredis`) so we can easily swap the mode (from normal provider to cluster mode) or to even swap a provider as needed. It will also would allow us to have different providers available depending on environment.
So far we leave it connected only to the cache service.
It is one of the first steps of the performance improvements by targeting to move cache service and distributed lock service to a Redis cluster setting.
=> feat(api): in-memory provider service

apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/widgets/dtos/mark-message-action-as-seen.dto.ts
Add `MarkMessageActionAsSeenDto` 
Fixes [NV-1180](https://linear.app/novu/issue/NV-1180)
=> feat: add mark message action as seen dto

libs/dal/src/repositories/message/message.repository.ts, libs/dal/src/repositories/notification/notification.repository.ts
leverage the mongo read replicas instead of making all of the queries and commands to the primary replica
=> feat: add secondary preferred

apps/api/src/app/events/services/distributed-lock-service/index.ts, apps/api/src/app/events/usecases/add-job/add-digest-job.usecase.ts, apps/api/src/app/shared/services/distributed-lock/distributed-lock.service.spec.ts, apps/api/src/app/shared/services/distributed-lock/distributed-lock.service.ts, apps/api/src/app/shared/services/in-memory-provider/in-memory-provider.service.ts, apps/api/src/app/shared/services/in-memory-provider/redis-provider.ts, apps/api/src/app/shared/shared.module.ts
Makes the distributed lock service to reuse the in-memory provider service.
We plan to implement Redis cluster as in-memory provider service for the Cache service and the Distributed Lock service. So far we had both connections to the in-memory provider (ioredis) separatedly even if using the same instance.
=> feat(api): distributed lock service should reuse in memory provider svc

docker/Readme.md, docker/local/Readme.md
Revert reference to redis cluster in docker get started readme
=> fix(docker): revert docker readme change

apps/api/src/app/inbound-parse/inbound-parse.module.ts
- Adds the missing import for the "AuthModule" inside `inbound-parse.module.ts`
- It will fix the "internal server error" when accessing the endpoint
=> fix: Add missing import for AuthModule

apps/api/src/app/events/usecases/send-message/send-message-in-app.usecase.ts, apps/api/src/app/messages/usecases/get-messages/get-messages.usecase.ts, apps/api/src/app/widgets/usecases/get-notifications-feed/get-notifications-feed.usecase.ts, libs/dal/src/repositories/message/message.entity.ts, libs/dal/src/repositories/message/message.repository.ts, libs/dal/src/repositories/message/message.schema.ts
- Serves the latest available avatar of the actor while fetching messages/feeds
- Previously, during the queue job processing the avatar was fetched and served to the notification list.
This caused a scenario where after updating the avatar, the notification list will still show the old avatar for older messages
=> fix: get latest version of actor details while retreiving messages/feed list

apps/web/src/pages/quick-start/steps/GetStarted.tsx
Scrolls to the respective `integration store's section` to which the user want to integrate when opening the `integration store modal`.
Fixes [#3129](https://github.com/novuhq/novu/issues/3129)
https://www.awesomescreenshot.com/video/16219996?key=ab0e9accd2560833668fbb48cde6e36e
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> NV-1898 - Missing scrollTo channel in quickstart -> configure provider

apps/api/src/app/events/usecases/message-matcher/message-matcher.usecase.ts, apps/api/src/app/execution-details/usecases/get-execution-details/get-execution-details.usecase.ts, libs/dal/src/repositories/execution-details/execution-details.repository.ts, libs/dal/src/repositories/execution-details/execution-details.schema.ts, libs/dal/src/types/enforce.ts
Why? (Context)
We want to remove as many inefficient indexs and queries as possible.
Stop using single indexes on the mongoose key implementation
Add compound indexes for common queries and patterns using MongoDB index best practices
Remove unused indexes from MongoDB atlas after implementing the new compound indexes
=> Index Cleanup -  Execution Details

apps/api/src/app/notifications/dtos/activity-stats-response.dto.ts, apps/api/src/app/notifications/e2e/get-activity-stats.e2e.ts, apps/api/src/app/notifications/usecases/get-activity-stats/get-activity-stats.usecase.ts, apps/web/src/pages/activities/components/ActivityStatistics.tsx, libs/dal/src/repositories/base-repository.ts, libs/dal/src/repositories/notification/notification.repository.ts
This removes the yearly aggregation from the stats endpoint that causes performance issues when doing the queries against notification collection. 
For larger organizations this results in a very long operations, we will review our analytical approach there in the future, but for now disabling this to avoid bottlenecks.
=> feat: remove yearly stats due to performance issues

apps/api/src/app/events/e2e/trigger-event.e2e.ts, libs/dal/src/repositories/base-repository.ts, libs/dal/src/repositories/message/message.entity.ts, libs/dal/src/repositories/message/message.schema.ts, libs/dal/src/repositories/notification/notification.entity.ts, libs/dal/src/repositories/notification/notification.schema.ts
WIP : an initial version of setting a ttl index for Message and Notification schemes. 
I will of course, improve the function of expire date calculation- I first want to progress on how we will handle a notification/job that is delayed/ not completed on the time of its creation. And therefore its expiration date should take that into account.
=> Initial setting of TTL index

apps/api/src/app/events/usecases/add-job/add-delay-job.usecase.ts, apps/api/src/app/events/usecases/queue-next-job/queue-next-job.usecase.ts, apps/api/src/app/events/usecases/send-message/digest/get-digest-events.usecase.ts, apps/api/src/app/events/usecases/trigger-event/trigger-event.usecase.ts, libs/dal/src/repositories/job/job.repository.ts, libs/dal/src/repositories/job/job.schema.ts
Why? (Context)
We want to remove as many inefficient indexs and queries as possible.
Stop using single indexes on the mongoose key implementation
Add compound indexes for common queries and patterns using MongoDB index best practices
Remove unused indexes from MongoDB atlas after implementing the new compound indexes
=> Index Cleanup - Job

providers/ses/src/lib/ses.provider.spec.ts, providers/ses/src/lib/ses.provider.ts
- This PR sets the replyTo parameter in nodemailer SES transport.
- `replyTo` wasn't working for AWS SES provider. This PR fixes that bug.
Closes #3122
=> fix: add reply to support for aws ses provider

apps/api/src/app/widgets/widgets.controller.ts, docs/docs/notification-center/FAQ.md, docs/docs/notification-center/angular-component.md, docs/docs/notification-center/custom-styling.md, docs/docs/notification-center/headless/_category_.json, docs/docs/notification-center/headless/api-reference.md, docs/docs/notification-center/headless/headless.md, docs/docs/notification-center/iframe-embed.md, docs/docs/notification-center/vue-component.md, docs/docs/notification-center/web-component.md, packages/client/src/api/api.service.ts, packages/headless/src/lib/headless.service.test.ts, packages/headless/src/lib/headless.service.ts, packages/headless/src/lib/types.ts, packages/headless/src/utils/query-keys.ts
- Updates the headless package with new features
- Fixed type errors
- new test cases
- docs
=> Nv 1890 novuheadless library

docs/docs/notification-center/headless/api-reference.md, docs/docs/notification-center/headless/headless-service.md, packages/headless/src/lib/headless.service.test.ts, packages/headless/src/lib/headless.service.ts
- adds an example usage for the socket listeners on the quick start page.
- adds the listener for unread_count.
- updates the API reference doc with the unread_count
- test for listenUnreadCountChange
=> Nv 2109 add example for socket listener

apps/api/src/app/shared/services/distributed-lock/distributed-lock.service.spec.ts, apps/api/src/app/shared/services/in-memory-provider/elasticache-cluster-provider.ts, apps/api/src/app/shared/services/in-memory-provider/in-memory-provider.service.spec.ts, apps/api/src/app/shared/services/in-memory-provider/in-memory-provider.service.ts, apps/api/src/app/shared/services/in-memory-provider/redis-cluster-provider.ts
A functionality for the in-memory provider service to await to operate until it is ready.
Also fix some tests that weren't properly designed.
We have been observing some flakiness in tests related to the implement of Redis cluster mode and therefore in services dependent of the InMemoryProvider service such the DistributedLock service.
We need to add a functionality for testing that can be used to wait to execute the tests when the in-memory providers are ready to operate to avoid race conditions and flakey tests.
=> feat(cluster): implement wait until readiness functionality

apps/api/src/app/events/services/distributed-lock-service/index.ts, apps/api/src/app/events/usecases/add-job/add-digest-job.usecase.ts, apps/api/src/app/shared/services/in-memory-provider/in-memory-provider.service.ts, apps/api/src/app/shared/shared.module.ts
Previously the caching service was initialized 3 times because it was injected another un-needed time.
I'm concerned that we have a split connection for some of the redis calls.
=> refactor: remove duplicate cache service initialization

packages/application-generic/jest.config.js
Instructs Jest to use Axios CJS module.
Allows the Application Generic package tests to be run in the local environment. Some of the test suites were failing because they used Axios and Jest was not correctly instructed to use the CJS package of Axios.
=> fix(app-generic): allow jest to use axios using cjs

.github/ISSUE_TEMPLATE/docs_feedback.yml, README.md
=> fix: add new providers in readme

apps/web/src/pages/activities/components/ActivityItem.tsx, libs/dal/src/repositories/notification/notification.repository.ts
Fix - show the user's defined id for the subscriber (subscriberId). Currently in Activity Feed we are showing novu's id for that subscriber(subscriber._id).
=> Activity Feed: show subscriberId instead of novu's internal id 

docs/docs/channels/email/infobip.md
Add Infobip provider documentation
=> feat(docs): Add infobip provider documentation

packages/application-generic/src/services/cache/cache.service.ts, packages/application-generic/src/services/cache/invalidate-cache.service.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts, packages/application-generic/src/services/in-memory-provider/redis-cluster-provider.ts
Adds extra logging for the Cluster Pipeline execution inside of the Cache Service.
We were receiving errors in Sentry that weren't captured in NewRelic.
=> feat(app-generic): add cluster pipeline logging in cache service

libs/dal/src/repositories/subscriber/subscriber.schema.ts
Why? (Context)
We want to remove as many inefficient indexs and queries as possible.
Stop using single indexes on the mongoose key implementation
Add compound indexes for common queries and patterns using MongoDB index best practices
Remove unused indexes from MongoDB atlas after implementing the new compound indexes
=> Index Cleanup - Subscriber

providers/outlook365/src/lib/outlook365.provider.ts
Fix - office 365 email provider failing. 
1. password to pass
2. weren't returning the created mail data
=> fix: office 365 email provider is failing

apps/api/src/app/change/changes.controller.ts, apps/api/src/app/channels/channels.controller.ts, apps/api/src/app/environments/environments.controller.ts, apps/api/src/app/events/events.controller.ts, apps/api/src/app/execution-details/execution-details.controller.ts, apps/api/src/app/feeds/feeds.controller.ts, apps/api/src/app/inbound-parse/inbound-parse.controller.ts, apps/api/src/app/integrations/dtos/get-channel-type-limit.sto.ts, apps/api/src/app/integrations/integrations.controller.ts, apps/api/src/app/layouts/layouts.controller.ts, apps/api/src/app/messages/messages.controller.ts, apps/api/src/app/notification-groups/notification-groups.controller.ts, apps/api/src/app/notification-template/notification-template.controller.ts, apps/api/src/app/notifications/notification.controller.ts, apps/api/src/app/shared/dtos/data-wrapper-dto.ts, apps/api/src/app/shared/framework/response.decorator.ts, apps/api/src/app/storage/storage.controller.ts, apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/topics/topics.controller.ts, apps/api/src/app/user/user.controller.ts
Add DataWrapperDto
Add ApiResponse custom decorator
Fix extra data field not showing in swagger 
Add DataBooleanDto and DataNumberDto
=> feat: add api response custom decorator

apps/api/package.json, apps/web/cypress/tests/changes.spec.ts, packages/application-generic/package.json, pnpm-lock.yaml
Removes @types/handlebars package references, as these do not need to be installed according to https://www.npmjs.com/package/@types/handlebars
=> chore(deps): remove @types/handlebars

apps/api/src/app/change/e2e/promote-changes.e2e.ts, apps/api/src/app/notification-template/usecases/change-template-active-status/change-template-active-status.usecase.ts
This PR adds a merge of status change to parent change, which will help the user to promote the changes in historical order.
At the moment status changes create separate changes which can cause issues if the order of the promotions is different from the historical order.
Closes https://github.com/novuhq/novu/issues/3287
What change does this PR introduce?
This PR adds a merge of status change to parent change, which will help the user to promote the changes in historical order.
=> fix: merge template status to parent change

packages/notification-center/src/components/notification-center/components/AppContent.tsx
- removed the media query code added recently. It was considering the width of the iframe instead of the window.
Still not sure about the width increase behavior on hover/click.
https://user-images.githubusercontent.com/29251776/235912776-5b3122e2-03bc-47fa-9f0d-91a302b013b2.mov
=> fix: iframe nc width issue

apps/web/src/pages/settings/tabs/EmailSettings.tsx
Allow updating allowed domains on prod env as well.
So users could add addition dns environments for their domain.
=> Remove readonly on allowed domains

package.json, packages/application-generic/src/factories/mail/handlers/mailjet.handler.ts, providers/mailjet/src/lib/mailjet.provider.spec.ts, providers/mailjet/src/lib/mailjet.provider.ts
Add senderName option in mailjet provider
With mailjet as active integration, sender name was not visible in email
=> fix: add sender name option in mailjet

.gitmodules, enterprise/README.md, lerna.json, package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Implement Git Submodules for the private repository
=> feat: implement git submodules

packages/application-generic/src/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts
We query message templates just to get the step types. I don't see why it is needed.
=> feat: remove query to message templates

apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts
validate notification group on template id.
in order to make sure we won't get edge cases when we get notification groups from other environments.
=> feat: validate notification group

packages/application-generic/src/usecases/process-subscriber/process-subscriber.usecase.ts
Fetch subscriber from cache in processing of subscriber after trigger. Also, added it to be read from secondary.
=> feat: add caching for subscriber in trigger

packages/application-generic/src/factories/mail/handlers/mailgun.handler.ts
modify the integration credentials DTO to include the baseUrl property.
NV-2222 #3342
Fixes https://github.com/novuhq/novu/issues/3342
To let users with `EU` region domain use the mail gun integration smoothly
=> feat(integrations): Add baseUrl to mailgun-handler

apps/api/src/bootstrap.ts
This increases the timeout of the api server to be greater then the alb.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout
=> fix(alb-timeout): increase server timeout above the alb timeout NV-2265

packages/node/src/lib/subscribers/subscriber.interface.ts, packages/node/src/lib/subscribers/subscribers.spec.ts
According to the OpenAPI documentation and testing, the `feedIdentifier` param is [optional](https://github.com/novuhq/novu/blob/next/apps/api/src/app/subscribers/dtos/get-in-app-notification-feed-for-subscriber.dto.ts#L9) when fetching a subscriber's notification feed.
The node client typings have this parameter as required. This updates the node client typings to reflect the API definition, so that the param can be excluded.
The `feedIdentifier` is an optional parameter, and the API accepts an empty object as the second argument to `getNotificationsFeed`, but it requires suppressing the following typescript error:
```
Argument of type '{}' is not assignable to parameter of type 'IGetSubscriberNotificationFeedParams'.
Property 'feedIdentifier' is missing in type '{}' but required in type …
```
=> fix: Update node subscriber feed params typings

packages/application-generic/src/services/cache/interceptors/cached-entity.interceptor.ts, packages/application-generic/src/services/cache/interceptors/cached-query.interceptor.ts, packages/application-generic/src/services/cache/interceptors/cached.interceptor.ts
Improves the logging and information provided in the logging for the CacheService.
We are experiencing problems with the Elasticache instances when load testing in DEV that are returning some auto pipelining errors in the Cache Service. As it is right now is hard to understand where the potential problem comes from so I am trying to improve the information we have at hand to be able to identify if there is any codebase problem that throws those errors at high loads, before digging deeper in the investigation of the infra resources.
=> feat(infra): improve cache service logging

docker/kubernetes/kustomize/env-dev, docker/kubernetes/kustomize/kustomization.yaml
- Add missing worker resources
- Add missing env
1. Add missing worker resources in kustomization.yaml.
2. Add missing `REACT_APP_API_URL` env.
- Worker resource is missing when running `kubectl apply -f ./kustomize`
- When deploying to custom api URL, `web` app was still pointing to `http://localhost:3000`
=> Add missing worker resources.

apps/web/src/api/hooks/notification-templates/useTemplateFetcher.ts, apps/web/src/design-system/tooltip/Tooltip.tsx, apps/web/src/pages/templates/components/StepNameInput.tsx, apps/web/src/pages/templates/components/TemplateEditor.tsx, apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx, apps/web/src/pages/templates/components/email-editor/EmailInboxContent.tsx, apps/web/src/pages/templates/components/email-editor/EmailMessageEditor.tsx, apps/web/src/pages/templates/components/formTypes.ts, apps/web/src/pages/templates/components/notificationTemplateSchema.ts, apps/web/src/pages/templates/components/templateToFormMappers.ts, apps/web/src/pages/templates/components/useTemplateController.ts, apps/web/src/pages/templates/filter/Filters.cy.tsx, apps/web/src/pages/templates/filter/Filters.tsx, apps/web/src/pages/templates/shared/errors.ts, apps/web/src/pages/templates/workflow/DelayMetadata.tsx, apps/web/src/pages/templates/workflow/DigestMetadata.cy.tsx, apps/web/src/pages/templates/workflow/DigestMetadata.tsx, apps/web/src/pages/templates/workflow/RegularDigestMetadata.tsx, apps/web/src/pages/templates/workflow/TimedDigestMetadata.tsx, apps/web/src/pages/templates/workflow/digest/BackOffFields.tsx, apps/web/src/pages/templates/workflow/digest/ScheduleMonthlyFields.tsx, apps/web/src/pages/templates/workflow/digest/TimedDigestWillBeSentHeader.tsx, apps/web/src/pages/templates/workflow/digest/WillBeSentHeader.tsx, apps/web/src/pages/templates/workflow/workflow/FlowEditor.tsx, apps/web/src/utils/pluralize.ts, libs/shared/src/dto/message-template/message-template.dto.ts, libs/shared/src/dto/notification-templates/notification-template.dto.ts
Improved the timed digest form:
- updated form schema
- the digest/delay step metadata in the form state is split between `digestMetadata` and `delayMetadata`;
- independent form state for the different digest tabs:
- regular and timed
- min, hour, daily, weekly, monthly; 
- thanks to this the values typed in the form are persisted when switching tabs
- default value set on blur when the value is empty: regular digest - amount, backoff amount; timed digest - amount, at time
- improved "Will be sent" field accordion header
- code split into separate components
- added missed default values
This is a part of the Timed Digest PRD.
https://github.com/novuhq/novu/assets/2607232/88e93618-baf4-451e-9c9d-e945e3c4b921
https://github.com/novuhq/novu/assets/2607232/5047d046-db79-4c2c-8752-95e651aaddd …
=> fix(web): improved timed digest form behaviour

packages/notification-center/src/hooks/useFetchNotifications.ts, packages/notification-center/src/hooks/useNotifications.test.tsx, packages/notification-center/src/shared/interfaces/index.ts
Adds an optional parameter  `page` to the `refetch` function in the `notification-center` which  enables the user to `refetch` the notifications for a specific page, rather than resetting the page to `0`.
This change enables the user to `refetch` the notifications for a specific page, which means they can view the notifications from that point on without having to load possibly multiple pages.
Closes: https://github.com/novuhq/novu/issues/2561
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
=> NV-1557 🚀 Feature: Allow pagination handling in refetch method

packages/node/src/lib/notification-template/notification-template.spec.ts, packages/node/src/lib/notification-template/notification-template.ts
- Also adding additional unit tests for page and limit on Getting All Notification templates
Just when I was trying to use the `novu/node` package and getting all templates.. I found that I made an error in making the SDK last year that Getting all the notification templates was throwing..
```node
import { Novu } from '@novu/node';
const novu = new Novu('<API_KEY>');
async function main() {
const result = await novu.notificationTemplates.getAll();
console.log(result.data);
}
main();
```
No issue is open currently for this...
Output of the above code
=> fix(novu/node): Get all Notification templates without any parameter

.gitmodules, packages/application-generic/package.json, packages/application-generic/src/services/calculate-delay/calculate-delay.service.ts, packages/application-generic/src/services/calculate-delay/timed-digest-delay.service.spec.ts, packages/application-generic/src/services/calculate-delay/timed-digest-delay.service.ts, pnpm-lock.yaml
We've decided to move the calculations for the timed digest delay to the main repo. This is what is this PR about.
Tested it locally and it works fine.
=> chore(application-generic): moved the timed digest delay calculations

docs/docs/channels/push/apns.md
changes link from [developer.apple.com.](https://developer.apple.com.) to [developer.apple.com](https://developer.apple.com) in [APNs docs](https://docs.novu.co/channels/push/apns/).
because we don't want invalid links in docs :)
=> fix: corrected apple dev link in apns docs

apps/web/cypress/tests/digest-playground.spec.ts, apps/web/cypress/tests/notifications.spec.ts, apps/web/src/api/hooks/notification-templates/index.ts, apps/web/src/api/hooks/notification-templates/useFetchBlueprints.ts, apps/web/src/api/query.keys.ts, apps/web/src/design-system/popover/Popover.tsx, apps/web/src/pages/quick-start/steps/DigestPreview.tsx, apps/web/src/pages/templates/TemplatesListNoData.tsx, apps/web/src/pages/templates/TemplatesListPage.tsx, apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx, apps/web/src/pages/templates/components/templates-store/TemplatesStoreModal.tsx, apps/web/src/pages/templates/constants.tsx, apps/web/src/pages/templates/hooks/useTemplatesStoreModal.tsx
When there is no data on the Notification Templates page we will show the "empty state" component that allows you to create a blank template, pick the most popular one, or browse the Templates Store modal for one.
Templates Store PRD.
https://github.com/novuhq/novu/assets/2607232/ab12a2ac-aabd-45e8-80a5-267a1aa4592c
https://github.com/novuhq/novu/assets/2607232/f5dab96b-a273-4cb6-8c4d-1c4d79169171
https://github.com/novuhq/novu/assets/2607232/7572458c-74b5-4302-a7e0-97cf651387e5
=> feat(web): templates store - templates page when there is no data show create template tiles

apps/api/src/app/notifications/notification.controller.ts, apps/api/src/app/notifications/usecases/get-activity-feed/get-activity-feed.command.ts, apps/api/src/app/notifications/usecases/get-activity-feed/get-activity-feed.usecase.ts, apps/web/src/pages/activities/ActivitiesPage.tsx, libs/dal/src/repositories/subscriber/subscriber.repository.ts
=> fix: emails null condition

apps/api/src/app/blueprint/blueprint.controller.ts, apps/api/src/app/blueprint/dto/get-blueprint.response.dto.ts, apps/api/src/app/blueprint/dto/grouped-blueprint.response.dto.ts, apps/api/src/app/blueprint/usecases/create-blueprint-notification-template/create-blueprint-notification-template.command.ts, apps/api/src/app/blueprint/usecases/create-blueprint-notification-template/index.ts, apps/api/src/app/blueprint/usecases/create-blueprint/create-blueprint.command.ts, apps/api/src/app/blueprint/usecases/create-blueprint/create-blueprint.usecase.ts, apps/api/src/app/blueprint/usecases/create-blueprint/index.ts, apps/api/src/app/blueprint/usecases/get-blueprint-notification-template/index.ts, apps/api/src/app/blueprint/usecases/get-blueprint/get-blueprint.command.ts, apps/api/src/app/blueprint/usecases/get-blueprint/get-blueprint.usecase.ts, apps/api/src/app/blueprint/usecases/get-blueprint/index.ts, apps/api/src/app/blueprint/usecases/get-blueprints/get-grouped-blueprints.command.ts, apps/api/src/app/blueprint/usecases/get-blueprints/get-grouped-blueprints.usecase.ts, apps/api/src/app/blueprint/usecases/get-blueprints/index.ts, apps/api/src/app/blueprint/usecases/index.ts, apps/api/src/app/change/usecases/promote-notification-template-change/promote-notification-template-change.usecase.ts, libs/dal/src/repositories/notification-template/notification-template.repository.ts, libs/shared/src/entities/notification-group/index.ts, libs/shared/src/entities/notification-group/notification-group.interface.ts, libs/shared/src/index.ts
Adds get grouped by category blueprint list.
refactored some old code.
switched to fetch by prod env and not the organization.
So the client could get all the available blueprints.
=> NV-2336 - Template Store -Add grouped by category blueprints

apps/web/cypress/global.d.ts, apps/web/cypress/plugins/index.ts, apps/web/cypress/support/commands.ts, apps/web/cypress/tests/notification-editor/create-notification.spec.ts, apps/web/cypress/tests/notification-editor/main-functionality.spec.ts, apps/web/cypress/tests/notification-editor/steps-actions.spec.ts, apps/web/cypress/tests/start-from-scratch-tour.spec.ts, apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx, apps/web/src/pages/templates/components/useTemplateController.ts, libs/testing/src/user.service.ts, libs/testing/src/user.session.ts
This PR fixes the issue that happens when visiting the template editor twice for the same template. Currently, the form state is not "set", which results in the template steps not being loaded into the workflow. 
Also, there is another issue, like when the template is updated and the user navigates to the templates list page and back, then the old template state is shown.
This PR fixes both issues.
Fixes the above issue.
https://github.com/novuhq/novu/assets/2607232/c3d460b3-e78b-4e85-afb7-8b4b802c6631
https://github.com/novuhq/novu/assets/2607232/0b3891ab-49cc-498c-a72e-f7237b4348f2
=> [NV-2360] fix(web): fixed the issue when visiting the same workflow template editor twice

packages/application-generic/src/factories/push/handlers/apns.handler.ts
Add default value for apns `production` option. Undefined value leads to unexpected behaviour.
Closes #3416 - everything is well described in this issue
https://github.com/node-apn/node-apn#connecting
> By default, the provider will connect to the sandbox unless the environment variable NODE_ENV=production is set
Basically when user creates APNs integration, by default it creates credentials where `secure` is optional field so it's undefined when value not specified (`secure` field is used for `production` option for `node-apn`). So when `secure` is undefined, then `node-apn` package uses `NODE_ENV` to determine if production is true or false. It may lead to scenario where user has production set to undefined (in GUI it's switch which indicates that production should be disabled) but Novu …
=> fix: apns production option

README.md
A hyperlink to the Python SDK
There appears to be an SDK that supports Python. Initially I avoided using Novu because of the lack of Python support but now that I found it I will give it a try and do what I can to support the Python SDK.
=> Add Python to the list of available SDKs in the README

apps/api/src/app/feature-flags/services/feature-flags.service.ts, apps/api/src/app/feature-flags/services/launch-darkly.service.ts, apps/api/src/app/feature-flags/types/index.ts, apps/api/src/app/feature-flags/use-cases/get-feature-flag/get-feature-flag.command.ts, apps/api/src/app/feature-flags/use-cases/get-feature-flag/get-feature-flag.use-case.ts
Adds mapping for the different potential contexts we might have for the feature flags (organization, environment, user).
We need to adapt Novu's context to Launch Darkly's one.
I am missing for now adding other contexts such as version and region that were discussed but we still don't have the implementation for them in the apps. The implementation of the contexts in this PR should be enough to give an idea how to implement them in the future.
=> feat(api): implement mappers for the different contexts in feature flags

.github/workflows/dev-deploy-web.yml, .github/workflows/prod-deploy-web.yml, apps/api/src/app/feature-flags/types/index.ts, apps/web/package.json, apps/web/src/App.tsx, apps/web/src/config/index.ts, apps/web/src/hooks/index.ts, apps/web/src/hooks/useFeatureFlags.ts, libs/shared/src/types/feature-flags/index.ts, libs/shared/src/types/index.ts, pnpm-lock.yaml
Implements Launch Darkly React client SDK and the feature flag needed for the Template Store feature.
We had the implementation in the backend but we needed the frontend implementation.
=> feat(web): implement is template store enabled feature flag in web

apps/api/src/app/auth/auth.controller.ts
Fixing the redirect vulnerability in github oauth endpoint.
=> feat: add check for at signs in redirect url

packages/node/src/index.ts
This PR exports additional enums and types that are important when building programmatic resource generation as these types facilitate the type-safety.
I'm open to suggestions if this doesn't feel like the right thing to do but I would like to access as much as possible the underlying types references
Closes #3442
=> feat: Export additional types and enums from sdk

apps/web/src/pages/templates/TemplatesListPage.tsx
Add loader to template list & no templates
So the user will see the loader while the data is fetching, and after it is fetched we can show the data/skeletons 
Before
https://www.loom.com/share/133cd8324756431597d1f1e2f6e0cd88
After 
https://www.loom.com/share/0022387b3b7247af9f3eb21764bb383f
=> Template Store - add create template from popular tests

apps/api/src/app/widgets/usecases/mark-all-messages-as/mark-all-messages-as.usecase.ts, apps/api/src/app/widgets/widgets.controller.ts, docs/docs/notification-center/react/api-reference.md, packages/notification-center/src/components/notification-center/components/FeedsTabs.tsx, packages/notification-center/src/components/notification-center/components/layout/header/Header.tsx, packages/notification-center/src/components/popover-notification-center/components/Popover.tsx, packages/notification-center/src/hooks/useMarkNotificationAsRead.ts, packages/notification-center/src/hooks/useMarkNotificationAsSeen.ts, packages/notification-center/src/hooks/useNotifications.test.tsx, packages/notification-center/src/shared/interfaces/index.ts, packages/notification-center/src/store/notifications-provider.context.tsx
1. Changed:- 
markAllNotificationsAsRead => markFetchedNotificationsAsRead
markAllNotificationsAsSeen => markFetchedNotificationsAsSeen
markAllNotificationsAsReadByFeed => markAllNotificationsAsRead
2. Added:- 
markAllNotificationsAsSeen
3. Update Docs
=> fix: update naming of markAllNotifications methods in react NC

apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts
Add digest data and subscriber to push payload that are sent to provider
To enable the receiver of the webhook push to use the raw digest and subscriber data
=> feat: add digest and subscriber to push send payload

docs/docs/community/run-locally.md
There are two ```REDIS_DB_INDEX``` keys
I guess it should be only one key..
=> docs(run-locally.md): duplicate REDIS_DB_INDEX key

apps/api/src/app/change/usecases/promote-message-template-change/promote-message-template-change.ts, apps/api/src/app/feeds/e2e/delete-feed.e2e.ts, apps/api/src/app/message-template/usecases/delete-message-template/delete-message-template.command.ts, apps/api/src/app/message-template/usecases/delete-message-template/delete-message-template.usecase.ts, apps/api/src/app/message-template/usecases/index.ts, apps/api/src/app/notification-template/e2e/delete-notification-template.e2e.ts, apps/api/src/app/notification-template/usecases/delete-notification-template/delete-notification-template.usecase.ts, apps/api/src/app/notification-template/usecases/update-notification-template/update-notification-template.usecase.ts, apps/web/src/pages/integrations/components/NovuProviderBase.tsx, apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx, libs/dal/src/repositories/message-template/message-template.entity.ts, libs/dal/src/repositories/message-template/message-template.repository.ts, libs/dal/src/repositories/message-template/message-template.schema.ts
- Delete the message templates and add them to the changes upon deletion of the Notification template
=> Nv 2215 delete messagetemplates of deleted templates

docker/kubernetes/kustomize/env-dev, docker/kubernetes/kustomize/kustomization.yaml, docker/kubernetes/kustomize/mongodb-deployment.yaml, docker/kubernetes/kustomize/mongodb-service.yaml
add mongodb
We don't have mongodb on kubernetes
=> add mongodb

docs/docs/community/run-locally.md
Incorrect production env value when I try to deploy.
There are incorrect env for production on Set up your environment variables section. The production value of `NODE_ENV` should be `production` instead of `prod`.
Closes #3568
You can search `NODE_ENV` and `REACT_APP_ENVIRONMENT` to check.
https://github.com/search?q=repo%3Anovuhq%2Fnovu%20NODE_ENV&type=code
=> fix: update prod `env` value in  `run-locally.md`

apps/api/src/app/events/dtos/trigger-event-request.dto.ts, apps/api/src/app/events/dtos/trigger-event-to-all-request.dto.ts, apps/api/src/app/events/e2e/trigger-event-topic.e2e.ts, apps/api/src/app/events/events.controller.ts, apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.command.ts, apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.e2e.ts, apps/api/src/app/events/usecases/map-trigger-recipients/map-trigger-recipients.use-case.ts, apps/api/src/app/events/usecases/parse-event-request/parse-event-request.command.ts, apps/worker/package.json, apps/worker/src/app/workflow/usecases/message-matcher/types.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts, libs/shared/src/dto/events/event.interface.ts, libs/shared/src/dto/subscriber/subscriber.dto.ts, libs/shared/src/entities/subscriber/subscriber.interface.ts, libs/shared/src/types/events/index.ts, libs/shared/src/types/index.ts, libs/shared/src/types/subscriber/index.ts, libs/testing/package.json, libs/testing/src/user.session.ts, packages/application-generic/package.json, packages/application-generic/src/factories/mail/interfaces/send.handler.interface.ts, packages/node/src/lib/events/events.interface.ts, packages/node/src/lib/novu.interface.ts, packages/node/src/lib/topics/topic.interface.ts, pnpm-lock.yaml
Removes strange Node package dependencies from most of the apps and libs that are dependencies for either our infra or setup.
I notice about this while trying to solve the failing tests of another PR. Part is inherited of a bad implementation of the Topics feature and other were inherit from previous refactors.
Note that we are missing to totally remove a dependency of the Node package from API app as all the invite system is depending on it (not ideal).
=> fix(infra): remove node package strange dependencies and move to shared

apps/web/src/pages/quick-start/consts.tsx
Usage of `WIDGET_EMBED_PATH` instead of hard coded localhost adress.
To make it look correct in cloud version
=> fix: widget embed path for js quick start

libs/dal/src/repositories/tenant/index.ts, libs/dal/src/repositories/tenant/tenant.entity.ts, libs/dal/src/repositories/tenant/tenant.repository.ts, libs/dal/src/repositories/tenant/tenant.schema.ts, libs/dal/src/repositories/tenant/types.ts, libs/shared/src/types/index.ts, libs/shared/src/types/shared/index.ts, libs/shared/src/types/subscriber/index.ts, libs/shared/src/types/tenant/index.ts
The tenants entity. The tenants for the current version should include the following information:
* Unique Identifier (key/tenantId) - A user-provided id that will be used to retrieve and manipulate tenants.
* Name - The name of the tenant
* (Optional) Custom Data - An object provided by the user to contain custom tenant data. 
Tenants are attached to the environment level of the system.
So that our users will be able to manage and create tenants in our system.
=> NV-2457 - Create Tenant Repository

apps/api/src/app.module.ts, apps/api/src/app/shared/shared.module.ts, apps/api/src/app/tenant/dtos/create-tenant-request.dto.ts, apps/api/src/app/tenant/dtos/create-tenant-response.dto.ts, apps/api/src/app/tenant/e2e/create-tenant.e2e.ts, apps/api/src/app/tenant/tenant.controller.ts, apps/api/src/app/tenant/tenant.module.ts, apps/api/src/app/tenant/usecases/create-tenant/create-tenant.command.ts, apps/api/src/app/tenant/usecases/create-tenant/create-tenant.usecase.ts, apps/api/src/app/tenant/usecases/index.ts, libs/dal/src/index.ts, libs/dal/src/repositories/tenant/tenant.schema.ts
adds the create use case, in order to create new tenant entities in the system.
because it is the first tenant use case this PR will contain the initial tenant module as well.
in order to create new tenant entities.
=> Nv 2458 - Add Tenant Create Usecase

libs/dal/src/repositories/integration/integration.entity.ts, libs/dal/src/repositories/integration/integration.schema.ts, libs/dal/src/repositories/integration/types.ts
Update integration entity schema...
...to support multi provider configuration.
=> feat(dal): update integration entity schema for multi provider

_templates/provider/new/package.ejs.t, _templates/provider/new/src/lib/provider.ejs.t, docs/docs/community/create-provider.md, package.json
- Fix version and few minor things in ejs templates
- Update new provider docs with correct path and steps
=> fix: update how to add new provider docs

apps/api/src/app/integrations/usecases/create-integration/create-integration.usecase.ts, apps/api/src/app/integrations/usecases/remove-integration/remove-integration.usecase.ts, apps/api/src/app/integrations/usecases/update-integration/update-integration.usecase.ts, apps/api/src/app/widgets/e2e/initialize-widget-session.e2e.ts, apps/worker/src/app/workflow/usecases/send-message/send-message.base.ts, packages/application-generic/src/services/cache/key-builders/queries.ts, packages/application-generic/src/usecases/select-integration/select-integration.usecase.ts
We would like to apply the caching mechanism over the Integration Selection use-case. The rationale is that the integration configurations should not be changing really often.
=> NV 2418 - Integration Selection Caching

apps/api/src/app/tenant/dtos/update-tenant-request.dto.ts, apps/api/src/app/tenant/dtos/update-tenant-response.dto.ts, apps/api/src/app/tenant/e2e/update-tenant.e2e.ts, apps/api/src/app/tenant/tenant.controller.ts, apps/api/src/app/tenant/usecases/index.ts, apps/api/src/app/tenant/usecases/update-tenant/update-tenant.command.ts, apps/api/src/app/tenant/usecases/update-tenant/update-tenant.usecase.ts
Adds updated tenant metadata.
So the user's tenants will be updated.
=> Nv 2460 - Update Tenant Endpoint

docs/docs/community/_category_.json, docs/docs/guides/How to Add Digest to In-App Notifications.md, docs/docs/guides/_category_.json, docs/docs/guides/how-to-add-digest-to-in-app-notifications.md, docs/src/components/Discover.tsx
Adds a guide on using digest engine for in-app notifications
There's no guide for the stated use-case
As discussed with @unicodeveloper, first commit creates a new segment called 'guides' above 'community'. This is where all the future guides (on specific use-cases) will live:
> The second guide seen in the image above is something I'm yet to start working on. The image above is for demo purpose only
@unicodeveloper please review!
=> docs: guides on specific use cases

libs/shared/src/consts/handlebar-helpers/handlebarHelpers.ts, packages/application-generic/src/usecases/compile-template/compile-template.spec.ts, packages/application-generic/src/usecases/compile-template/compile-template.usecase.ts
1. Add `unique` handlebar helper and its test.
To remove duplicates in array iteration
Usage Example:- 
Custom code
```
{{#each (unique names "name")}}
--<b>{{this}}</b>--- 
{{/each}}
```
Input:- 
```
{
"names": [{
"name": "Name 1",
"age": "30"
}, {
"name": "Name 2"
}, {
"name": "Name 1"
}]
}
```
HTML output:- 
` --Name 1----Name 2--`
=> feat: add unique handlebar helper

apps/web/src/pages/integrations/UpdateProviderPage.tsx
UX consistency in the product. We display the Input "Name" of a Workflow in the WF settings. 
Input "Name" is displayed in the update integration sidebar
=> feat: add name field to update sidebar

apps/worker/src/app/workflow/usecases/send-message/digest/get-digest-events-backoff.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/digest/get-digest-events-regular.usecase.ts, libs/dal/src/repositories/job/job.repository.ts, packages/application-generic/src/usecases/digest-filter-steps/digest-filter-steps.usecase.ts
1. **Fix - digestKey events don't aggregate the digested payloads**:
The digested events were added only for the first digestKey runs. All other digestKeys had the first event payload but marked all the others as digested.
For example: 
digestKey: 1 , trigger 3 times. get one email with the payload of all 3 triggers (as expected) 
digestKey: 2 , trigger 3 times. get only one email with the payload of only the first trigger
2. **Fix - no digestKey functionality for a nested digestKey path**
Giving a nested path for the digestKey value resulted in the normal digest behaviour, ignores the digest key values
Fix bug of digestKey
=> fix: aggregation of events by digest key, fix nested digest key

apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts, providers/sendgrid/src/lib/sendgrid.provider.ts
remove the option to set ip pool name with an undefined/empty string.
send grid does not support nulish value for the ip pool name and throws an exception.
my mistake in adding the support and not validating the full flow properly.
=> fix: remove undefined ip pool name

apps/web/cypress/tests/notification-editor/create-notification.spec.ts, apps/web/src/pages/templates/components/TemplateEditorFormProvider.tsx
fix - update resets to default values of digest or delay metadata.
Reproducing steps: 
1. add digest step
2. change any value of regular digest
3. click update 
https://www.loom.com/share/038f03d3f7ab4695b70636e69c5be858
The problem was that we reset the steps in the form from the response we got from the update. We have different field names for the digest metadata in the backend vs the frontend.
=> fix: digest and delay values are reset to default values on update

docker/kubernetes/helm/templates/api/deployment.yaml, docker/kubernetes/helm/templates/web/deployment.yaml, docker/kubernetes/helm/templates/worker/deployment.yaml, docker/kubernetes/helm/templates/ws/deployment.yaml
In the k8s chart, the labels "app.kubernetes.io/component" are now generated, taking into account the ".Release.Name". 
If the release name did not correspond to "novu", the selector labels of the services were wrong.
=> fix: k8s component labels hard coded

docker/kubernetes/helm/values.yaml
In the values.yaml, the configuration for the points that are used by the web deployment is missing.
Due to its absence, the API cannot always be accessed from the web component.
=> fix: helm values.yaml missing web endpoints

docker/kubernetes/helm/templates/web/deployment.yaml
The web deployment accesses the node_env variable of the api and not its own.
=> fix: web deployment using wrong NODE_ENV

docs/docs/overview/quickstart/get-started-with-ruby.md
Document a Ruby quickstart for Novu API
TODO: 
1. This file should be uploaded so it can be added to the docs
2. Add link to sample code - https://github.com/Eazybright/novu-ruby-quickstart.git
=> docs: add ruby quickstart documentation

apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts, packages/stateless/src/lib/provider/provider.interface.ts, pnpm-lock.yaml, providers/expo/src/lib/expo.provider.spec.ts, providers/fcm/src/lib/fcm.provider.spec.ts, providers/fcm/src/lib/fcm.provider.ts, providers/one-signal/package.json, providers/one-signal/src/lib/one-signal.provider.spec.ts, providers/push-webhook/src/lib/push-webhook.provider.spec.ts, providers/push-webhook/src/lib/push-webhook.provider.ts
The FCM data message `data` field should be a type of `Record<string, string>` otherwise the FCM platform will raise an error.
FCM docs:
https://firebase.google.com/docs/cloud-messaging/concept-options
https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.basemessage.md#basemessage_interface
=> fix(worker): fixed the fcm data message issue with payload messed with additional data

apps/worker/src/app/shared/logs/create-log.usecase.ts, apps/worker/src/app/workflow/services/metric-queue.service.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts, packages/application-generic/src/services/analytics.service.ts, packages/application-generic/src/services/cache/cache.service.ts, packages/application-generic/src/services/cache/interceptors/cached-entity.interceptor.ts, packages/application-generic/src/services/cache/interceptors/cached-query.interceptor.ts, packages/application-generic/src/services/cache/interceptors/cached.interceptor.ts, packages/application-generic/src/services/cache/invalidate-cache.service.ts, packages/application-generic/src/services/distributed-lock/distributed-lock.service.ts, packages/application-generic/src/services/feature-flags.service.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts, packages/application-generic/src/services/launch-darkly.service.ts, packages/application-generic/src/services/readiness.service.ts, packages/application-generic/src/usecases/create-notification-jobs/create-notification-jobs.usecase.ts, packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
Sets the proper order of the arguments for the usage of `Logger.error` from NestJS throughout our codebase.
In a previous PR I spotted mixing order of usage of error and context params in the function. I corrected it after understanding the proper order that makes usage of the context. This will help debugging and error control and fix a bit of tech debt.
=> fix(worker): set the proper argument order in the logger error function

packages/notification-center-vue/package.json, pnpm-lock.yaml
Fixes that failing build for the `notification-center-vue` package.
=> fix(notification-center-vue): revert the @vue/tsconfig lib update

apps/api/Dockerfile, apps/worker/src/app/workflow/usecases/run-job/run-job.usecase.ts
Only remove attachments on the last job execution phase, or when a failure happened without retry.
In case of multiple nodes where the email is the last node, it would remove the attachments before the email will be sent.
=> Remove attachments on last job execution only

apps/api/src/app/inbound-parse/services/inbound-parse.queue.service.ts, apps/inbound-mail/src/server/queue-service.ts, apps/worker/src/app/workflow/services/metric-queue.service.ts, apps/worker/src/app/workflow/services/trigger-processor-queue.service.ts, apps/worker/src/app/workflow/services/workflow-queue.service.spec.ts, apps/worker/src/app/workflow/services/workflow-queue.service.ts, apps/ws/src/socket/socket.module.ts, packages/application-generic/src/services/bull-mq.service.ts, packages/application-generic/src/services/index.ts, packages/application-generic/src/services/queue.service.ts, packages/application-generic/src/services/trigger-queue.service.ts
Consolidates the usage and instantiation of the Redis instance used by BullMQ for the queues and workers of Novu.
It is needed in preparation of the move in the Cloud offering to support MemoryDB for our solution.
Haven't yet touched:
- `libs/testing/src/queue.service.ts`: as it is used by `@novu/application-generic` and we should think if we want to reuse the Redis instance / MemoryDB instance for the testing Queue. In Test environment we use the same DB index for the testing Queue service and for the apps.
- `apps/ws/src/shared/framework/redis.adapter.ts`: it shares the configuration of the Redis instance used by BullMQ, even using the same DB, so I am tempted (I think we should) to implement it there.
=> feat(infra): consolidate usage of redis instance by bull-mq

docs/docs/guides/how-to-add-digest-to-email-notifications.md
Adds a guide for email digest notifications.
There was no guide for the same.
https://github.com/novuhq/novu/assets/62152915/eeeab65c-e829-46d0-bbf3-14a14314fac6
=> docs: add digest email guide

packages/node/src/index.ts, packages/node/src/lib/events/events.interface.ts, packages/node/src/lib/topics/topic.interface.ts
Exports `TriggerRecipientsTypeEnum` and remove some random unused imports inside SDK.
Because I was unable to use Novu Node.js SDK inside TypeScript project (without `//@ts-ignore` what I want avoid for sure in my apps)
Closes #3786
=> fix: export TriggerRecipientsTypeEnum in Node.js SDK

docs/docs/overview/quickstart/get-started-with-dotnet.md
dotnet quickstart referenced "client" instead of "novu" for a variable name
to be consitent with the rest of the guide
=> replace client with novu in dotnet quickstart

packages/node/src/lib/subscribers/subscriber.interface.ts, packages/node/src/lib/subscribers/subscribers.spec.ts, packages/node/src/lib/subscribers/subscribers.ts
Add `markMessageRead `method in node SDK similar to `markMessageSeen`
=> fix: add mark message read method in node sdk

apps/web/cypress/tests/notification-editor/create-notification.spec.ts, apps/web/src/hooks/useVariablesManager.ts, apps/web/src/pages/templates/components/VariableManager.tsx, apps/web/src/pages/templates/components/email-editor/variables-management/VariablesManagement.tsx
Any update workflow click, clears the default values set for the variables. 
to reproduce:
1. open any step that has values for default values/required set 
2. edit any content 
3. click update 
4. the values has been cleared 
https://www.loom.com/share/8ef844b9293c4125aec2508f98231285
=> Nv 2434 update workflow sets variables to default value

apps/web/cypress/tests/notification-editor/create-notification.spec.ts, apps/web/cypress/tests/notification-editor/steps-actions.spec.ts
Flaky test - needed a wait after loading the template as sometimes only 1 sms step was added. 
Same for a flaky test that the first email step was not added.
=> fix: flaky test because first sms step was not being added

apps/api/src/app/events/e2e/trigger-event.e2e.ts
Skip override integration test that fails because the feature flag is changed on the "API" running instance, but not on the worker service.
So the API runs with the feature flag enabled, but the worker runs without it
=> test: skip failing test until we can control feature flag in worker 

docs/docs/cookbook/introduction.md, docs/docs/overview/architecture.md
Introduces a visual model of workflow/trigger/event/notification flow to Cookbook & Architecture pages.
To help readers understand how Novu workflows and notifications work.
=> Docs: Add Uml flow to Cookbook & Architecture pages

apps/web/src/design-system/icons/general/Buildings.tsx, apps/web/src/pages/tenants/components/list/TenantsList.tsx, apps/web/src/pages/tenants/components/list/TenantsListNoData.tsx
Display an empty state when no tenants are found
=> Nv 2612 - Tenant Page Empty State

apps/api/src/app/shared/dtos/pagination-response.ts, apps/web/src/api/tenants.ts, apps/web/src/hooks/useTenants.ts, apps/web/src/pages/tenants/components/list/TenantsList.tsx, libs/shared/src/dto/shared/shared.ts
Created the same pagination we have on the subscriber list page in order to reuse existing components.
in order to check long lists of tenants.
https://www.loom.com/share/f8e823495fe34c2d9fa542da79b60f0f
=> NV 2613 - Tenant Page Pagination

apps/api/src/app/integrations/usecases/update-integration/update-integration.usecase.ts
To disable Novu provider if another provider is activated
=> fix: so activating a provider deactivates novu provider

apps/api/src/app/tenant/e2e/get-tenants.e2e.ts, apps/api/src/app/tenant/usecases/get-tenants/get-tenants.usecase.ts, apps/web/src/components/layout/components/SideNav.tsx
Feature flag to hide Tenant functionality.
We introducing new Tenant functionality that needs to be hidden before the general auditory release. We are planning to roll out that functionality to some early birds before the GA release.
* Tenant functionality is hidden under the feature flag
=> NV 2602 - Hide Tenant functionality under the feature flag

apps/api/src/app/shared/framework/response.interceptor.ts, apps/api/src/app/tenant/e2e/get-tenant.e2e.ts
allow return 'data' as response prop
so we could create entities with a 'data' prop on the root layer and return them properly.
=> fix: allow return 'data' as response prop

apps/web/src/pages/templates/workflow/DigestMetadata.cy.tsx
This test would fail every time we run it on the 31th or the 1th of every month. 
Because today's value is already selected by default and in the test we click on the 31 and 1 -> so if the run is on that day we de-select them.
=> test: fix failing test because of a run on same day

apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/api/src/app/integrations/e2e/get-decrypted-integrations.e2e.ts, apps/web/cypress/tests/integrations-list-modal.spec.ts, apps/web/cypress/tests/integrations-list-page.spec.ts, apps/web/src/pages/integrations/components/UpdateIntegrationCommonFields.tsx, apps/web/src/pages/integrations/components/UpdateIntegrationSidebarHeader.tsx, apps/web/src/pages/integrations/components/multi-provider/UpdateProviderSidebar.tsx
Change to the normal update header for provider and add name + identifier fields.
=> feat: add delete item and name fields for novu providers

apps/api/src/app/tenant/tenant.controller.ts, apps/api/src/app/tenant/usecases/create-tenant/create-tenant.command.ts, apps/api/src/app/tenant/usecases/create-tenant/create-tenant.usecase.ts, apps/api/src/app/tenant/usecases/delete-tenant/delete-tenant.command.ts, apps/api/src/app/tenant/usecases/update-tenant/update-tenant.command.ts, apps/web/src/pages/tenants/TenantsPage.tsx
I was not sure what analytics we could want to track at the moment, at the moment I added `tenant page visit` and `tenant creation`
In order to track if a user that enters to the tenant's page creates new tenants.
---
Would love to hear if you think this one is redundant or if we would like to track other events on this feature as well.
=> [Tenants] - Add Tenants Analytics

apps/api/src/app/blueprint/e2e/get-grouped-blueprints.e2e.ts, apps/api/src/app/events/e2e/process-subscriber.e2e.ts, apps/api/src/app/health/e2e/health-check.e2e.ts, apps/api/src/app/shared/shared.module.ts, apps/api/src/app/widgets/e2e/get-count.e2e.ts, apps/api/src/app/widgets/e2e/get-unseen-count.e2e.ts, apps/api/src/app/widgets/e2e/initialize-widget-session.e2e.ts, apps/worker/src/app/health/e2e/health-check.e2e.ts, apps/worker/src/app/shared/shared.module.ts, packages/application-generic/src/health/in-memory.health-indicator.ts, packages/application-generic/src/services/cache/cache-service.spec.ts, packages/application-generic/src/services/distributed-lock/distributed-lock.service.spec.ts, packages/application-generic/src/services/distributed-lock/distributed-lock.service.ts, packages/application-generic/src/services/in-memory-provider/elasticache-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.spec.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts, packages/application-generic/src/services/in-memory-provider/redis-cluster-provider.ts, packages/application-generic/src/usecases/create-subscriber/create-subscriber.spec.ts, packages/application-generic/src/usecases/update-subscriber/update-subscriber.spec.ts
Allows to provide the provider choose for any specific InMemoryProviderService instance.
Also it fallbacks to Redis instance if no provider chosen or the configuration validation for the provider chosen fails.
Right now we only have Elasticache as provider implemented with Redis Cluster compatibility. In order to support further Redis Cluster compatible providers we need to refactor InMemoryProviderService.
=> feat(app-generic): refactor in-memory-provider service

apps/web/package.json, apps/widget/package.json, pnpm-lock.yaml
Update cypress version to address https://github.com/novuhq/novu/security/dependabot/173 closes NV-2654
Due to security issue in a sub-dependency
=> chore: update cypress version due to security update

apps/api/migrations/novu-integrations/novu-integrations.migration.ts
Add migration script for Novu providers.
=> feat: add migration script to add novu providers to database

apps/api/package.json, apps/inbound-mail/package.json, apps/ws/package.json, docs/package.json, libs/dal/package.json, libs/embed/package.json, packages/application-generic/package.json, pnpm-lock.yaml, providers/ses/package.json, providers/sns/package.json, providers/twilio/package.json
Fixing some sub dependencies critical vulnerabilities.
=> chore: update dependencies with security issues

apps/api/src/app/subscribers/usecases/update-subscriber-preference/update-subscriber-preference.usecase.ts, libs/shared/src/entities/subscriber-preference/subscriber-preference.interface.ts, libs/shared/src/types/subscriber/index.ts, packages/application-generic/src/usecases/get-subscriber-preference/get-subscriber-preference.usecase.ts, packages/application-generic/src/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts
Fixes a circular dependency between 2 use case modules. Arranges also the location of the types.
=> fix(app-generic): circular dependency on subscriber pref use cases

apps/worker/src/app/workflow/usecases/send-message/digest/digest.usecase.ts
When concurrently triggering a workflow with a digest + digest key for multiple subscribers in same trigger, some events contained did not belong to the correct digest key.
When getting the jobs to update the digest field with the events we save on job, we didn't filter it with the subscriberId (🤦‍♀️ ). Meaning that when we trigger for multiple subscribers ( they have the same transactionId ) we update all the "next jobs" - all the not completed jobs of all the subscribers with the same transaction - with the digest: {events }. And by that we are overriding the other settings we had in that digest object, like the digest key. So, when later, in the execution of that job we accidentally updated he doesn't have the digestKey and so he aggregates all the events. As if there was no digestKey.
=> fix: fix update of digest jobs only for current subscriber

apps/web/src/components/workflow/FlowEditor.tsx, apps/web/src/design-system/template-button/DragButton.tsx
Change cursor for drag buttons and drop area
https://www.loom.com/share/bc4ec018019345088a55d4d5b3824647
=> feat: fix cursors for drag buttons and drop area

apps/api/src/app/events/services/workflow-queue/trigger-handler-queue.service.spec.ts, apps/worker/src/app/workflow/services/metric-queue.service.spec.ts, apps/worker/src/app/workflow/services/trigger-processor-queue.service.spec.ts, packages/application-generic/src/services/bull-mq.service.spec.ts, packages/application-generic/src/services/bull-mq.service.ts, packages/application-generic/src/services/queue.service.spec.ts, packages/application-generic/src/services/trigger-queue.service.spec.ts, packages/application-generic/src/services/ws-queue.service.spec.ts, packages/application-generic/src/services/ws-queue.service.ts
Adds unit tests for worker and queue services dependant of BullMqService.
Give extra confidence in the changes for MemoryDB and identify possible migration mistakes.
=> feat(tests): add tests for worker and queue services

packages/application-generic/src/usecases/add-job/add-job.usecase.spec.ts, packages/application-generic/src/usecases/add-job/add-job.usecase.ts
Adds unit test for AddJob use case.
To validate the QueueService injection in the MemoryDB PR for validation.
=> feat(app-generic): add test for add job use case to check the injected queue service

apps/api/src/app/subscribers/dtos/get-in-app-notification-feed-for-subscriber.dto.ts, apps/api/src/app/subscribers/e2e/get-notifications-feed.e2e.ts, apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/widgets/e2e/get-notification-feed.e2e.ts, apps/api/src/app/widgets/usecases/get-notifications-feed/get-notifications-feed.command.ts, apps/api/src/app/widgets/usecases/get-notifications-feed/get-notifications-feed.usecase.ts, apps/api/src/app/widgets/widgets.controller.ts, libs/dal/src/repositories/message/message.repository.ts, packages/client/src/api/api.service.ts, packages/client/src/index.ts, packages/node/src/lib/subscribers/subscriber.interface.ts, packages/node/src/lib/subscribers/subscribers.ts
Allow filtering of the notifications feed by the custom data from the payload object.
The two endpoints `GET /subscribers/:subscriberId/notifications/feed` and `GET /widgets/notifications/feed` now can take the query param like `?payload=eyJmb28iOjEyM30=`. 
The value is a base64 encoded string of the partial payload JSON object. 
For example, if the payload passed to the trigger event was like `{ foo: 123, bar: 'bar' }`, then you filter notifications by `{ foo: 123 }` by doing `btoa(JSON.stringify({ foo: 123 }))` that results in base64 encoded string `eyJmb28iOjEyM30=` and passing it to the query param.
Allows building custom notification center experiences.
=> feat(api): notifications feed filtering by partial payload object

apps/api/src/app/execution-details/dtos/execution-details-request.dto.ts, apps/api/src/app/execution-details/e2e/get-execution-details.e2e.ts, apps/api/src/app/execution-details/usecases/get-execution-details/get-execution-details.usecase.ts
https://docs.novu.co/api/get-execution-details/ API expects two things notificationId and subscriberId. In implementation, it is MongoDBId generated by Novu. But the endpoint should accepts the user's subscriberId
=> feat: get execution details endpoint by external subscriber id

apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts, docs/docs/platform/layouts.md, packages/application-generic/src/usecases/create-execution-details/types/index.ts, packages/node/src/lib/events/events.interface.ts, packages/node/src/lib/events/events.spec.ts
allow to override the layoutIdentifier with overrides property 
Note - I am still working on adding tests, I am not sure yet how to check in a test which layout was actually executed as we don't save the resulting content.
=> feat: add override layout in trigger functionality

.github/workflows/reusable-api-e2e.yml, .github/workflows/test.yml, apps/api/src/app/events/dtos/trigger-event-request.dto.ts, apps/api/src/app/shared/dtos/pagination-response.ts
=> fix: so swagger json validates

.github/actions/run-worker/action.yml, .github/actions/setup-project/action.yml, .github/workflows/reusable-api-e2e.yml, .github/workflows/reusable-web-e2e.yml, .github/workflows/reusable-widget-e2e.yml
=> feat(ci): reuse instructions to tidy up pipelines

.github/actions/run-api/action.yml, .github/actions/validate-swagger/action.yml, .github/workflows/test.yml, scripts/print-affected-array.mjs
Separates the Swagger validation in its own runner to avoid interfering in E2E test runners. Also isolates some reusable actions.
Clarify the intention of the Swagger validation.
=> feat(ci): separate the swagger validation in own runner plus improvement

libs/dal/src/repositories/integration/integration.schema.ts
add organization id index in integration.
in the get decrypted integration usecase there is a possibility to fetch by an organization, therefore we won't have any index by which we could fetch.
=> feat  add organization id index in integration

apps/web/cypress/tests/integrations-list-modal.spec.ts, apps/web/cypress/tests/integrations-list-page.spec.ts, apps/web/src/pages/integrations/IntegrationsList.tsx
=> fix: so add a provider is not displayed in empty state

.github/actions/run-backend/action.yml, .github/workflows/reusable-web-e2e.yml, .github/workflows/reusable-widget-e2e.yml
Creates an action to run API and Worker apps to be used in the reusable workflows of Web and Worker.
Tidying up the pipelines.
=> feat(ci): reusable action to run backend (api, worker) for clients

.github/actions/run-backend/action.yml, .github/workflows/reusable-web-e2e.yml, .github/workflows/reusable-widget-e2e.yml
=> fix(ci): proper settings for secrets for run backend

CONTRIBUTING.md, docker/Readme.md, docs/docs/overview/docker-deploy.md
closes #3995 
Removed or replaced github discussion links from repo and docs with discord server link
=> fix: remove github discussion link

apps/api/src/app/logs/usecases/create-log/create-log.usecase.ts, apps/inbound-mail/src/server/index.ts, apps/worker/src/app/shared/logs/create-log.usecase.ts, apps/worker/src/app/workflow/services/metric-queue.service.ts, apps/worker/src/app/workflow/services/workflow-queue.service.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts, apps/worker/src/app/workflow/usecases/webhook-filter-backoff-strategy/webhook-filter-backoff-strategy.usecase.ts, apps/ws/src/socket/services/socket-queue-consumer.service.ts, packages/application-generic/src/services/analytics.service.ts, packages/application-generic/src/services/cache/cache.service.ts, packages/application-generic/src/services/cache/interceptors/cached-entity.interceptor.ts, packages/application-generic/src/services/cache/interceptors/cached-query.interceptor.ts, packages/application-generic/src/services/cache/interceptors/cached.interceptor.ts, packages/application-generic/src/services/cache/invalidate-cache.service.ts, packages/application-generic/src/services/distributed-lock/distributed-lock.service.ts, packages/application-generic/src/services/feature-flags.service.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts, packages/application-generic/src/services/launch-darkly.service.ts, packages/application-generic/src/services/readiness.service.ts, packages/application-generic/src/usecases/create-notification-jobs/create-notification-jobs.usecase.ts, packages/application-generic/src/usecases/digest-filter-steps/digest-filter-steps.usecase.ts, packages/application-generic/src/usecases/trigger-event/trigger-event.usecase.ts
=> next fix logger error order

apps/worker/src/app/workflow/usecases/message-matcher/message-matcher.usecase.spec.ts, apps/worker/src/app/workflow/usecases/message-matcher/message-matcher.usecase.ts, apps/worker/src/app/workflow/usecases/message-matcher/types.ts, apps/worker/src/app/workflow/usecases/send-message/send-message.usecase.ts, packages/application-generic/src/index.ts, packages/application-generic/src/utils/filter-processing-details.ts, packages/application-generic/src/utils/filter.ts
I move some of the methods that will be used for conditions as well from message matcher so we can reuse it. I was not able to move as much as I would like to lets see if we can move some more when we are doing the conditions equal usecase.
=> refactor: so filter logic from message matcher to filter abstract class

apps/api/src/app/integrations/usecases/set-integration-as-primary/set-integration-as-primary.usecase.ts
Not sure it's supposed to be this easy but. it should empty conditions when an integration is set as primary.
=> feat: fix so conditions are emptied when integration are set as primary

packages/node/src/lib/events/events.interface.ts
Made `integrationIdentifier` as optional
To fix this error
=> fix: make integration identifier optional

apps/web/src/pages/templates/components/notification-setting-form/NotificationSettingsForm.tsx, docs/docs/notification-center/react/api-reference.md, libs/shared/src/entities/subscriber-preference/subscriber-preference.interface.ts, packages/application-generic/src/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts, packages/client/src/index.ts
Adds the ability to use tags in the workflow settings screen.
This change allows usecases to group multiple workflows under the same tag, and then use it to filter subscriber preferences for example.
=> feat: add tags for workflow settings

apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/widgets/widgets.controller.ts
If no seen param provided convert it to false.
i suspect we had it as false from nest, could be some versioning issue.
=> fix: unseen count default

apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/widgets/e2e/get-count.e2e.ts, apps/api/src/app/widgets/e2e/get-unseen-count.e2e.ts, apps/api/src/app/widgets/widgets.controller.ts
Fix the unseen count default query param and test.
=> Fix unseen count

apps/api/package.json, apps/api/src/app.module.ts, pnpm-lock.yaml
=> feat: add external oauth module

.github/workflows/test.yml, .gitignore, .idea/vcs.xml, apps/api/package.json, apps/api/src/app.module.ts, apps/api/src/app/auth/e2e/oauth.e2e-ee.ts, apps/api/src/app/auth/services/passport/github.strategy.ts, pnpm-lock.yaml
created e2e ee test.
in order to validate that the module is properly imported.
=> Nv 2764 e2e tests

apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-in-app.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts
Fix: tenant.data payload was spread, so it was missing the data when used in the editor
Example: instead of using `{{tenant.data.count}}` in the editor it was `{{tenant.count}}`
=> fix: missing data prop in the compile payload

packages/notification-center/src/i18n/languages/es.ts
Add ES i18n messages
There is no traduction for some ES messages
=> Add ES i18n translations

apps/web/src/components/conditions/Conditions.tsx, apps/web/src/components/conditions/index.ts, apps/web/src/components/conditions/types.ts, apps/web/src/design-system/tooltip/Tooltip.styles.ts, apps/web/src/design-system/tooltip/Tooltip.tsx, apps/web/src/design-system/typography/title/Title.tsx, apps/web/src/pages/integrations/components/ConditionIconButton.tsx, apps/web/src/pages/integrations/components/PrimaryIconButton.tsx, apps/web/src/pages/integrations/components/UpdateIntegrationSidebarHeader.tsx, apps/web/src/pages/integrations/components/multi-provider/CreateProviderInstanceSidebar.tsx, apps/web/src/pages/integrations/components/multi-provider/UpdateProviderSidebar.tsx, apps/web/src/pages/integrations/types.ts, apps/web/src/pages/templates/WorkflowListPage.tsx
=> refactor: conditions component

.github/workflows/reusable-inbound-mail-e2e.yml
=> fix(ci): inbound mail pipeline indent

.github/workflows/staging-deploy-web.yml
This Pull Request adds a new pipeline to run and update novu's staging deployment for web.
Updates the same way as dev.
=> Add Staging Web Pipeline

docker/kubernetes/kustomize/kustomization.yaml, docker/kubernetes/kustomize/mongodb-deployment.yaml, docker/kubernetes/kustomize/mongodb-volume.yaml
This PR introduces the addition of a volume claim to the MongoDB deployment in the Novu open-source project. It involves modifying the configuration of the MongoDB deployment to include a volume claim, which allows for persistent storage of data.
This change was needed to address the need for data persistence and reliability in the Novu project's MongoDB deployment. Without a volume claim, MongoDB data would be stored in ephemeral containers, which means that any data stored would be lost if the container were to be restarted or recreated. By adding a volume claim, we ensure that data is stored persistently and can survive container restarts and recreations.
=> add volume claim to mongodb deployment

packages/node/README.md, packages/node/src/lib/integrations/integrations.interface.ts, packages/node/src/lib/integrations/integrations.spec.ts, packages/node/src/lib/integrations/integrations.ts
- adds the missing setIntegration primary API endpoint to the node package
=> feat: add missing endpoints

apps/api/src/app/integrations/e2e/create-integration.e2e.ts, apps/api/src/app/integrations/usecases/create-integration/create-integration.usecase.ts, apps/web/cypress/tests/integrations-list-page.spec.ts, apps/web/src/pages/integrations/components/multi-provider/CreateProviderInstanceSidebar.tsx, apps/web/src/pages/integrations/components/multi-provider/SelectProviderSidebar.tsx
- allows the user to create Novu email and SMS integrations
- each provider is limited to 1 for each environment
- After deleting a Novu provider there was no option to re-add them.
=> Nv 2795 allow to create integration for novu sms and email providers

.github/workflows/test.yml
=> feat: skip ee tests if no token

apps/worker/src/app/workflow/usecases/send-message/send-message-in-app.usecase.ts, apps/ws/src/socket/usecases/external-services-route/external-services-route.spec.ts, apps/ws/src/socket/usecases/external-services-route/external-services-route.usecase.ts
From the Worker we will only send one event instead of 3 and we will process it executing the functions that before were triggered by 3 different events, as they are sent at the same time.
We also only process the event and trigger the messages to the WebSocket if the user is online as if not it is a waste of resources.
It is a performance improvement identified during the MemoryDB migration.
=> feat(ws): simplify events for web sockets queue for performance

apps/api/src/app/workflows/e2e/update-notification-template.e2e.ts, apps/api/src/app/workflows/usecases/update-notification-template/update-notification-template.usecase.ts
Update the PUT /workflows endpoint to support the variants on the steps.
The parts of the code we have to update:
variables for all steps + variants
create message templates for variants
changes for variants
the PUT /workflows endpoint supports the variants on the steps
e2e tests
=> feat: add support for variants update

README.md
This PR removes the duplicate mention of SNS in the SMS providers section of the Readme file.
This change was needed to ensure that the information in the Readme file is accurate and concise. The duplicate mention of SNS in the SMS providers section can lead to confusion and redundancy.
Closes #4196
=> Remove duplicate mention of SNS in SMS providers

apps/worker/src/app/workflow/usecases/send-message/digest/digest-events.command.ts, apps/worker/src/app/workflow/usecases/send-message/digest/digest.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/digest/get-digest-events-backoff.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/digest/get-digest-events-regular.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/digest/get-digest-events.usecase.ts, packages/application-generic/src/usecases/digest-filter-steps/digest-filter-steps.usecase.ts
Refactors the logic flow in getting the digest events for message of type digest.
During the works to provide stability to the Digest feature performed by @scopsy and @davidsoderberg it was noticed that we needed improvements in the send message codebase.
I noticed in the Digest Events flow that unneeded calls to the database were made and we could avoid that with a simple refactor, besides reusing functionality for regular and backoff digest cases.
This PR shouldn't conflict with https://github.com/novuhq/novu/pull/4158 but let's keep an eye in both and prioritise the linked one as it is more crucial for our needs.
=> feat(worker): refactor get digest events flow

apps/api/src/app/events/dtos/trigger-event-response.dto.ts, apps/api/src/app/events/usecases/parse-event-request/parse-event-request.usecase.ts, apps/api/src/app/events/usecases/process-bulk-trigger/process-bulk-trigger.usecase.ts, apps/api/src/app/events/usecases/trigger-event-to-all/trigger-event-to-all.usecase.ts, libs/shared/src/types/events/index.ts
Creates an enum to gather all the potential status of the result of executing the trigger event endpoints.
=> feat(api): create trigger event status enum

apps/ws/src/socket/services/index.ts, apps/ws/src/socket/services/old-instance-web-sockets-worker.service.ts, apps/ws/src/socket/services/old-instance-web-sockets.worker.ts, apps/ws/src/socket/socket.module.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts, packages/application-generic/src/services/index.ts
Adds Worker for pulling jobs from old instance during transition to MemoryDB to not have old jobs unprocessed.
=> feat(ws): add old instance worker for web sockets jobs

apps/worker/src/app/workflow/services/cold-start.service.ts, apps/worker/src/app/workflow/services/index.ts, apps/worker/src/app/workflow/services/old-instance-standard.worker.ts, apps/worker/src/app/workflow/services/old-instance-workflow.worker.ts, apps/worker/src/app/workflow/workflow.module.ts, packages/application-generic/src/modules/queues.module.ts, packages/application-generic/src/services/workers/index.ts, packages/application-generic/src/services/workers/old-instance-workflow-worker.service.ts
Adds a worker connected to the old instance that will process the jobs in the Trigger handler queue so while we deploy the MemoryDB migration as not all the apps are deployed at the same time, if there are ongoing triggered notifications those can be processed by rerouting them to the new MemoryDB instance while the API app is not fully deployed with the new version that directly routes the triggered events to store the jobs and add them to the trigger handler queue located in MemoryDB.
=> feat(worker): add trigger-handler queue worker for old instance redis

apps/api/e2e/compile-email-template.e2e.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts, packages/application-generic/src/usecases/compile-email-template/compile-email-template.command.ts, packages/application-generic/src/usecases/compile-email-template/compile-email-template.usecase.ts
- pass senderName variable to compile template to parse the variable
- use parsed sender name as sender name to email provider
closes #3958
=> feat: allow variables in sender name field of email editor

.github/actions/docker/build-api/action.yml, .github/actions/docker/build-worker/action.yml, .github/workflows/dev-deploy-embed.yml, .github/workflows/dev-deploy-inbound-mail.yml, .github/workflows/dev-deploy-web.yml, .github/workflows/dev-deploy-webhook.yml, .github/workflows/dev-deploy-widget.yml, .github/workflows/dev-deploy-ws.yml, .github/workflows/jarvis.yml, .github/workflows/prod-deploy-api.yml, .github/workflows/prod-deploy-embed.yml, .github/workflows/prod-deploy-inbound-mail.yml, .github/workflows/prod-deploy-web.yml, .github/workflows/prod-deploy-webhook.yml, .github/workflows/prod-deploy-widget.yml, .github/workflows/prod-deploy-worker.yml, .github/workflows/prod-deploy-ws.yml, .github/workflows/reusable-api-e2e.yml, .github/workflows/reusable-web-e2e.yml, .github/workflows/reusable-widget-e2e.yml, .github/workflows/reusable-worker-e2e.yml, .github/workflows/reusable-ws-e2e.yml, .github/workflows/staging-deploy-web.yml, .github/workflows/test.yml
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=IMAGE::ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG"
```
**TO-BE**
```yaml
echo "IMAGE=ghcr.io/$REGISTRY_OWNER/$DOCKER_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT
```
Closes #4207 
None
=> chore: Replace deprecated command with environment file

apps/api/src/app/shared/helpers/content.service.spec.ts, apps/api/src/app/shared/helpers/content.service.ts
Fixes errors thrown by malformed filters in messages.
To fix this:
https://novu-r9.sentry.io/issues/4518246046/?alert_rule_id=10492815&alert_timestamp=1696232113867&alert_type=email&environment=production&notification_uuid=1f7176c6-ff05-4643-9a24-8b06a20c32e5&project=6248811&referrer=alert_email
=> fix(api): malformed filters in messages throw errors

CONTRIBUTING.md
This PR updates the node version specified in CONTRIBUTING.md file.
* The current Docs of CONTRIBUTING.md is:
* Actually, Docs should be like:
It causes a number of issues with the specified node version in the CONTRIBUTING.md file.
=> docs: Updated node version in CONTRIBUTING.md

README.md
Adds the Elixir SDK to the hacktoberfest repo list
We have added a [CONTRIBUTING.md](https://github.com/novuhq/novu-elixir/blob/main/CONTRIBUTING.md) file, ensured CI is passing, and [labeled recent issues for hacktoberfest](https://github.com/novuhq/novu-elixir/issues).
cc @Cliftonz
=> chore: add Elixir SDK to hacktoberfest list

README.md
Brings the list of Chat providers in line and consistent with the others with quick links to the usage documentation file.
Consistency reasons along with providing a quick way for users to access the provider documentation they are looking for.
N/A
=> fix/docs: Add missing provider links in README

apps/worker/src/app/workflow/usecases/run-job/run-job.usecase.ts
For more context on APM transactions and breaking down transactions by org and job type (digest, delay, etc...)
=> feat: add newrelic custom attributes

apps/api/src/app/subscribers/usecases/update-subscriber-preference/update-subscriber-preference.usecase.ts, packages/application-generic/src/usecases/get-subscriber-template-preference/get-subscriber-template-preference.usecase.ts
- updates the get preferences to allow preferences with missing level property to be fetched as Template level
=> Allow fetching of no level preferences

packages/headless/src/lib/types.ts
- Few interfaces and types were not being exported from @novu/headless.
This PR  exports those missing interfaces types to be able to imported from @novu/headless
=> feat: export types/interfaces from headless servive

apps/api/src/bootstrap.ts
Adds an Access-Control-Max-Age response header to API responses, with cache duration of 86400 (maximum allowable on browsers, 1 day).
By specifying a Max-Age CORS header, we can provide a more responsive browser experience by eliminating a round-trip to the API in event of a preflight request cache-hit, and significantly reduce API server load.
After a successful preflight request against a URI, subsequent requests against the same URI do not require a new preflight request.
=> feat(api): Add Access-Control-Max-Age response header

README.md
The change is in the README.md, where I added the API reference link from the official Novu documentation.
I provided a direct link to the Novu API, even though the link to the official documentation is already mentioned. I added the direct API reference link so that users can conveniently access the APIs in other languages directly from the provided link. This makes it easier for users and can save them some time as well.
=> added API reference docs

apps/api/src/app/events/e2e/send-message-push.e2e.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts, packages/application-generic/src/usecases/create-execution-details/types/index.ts
Improves the handling of different push notifications messages sending:
- Doesn't throw anymore breaking the loop so cases of multiple push providers are handled properly.
- Increases the details in the activity feed for the cases of missing configuration, missing device tokens, when there is an error in one or many of multiple providers active.
- Creates a new notification error detail for the summary card of the execution details.
Code wasn't handling properly cases where multiple Push providers were active at the very same time.
Also there was no test suite for sending push notifications so it was added.
=> feat(worker): handle different push flows with better exec details

pnpm-lock.yaml
https://github.com/novuhq/novu/security/dependabot/231
=> chore: upgrade babel traverse vulnerability

apps/worker/src/app/workflow/services/active-jobs-metric.service.ts, apps/worker/src/app/workflow/services/completed-jobs-metric.service.ts
Fixes the graceful shutdown for the Metrics services for the self hosted users.
Because self hosted users didn't have the Metrics services initialised the graceful shutdown would fail throwing an error and potentially blocking the shutdown.
=> fix(worker): self hosted metrics services were not shutdown properly

packages/application-generic/src/usecases/add-job/add-job.usecase.ts
NV-3010
Update the log message to better reflect the next job scheduling to not confuse with the start of the processing of a job.
This happens in the end of an existing job, while scheduling the next one. hence starting is a bit confusing
=> style: update log message to better reflect context

.gitmodules, enterprise/README.md, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(infra): some pnpm workspace improv for dev flow

packages/notification-center/src/i18n/lang.ts, packages/notification-center/src/i18n/languages/kn.ts
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
It adds two more words for the translation to kannada and changes the actual language code for Kannada
Why was this change needed?
Because settings and no new notification words were not translated into Kannada
And the actual code for kannada language is kn not ka
=> Added words for Kannada language translation and also changed the language code

.commitlintrc.json, apps/api/src/app/events/e2e/delay-events.e2e.ts, apps/api/src/app/events/usecases/cancel-delayed/cancel-delayed.usecase.ts, pnpm-lock.yaml
=> fix(api): Cancel all jobs related to a transactionId from the 'cancel' method

libs/shared/src/types/events/index.ts, packages/node/src/lib/events/events.interface.ts, packages/node/src/lib/events/events.spec.ts, packages/stateless/src/lib/provider/provider.interface.ts
Recently added customData field was not allowing `{ templateId : "templateId" }` due to typescript type
=> fix: change custom data type and add test in node sdk

packages/notification-center-vue/package.json
* Fixes the repository `url` in the Vue Notification center
* An incocrect repository URL was present for the Vue Notification Center
N/A
=> docs(notification-center-vue): Fix repository url

libs/design-system/src/sidebar/Sidebar.tsx
Reverts novuhq/novu#4574 as it doesn't fix the problem.
=> Revert "Fix icon overlapping"

apps/api/src/app/blueprint/e2e/get-grouped-blueprints.e2e.ts, apps/api/src/app/change/e2e/get-changes.e2e.ts, apps/api/src/app/change/e2e/promote-changes.e2e.ts, apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/api/src/app/integrations/e2e/create-integration.e2e.ts, apps/api/src/app/shared/helpers/content.service.spec.ts, apps/api/src/app/workflows/e2e/create-notification-templates.e2e.ts, apps/web/src/components/conditions/Conditions.tsx, apps/web/src/components/execution-detail/ExecutionDetailsConditionItem.cy.tsx, apps/web/src/components/execution-detail/ExecutionDetailsConditions.cy.tsx, apps/web/src/pages/templates/filter/FilterModal.tsx, apps/web/src/pages/templates/filter/Filters.cy.tsx, apps/web/src/pages/templates/filter/Filters.tsx, apps/web/src/pages/templates/filter/OnlineFiltersForms.tsx, apps/worker/src/app/workflow/usecases/message-matcher/message-matcher.usecase.spec.ts, apps/worker/src/app/workflow/usecases/message-matcher/message-matcher.usecase.ts, libs/shared/src/types/builder/builder.types.ts, packages/application-generic/src/utils/filter.ts, packages/node/src/lib/integrations/integrations.spec.ts
Creates an enum with existing filter operators that were hardcoded in the codebase.
In order to implement events broadcast filtering in the payload I found useful to reuse a similar implementation for filtering in a similar way we did for the Workflow steps filtering.
=> feat(shared): tidy up filters operators to reuse in events broadcast

packages/notification-center/src/components/novu-provider/NovuProvider.tsx, packages/notification-center/src/hooks/useUnreadCount.ts, packages/notification-center/src/shared/interfaces/index.ts
This fixes an issue where the useUnreadCount hook closes the wrong websocket channel.
https://github.com/novuhq/novu/issues/4582
=> [NV-3037] Fixed closing off the wrong socket in useUnreadCount.ts

apps/web/src/pages/templates/components/VariantItemCard.tsx, apps/web/src/pages/templates/hooks/useStepSubtitle.tsx, apps/web/src/pages/templates/workflow/DigestMetadata.tsx, apps/web/src/pages/templates/workflow/digest/WillBeSentHeader.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/ChannelNode.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNodeActions.tsx
Fixed two small UI issues found for the Variants project:
- the workflow node dropdown menu was closing when hovered on the last item (which was rendered outside the node)
- the digest node was missing the content information about the time
https://github.com/novuhq/novu/assets/2607232/8463be05-f97a-4247-8e17-c534845ed64f
=> fix(web): variants project ui issues

packages/application-generic/src/services/in-memory-provider/providers/elasticache-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/memory-db-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/redis-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/redis-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/variable-mappers.ts
Converts null and undefined strings to proper values.
Azure Redis configurations demand non empty values even if not set but we don't want to pass them down to our system.
=> feat(infra): safe value in-memory provider configs

README.md
Include Pushpad provider in README.
Pushpad push provider has been merged (https://github.com/novuhq/novu/pull/4235) but it is not listed in README. 
@LetItRock Can you please merge this missing piece?
=> Add Pushpad provider to README.md

packages/application-generic/src/services/bull-mq/old-instance-bull-mq.service.ts, pnpm-lock.yaml
Sets a temporary environment variable so the OldInstanceBullMqService is not instantiated.
To unblock Azure deployment as it doesn't need to connect to the old Redis cluster instance.
=> feat(infra): temporary env var to decommission old cluster in azure

apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/api/src/app/integrations/integrations.module.ts, apps/worker/src/app/workflow/specs/conditions-filter.usecase.spec.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-in-app.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message.base.ts, apps/worker/src/app/workflow/usecases/send-message/send-message.command.ts, apps/worker/src/app/workflow/usecases/send-message/send-message.usecase.ts, packages/application-generic/src/usecases/conditions-filter/conditions-filter.usecase.ts, packages/application-generic/src/usecases/create-execution-details/types/index.ts, packages/application-generic/src/usecases/select-integration/select-integration.spec.ts, packages/application-generic/src/utils/filter-processing-details.ts
When filtering a step, allow using payload/subscriber/actor.tenant values 
for example:
Payload :
Key: data.customProp
Value: {{subscriber.data.someOtherValue}}
Subscriber:
Key: data.subscriberValue
Value: {{someProp.from.payload}}
=> feat: add support for variables in filter values

apps/web/cypress/tests/notification-editor/index.ts, apps/web/cypress/tests/notification-editor/variants.spec.ts, apps/web/src/pages/templates/components/EditorSidebarHeaderActions.tsx, apps/web/src/pages/templates/components/VariantItemCard.tsx, apps/web/src/pages/templates/components/VariantsListSidebar.tsx, apps/web/src/pages/templates/components/VariantsPage.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNode.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNodeActions.tsx
The E2E tests for the Variants project, covering:
- add variant flow
- add conditions for step/variant
- edit step/variant
- delete step/variant
- check available actions on step, step with variants, inside the editor, and variants list
=> chore(web): variants cypress e2e tests

apps/api/src/app/workflows/e2e/delete-workflow-override.e2e.ts, apps/api/src/app/workflows/usecases/delete-workflow-override/delete-workflow-override.command.ts, apps/api/src/app/workflows/usecases/delete-workflow-override/delete-workflow-override.usecase.ts, apps/api/src/app/workflows/usecases/index.ts, apps/api/src/app/workflows/workflow.controller.ts
* Workflow configurations (enabled, disabled)
* Channel Preferences
In some cases particular workflows should be managed in coordination with a given tenant, meaning that for a workflow:
* Tenants can have different preference defaults
* The tenant can have the whole workflow as disabled altogether
* add delete workflow override usecase.
* e2e
=> Delete workflow override use-case

apps/api/README.md, apps/api/package.json
* Modifies the existing and now defunct `migration` script to allow the migration script path to be provided as a positional npm script argument
* Removes feature specific migration scripts in favour of the new pattern. These are unreleased migrations, so no customer impact is expected.
* Adds documentation for API database migrations
Every time a new migration script is added, we are currently adding a new NPM script. This is not DRY and can result in migrations being run differently. Furthermore, abstracting this pattern will enable us to write consistent documentation for our users to migrate their self-hosted Novu databases.
_Migrations section in `apps/api/README.md`_
=> chore(api): Add generic migration helper script

pnpm-lock.yaml, providers/sparkpost/jest.config.js, providers/sparkpost/package.json, providers/sparkpost/src/lib/sparkpost.error.ts, providers/sparkpost/src/lib/sparkpost.provider.ts
Migrate from non mantained SparkPost SDK to direct API calls with axios.
This PR is tested manually with real credentials against real API.
> Email sent by provider with attachment
Closes #4588
- SparkPost API reference: https://developers.sparkpost.com/api/transmissions/
=> refactor(providers): migrate from sparkpost sdk to axios

README.md
Changes package in npm badges from `novu` to `@novu/node`.
It also fixes some weird line with mixed markdown syntax and HTML.
In my opinion we should show `@novu/node` package in readme badges. Why? Because this is package that developers are going to use and it also has 50k+ downloads/month, so it will show better numbers.
HTML and markdown shouldn't be mixed in single line:
> This is how README looks like in official GitHub Mobile app
=> chore: update npm badges in readme

apps/api/src/app/widgets/widgets.controller.ts
Closes NV-3180
Trying to call split on a number causes an unexpected exception
=> fix(api): eliminate number conversion for split message

apps/web/cypress/tests/notification-editor/variants.spec.ts, apps/web/src/pages/templates/components/EditorSidebarHeaderActions.tsx, apps/web/src/pages/templates/components/VariantsPage.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNode.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNodeActions.tsx, libs/shared/src/types/channel/index.ts
Disable the add variant flow for the digest and delay steps (we don't support it currently on the backend).
https://github.com/novuhq/novu/assets/2607232/9fe2aa57-8ac9-44d6-9f56-d3be6ac7e472
=> chore(web): disable add variant flow for the digest and delay

apps/web/cypress/tests/notification-editor/variants.spec.ts, apps/web/src/pages/templates/components/EditorSidebarHeaderActions.tsx, apps/web/src/pages/templates/editor/TemplateEditorPage.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNode.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNodeActions.tsx
In the production environment:
1. Step and Variant node actions: 
- edit
- view existing conditions - if conditions exist
2. Step and Variant Editor header actions:
- view existing conditions - if conditions exist
- close
https://github.com/novuhq/novu/assets/2607232/e2e258b4-70cc-4f44-bf29-3f8f1859ac52
=> chore(web): step and variant actions in the production environment

apps/api/src/app/message-template/shared/sanitizer.service.spec.ts, apps/api/src/app/message-template/shared/sanitizer.service.ts
Adds preservation of style tags and attributes through the `sanitize-html` library configuration options. In-App and Email HTML content now preserves style tags and attributes on save.
Closes [NV-3026](https://linear.app/novu/issue/NV-3026/on-update-button-click-css-styles-are-removed-in-in-app-template)
[In-App Editor Update: Preserving Style Tags and Attributes - Watch Video](https://www.loom.com/share/c55832f7552f4aeaaa45e32241520cf9)
=> feat(api): Allow style tags and attributes in the In-App & Email Editor

apps/api/package.json
Loads the built docker to the local machine.
Community tests been failing due to latest tag not found. See docker docs: https://docs.docker.com/engine/reference/commandline/buildx_build/#load
=> fix(ci): docker build test.yml for forks

providers/africas-talking/src/lib/africas-talking.provider.ts, providers/firetext/src/lib/firetext.provider.ts, providers/forty-six-elks/src/lib/forty-six-elks.provider.ts, providers/generic-sms/src/lib/generic-sms.provider.ts, providers/infobip/src/lib/infobip.provider.ts, providers/kannel/src/lib/kannel.provider.ts, providers/maqsam/src/lib/maqsam.provider.ts, providers/nexmo/src/lib/nexmo.provider.ts, providers/plivo/src/lib/plivo.provider.ts, providers/sendchamp/src/lib/sendchamp.provider.ts, providers/sms-central/src/lib/sms-central.provider.ts, providers/sms77/src/lib/sms77.provider.ts, providers/telnyx/src/lib/telnyx.provider.ts, providers/twilio/src/lib/twilio.provider.ts
Added `options.from` in those SMS provider which support from value
In https://github.com/novuhq/novu/pull/4168 PR, we added support for overrides in SMS providers. Currently `to` and `content` overrides is working fine but `from` value is not taken from overrides.
=> fix(sms): add options from in sms providers

apps/web/src/components/layout/components/HeaderNav.tsx
Track the user theme preference. Unfortunately the way it is implemented we are not able to send two separate events: when the app is loaded and when the theme is changed.
=> chore(web): segment track the user theme preference

apps/api/README.md
Resolves #4869 
This pull request addresses the issue where clicking on the "Run in Local Machine" button redirects users to the introduction page instead of the expected "Run in Local Machine" page. The fix involves updating the redirection logic to ensure that users are directed to the correct page when initiating the "Run in Local Machine" action.
Modified the redirection logic for the "Run in Local Machine" button.
Verified the correct behavior by testing the redirection after the fix.
=> fix(docs): Fix Redirect Issue for "Run in Local Machine" Button

apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts
Add raw error for `CHAT_WEBHOOK_URL_MISSING` and `SUBSCRIBER_NO_ACTIVE_INTEGRATION` so that user can debug the issue from activity feed logs
=> feat(worker): add raw error details for chat channel errors

providers/braze/README.md
The import statement in the code was not right. The correct way to import is using ' ' quotes
The current code will not handle the import as there is an syntax mistake . It should be corrected for the correct working of the code
=> docs(providers): Fix syntax mistake

providers/clickatell/README.md
Clickatell documentation incorrectly shows TwilioSmsProvider  instead of ClickatellSmsProvider
Fixes a typo of TwilioSmsProvider in when it should be ClickatellSmsProvider 
Fixes documentation.
=> docs(providers): Clickatell documentation incorrectly shows TwilioSmsProvider 

apps/web/src/pages/invites/components/MembersTable.tsx
NV-3227
Drop down was cut half in most screens.
Current behaviour:
=> fix(web): position of dropdown arrow for team page

packages/application-generic/src/services/in-memory-provider/cache-in-memory-provider.service.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.spec.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts, packages/application-generic/src/services/in-memory-provider/providers/azure-cache-for-redis-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/elasticache-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/memory-db-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/providers.ts, packages/application-generic/src/services/in-memory-provider/providers/redis-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/redis-provider.ts, packages/application-generic/src/services/in-memory-provider/types.ts, packages/application-generic/src/services/in-memory-provider/workflow-in-memory-provider.service.ts
Dependency injection of the provider and its config in InMemoryProviderService.
This allows configuration overriding and will allow multiple instances of the same provider with different configurations.
=> feat(infra): d.i. config and provider in in-memory provider service

.cspell.json
* Adds rate limit terms to cspell dictionary
* The cspell check did not run on the original PR for an unknown reason.
N/A
=> fix(api): Add spelling for rate limiting to cpsell dictionary

apps/api/e2e/compile-email-template.e2e.ts, packages/application-generic/src/usecases/compile-email-template/templates/basic.handlebars
This PR changes [basic.handlebars](https://github.com/novuhq/novu/compare/next...JoeyEamigh:novu:fix/editor-button-escaping?expand=1#diff-5e57d7ef68eade062d5ddaf60f552d53c66e6800074a7abe13ac5517d2b284dfL38-R40) to use triple curly braces for button content, as [compile-email-template.usecase.ts](https://github.com/JoeyEamigh/novu/blob/cece21e27e9e535a51622e27d61326b7d10fa09e/packages/application-generic/src/usecases/compile-email-template/compile-email-template.usecase.ts#L108-L114) already escapes the content of a button if the template is using double curly braces. Fixes my issue #4851 and may be related to #2063 and #2564.
When providing a complex URL like `https://example.com?email=button+testing@example.com` to the button template, it would be escaped regardless of whether double or …
=> fix(worker): Properly Unescape Button Templates (fixes #4851)

apps/api/package.json, apps/api/src/app.module.ts, apps/api/src/app/content-templates/content-templates.controller.ts, packages/application-generic/package.json, packages/application-generic/src/usecases/compile-email-template/compile-email-template.usecase.ts, packages/application-generic/src/usecases/compile-in-app-template/compile-in-app-template.usecase.ts, packages/application-generic/src/usecases/compile-template/compile-template.base.ts, packages/application-generic/src/usecases/send-test-email/send-test-email.usecase.ts, pnpm-lock.yaml
=> Fix nx circular dependencies

apps/api/src/app/auth/auth.controller.ts
To prevent browser storing on disk sensitive tokens
=> feat(api): dont cache auth endpoints

libs/shared/src/consts/providers/credentials/provider-credentials.ts
Make APNS provider `Production` field to be optional and default to `false`.
https://github.com/novuhq/novu/assets/2607232/3d17361b-f429-45d9-a286-22846bd4fd62
https://github.com/novuhq/novu/assets/2607232/377246cb-7c31-44cb-935d-16e720d998d7
=> chore(web): make apns provider production field optional

apps/web/src/pages/templates/components/EditorSidebarHeaderActions.tsx, apps/web/src/pages/templates/workflow/workflow/node-types/WorkflowNodeActions.tsx
Updated the conditions icon on the Workflow Editor node and in the Variants List sidebar.
https://github.com/novuhq/novu/assets/2607232/26cb108a-7d57-4a70-8078-d4c62ea9b481
=> chore(web): update the conditions icon

apps/api/.spectral.yaml
* Disables cspell on Spectral file
Cspell failed to detect changes in tests before merging to next. Spectral will continue to have many cspell errors due to the JSON pointer syntax used, hence the full disable.
N/A
=> fix(api): Disable cspell on spectral file

libs/shared/src/types/events/index.ts, packages/stateless/src/lib/template/template.interface.ts, providers/sendgrid/src/lib/sendgrid.provider.ts
CID attachment is used for inline image embedding
Example:- 
To show novu logo as inline embed in html
```
<html>
<body>
<p>Before image</p>
<p>After image</p>
</body>
</html>
```
Sendgrid attachment example code:-
```
{
"content": "imageFileBase64",
"filename": "index.jpeg",
"type": "image/jpeg",
"disposition": "inline",
"content_id": "novu-logo"
}
```
Novu has 3 fields for attachments currently:-
```
{
file: "base64 of file",
name: 'file_name.jpeg',
mime: 'image/jpeg',
}
```
Definition of Done
Add new fields to support CID based attachments
=> Add support for cid based attachment in email

apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/web/src/components/execution-detail/ExecutionDetailsStepHeader.tsx, apps/worker/src/app/workflow/usecases/queue-next-job/queue-next-job.usecase.ts, libs/dal/src/repositories/job/job.repository.ts, packages/application-generic/src/usecases/add-job/add-job.usecase.ts, packages/application-generic/src/usecases/add-job/merge-or-create-digest.command.ts, packages/application-generic/src/usecases/add-job/merge-or-create-digest.usecase.ts, packages/application-generic/src/usecases/create-execution-details/types/index.ts
For a digest with filters that passes - it sent separate message for each trigger, instead of aggregating the events into one message. 
Another problem fixed in this PR, is that a digest that is filtered (message should be sent immediately) was merged into a current delayed digest.
Closes #4957
=> fix: digest with passing filters are not aggregated

apps/web/src/pages/integrations/IntegrationsList.tsx
This PR fixes the incorrect alignment of the Integrations store's add button with the heading "Integrations Store".
The change was to perfectly align the "add a provider" button with the heading on the page as in the case of other routes like workflows as shown in the screenshot attached
Fixes #4943
expected behavior as in case of Workflows
actual behavior
after change behavior
=> fix(web): Fixed Integrations Store's add button alignment

packages/application-generic/src/services/in-memory-provider/cache-in-memory-provider.service.ts, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.spec.ts, packages/application-generic/src/services/in-memory-provider/providers/azure-cache-for-redis-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/elasticache-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/index.ts, packages/application-generic/src/services/in-memory-provider/providers/memory-db-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/providers.ts, packages/application-generic/src/services/in-memory-provider/providers/redis-cluster-provider.ts, packages/application-generic/src/services/in-memory-provider/providers/redis-provider.ts, packages/application-generic/src/services/in-memory-provider/types.ts, packages/application-generic/src/services/in-memory-provider/workflow-in-memory-provider.service.ts
Allows to select from environment variables the provider for the Workflow Engine and the Cache Service. In the case of not being set up by the new method it will fall back to the retro-compatible current way.
To simplify the configuration of the providers for the Workflow Engine and the Cache service and allow the users to choose their own providers.
New environment variables to set up the providers:
```
process.env.CACHE_PROVIDER_ID;
process.env.CACHE_HOST;
process.env.CACHE_PORTS;
process.env.CACHE_USERNAME;
process.env.CACHE_PASSWORD;
process.env.WORKFLOW_PROVIDER_ID;
process.env.WORKFLOW_HOST;
process.env.WORKFLOW_PORTS;
process.env.WORKFLOW_USERNAME;
process.env.WORKFLOW_PASSWORD;
```
Potentially we can add the rest of the configuration. That could be done further down the line.
=> feat(infra): select provider from environment variables

.idea/vcs.xml, apps/api/src/app/workflows/dto/index.ts, apps/api/src/app/workflows/dto/variables.response.dto.ts, apps/api/src/app/workflows/usecases/get-workflow-variables/get-workflow-variables.command.ts, apps/api/src/app/workflows/usecases/get-workflow-variables/get-workflow-variables.usecase.ts, apps/api/src/app/workflows/usecases/index.ts, apps/api/src/app/workflows/workflow.controller.ts, libs/shared/src/consts/handlebar-helpers/getTemplateVariables.ts, packages/application-generic/src/services/cache/key-builders/entities.ts, packages/application-generic/src/services/cache/key-builders/shared.ts
Implement the endpoint that will return for a given template all the system and translation variables.
We need to provide the information about what variables are accessible to the user when editing the template content in the editor. We have introduced the translation variables which are dynamic and based on the uploaded translation files.. System variables are hardcoded on the FE, which is bad. All of the above is a reason for creating the new endpoint.
=> Nv 2991 endpoint to return all the template variables

providers/resend/src/lib/resend.provider.ts
Added `options.senderName` so that sendername from payload/overrides/template is used and in absence of all of three config one is used
=> fix: add options in resend senderName

apps/api/src/app/testing/translations/edit-translation.e2e-ee.ts, libs/design-system/src/sidebar/Sidebar.tsx
- Added Edit translation file functionality
- added endpoint to handle saving of edited files and fileName
- Added Editor support for translation file
- Added error states in the editor
- Added add new translation file screen
https://github.com/novuhq/novu/assets/29251776/d85f95ff-281f-4f89-963b-68b87402b0ba
=> Nv 2899 edit translation file

libs/embed/Dockerfile
These changes will allow us to use user 1000 instead of ROOT to support running containers on k8.
It's needed to support running containers on k8 and for security reasons. I missed the embed service when I was working on [this PR](https://github.com/novuhq/novu/pull/5084)
The main process is run by user 1000 after these changes
=> fix(pkg): User 1000 instead of root

apps/web/cypress/tests/notification-editor/variants.spec.ts, apps/web/src/components/conditions/Conditions.tsx, apps/web/src/pages/templates/components/EditorSidebarHeaderActions.tsx, apps/web/src/pages/templates/components/VariantItemCard.tsx
Front-end fixes for preventing empty variant conditions
- Introduces test to catch issue with saving variants with empty conditions
- Disable submit button and add tooltip when removing all conditions from a variant
Fixes NV-3147
=> fix(web): prevent updating variants to have empty conditions (front-end only)

apps/web/src/pages/templates/components/CustomCodeEditor.tsx, apps/web/src/pages/templates/components/email-editor/AutoSuggestionsDropdown.tsx
In i18n autocomplete, it completes to file.key but the usage is "file.key".
It should complete with the quotations
=> fix: autocomplete i18n files with quotations

apps/api/src/app/events/e2e/trigger-event.e2e.ts, apps/worker/src/app/workflow/usecases/queue-next-job/queue-next-job.usecase.ts, packages/application-generic/src/usecases/add-job/add-job.command.ts, packages/application-generic/src/usecases/add-job/add-job.usecase.ts
Bug fix - a delay as a first step didn't apply filters, the delay was still executed. The problem was that the check of the filters for action steps was done in the queue-next-step usecase but when delay is the first step that usecase is not executed and add-job is first (there was no problem with digest because we add a trigger step for digest)
=> fix: filters dont apply to a delay that is the first step in workflow

apps/web/src/api/hooks/index.ts, apps/web/src/api/hooks/notification-templates/index.ts, apps/web/src/api/hooks/notification-templates/useWorkflowVariables.ts, apps/web/src/pages/templates/components/CustomCodeEditor.tsx, apps/web/src/pages/templates/components/email-editor/TextRowContent.tsx, apps/web/src/pages/templates/components/email-editor/variables-management/VariablesManagement.tsx
1. Fixes the unhandled exception when the workflow variables object is undefined (while the request is loading).
2. Small refactor that creates a reusable `useWorkflowVariables` hook that is used everywhere in the code: editor, custom code, variables sidebar.
=> chore(web): translation management handle undefined workflow variables object

providers/sendinblue/src/lib/brevo.provider.ts
Hi guys !
First of all, a big thank you for this great work on Novu! ❤️ 
While working with Novu, I realized that email templates for Brevo (formerly SendinBlue) were not supported. This is why I am opening this little PR.
Hoping it will be available in the next release! 🤞 
Don't hesitate if there is a need for more info or modification.
Closes #5122
=> feat(brevo): add support for brevo email templates

libs/shared/src/consts/providers/credentials/provider-credentials.ts, providers/generic-sms/src/lib/generic-sms.provider.ts
1. Updae `datePath` and `authenticateByToken` as required false in generic SMS provider
2. Add current date as fall back date in response of generic SMS provider
=> fix: make date path and authenticate by token optional

apps/web/src/pages/templates/components/CustomCodeEditor.tsx
Translation missing warning was not working. The wrong variable object was being sent to process
=> fix: translation missing warning not working

apps/api/src/app/widgets/widgets.controller.ts, packages/client/src/api/api.service.ts, packages/headless/src/lib/headless.service.ts, packages/headless/src/lib/types.ts
=> feat(headless): add remove notifications method

apps/api/src/app/subscribers/e2e/bulk-create-subscribers.e2e.ts, libs/dal/src/repositories/subscriber/subscriber.repository.ts
When deleted subscribers are "recreated" with bulk create endpoint we will "mark" them as `deleted: false` (not deleted).
https://github.com/novuhq/novu/assets/2607232/247f749a-498f-4092-bee4-4bb2b161c10d
=> fix(api): bulk create subscribers after they were deleted

packages/client/src/api/api.service.ts, packages/headless/src/lib/headless.service.test.ts, packages/notification-center/src/hooks/index.ts
Fixes the payload on bulk remove messages in the API client.
=> Fix client payload on remove messages

.gitignore, enterprise/packages/auth/package.json, enterprise/packages/auth/src, enterprise/packages/billing-web/package.json, enterprise/packages/billing/package.json, enterprise/packages/libs/dal/package.json, enterprise/packages/libs/dal/src, enterprise/packages/translation-web/package.json, enterprise/packages/translation-web/src, enterprise/packages/translation/package.json, enterprise/packages/translation/src, package.json, scripts/symlink-ee.mjs
* [feat: Add ee symlinking script](https://github.com/novuhq/novu/commit/145dfdf84bfa77b16ec35e14d2be51cb246f5df5)
* [fix: Add nx cache to gitignore](https://github.com/novuhq/novu/commit/17258086251b2f78b851355ab04768f29b6e4a85)
* [fix: Git ignore ee symlink binaries](https://github.com/novuhq/novu/commit/6e9d20adf23dfb94473554463b26a0969780ff23)
* [refactor: Remove redundant symlink script from ee package.json](https://github.com/novuhq/novu/commit/5a22ac94d009928500176f76e962338c41d17d32)
* Each EE package needed a symlink script with custom file depth, we can abstract this into a script following a common pattern.
* Symlinks were being checked into source, this will cause broken symlinks for community contributors
* Symlinks were recursively nesting in EE src folders
* Without the …
=> refactor(infra): EE symlinks

apps/api/src/app/message-template/usecases/create-message-template/create-message-template.usecase.ts, apps/api/src/app/workflows/e2e/update-notification-template.e2e.ts, apps/web/src/pages/templates/components/in-app-editor/preview/InAppWidgetPreview.tsx
Resolve the issue where the user is storing an invalid value under message-template.cta.action
bug
=> Nv 3475 - typeerror cannot create property buttons on string

apps/api/src/app/message-template/usecases/create-message-template/create-message-template.usecase.ts, apps/api/src/app/workflows/e2e/update-notification-template.e2e.ts, apps/web/src/pages/templates/components/in-app-editor/preview/InAppWidgetPreview.tsx
=> hotfix: NV-3475

.github/actions/docker/build-api/action.yml, .github/actions/run-api/action.yml, apps/api/Dockerfile
**What?**
Revert these commits to re-enable NX Caching for API build and run tasks: 
* https://github.com/novuhq/novu/commit/14311d43cd0262116995c1a864caaa655e00a1cc
* https://github.com/novuhq/novu/commit/055e08c60caefe3c73b3d0239debe6f55fdbe9d7
**Why? (Context)**
The commit disables NX caching of the API build and run artifacts, including all providers. The build duration was 1.25 hours without caching, and re-enabling the NX cache will significantly improve build speed (see [this build](https://github.com/novuhq/novu/actions/runs/7865361667/job/21458232629?pr=5152)).
**Definition of Done**
Dev API run and build scripts are cache and run faster
**Results**
* Build API Run -
=> revert(api): Disabling NX cache

.gitignore
* Adds the src symlink directories back under the git file tree
NX was failing to cache the `src` folder for EE repos because it [tracks the `.gitignore` file by default](https://nx.dev/reference/nxignore). This resulted in the `src` folder not being copied across into Docker when NX replays the `build` task dependency on EE packages via the `build:api` command, and therefore no `src` is available for building the API dependencies.
_Inspecting Docker file system before change_
```bash
> docker exec -it novu-api sh
/usr/src/app/apps/api $ cd ../../enterprise/packages/billing
/usr/src/app/enterprise/packages/billing $ ls -la
total 36
drwxr-xr-x    1 node     node          4096 Feb 12 13:56 .
drwxr-xr-x    1 node     node          4096 Feb 12 13:52 ..
-rw-r--r--    1 node     node …
```
=> fix(infra): Remove gitignore for EE symlinked src folders

apps/api/migrations/topic-subscriber-normalize/topic-subscriber-normalize.migration.spec.ts, apps/api/migrations/topic-subscriber-normalize/topic-subscriber-normalize.migration.ts, apps/api/src/app/subscribers/e2e/remove-subscriber.e2e.ts, apps/api/src/app/subscribers/usecases/remove-subscriber/remove-subscriber.usecase.ts
Subscribers can be added in topic using subscriberId. 
Subscriber can be deleted later using API or SDK, however a user manually also has to delete them from every topic they where apart of.
If subscriber is deleted, it is still part of topic
Currently user had to call API to first check if subscriber is part of any topic then remove that subscriber from topic.
* Novu should automatically handle this usecase
* The migration script to remove not existing subscribers from the topics
=> Auto Remove Deleted Subscribers from topic

apps/api/Dockerfile, apps/inbound-mail/Dockerfile, apps/worker/Dockerfile
We face the issues during a docker build process:
```
#32 45.77  WARN  Issue while reading "/usr/src/app/.npmrc". Failed to replace env in config: ${BULL_MQ_PRO_NPM_TOKEN}
#32 45.77 
#32 45.77 > @novu/ee-billing@0.23.1 build /usr/src/app/enterprise/packages/billing
#32 45.77 > node ./check-ee.mjs
```
[CI page](https://github.com/novuhq/novu/actions/runs/7834909085/job/21379680417#step:6:1212)
=> fix(ci): Mount token to a build svc command

apps/web/src/pages/get-started/components/GetStartedAnimationContainer.tsx, apps/web/src/pages/get-started/components/timeline/Timeline.styles.ts, apps/web/src/pages/get-started/consts/DelayUseCase.const.tsx, apps/web/src/pages/get-started/consts/DigestUseCase.const.tsx, apps/web/src/pages/get-started/consts/InAppUseCase.const.tsx, apps/web/src/pages/get-started/consts/MultiChannelUseCase.const.tsx, apps/web/src/pages/get-started/consts/TranslationUseCase.const.tsx, apps/web/src/pages/get-started/consts/shared.tsx, apps/web/src/pages/integrations/useGetIntegrationsByChannel.ts
- Add all static links for each use case
- Connect In-App tab to specific Integration store side panel
- Create abstraction to make adding animations easier for the different color schemes
- Fix Timeline styling in light mode
- Reduces future work while we await next steps (for [NV-3243](https://linear.app/novu/issue/NV-3243/🙋-in-app-use-case-tab) - 3247)
https://www.loom.com/share/1d42b72c833e4f128353721d0cc420b3?sid=6fde9997-ecb6-4bd0-806a-a2bacf1d76b0
=> [Onboarding] - Groundwork for all use cases

.github/workflows/reusable-web-deploy.yml
What?
Add the REACT_APP_STRIPE_CLIENT_KEY to the env config
Add secret to Github secrets
Why? (Context)
We need the Stripe env var for Stripe client components
Definition of Done
Stripe checkout loads correctly
=> chore: Expose stripe client key to Web app

apps/api/src/app/events/e2e/trigger-multicast.e2e.ts, apps/api/src/app/events/e2e/trigger-multicast.spec.ts, apps/api/src/app/topics/e2e/helpers/index.ts, libs/dal/src/repositories/base-repository.ts, libs/dal/src/repositories/topic/topic-subscribers.repository.ts, packages/application-generic/src/usecases/trigger-multicast/trigger-multicast.usecase.ts
Currently the process to pull all of the subscribers for a topic works until we start having the size of 2 million. This gives us a clue that we have not optimized this database call to efficiently get an "infinite" amount of subscriber.
However, this does put more issues in terms of idempotency to the system as what happens if a worker fails to create all of the jobs.
We should also consider caching topic calls pass as redis keys hold upto 512MB, however we are unsure if parsing that big of a document would be faster then calling mongodb
Fixing this will allow large companies with large topics to send them messages without failure at the database level.
* mongo qurey uses pagination
* paginated query must be able to be used for other models
References …
=> feat(worker): add topics fanout in batches by cursor

apps/api/e2e/setup.ts, apps/api/src/app/testing/billing/create-usage-records.e2e-ee.ts, apps/api/src/app/testing/billing/get-platform-notification-usage.e2e-ee.ts, apps/api/src/app/testing/billing/get-prices.e2e-ee.ts, apps/api/src/app/testing/billing/upsert-subscription.e2e-ee.ts, apps/api/src/app/testing/billing/verify-customer.e2e-ee.ts, apps/api/src/app/testing/billing/webhook.e2e-ee.ts, apps/api/tsconfig.build.json, enterprise/packages/billing/package.json, packages/application-generic/src/services/in-memory-provider/in-memory-provider.service.ts
* Point to `next` EE submodule reference.
* Add unit tests for Billing use-cases
* Warn on in-memory shutdown failure to improve testing UX
* Stop truncating Chai error messages to improve testing UX
* Bringing in latest EE changes.
* Verifying the logic in Billing use-cases
_Test suite passing_
_In-memory provider error changed to `warn` log, no longer showing in test cli output_
```bash
[11:56:35.970] ERROR (97434): [Provider: Elasticache] In-memory provider service shutdown has failed
serviceName: "@novu/api"
serviceVersion: "0.23.1"
platform: "Docker"
tenant: "OS"
context: "InMemoryProviderService"
err: {
"type": "Error",
"message": "Connection is closed.",
"stack":
Error: Connection is closed.
at InMemoryProviderService.<anonymous> …
```
=> test(api): Billing unit tests

apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/subscribers/usecases/chat-oauth-callback/chat-oauth-callback.usecase.ts, apps/api/src/app/subscribers/usecases/delete-subscriber-credentials/delete-subscriber-credentials.spec.ts, apps/api/src/app/subscribers/usecases/update-subscriber-channel/update-subscriber-channel.command.ts, apps/api/src/app/subscribers/usecases/update-subscriber-channel/update-subscriber-channel.spec.ts, apps/api/src/app/subscribers/usecases/update-subscriber-channel/update-subscriber-channel.usecase.ts
* Modify the existing `PUT /:subscriberId/credentials` operation to be idempotent
* Add a new `PATCH /:subscriberId/credentials` operation that appends to the deviceTokens array
* We are not currently following the PUT specification for the endpoint in question
* API clients would like to be able to append deviceTokens to an existing list
_OpenAPI spec including new PATCH operation, alongside existing PUT operation_
=> feat(api): Add idempotent subscriber credential update operation

apps/api/src/app/content-templates/content-templates.controller.ts, apps/worker/src/app/workflow/usecases/send-message/send-message.base.ts
[enterprise PR
](https://github.com/novuhq/packages-enterprise/pull/90)
When a subscriber has a locale set for him - but there is no such locale for the translation group -> use the default locale of the organization as a fallback.
Currently - it shows the translation keys in the content.
For example:
Organization default locale is en_US
The subscriber locale is en_CA
In the editor there is {{i18n group.key}}and the group has a translation file for en_US but not one for  en_CA. 
Currently, for this subscriber it will show in the message the text group.key 
It should show the translation provided for the default locale
=> feat: add fallback lng

apps/web/cypress/tests/digest-playground.spec.ts, apps/web/cypress/tests/integrations-list-modal.spec.ts, apps/web/cypress/tests/integrations-list-page.spec.ts, apps/web/cypress/tests/layout/side-menu.spec.ts, apps/web/src/components/layout/components/SideNav.tsx, apps/web/src/components/quick-start/digest-demo-flow/consts.ts, apps/web/src/components/utils/Spotlight.tsx, apps/web/src/pages/auth/components/SignUpForm.tsx, apps/web/src/pages/integrations/components/FrameworkDisplay.tsx, apps/web/src/pages/integrations/components/NovuInAppForm.tsx, apps/web/src/pages/integrations/components/NovuInAppFrameworks.tsx, apps/web/src/pages/integrations/components/NovuProviderBase.tsx, apps/web/src/pages/quick-start/consts.tsx, apps/web/src/pages/quick-start/steps/GetStarted.tsx, apps/web/src/pages/templates/TemplatesDigestPlaygroundPage.tsx, libs/design-system/src/iconsV2/IconProvider.tsx, libs/shared/src/consts/providers/channels/chat.ts, libs/shared/src/consts/providers/channels/email.ts, libs/shared/src/consts/providers/channels/in-app.ts, libs/shared/src/consts/providers/channels/push.ts, libs/shared/src/consts/providers/channels/sms.ts, libs/shared/src/ui/index.ts, libs/shared/src/ui/marketing.ts
To all `https://novu.co` and `https://docs.novu.co` references in the app, we would like to add the marketing `utm_campaign=in-app` query param.
=> chore(web): marketing utm campaign on doc links

docker/kubernetes/helm/README.md, docker/kubernetes/helm/values.yaml
In the Helm README.md and values.yaml, the installation instructions have been changed to include command for setting the encryption key. The default encryption key in values.yaml has been removed. This is done for providing more security by advising users to set their own encryption keys during the installation process.
=> Remove Helm Default Encryption Key

packages/application-generic/src/usecases/add-job/add-job.usecase.ts
Passes step to conditionsFilter.filter so it correctly recognises when a digest filter depends on subscriber.
Closes #5163
=> fix: subscriber details not available for digest filters

apps/web/src/api/hooks/notification-templates/useCreateDigestDemoWorkflow.ts, apps/web/src/components/quick-start/in-app-onboarding/TriggerNode.tsx, apps/web/src/constants/workflowConstants.ts, apps/web/src/hooks/useTemplates.ts, apps/web/src/pages/activities/ActivitiesPage.tsx, apps/web/src/pages/templates/WorkflowListPage.tsx, libs/design-system/src/pagination/usePaginationState.spec.tsx, libs/design-system/src/pagination/usePaginationState.ts
This PR fixes a few problems:
- the paginated search params on the Activity Feed page from the `useTemplates` hook
- query cache issue when navigating between Workflows and Activity Feed pages (on slow network)
Before:
https://github.com/novuhq/novu/assets/2607232/49629106-d507-4fea-aba5-e53fe38fbde3
Now:
https://github.com/novuhq/novu/assets/2607232/dba64f00-8b05-4d81-a13a-58c006c790f8
=> fix(web): pagination search params on activity feed page

apps/web/cypress/global.d.ts, apps/web/cypress/plugins/index.ts, apps/web/cypress/support/commands.ts, apps/web/cypress/tests/get-started-page.spec.ts, apps/web/cypress/tests/templates-store.spec.ts, apps/web/src/pages/get-started/components/OpenWorkflowButton.tsx, apps/web/src/pages/get-started/consts/DelayUseCase.const.tsx, apps/web/src/pages/get-started/consts/DigestUseCase.const.tsx, apps/web/src/pages/get-started/consts/InAppUseCase.const.tsx, apps/web/src/pages/get-started/consts/MultiChannelUseCase.const.tsx, apps/web/src/pages/get-started/consts/TranslationUseCase.const.tsx, apps/web/src/pages/get-started/consts/shared.tsx, apps/web/src/pages/quick-start/components/layout/GetStartedLayout.tsx, libs/shared/src/consts/template-store/index.ts, libs/testing/src/notification-template.service.ts
- Small tweaks for tabs
- Cypress tests for the Get Started page
- Closes [NV-3262](https://linear.app/novu/issue/NV-3262/%F0%9F%99%8B-tests-for-the-onboarding-functionality)
=> [Onboarding] NV-3262 | Cypress tests

libs/design-system/src/pagination/ControlButton.tsx, libs/design-system/src/pagination/GoToPageInput.tsx
- Change `GoToInput` to controlled input to reset the value onBlur; uncontrolled was auto-clamping despite attempting to reset the value via a ref.
- Disable autocomplete / autosuggest -- MANTINE, WHY?!
- Remove invalid prop from being passed to the DOM
- Fixes [NV-3497](https://linear.app/novu/issue/NV-3497/fix-go-to-page-behaviour-for-pagination)
_Note: no warnings in the console about `isCurrentPage` being an invalid DOM prop_
https://www.loom.com/share/0ec132d17e9c4167a6783720dded96d5?sid=3954ff36-da84-47ee-9c31-ec0684f952ce
=> NV-3497 - Pagination Tweaks

.github/workflows/dev-deploy-api.yml, .github/workflows/dev-deploy-inbound-mail.yml, .github/workflows/dev-deploy-worker.yml, .github/workflows/dev-deploy-ws.yml, .github/workflows/prod-deploy-api.yml, .github/workflows/prod-deploy-inbound-mail.yml, .github/workflows/prod-deploy-worker.yml, .github/workflows/prod-deploy-ws.yml, .github/workflows/reusable-api-e2e.yml, .github/workflows/reusable-docker.yml, .github/workflows/reusable-inbound-mail-e2e.yml, .github/workflows/reusable-web-e2e.yml, .github/workflows/reusable-webhook-e2e.yml, .github/workflows/reusable-widget-deploy.yml, .github/workflows/reusable-widget-e2e.yml, .github/workflows/reusable-worker-e2e.yml, .github/workflows/test.yml
The runner type for all Github Workflows has been updated to 'ubuntu-latest-large'. This change aims to provide more resources for the jobs' execution, improving performance and stability by increasing cpus and storage on critical builds
=> Update runner type to ubuntu-latest-large

providers/gupshup/src/lib/gupshup.provider.ts
- fixed Gupshup provider request format to use form-encoded
- [Gupshup docs](https://docs.gupshup.io/docs/sample-code#sample-nodejs-code-for-sending-a-single-message)
=> fix: Update Content-Type header to application/x-www-form-urlencoded

.vscode/settings.json
Update enterprise submodule to bring in billing changes.
=> chore: Update submodule

apps/api/src/app/testing/translations/update-default-locale.e2e-ee.ts
[Enterprise PR
](https://github.com/novuhq/packages-enterprise/pull/103)
When the default language is changed for the organization we should also update all associated translation groups with that new default language, meaning we should create a new empty translation but only when it doesn't exist.
=> Update groups for new default language

.github/workflows/dev-deploy-web-component.yml, .github/workflows/prod-deploy-web-component.yml, .github/workflows/reusable-notification-center.yml
This PR introduce the changes to fix Notification Center Component Pipeline. The NC pipeline is not picking up a correct artifact and is not able to deploy it. The ticket is [INF-291](https://linear.app/novu/issue/INF-291/fix-notification-center-component-pipeline)
Example of the pipeline that was failed https://github.com/novuhq/novu/actions/runs/8177087539
Most likely cause is versions capability. I checked and it was confirmed, the version `actions/download-artifact@master` 
can't work with `actions/upload-artifact@v3`. The Action was updated about 3 month ago and since then the workflow has no success. 
It's an importartant to have a comatible version. See [GitHub Documentation](https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#which-versions-of-the-artifacts-p …
=> fix(ci): Versions compatibility

apps/api/src/app/shared/dtos/pagination-request.ts, apps/api/src/app/shared/dtos/pagination-with-filters-request.ts, apps/api/src/app/shared/types.ts, apps/api/src/app/subscribers/subscribers.controller.ts, apps/api/src/app/tenant/tenant.controller.ts, apps/api/src/app/widgets/widgets.controller.ts, apps/api/src/app/workflow-overrides/workflow-overrides.controller.ts, apps/api/src/app/workflows/dto/workflows-request.dto.ts, apps/api/src/app/workflows/e2e/get-notification-templates.e2e.ts, apps/api/src/app/workflows/notification-template.controller.ts, apps/api/src/app/workflows/usecases/get-notification-templates/get-notification-templates.command.ts, apps/api/src/app/workflows/usecases/get-notification-templates/get-notification-templates.usecase.ts, apps/api/src/app/workflows/workflow.controller.ts, libs/dal/src/repositories/notification-template/notification-template.repository.ts, libs/dal/src/repositories/notification-template/notification-template.schema.ts
Allow searching workflows by name or trigger identifier.
=> feat(api): search workflows by name or trigger identifier

apps/web/src/pages/templates/components/email-editor/TextRowContent.tsx
In the editor, after adding a {{..}} once. Writing only one { opens the autocomplete dropdown, when adding the second { (so its {{ ) the dropdown does not show again.
The slice was wrong, at the second input of {{ it took the whole content and so used the indexes of the first {{
=> Editor autocomplete - does not open in a second use

apps/api/src/app/integrations/usecases/create-novu-integrations/create-novu-integrations.usecase.ts, apps/api/src/app/organization/e2e/create-organization.e2e.ts
FIX: when creating a new org, Novu Email and SMS providers are not marked as primary on all environments.
Once a user creates a new organization, everything should work out of the box
=> fix: set novu providers as primary for new orgs

apps/web/src/pages/integrations/components/IntegrationStatus.tsx, apps/web/src/pages/templates/components/ListProviders.tsx, apps/web/src/pages/templates/components/ProvidersPage.tsx
Fixed the issue in the Workflow Settings - Providers tab, that the channel "warning banners" were cut off.
https://github.com/novuhq/novu/assets/2607232/02d7cecf-2a9d-46b8-94c3-fc0a4e14c711
=> fix(web): workflow settings - providers warnings were cut off

apps/web/src/pages/templates/hooks/usePreviewEmailTemplate.ts, apps/web/src/pages/templates/hooks/usePreviewInAppTemplate.ts, apps/web/src/utils/utils.ts
Catch the parsing error for invalid json input on the variables assignment. 
I decided to return an empty payload so it will be more pronounced for the user that  the preview shown is without his variable assignments.
=> Unhandled Error: SyntaxError JSON.parse(<anonymous>)

apps/api/src/app/message-template/shared/sanitizer.service.spec.ts, apps/api/src/app/message-template/shared/sanitizer.service.ts
Novu used an npm packaged called [sanitize-html](https://www.npmjs.com/package/sanitize-html), [the default allowed tags](https://www.npmjs.com/package/sanitize-html#default-options), doesnt include img tags, this PR aims to include it as it was done for the style tag in this https://github.com/novuhq/novu/pull/4841.
Closes #5310
=> feat(api): Allow img tags in the In-App & Email Editor 

libs/dal/src/repositories/subscriber/subscriber.schema.ts, libs/dal/src/shared/types/index.ts, libs/dal/src/shared/types/index.type.ts
We want to optimize the call checking for non deleted subscribers.
This change is recommended by Mongodb Atlas.
As an alternative, the query may need to be changed.
This will increase the query speed of calls looking for non deleted subscribers and will increase the trigger speed.
=> feat(dal): add deleted index and type safety index

packages/notification-center/src/hooks/useInitializeSocket.ts
During our most recent incident we observed that the In-app notification center was constantly tring to reconnect to the websocket service and creating a thundering herd on our websocket system.
https://github.com/novuhq/novu/blob/4b9b81870a9a7b0aba9c0eb6fed547a48d46333b/packages/application-generic/src/resilience/delay.ts#L8
This will prevent our system from being overloaded if a network failure or a upgrade happens.
=> Add exponential backoff with jitter for the In-App Notification Center to re-establish WebSocket connections

apps/api/src/app/auth/e2e/login.e2e.ts, apps/api/src/app/auth/usecases/login/login.usecase.ts, apps/web/cypress/tests/auth.spec.ts, apps/web/src/pages/auth/components/LoginForm.tsx, apps/web/src/utils/errors.ts
This PR patches the following issue:
1. Sign up with Github with user A
2. Sign out
3. Try to sign in with the email of user A
4. The API returns a 400 error not displayed in the Login form right away in smaller screens.
After this PR, all server auth errors will be displayed in the UI.
It also contains some minor copywriting fixes and clean-ups.
https://github.com/novuhq/novu/assets/1352422/674ac4ef-7914-419d-bf48-99d3e163a752
=> fix: Surface all auth server errors during login in email input.

apps/web/src/components/layout/components/SideNav.tsx
Tweak scrollbar placement to stick to the right side of the sidebar.
In smaller screens or resolutions and especially in other OS (not in OSX) it looks like this:
https://github.com/novuhq/novu/assets/1352422/5619bfcc-19a3-4e1c-8171-3615774b17fa
=> fix(web): Tweak scrollbar placement in sidebar

apps/web/src/pages/templates/WorkflowListPage.tsx, apps/web/src/pages/templates/components/WorkflowSidebar.tsx
1. replace useLocalThemePreference hook with useMantineColorScheme 
2. replace chimera with echo in tooltip
To fix this issue 
https://github.com/novuhq/novu/assets/39362422/14affa15-a3f9-4059-93ba-e94587ec75a0
After fix:- 
https://github.com/novuhq/novu/assets/39362422/4cfe298e-e873-410a-aea8-182bd085958a
=> fix: used mantine color scheme hook to handle color scheme

apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts, providers/resend/src/lib/resend.provider.ts
1. handled resend error case
2. updated email message usecase raw field for error case
1. [Discord](https://discord.com/channels/895029566685462578/1224393606950031560)
2. [Slack](https://novu.slack.com/archives/C04STJLFJ65/p1711442745444539?thread_ts=1711376460.553099&cid=C04STJLFJ65)
Below is the error and success response format from Resend 👇🏻
=> fix: handle resend error case

.github/workflows/dev-deploy-worker.yml, .github/workflows/prod-deploy-worker.yml
* Remove CI steps for deploying Dev+Prod-US+Prod-EU redundant general worker
* The general worker has been removed from the infrastructure as code
The Github workflow is currently failing due to missing TF outputs:
https://github.com/novuhq/novu/actions/runs/8530276325/job/23368621576#step:8:13
=> chore(infra): Remove CI steps for redundant general worker

scripts/github-conventional-comments.js
- Provide script for setting up Conventional Comments in Github Saved Replies
- Establish a common and actionable language for reviews
=> Conventional comments setup

apps/worker/src/app/workflow/usecases/send-message/send-message-chat.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-in-app.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-push.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts
* Skip template rendering for Push, SMS, In-App, and Chat channels when chimera content is present
Push, SMS, and Chat channels re-map some payload attributes (e.g. for SMS, `content` becomes `body`). This causes the template rendering to be passed a falsy object, and subsequently, template rendering fails with the following error seen in the Activity Log (see other info).
The Email channel already has this conditional skip (https://github.com/novuhq/novu/blob/next/apps/worker/src/app/workflow/usecases/send-message/send-message-email.usecase.ts#L205) and therefore is working correctly. The remaining channels are updated to skip rendering.
Due to the In-App channel not having any payload remapping, this channel was not impacted, but has been updated also for consistency.
_Push_
_SMS_ …
=> fix(worker): Skip template rendering for Echo Workflow steps

apps/worker/src/app/workflow/usecases/send-message/send-message-sms.usecase.ts
* Move missing SMS content check inside echo conditional
SMS channel requires content to be present for successful delivery. This change moves the content check inside the echo conditional branch
N/A
=> fix(worker): Move missing SMS content check inside echo conditional

apps/widget/cypress/e2e/notifications-list.spec.ts, apps/widget/cypress/plugins/index.ts, packages/notification-center/src/components/notification-center/components/NotificationsList.tsx
Fixes the issue introduced in: #5019, with not scrollable parent component.
Fixes the Widget test for the infinite scroll which was always passing, and makes sure that the scroll event is triggered on the scrollable element.
https://github.com/novuhq/novu/assets/2607232/9bd2fd91-e95a-4a8b-8da0-6e7fac39462d
https://github.com/novuhq/novu/assets/2607232/be3ec601-f2d7-4baf-b900-ec4e074e19af
=> fix(notification-center,widget): infinite scroll issue

apps/web/src/initializeApp.ts
We've noticed that some Sentry errors are not application related, and are thrown by @sentry/react, which results in that we are seeing them in the Sentry dashboard, for example [the error](https://novu-r9.sentry.io/issues/3842125709/?project=6250907&query=is%3Aunresolved&referrer=issue-stream&stream_index=1) ResizeObserver loop completed with undelivered notifications.
We would like to configure the common ignore rules in our web application.
=> feat: decluttering sentry errors

apps/web/src/pages/templates/components/in-app-editor/InAppEditorBlock.tsx
The code editor was using a fixed height of 100px. Making it scroll even when there is available space.
This changes makes it take full height of its parent
Before:
After:
=> fix(web): make InApp code editor fit the height of its parent container

.github/workflows/pr-manager.yml
Update stale pull requests settings to be stale after 90 days, and closed after another 30 days.
To help with maintaince.
=> feat(ci): add stale bot for pull requests

libs/dal/package.json, libs/shared-web/package.json, pnpm-lock.yaml
It is just a clean up to speed up pnpm i a bit
=> chore: Remove unused dependencies

apps/web/panda.config.ts
- Add a new property to the panda config
- I was having issues with panda generating styles for `cva` (atomic recipes)
- A maintainer of Panda suggested that our nested output (`./src/styled-system`) was the reason, and thus suggested this as a fix ([Discord thread](https://discord.com/channels/1118988919804010566/1227407665672749088))
=> fix: Ensure panda works with nested output directory

apps/api/src/app/health/health.controller.ts, apps/webhook/src/health/health.controller.ts, apps/worker/src/app/health/health.controller.ts, apps/ws/src/health/health.controller.ts, apps/ws/src/socket/services/ws-server-health-indicator.service.ts, packages/application-generic/src/health/cache.health-indicator.ts, packages/application-generic/src/health/dal.health-indicator.ts
This PR throws the Terminus error when the indicator is unhealthy and applies minor code refactorings to most health indicators. Throwing the right error results in the correct status page result (see screenshots). 
Currently, the DAL and Cache health checks won't cause the overall health status of the app to return an error, as Terminus requires us to throw a HealthCheck error from the indicator when its status is unhealthy.
For more information, refer to https://docs.nestjs.com/recipes/terminus#custom-health-indicator
=> fix: Ensure health check return the correct status

.cspell.json, apps/web/src/pages/auth/components/QuestionnaireForm.tsx, apps/web/src/pages/auth/components/useDomainHook.ts
Add `useDomainParser` Hook
handle invalid domain field value
<details>
</details>
=> fix: add domain parser hook and domain condition

apps/web/src/pages/auth/components/SignUpForm.tsx
Customers can provide any single word as their full name. We don't benefit from being too strict about it during sign-up as the email address is what matters.
=> fix(web): Remove strict lastname validation

apps/api/src/config/cors.ts
- Add logging to gain visibility on why CORS error is still occurring for Deploy Previews
<details>
- Are there any concerns logging the information included in the context?
</details>
=> test: Add visibility for CORS processing

apps/api/migrations/subscribers/remove-duplicated-subscribers/remove-duplicated-subscribers.migration.spec.ts, apps/api/migrations/subscribers/remove-duplicated-subscribers/remove-duplicated-subscribers.migration.ts, apps/ws/src/shared/subscriber-online/subscriber-online.service.ts, libs/dal/src/repositories/subscriber/subscriber.repository.ts, libs/dal/src/repositories/subscriber/subscriber.schema.ts, libs/dal/src/shared/types/index.ts, libs/dal/src/shared/types/index.type.ts, libs/dal/src/types/error.enum.ts, libs/dal/src/types/index.ts, packages/application-generic/src/usecases/create-subscriber/create-subscriber.usecase.ts
During the burst of trigger events the processed subscribers might get duplicated in the database. This could happen due to the race conditions in the worker's concurrent processing.
Duplicated subscribers mean that the wrong document might be picked from the database and for example some fields might be missing (email), resulting in messages not being delivered.
We have to introduce the unique index on the subscriberId and environmentId combo to prevent and fix this problem.
=> Nv 3567 subscribers are duplicated during the burst of events

.idea/runConfigurations/_template__of_mocha_javascript_test_runner.xml, apps/api/src/app/testing/echo/echo-sync.e2e-ee.ts
Added an E2E scaffold for echo sync tests
<details>
</details>
=> test(api): add echo sync tests

apps/worker/src/app/workflow/usecases/send-message/digest/digest.usecase.ts, apps/worker/src/app/workflow/usecases/send-message/send-message.usecase.ts, packages/application-generic/src/usecases/add-job/add-delay-job.usecase.ts, packages/application-generic/src/usecases/add-job/add-job.usecase.ts, packages/application-generic/src/usecases/add-job/merge-or-create-digest.usecase.ts
* Echo endpoints were not received the correct `data` and `inputs` context, resulting in the endpoints throwing a BadRequestError. This change ensures the correct context is provided to those endpoints for the `delay` and `digest` steps.
See https://github.com/novuhq/packages-enterprise/pull/126
<details>
[]
https://github.com/novuhq/packages-enterprise/pull/126
</details>
=> fix(worker): Provide correct execution context to Echo endpoints

apps/api/src/app/testing/product-feature.e2e.ts, apps/web/cypress/tests/billing/annual-subscription.spec-ee.ts
* Fix the annual susbcription tests
<details>
</details>
=> test(web): Fix annual subscription tests

apps/api/src/config/cors.spec.ts, apps/api/src/config/cors.ts
- Use `origin` instead of `host` while determining CORS
Taken from [NewRelic](https://one.eu.newrelic.com/nr1-core/logger/logs-summary/MzgxMjQwOHxBUE18QVBQTElDQVRJT058NDk3NjQzODIy?account=3812408&duration=604800000&state=4aa1cd09-11ed-2121-01ee-7ea96322f3e7)
```
req.headers.host:dev.api.novu.co
...
req.headers.origin:https://dev.web.novu.co
```
=> fix: Use origin instead of host

packages/notification-center/src/hooks/useInitializeSocket.ts
=> Revert "Add exponential backoff with jitter for the In-App Notification Center to re-establish WebSocket connections"

apps/api/src/config/cors.spec.ts, apps/api/src/config/cors.ts
Unfortunately, this is still not working. While the origin code change seems to have been right anyway (yay!), it's still failing between the OPTIONS and POST requests...
Here are [the logs](https://one.eu.newrelic.com/nr1-core/logger/logs-summary/MzgxMjQwOHxBUE18QVBQTElDQVRJT058NDk3NjQzODIy?account=3812408&duration=1800000&state=95cf8453-0b31-ed61-b956-7c9a9f505491) for me logging into dev successfully (via `dev.web.novu.co`). You’ll notice that two requests have req.url: /v1/auth/login . However, when I [search by that](https://one.eu.newrelic.com/nr1-core/logger/logs-summary/MzgxMjQwOHxBUE18QVBQTElDQVRJT058NDk3NjQzODIy?account=3812408&begin=1713385225484&end=1713385345484&state=80d50e9b-44b6-f894-c625-cc241aa72ca8) immediately after trying to login via the deploy-preview, I don’t see a …
=> ci: Use * instead of ['*']

apps/web/src/pages/quick-start/components/OnboardingExperimentModal.tsx, apps/web/src/pages/quick-start/steps/GetStarted.tsx
hide modal in mobile so that user is not blocked 
replace useEffect from get started page to modal component
<details>
</details>
=> feat: add mobile condition with modal

apps/api/src/app/integrations/e2e/update-integration.e2e.ts
Removal of indexes in https://github.com/novuhq/novu/commit/979f79c42045101488ca6cebe2faeb8e06320cf4 resulted in this test exhibiting flakey behaviour. The update integration test filter has been updated to specify the relevant `integrationId` to create a more robust assertion.
_Previously failing test is passing in Local:_
<details>
</details>
=> test(api): Filter on integrationId before assertion

.github/actions/cache/action.yml, .github/actions/docker/build-api/action.yml, .github/actions/docker/build-worker/action.yml, .github/workflows/dev-deploy-api.yml, .github/workflows/dev-deploy-inbound-mail.yml, .github/workflows/dev-deploy-worker.yml, .github/workflows/dev-deploy-ws.yml, .github/workflows/prod-deploy-api.yml, .github/workflows/prod-deploy-inbound-mail.yml, .github/workflows/prod-deploy-worker.yml, .github/workflows/prod-deploy-ws.yml, .github/workflows/reusable-docker.yml, apps/api/package.json, apps/web/package.json, apps/webhook/package.json, apps/widget/package.json, apps/worker/package.json, libs/embed/package.json
We want to update the runners to have cache for docker, pnpm, etc to decrease the build time.
To bypass the Github cache restriction in 10Gb we decide to use the GitHub package registry as a cache. After the first run the new package with the name "cache" will be created for storing the cache images separated by tags. More information about this type of cache you can see [here](https://docs.docker.com/build/cache/backends/registry/)
WEBHOOK service
**Without the cache:**
https://github.com/novuhq/novu/actions/runs/8738434410
**With the cache:**
https://github.com/novuhq/novu/actions/runs/8739026750
**Without the cache:**
**With the cache:**
**Cache package:**
=> feat(ci): Docker build cache

apps/api/src/app/organization/dtos/update-branding-details.dto.ts, apps/web/cypress/tests/layout/main-nav.spec.ts, apps/web/cypress/tests/notification-editor/create-notification.spec.ts, apps/web/cypress/tests/notification-editor/debugging-test-trigger.spec.ts, apps/web/cypress/tests/organization-brand.spec.ts, apps/web/cypress/tests/organization-page.spec.ts, apps/web/cypress/tests/organization-switch.spec.ts, apps/web/cypress/tests/settings.spec.ts, apps/web/cypress/tests/settings/user-profile.spec.ts, apps/web/src/pages/settings/user-profile-page/UserProfilePasswordSidebar.tsx, apps/web/src/pages/templates/components/StepEditorSidebar.tsx, apps/web/src/pages/templates/components/TestWorkflow.tsx, apps/web/tests/start-from-scratch-tour.spec.ts, libs/design-system/src/sidebar/Sidebar.const.ts, libs/design-system/src/sidebar/Sidebar.styles.ts, libs/design-system/src/sidebar/Sidebar.types.ts, libs/design-system/src/sidebar/SidebarFormless.tsx, libs/design-system/src/sidebar/index.ts
- fixes cypress tests
<details>
</details>
=> fix: tests

packages/node/src/lib/novu.spec.ts, packages/node/src/lib/novu.ts
Fix Novu SDK when the API key is passed as a string.
=> fix(@novu/node): Fix parameter parsing
